Dynatrace/dynatrace-operator

test/scenarios/activegate/basic/activegate_test.go, test/scenarios/activegate/proxy/activegate_test.go, test/scenarios/applicationmonitoring/applicationmonitoring_test.go, test/scenarios/classic/classic_test.go, test/scenarios/classic/switch_modes/switch_modes_test.go, test/scenarios/cloudnative/basic/cloudnative_test.go, test/scenarios/cloudnative/codemodules/cloudnative_test.go, test/scenarios/cloudnative/disabled_auto_injection/cloudnative_test.go, test/scenarios/cloudnative/istio/cloudnative_test.go, test/scenarios/cloudnative/network/cloudnative_test.go, test/scenarios/cloudnative/proxy/cloudnative_test.go, test/scenarios/cloudnative/public_registry/cloudnative_test.go, test/scenarios/cloudnative/specific_agent_version/cloudnative_test.go, test/scenarios/cloudnative/switch_modes/switch_modes_test.go, test/scenarios/cloudnative/upgrade/cloudnative_test.go
Set a proper logger for controller-runtime in E2E tests. Otherwise, the E2E logs are spammed with messages about a missing logger.
Run E2E tests and check that output doesn't contain messages like:
```
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
```
=> Set logger for controller-runtime.

src/dtclient/endpoints.go, src/dtclient/endpoints_test.go
OneAgent and ActiveGate API endpoints now relate to the configured dynakube network zone
- Unit tests
- Apply a dynakube with `spec.networkZone` property
=> Add network zone to OneAgent and ActiveGate endpoints

src/controllers/edgeconnect/deployment/deployment.go, src/controllers/edgeconnect/deployment/deployment_test.go
This PR fixes the absence of a few missing fields from CRD that are landed correctly yo deployment:
Missing fields:
* Env
* resources
* NodeSelector
* Tolerations
* TopologySpreadConstraints
```
kubectl apply -f - <<EOF
apiVersion: dynatrace.com/v1alpha1
kind: EdgeConnect
metadata:
name: andrii-test
spec:
apiServer: "<tenant>.dev.apps.dynatracelabs.com"
oauth:
clientSecret: edge-connect-client-secret
endpoint: https://<sso-url-here>/sso/oauth2/token
resource: urn:dtenvironment:<tenant>
env: 
- name: DEBUG
value: "true"
EOF
```
Check env vars of the pod has DEBUG=true:
```
k get pods andrii-test-5d894dbcf9-wn8p5 -o=jsonpath='{range .items[*]}{.spec.containers[*].env}' | jq
[
{
"name": "DEBUG",
"value": "true"
},
{
"name": "EDGE_CONNECT_NAME",
"value": "andrii-test"
}, …
```
=> Add missing usage of EdgeConnect Spec for: Env, Resources, NodeSelector, Toleration, TopologySpreadConstraints

assets/calico/activegate-policy.yaml, assets/calico/dynatrace-policies.yaml, doc/network.md
Rework the existing network policies using the minimum ports.
New documentation under doc/network.md.
> [!NOTE]
> I would appreciate some help here as I'm not really sure if everything works as expected while running the operator with the network policies. As far as I can see in my cluster, everything is green and no errors.
- Apply assets/calico/dynatrace-policies.yaml
- Apply assets/calico/activegate-policy.yaml
- Running operator locally with a CloudNativeFullStack dynakube and seeing no errors on the pods/logs.
=> Add network.md and refactor calico network policies

assets/calico/activegate-policy.yaml
Just noticed that these two ports (that I removed in a previous PR) were needed for ActiveGate in order to start a cluster from scratch.
Before, ActiveGate was never ready because it wasn't able to use 443 port.
Fresh install a cluster with the operator and a dynakube having the activegate-policy and dynatrace-policies installed.
=> Add missing ports for ActiveGate network policy

src/dtclient/endpoints.go, src/dtclient/endpoints_test.go
As discussed, we should not use network zone for the ActiveGate API endpoint.
- Unit tests
=> Remove network zone from ActiveGate API endpoint

.github/workflows/release.yaml, hack/build/ci/generate-new-helm-index-yaml.sh
Use pre-release workflow for final releases as well. `cosign.pub` is now attached to the release.
Fork the repo and create a new release
Tested in my fork:
- [GH Action](https://github.com/albertogdd/alberto-dynatrace-operator/actions/runs/6196927449)
- [Release result](https://github.com/albertogdd/alberto-dynatrace-operator/releases/tag/v9.0.24)
=> Add release action

.github/pre-commit, .github/workflows/ci.yaml, .markdownlint.json, ARCHITECTURE.md, CONTRIBUTING.md, HACKING.md, README.md, config/helm/README.md, config/helm/chart/default/README.md, config/olm/README.md, doc/coding-style-guide.md, doc/isito.md, hack/doc/README.md, hack/helm/google-marketplace/README.md, hack/make/markdown.mk, hack/make/prerequisites.mk, test/scenarios/README.md, test/testdata/secrets-samples/README.md
Add [Markdownlint](https://github.com/DavidAnson/markdownlint) GH action on CI.
Fix all existing lint errors in `.md` files.
`.markdownlint.json` config file was already introduced before.
Commands added:
- `make markdown/lint`
- `make prerequisites/markdownlint`
I also set the pre-commit hook to run the linter
Introduce a lint error in a .md file and trigger the action. The PR should get blocked.
You can see I tested that in my commit "Test" of this PR.
=> Add markdownlint CI check and refactor md files

src/webhook/validation/dynakube/config.go, src/webhook/validation/dynakube/dynakube_name.go, src/webhook/validation/dynakube/dynakube_name_test.go
With this a new validator is added that checks. whether a `dynakube` is applied that starts with a digit. This should be prohibited, as then also services etc. would be created with a leading digit. There are rules for service names that need to conform to DNS-1035 labels and cannot start with numbers.
Apply a `dynakube` with a name that starts with a digit.
=> Add validator to check dynakube name for leading digits

hack/make/tests/e2e.mk, test/scenarios/cloudnative/codemodules/codemodules.go, test/scenarios/cloudnative/network_problems/network_problems.go
Things I fixed: (you can just look at the commits, they have the same comments 😅 )
- Fix CodeModulesImage e2e test
- The 1.  dynakube (cloudNativeDynakube) was not created
- Fix csi resilience e2e test
- Sample namespace has to removed before the operator, so the csi-driver can be unmount the sample app
- Remove ill advised oneAgent arg
- This is a "secret" arg for allowing downgrades, however AFAIK it can cause weird behaviour
Run the effected tests I fixed:
- `make test/e2e/cloudnative/codemodules`
- `make test/e2e/cloudnative/network`
=> Minor fixes for the e2e tests

src/standalone/run.go, src/standalone/run_test.go
Always write the cluster id to the container.conf file independent of any host monitoring OneAgent being present on the node  ore not.
* Deploy operator
* Deploy application monitoring DynaKube
* Deploy sample app
* Shell into app pod
* cat /var/lib/dynatrace/oneagent/agent/config/container.conf
* make sure that `k8s_cluster_id` and `k8s_node_name` entries are present
=> Always write cluster id to container.conf

test/scenarios/cloudnative/codemodules/codemodules.go, test/scenarios/cloudnative/codemodules/codemodules_test.go, test/scenarios/cloudnative/istio/istio_test.go
For some reason we can run the codeModulesImage e2e with an `istio: true` arg, which does not really make sense.
- The istio integration does not involve the codeModulesImage field, as the would require us to create a serviceEntry/virtualService for the custom image registry the customer may use to store the codeModulesImage.
- This test does nothing really with istio, other then make it inject our components, but we do not configure it to do anything.
`make test/e2e/cloudnative/codemodules` still exists
`make test/e2e/cloudnative/istio` doesn't take that long (as we no longer run the codeModulesImage e2e test here)
=> Remove codeModulesImage e2e test isito parts

src/standalone/files.go, src/standalone/run.go, src/standalone/run_test.go
Currently we have the problem that when writing the whole k8s config content into `container.conf` and using `applicationMonitoring` the injected sample apps do not show up in the UI as hosts. This is probably because of the k8s node name being written although it not being existent. With this fix now there is a distinction made and the node name is only written when `cloudNativeFullStack` is used. K8s cluster id on the other hand is still written always.
- deploy operator
- apply dynakube with applicationMonitoring
- deploy sample apps and inject into them
- check if sample apps are listed as hosts in the UI
=> Fix not appearing hosts when using application monitoring

src/controllers/dynakube/oneagent/daemonset/daemonset.go, src/controllers/dynakube/oneagent/daemonset/daemonset_test.go
Default oneagent liveness probe was too short to reliable start the container:
- Removed default initial delay used for both readiness and liveness probe
- Use "healthcheck start period" as is for liveness probe
- Higher values are not an issue, as it just delays the first health check
- Pod is still marked as healthy until the first probe is run
- Limit "healthcheck start period" to 90s, but allow lower values, for readiness probe
- Value should be limited to a sensible value, as probe needs to run once for pod to be marked as ready
- Add success threshold value of 1 for both probes (same as default, but more explicit)
Apply a Dynakube that deploys oneagent pods:
- readiness/liveness probe should both be set
- liveness probe
- values are used as is, no limit
- readiness probe
- tenant …
=> Update oneagent readiness and liveness probe defaults

hack/make/tests/e2e.mk
Operator e2e test should include the public registry e2e test by default.
Run `make test/e2e`.
=> Enable public registry e2e test

src/controllers/certificates/webhook_cert_controller.go, src/controllers/certificates/webhook_cert_controller_test.go, src/controllers/dynakube/activegate/internal/authtoken/reconciler.go, src/controllers/dynakube/activegate/internal/authtoken/reconciler_test.go, src/controllers/dynakube/activegate/internal/capability/mock.go, src/controllers/dynakube/activegate/internal/capability/reconciler.go, src/controllers/dynakube/activegate/internal/capability/reconciler_test.go, src/controllers/dynakube/activegate/internal/customproperties/reconciler.go, src/controllers/dynakube/activegate/internal/customproperties/reconciler_test.go, src/controllers/dynakube/activegate/internal/proxy/reconciler.go, src/controllers/dynakube/activegate/internal/proxy/reconciler_test.go, src/controllers/dynakube/activegate/internal/statefulset/reconciler.go, src/controllers/dynakube/activegate/internal/statefulset/reconciler_test.go, src/controllers/dynakube/activegate/reconciler.go, src/controllers/dynakube/activegate/reconciler_test.go, src/controllers/dynakube/connectioninfo/reconciler.go, src/controllers/dynakube/connectioninfo/reconciler_test.go, src/controllers/dynakube/deploymentmetadata/reconciler.go, src/controllers/dynakube/deploymentmetadata/reconciler_test.go, src/controllers/dynakube/dtpullsecret/generate_test.go, src/controllers/dynakube/dtpullsecret/reconciler.go, src/controllers/dynakube/dtpullsecret/reconciler_test.go, src/controllers/dynakube/dynakube_controller.go, src/controllers/reconciler.go
The `Reconcile(ctx)` function of `Reconciler` interface requires context parameter to enforce the use of the context.
ActiveGate Reconcilers used context.TODO() instead of top-level context. Now the context is passed along the call stack:
- authtoken
- capability
- customproperties
- proxy
- statefulset
Additionally the following Reconcilers also pass the context to functions that need it instead of keeping it in the Reconciler struct: 
- connectioninfo
- deploymentmetadata
- dtpullsecret
- webhook_cert_controller
All e2e tests should PASS.
=> Add context parameter to Reconcile function of the Reconciler interface

.github/workflows/release.yaml
The last pre-release action was trying to create a new helm index file, which is incorrect, as we are not releasing the helm-chart on a pre-release.
Fork the operator repo -> push a tag in the following format (vX.X.X-rcX) -> check if the helm manifest and index file creation is skipped
=> Skip helm index file creation incase of pre-release

src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynatraceapi/status.go, src/controllers/dynakube/token/tokens.go, src/controllers/dynakube/token/tokens_test.go
The Operator doesn't handle `ServiceUnavailable` and `TooManyRequests` DynatraceApi errors properly thus Dynakube Reconciler in not called as often as it should be in such a case (after a minute).
The root cause is  `concatErrors(errs []error)` function which concatenates error messages into a single string error so the information that `ServerError` has been encountered is lost.
The fixed logic returns an instance of ServerError if any of concatenated errors was ServerError. The disadvantage of this solution is that part of the final message is duplicated:
`dynatrace server error 503: error 1\n\tdynatrace server error 503: ServiceUnavailable`
It would be better to report:
`error 1\n\tdynatrace server error 503: ServiceUnavailable`
Finally `isDynatraceAPIUnreachable(err error)` function …
=> Fix operator behavior related to `503 ServiceUnavailable` DynatraceApi error

src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynatraceapi/status.go, src/controllers/dynakube/token/tokens.go, src/controllers/dynakube/token/tokens_test.go
cherry-pick of [fix](https://github.com/Dynatrace/dynatrace-operator/pull/2158)
We can't force the server to return 503 so I tested the fix using unit tests and debugged a small application consisting of investigated code and basic http server returning 503 response.
=> Fix operator behavior related to 503 ServiceUnavailable DynatraceApi error

.github/workflows/release.yaml
Same as in #2161
Same as in #2161
=> Skip helm index file creation incase of pre-release (#2161)

src/api/v1beta1/dynakube/feature_flags.go, src/api/v1beta1/dynakube/feature_flags_test.go, src/standalone/env.go, src/standalone/env_test.go, src/standalone/run.go, src/standalone/run_test.go
The `oneagent-install` initContainer either just swallow the error (if failure policy is set to `silent`) or is stuck in CrashLoopBackOff (if failure policy is set to `fail`) if the correct `hostTenant` can not be set (based on `monitoringNodes`).
To solve this problem `force` injection failure policy has been added. The new policy ignores the `monitoringNodes` when it comes to setting the `hostTenant`. The tenant from dynakube is used instead.
Install sample app:
```
cat test/testdata/sample-app/pod-base.yaml | sed "s/metadata:/metadata:\r\n  annotations:\r\n    oneagent.dynatrace.com\/failure-policy: force/" | kubectl -n <namespace> apply -f -
```
The following message should be printed to log:
`kubectl -n <namespace> logs -c install-oneagent pod/php-sample`
``` …
```
=> Adds 'force' injection failure policy

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml
As pointed out in #2173, the CSI driver daemonset is currently missing resource limits for the init container.
This PR adds them including the possibility to change them with helm values.
Deploy this branch and check limits.
=> Add limits to init container of CSI driver daemonset

pkg/controllers/dynakube/activegate/internal/statefulset/statefulset.go, pkg/controllers/dynakube/activegate/internal/statefulset/statefulset_test.go, pkg/controllers/dynakube/oneagent/daemonset/affinity.go, pkg/util/kubeobjects/affinity.go, pkg/util/kubeobjects/affinity_test.go
Currently the operator fails to roll out ActiveGate instances on ARM nodes due to missing node affinity settings. This PR adds those to the statefulset.
Get a cluster with a different architecture (i.e arm64)
Install the operator
Apply a Dynakube that rolls out an AG
Check if the AG pod is actually scheduled (may fail since the tenant registry only supports amd64 -> thats fine)
=> Adds missing nodeAffinity settings for arm and ppcle support to the activeGate statefulset

.github/actions/build-helm/action.yaml, .github/actions/upload-helm/action.yaml, .github/workflows/release.yaml, hack/build/ci/push-helm-chart.sh
This PR: 
- Fixes bug in the release pipeline where the parameters were named in the wrong way
- Add steps for upload and sign the helm-package to OCI registry
Run release steps and check in OCI registry if packages are there
=> Add helm-package upload to OCI registry

pkg/oci/registry/client.go
Currently the image digest for AMD64 images is used in OneAgent daemonsets. This causes errors if OneAgents should be rolled out on nodes with architectures other than amd64.
Instead of using the digest of the amd64 image the operator shall use the digest of the image index, that points to an image manifest containing images for all supported architectures.
- setup a K8s cluster with arm and amd nodes
- build and deploy a multi-arch operator
- create a dynakube with proper tolerations for one agent pods:
```
tolerations:
- effect: NoSchedule
key: kubernetes.io/arch
value: arm64
operator: Equal
```
- deploy DynaKube
- check that OneAgents can properly start on arm nodes
=> Use image index digest instead of plain image digest

hack/make/deploy/helm.mk
In our e2e pipelines we have the operator's namespace prepared with secrets to access registries, however if we remove the namespace after each test, which is not intended.
Run any e2e test, the namespace should remain there.
=> Keep namespace when running undeploy/helm

src/controllers/dynakube/version/reconciler.go
Bit of context:
- The current way the `version` package works is not optimal.
- So this is just a quick fix to mitigate the problem, otherwise it would require a major rethinking, which we shouldn't do last minute.
So what is actually is happening:
To decide which part of the status needs update we filter our list of `updaters`, [this filtering happens based on different things](https://github.com/Dynatrace/dynatrace-operator/blob/81e3e388426e2a74164549fe89bb5e7c2be61913/src/controllers/dynakube/version/reconciler.go#L89-L109).
After the filtering, we run all of them that remain.
The Bug: If there was any kind of `updater`, we checked/updated the healthcheck for the oneagent, which is not great.
- This didn't happen often, as we update all the `Statuses` in one go most of the time, they …
=> Only get oneagent healthcheck when needed

src/controllers/dynakube/activegate/internal/statefulset/statefulset.go, src/controllers/dynakube/activegate/internal/statefulset/statefulset_test.go, src/kubeobjects/affinity.go, src/kubeobjects/affinity_test.go
We should not set default tolerations to the activeGate statefulset, as we have a dedicated dynakube field to set them.
Deploy the operator -> Apply a DynaKube with an activeGate and without custom tolerations -> check if tolerations field is empty
=> Removes default tolerations for activeGate pods

pkg/controllers/dynakube/version/reconciler.go
cherry-pick of #2207
same as #2207
=> Only get oneagent healthcheck when needed #2207

test/scenarios/cloudnative/default/default.go
- fixes the Istio e2e test by creating the namespace of the SampleApp so the secret is in place when the oneagent init container is executed and subsequently checked in the test.
run the Istio e2e test(s)
=> Fix the flakey Istio e2e Test

config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/chart/default/values.yaml, pkg/controllers/dynakube/activegate/internal/statefulset/statefulset.go
Currently the `seccompProfile` is set on the container level only. Kyverno Policy prefers the profile to be set on the container level and the POD level.
`podSecurityContext` field has been added to `operator` and `webhook` sections of `values.yaml` file to make `seccompProfile` configurable on the POD level. 
In case of ActiveGate statefulset the `seccompProfile` field has been added on the POD level. It is hard-coded value.
Summarizing:
- `seccompProfile`s are defined on both levels (by default)
- `seccompProfile`s can be configured on both levels
1) Use helm tests:
```
make test/helm
```
2) Modify `values.yaml` file and deploy the operator using `make deploy/kubernetes` command. Check if `seccompProfile`s are set accordingly to the `values.yaml`.
For example set the following value in …
=> Add seccompProfile on the POD level

hack/make/prerequisites.mk
Add install mockery if you run `make prerequisites`
Remove mockery and run `make prerequisites`
=> add install mockery to prerequisites

Dockerfile
Change ubi9-micro to multi-arch image in dockerfile
Build for arm64, amd64 and ppc64le should work
=> Change ubi9-micro to multi-arch image in dockerfile

.github/workflows/release.yaml
The CRD file was missing when the release was automatically created.
This fix updates the pipeline to include the release file. 
Run the release pipeline and check for `dynatrace-operator-crd.yaml` in the created release.
=> Add missing CRD to GitHub actions release pipeline 

test/helpers/kubeobjects/namespace/namespace.go, test/helpers/proxy/proxy.go, test/scenarios/cloudnative/codemodules/codemodules.go
- adds labeling of existing namespaces
- cleans up cut-off pod
run codemodules with proxy e2e test/
=> Stabilises Codemodules e2e Test

hack/build/ci/generate-release-notes.sh
Currently the `generate_release_notes.sh` has incorrect release notes for the actual real release. The release notes are missing the *-csi.yaml manifests in the instructions how to install/update. These manifests are not release during a pre-release.
Fixed script:
- generates specific release-notes for `pre-release` and `release` versions
- the documentation links are updated and point to the new documentation
- `release` notes have `What's Changed` section and `pre-release` notes have `Features` section
- generate CHANGELOG.md file in `pre-release` mode:
```
(export GITHUB_REF_NAME="1.2.3" ; export PRE_RELEASE=true ; ./generate-release-notes.sh)
```
- generate CHANGELOG.md file in `release` mode:
```
(export GITHUB_REF_NAME="1.2.3" ;  ./generate-release-notes.sh)
```
~~- [ ] Unit tests …
=> Generate different notes for a pre-release and release version

.golangci.yml, pkg/api/v1beta1/dynakube/feature_flags_test.go, pkg/api/v1beta1/dynakube/properties_test.go, pkg/controllers/csi/metadata/correctness_test.go, pkg/controllers/csi/metadata/sqlite_test.go, pkg/controllers/csi/provisioner/processmoduleconfig_test.go, pkg/controllers/dynakube/activegate/internal/statefulset/statefulset_test.go
Enable new linter: perfsprint
Some context: 
>Sprint is the slowest way to convert small and big int to string, and on the other hand strconv. FormatInt is the fastest way to convert a int to string , strconv,Itoa is the second fastest way almost near to strconv. FormatInt. So hence prove that for either small or big always use strconv.
From benchmarks in https://dev.to/mavensingh/strconvitoa-vs-strconvformatint-vs-fmtsprintf-which-is-good-to-convert-int-to-string-in-golang-3iol#:~:text=Sprint%20is%20the%20slowest%20way,or%20big%20always%20use%20strconv.
unit-tests
=> Enable new linter: perfsprint

pkg/controllers/dynakube/dynakube_controller.go, pkg/controllers/dynakube/dynakube_controller_test.go, pkg/controllers/dynakube/istio/client.go, pkg/controllers/dynakube/istio/client_test.go, pkg/controllers/dynakube/istio/reconciler.go, pkg/controllers/dynakube/istio/reconciler_test.go, pkg/webhook/validation/dynakube/istio.go
Fixes a problem where owner references of created istio CRs were deleted after they were updated.
In addition refactors the istio client implementation to keep a reference to the owner directly, as one instance is anyway always using the same owner.
- create dynakube without active gate section and istio enabled
- check if service entries were created and have owner references
- update dynakube to have an active gate section 
- service entries should be updated and not loose the owner reference
- do the same for virtual services
=> Fix self deleting owner reference in created istio CRs

doc/network.md
Links to the calico yaml files in the networking.md file are fixed in this PR.
Browse to [links](https://github.com/Dynatrace/dynatrace-operator/blob/main/doc/network.md#kubernetes-network-policies)
=> Fix the broken links in the networking doc

assets/samples/hostMonitoring.yaml
Host monitoring sample is updated such that it has infra-only mode enabled by default.
=> Add infra-only mode to host monitoring sample

pkg/injection/startup/env.go, pkg/injection/startup/env_test.go
When the DynaKube feature flag `feature.dynatrace.com/automatic-injection` was set to false to use `oneagent.dynatrace.com/inject: "true"` on a pod, the pod did not get the env var `K8S_CLUSTER_ID` injected. This resulted in the OneAgent not being able to generate a correct host identifier which then lead to a pod not being visible in the UI.
This PR fixes that issue.
create a DynaKube with `feature.dynatrace.com/automatic-injection: "false"` and a sample app with `oneagent.dynatrace.com/inject: "true"`.
Then `/var/lib/dynatrace/oneagent/agent/config/container.conf` should contain a valid cluster ID.
=> Always Add ClusterId EnvVar To Pods

config/helm/chart/default/templates/Common/webhook/mutatingwebhookconfiguration.yaml, config/helm/chart/default/templates/Common/webhook/validatingwebhookconfiguration.yaml, config/helm/chart/default/tests/Common/webhook/mutatingwebhookconfiguration_test.yaml, config/helm/chart/default/tests/Common/webhook/validatingwebhookconfiguration_test.yaml, config/helm/chart/default/values.yaml
Make timeoutSeconds configurable for webhook configurations via values.yaml
Deploy the operator via helm and change the timeoutSeconds in the values.yaml -> check if the mutatingWebhookConfiguration and the validatingWebhookConfiguration has the correct value set
=> Make timeoutSeconds configurable for webhook configurations via values.yaml

go.mod
I will need the `slices` package in a different PR. It is not available in 1.20.
The operator is built and works with no changes.
=> Bump golang version to 1.21

pkg/controllers/dynakube/dynakube_controller_test.go, pkg/controllers/dynakube/dynatraceclient/builder.go
In case of a problem with the token we did only retry every 15 minutes to fix the token. By only setting the timestamp if a token could be validated we retry much more often until succeeded.
Deploy a dynakube with a proxy pointing nowhere- if described the dynakube is in error state because it cannot get the token. Reapply the dynakube without the proxy and it should get immediately healed.
=> Speed up retrying token fixing

pkg/controllers/dynakube/oneagent/oneagent_reconciler_test.go
Remove unused fakeVersionProvider mock
[type](https://github.com/Dynatrace/dynatrace-operator/blob/poc/mockery-manager-interface/pkg/controllers/dynakube/oneagent/oneagent_reconciler_test.go#L32)
On() [hooks](https://github.com/Dynatrace/dynatrace-operator/blob/poc/mockery-manager-interface/pkg/controllers/dynakube/oneagent/oneagent_reconciler_test.go#L415-L416)
unittests
=> Remove fakeVersionProvider mock

pkg/oci/registry/client.go, pkg/oci/registry/client_test.go
Currently we have the problem that the no-proxy feature flag is not used for the image library traffic. Therefore its not possible to add NO_Proxy values for this kind of communication. Especially when having customImages it can lead to problems.
Create a Dynakube with a Proxy and set NoProxy value to the target of the customImage, check if the image manifest can be accessed without accessing the proxy
=> Add no-proxy to image library transport

hack/make/tests/e2e.mk, pkg/api/scheme/scheme.go, pkg/controllers/dynakube/dynakube_controller_test.go, pkg/controllers/dynakube/istio/client.go, pkg/controllers/dynakube/istio/client_test.go, pkg/controllers/dynakube/istio/config.go, pkg/controllers/dynakube/istio/reconciler_test.go, pkg/controllers/dynakube/istio/serviceentry.go, pkg/controllers/dynakube/istio/serviceentry_test.go, pkg/controllers/dynakube/istio/virtualservice.go, pkg/controllers/dynakube/istio/virtualservice_test.go, test/helpers/istio/install.go
There are `v1beta1` versions of `ServiceEntry`, `VirtualService` CR's available. The operator still uses `v1alpha3` version of the isito CR's and it should be updated.
Install operator with istio enabled from the `main` branch (using `make deploy..` command). Deploy CloudNative Dynakube. Install/update operator from the PR's branch (using `make deploy..` command). After update is finished the `ServiceEntries` and `VirtualServices` should have the same contents (endpoints may be in a different order).
Istio e2e tests should PASS.
```
make test/e2e/istio
```
=> Upgrade the istio CR version to v1beta1

test/scenarios/istio/istio_test.go
`nsWithIstio.Namespace` is empty, which caused the error: 
```
F1116 01:15:25.193648   12580 env.go:375] Setup failure: an empty namespace may not be set during creation
```
run `make test/e2e/istio` and you have the otel secret setup locally
=> Fix e2e otel secret creation

pkg/api/v1beta1/dynakube/feature_flags.go, pkg/api/v1beta1/dynakube/feature_flags_test.go
When istio is injected alongside the oneagent codemodules then the DT service is created a bit inconsistently, that can hinder automated testing, so increasing the initial retry will make them consistent.
Dynakube with `enableIstio: true`, in a injected sample app's namespace the `dynatrace-dynakube-config` secret should have a `initialConnectRetry` set. (so not -1)
=> Add default oneagent initial retry in case of istio

pkg/clients/edgeconnect/client.go, pkg/clients/edgeconnect/client_test.go, pkg/clients/edgeconnect/edgeconnect.go
This PR adds an additional parameter to the create and update request of the edge connect client to tell the tenant that the request originated from the operator.
- Run unit tests or 
- create edge connect and check if the parameter is there in the tenant
=> Add managed-by-operator parameter when creating edgeConnect resources

pkg/util/otel/otel.go
We should fail more silently when there is NO otel-config secret
Run operator without otel-secret:
Before:
```
dynatrace-operator-f4448bb68-6bxkb dynatrace-operator {"error":"secrets \"dynatrace-operator-otel-config\" not found","level":"error","logger":"open-telemetry","msg":"failed to read OpenTelementry config secret","stacktrace":"secrets \"dynatrace-operator-otel-config\" not found
dynatrace-operator-f4448bb68-6bxkb dynatrace-operator github.com/Dynatrace/dynatrace-operator/pkg/util/kubeobjects/secret.Query.Get
dynatrace-operator-f4448bb68-6bxkb dynatrace-operator   github.com/Dynatrace/dynatrace-operator/pkg/util/kubeobjects/secret/secret.go:35
dynatrace-operator-f4448bb68-6bxkb dynatrace-operator github.com/Dynatrace/dynatrace-operator/pkg/util/otel.getOtelConfig …
```
=> fail more silently when there is NO otel-config secret

.github/workflows/ci.yaml, hack/build/create_go_build_tags.sh
Since we recently we switched the image library we are using, we can remove the build tags we introduced specifically for this old library.
Not really testable, build should work and the operator has to run as before
=> Remove unnecessary build tags

test/features/activegate/activegate.go
For some reason this used to work, don't really know how.
But in this test case it can be that we inject the activegate with istio, which adds a sidecar, so directly accessing the `Container` array is risky 😅 
`make test/e2e/activegate/proxy` passes
- ~[x] Unit tests have been updated/added~
=> Only check the actual activegate container for mounts in e2e test

CONTRIBUTING.md
Updates mockery rules  - how to use generated mock class to avoid dead or missing definitions of expectations. 
Read the `#### Migrating to Mockery` chapter
=> Updates mockery rules in CONTRIBUTING.md

pkg/api/v1beta1/dynakube/feature_flags.go, pkg/api/v1beta1/dynakube/feature_flags_test.go, pkg/webhook/mutation/pod_mutator/init_container_test.go
This PR change default value of `feature.dynatrace.com/injection-failure-policy` to `force`.
unittests
=> Default injection failure policy to force

cmd/startup_probe/builder.go
Setting hostname for startup probe to `kubernetes.default.svc.cluster.local` has the unnecessary requirement of `cluster.local`, which disallows custom domains.
Fixes #2399 
Startup probe should succeed.
=> Remove restriction to `cluster.local` domain for startup probe

.github/renovate.json5, hack/helm/install-unittest-plugin.sh, hack/make/prerequisites.mk
With this renovate also deals witth the versions of `markdownlint cli` and `helm unittest plugin`.
You can have a lookt at the PRs generated by renovate on my fork: https://github.com/waodim/dynatrace-operator/pulls
=> Make renovate pin versions of markdownlint-cli and helm unittest

hack/make/prerequisites.mk
Improve markdowncli-lint integration with renovate
Run: `make prerequisites/markdownlint`
=> Improve markdowncli-lint integration with renovate

hack/helm/install-unittest-plugin.sh, hack/make/prerequisites.mk
Improve helm-unittest renovate integration
`helm plugin list` should show you latest helm-unittest:
```
helm plugin list
NAME            VERSION DESCRIPTION
unittest        0.3.6   Unit test for helm chart in YAML with ease to keep your chart functional and robust.
```
=> Improve helm unittest integration with renovate

test/testdata/network/proxy.yaml
Newer versions of openshift enforces the Pod Security Admissions, just added a few labels to the proxy namespace, so that it wont be blocked, as its only for e2e tests
`make test/e2e/activegate/proxy` (on openshift 4.14)
=> Fix e2e proxy.yaml for latest openshift

.github/workflows/ci.yaml, hack/make/prerequisites.mk
This PR removes brew, because using brew we can't control versions of packages.
Add missing renovate comment for GH action.
>Note: If you already using brew version:
```
brew uninstall markdownlint-cli
```
CI is green and you can upgrade or downgrade:
```
npm install -g markdownlint-cli@v0.36.0
markdownlint -V
0.36.0
```
=> Remove brew deps for markdownlint and use nodejs

.github/workflows/release.yaml
We no longer need to push the release tags to Snyk. It is now automatically done from Snyk side.
Nothing to test.
=> Removes github action to push tag to snyk

config/helm/chart/default/values.yaml
As we recently have received several problems that were created because the customer didn't update the CRDs. This is mainly a problem in helm because you specifically have to opt in with the "installCRD: true" option.
Install the helm chart with default values file -> check if CRD is installed
=> Make installCRD default in values.yaml

.github/workflows/release.yaml
Cherry pick of #2431.
Cant be tested
=> Removes github action to push image tag to Snyk

README.md
Links to samples in the readme got outdated with the recent restructure of the different samples.
Links work correctly
=> Update sample link location

.github/renovate.json5, pkg/api/v1beta1/dynakube/feature_flags.go, pkg/api/v1beta1/dynakube/feature_flags_test.go, pkg/injection/namespace/initgeneration/initgeneration.go, pkg/injection/namespace/initgeneration/initgeneration_test.go, pkg/injection/startup/env.go, pkg/injection/startup/env_test.go, pkg/injection/startup/run.go, pkg/injection/startup/run_test.go, pkg/injection/startup/secret.go, pkg/webhook/mutation/pod_mutator/init_container_test.go
Currently the enforcement mode is enabled by default. However this setting is packed together with other failure policies (silent, fail). This is a problem, as they are not really related and the enforcement mode should be a standalone feature flag which is enabled by default. With this PR we introduced an own feature flag which is decoupled from the failure policy
Deploy a Dynakube -> check if the namespace secret has the correct value for EnforcementMode, which should be by default true.
Deploy a Dynakube with the annotation `feature.dynatrace.com/enforcement-mode: "false"` -> check if the namespace secret has EnforcementMode set to false
=> Add own feature flag for enforcementMode

.github/renovate.json5
In order to get automatic dependency updates on the new release branch, we have to add the branch to the config
=> Add release branch 0.15 to renovate config

pkg/api/v1beta1/dynakube/feature_flags.go, pkg/api/v1beta1/dynakube/feature_flags_test.go, pkg/injection/namespace/initgeneration/initgeneration.go, pkg/injection/namespace/initgeneration/initgeneration_test.go, pkg/injection/startup/env.go, pkg/injection/startup/env_test.go, pkg/injection/startup/run.go, pkg/injection/startup/run_test.go, pkg/injection/startup/secret.go, pkg/webhook/mutation/pod_mutator/init_container_test.go
Same as in: https://github.com/Dynatrace/dynatrace-operator/pull/2444
Same as in: https://github.com/Dynatrace/dynatrace-operator/pull/2444
=> Add own feature flag for enforcementMode (#2444)

test/helpers/kubeobjects/daemonset/wait.go
Revert previous commit and increase e2e oneagent-ready timeout to 10 min
Trigger OCP pipelines after merging and hopefully they pass
=> Revert oneagent-ready fail safe and increase timeout

pkg/clients/edgeconnect/client.go, pkg/controllers/edgeconnect/controller.go, pkg/controllers/edgeconnect/controller_test.go
Based on `managedByDynatraceOperator` attribute the EdgeConnect controller is able to properly handle errors:
- deleted edgeconnect client secret
- invalid EdgeConnect.ID on the tenant
1) 
- deploy EdgeConnect (`provisioner` mode enabled)
- remember ID of EdgeConnect
- remove `-client` secret (`kubectl delete secret <name>-client`)
EdgeConnect on the tenant and the `-client` secret should be created from scratch so ID should be different
2)
- deploy EdgeConnect (`provisioner` mode enabled)
- change ID in the client secret (`kubectl edit secret <>-client`)
EdgeConnect on the tenant and the `-client` secret should be created from scratch so ID should be different
3)
- deploy EdgeConnect (`provisioner` mode enabled)
- remove `-client` secret
- delete EdgeConnect CR
EdgeConnect on the tenant …
=> Added errors handling logic to the EdgeConnect controller

PROJECT, hack/build/bundle.sh, hack/build/create_go_linker_args.sh
Version package was moved to a different package and build still pointed to old location.
Log output of Operator startup correctly shows version, commit hash and build date.
=> Fix location of version package

.github/workflows/release.yaml
Current the cosign public key file was a file without multilines, but cosign verify expects a proper public certificate, which has multi-lines. We now store it base65 encoded in our GH secretes and decode it, when writing it the the release artefacts
`cosign verify --key <path to your keyfile> dynatrace/dynatrace-operator:v0.15.0`
=> Fix wrong cosign public key file

pkg/controllers/dynakube/controller_test.go, pkg/controllers/dynakube/dtpullsecret/reconciler.go, pkg/controllers/dynakube/dtpullsecret/reconciler_test.go
Remove a check that is meant to save a bit on requests by only creating the pull-secret when necessary, because in case of applicationMonitoring we don't really need it (unless codeModulesImage is used).
However other parts of the code requires this pull secret to be there, even its not used.
Fixing that would be take longer and should be done with lots of care.
So I remove this very minor "improvement" so that we don't break things
Deploy `applicationMonitoring` dynakube
=> Remove check before pull-secret generation

hack/build/build_image.sh, hack/build/push_image.sh
Add podman if docker cli is missing #2542
run: `make images/build/push`
=> Add podman if docker cli is missing

.github/workflows/release.yaml
Images in our release manifests are referenced using version@sha.. tag. For example:
```
image: public.ecr.aws/dynatrace/dynatrace-operator:v1.2.3@sha256:2f24a7e4295d4b005730d00e5952acb543ab1371b751f5a1e7bf1c65543a4807
```
`release` job uses SHA provided by `manifest` job. 
I use forked project. See [Kubernetes](https://github.com/abcxyzdef123654/dynatrace-operator/releases/download/v1.2.3/kubernetes.yaml) / [Openshift](https://github.com/abcxyzdef123654/dynatrace-operator/releases/download/v1.2.3/openshift.yaml) manifests.
kubernetes.yaml:
```
kind: Deployment
metadata:
name: dynatrace-operator
spec:
template:
spec:
containers:
- name: dynatrace-operator
image: public.ecr.aws/dynatrace/dynatrace-operator:v1.2.3@sha256:2f24a7e4295d4b005730d00e5952acb543ab1371b751f5a1e7bf1c65543a4807
kind: …
```
=> Add the image digest in manifests created by GitHub action

test/helpers/proxy/proxy.go
FIxup e2e test: Oneagent doesn't get ready in 300s in OCP e2e tests:
*Context* we use dynatrace.com as host to test absence of internet in during e2e tests. Sometimes it's flaky and returns 502.
```
curl dynatrace.com --verbose --head --fail
*   Trying 52.29.248.2:80...
* Connected to dynatrace.com (52.29.248.2) port 80
> HEAD / HTTP/1.1
> Host: dynatrace.com
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
< Connection: keep-alive
Connection: keep-alive
* The requested URL returned error: 503
* Closing connection
curl: (22) The requested URL returned error: 503
```
Better solution is to use explicitly https and www:
```
curl https://www.dynatrace.com --insecure …
```
=> Fixup: curl service unavailable during proxy e2e tests

.github/workflows/release.yaml
Release kubenetes/openshift manifest contains also csi driver manifest as in case of pre-release. Needed to enable csi driver by default.
I use forked project. See an [example](https://github.com/abcxyzdef123654/dynatrace-operator/releases/tag/v3.2.1).
=> Merge csi driver manifest to general manifest in release workflow

config/helm/chart/default/README.md
We want to point our ArtifactHub to the "new" OCI repository we use for our Helm releases.
Because ArtifactHub displays the README, we need to make sure that it mentions the OCI repository and from which version its available.
~⚠️ Only merge after our ArtifactHub repo has been updated to use the OCI url~ (this actually shouldn't matter)
Read the README 😅
=> Add the Helm OCI repository in the Helm README

test/scenarios/release/release_test.go
As we don't fetch the latest release version automatically yet, it has to be updated manually. 
Run `make test/e2e/cloudnative/upgrade`
=> Update latest release version in upgrade e2e tests

pkg/injection/startup/run.go, pkg/injection/startup/run_test.go
Fix empty secret config incase of dataIngest
Create a Dynakube with application Monitoring -> disable injection of oneAgent and just enable data ingest -> everything should work
=> Fix empty secret config incase of dataIngest

pkg/clients/dynatrace/client.go, pkg/clients/dynatrace/client_test.go, pkg/clients/dynatrace/dynatrace_client.go, pkg/clients/dynatrace/processmoduleconfig.go, pkg/clients/dynatrace/processmoduleconfig_test.go, pkg/controllers/dynakube/dynatraceclient/builder.go, pkg/controllers/dynakube/dynatraceclient/options.go
Use `hostgroup` parameter for process module config request.
1) "Create" a hostgroup  
Deploy dynakube:
```
spec:
activeGate:
capabilities:
oneAgent:
args:
- "--set-host-group=host-group-test"
```
UI: 
- go to `Deployment status`/`OneAgents` page
- click `Host group: host-group-test` link below host name
- from the menu on the left choose `Container technologies`
- enable `Docker for Windows Server containers` and save changes.
2) Check value of `dockerWindowsInjection` property. It's set to `on` (after few minutes).
```
watch -n 10 /bin/bash -c "date ; kubectl -n dynatrace exec -t pod/dynatrace-oneagent-csi-driver-<HASH> -- /bin/bash -c \"cat /data/<TENANT>>/config/agent/conf/ruxitagentproc.conf\" | grep \"^.*Injection o\" | sort | grep …
```
=> Add hostgroup parameter to process module config request URL

pkg/consts/agent_injection.go, test/features/applicationmonitoring/read_only_csi_volume.go
This PR fixup e2e test check for env var TestStandard/read_only_csi_volume 
The logic was removed in prev PR, so here we remove check from test.
`make test/e2e/standard`
=> fixup! TestStandard/read_only_csi_volume

pkg/controllers/dynakube/oneagent/daemonset/arguments.go, pkg/controllers/dynakube/oneagent/daemonset/arguments_test.go
Currently the hostIDSource is not set if cloudNativeFullStack is used.
Deploy a Dynakube with cloudNativeFullStack and check if the daemonset has an arg set -> `--set-host-id-source=k8s-node-name`
=> Add missing hostIdSource incase of cloudNativeFullStack

pkg/controllers/csi/driver/volumes/app/publisher.go, pkg/controllers/csi/driver/volumes/app/publisher_test.go, pkg/controllers/csi/driver/volumes/bind_config.go, pkg/controllers/csi/driver/volumes/bind_config_test.go, pkg/controllers/csi/metadata/path_resolver.go, pkg/controllers/csi/provisioner/install.go
Change the file path on which the ruxitagentproc.conf file is stored in the node fs. Adding dynakube name to allow having multiple dynakubes per tenant.
Old:
`rootDir/tenantUUID/config/ruxitagentproc.conf`
New:
`rootDir/tenantUUID/dynakubeName/config/ruxitagentproc.conf`
'Old' files are left behind in the old file path and will be cleaned up when old pods are terminated.
Unit tests + run operator locally with no errors shown.
=> Store ruxitagentproc file in node fs by dynakube name

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, pkg/api/v1beta1/dynakube/dynakube_status.go, pkg/controllers/dynakube/controller.go, pkg/controllers/dynakube/controller_test.go, pkg/controllers/dynakube/processmoduleconfigsecret/config.go, pkg/controllers/dynakube/processmoduleconfigsecret/reconciler.go, pkg/controllers/dynakube/processmoduleconfigsecret/reconciler_test.go
To reduce the number of requests to the tenant, the file ruxitagentproc.conf should be saved into a secret.
This will be the future source of truth for that file.
Create a cloudnative or application monitoring dynakube and check if the secret was created.
=> Create ruxitagentproc.conf secret on dynakube reconcile

.github/workflows/ci.yaml, cmd/integration/integration_test.go, hack/make/go.mk
With this a new integration (no e2e) test is added to check if the build variables (commitHash, version) are set correctly, as we had issues in the past with the corresponding log line.
run the test but do not forget the necessary flags.
example: `go test -ldflags="-X 'github.com/Dynatrace/dynatrace-operator/pkg/version.Commit=$(git rev-parse HEAD)' -X 'github.com/Dynatrace/dynatrace-operator/pkg/version.Version=$(git branch)'" **./cmd/integration/*`
=> Add integration test to check build variables

pkg/clients/dynatrace/dynatrace_client_test.go, pkg/clients/dynatrace/endpoints.go, pkg/controllers/dynakube/controller_test.go, pkg/controllers/dynakube/version/activegate.go, pkg/controllers/dynakube/version/activegate_test.go, pkg/controllers/dynakube/version/codemodules_test.go, pkg/controllers/dynakube/version/oneagent.go, pkg/controllers/dynakube/version/oneagent_test.go, pkg/controllers/dynakube/version/reconciler.go, pkg/controllers/dynakube/version/reconciler_test.go, pkg/controllers/dynakube/version/synthetic.go, pkg/controllers/dynakube/version/synthetic_test.go, pkg/controllers/dynakube/version/updater.go, pkg/controllers/dynakube/version/updater_test.go
Version status (OA,CodeModule,AG) doesn't use image manifest to get version of the image. The logic depends on the registry:
- for Tenant registry -> the response of the two endpoints (`.../latest/metainfo`) are used
- for Public registry -> no changes
- for custom image -> we do not detect the version for custom image anymore. For this reason downgrade check is also removed for custom image case. Additionally no verification of provided URI is performed,
`registry.GetImageVersion` call has been also removed from the Synthetic updater. Temporarily `Version` set to `latest`.
1) Use unit tests `make go/test` to verify if tenant endpoints are used to get image version. 
2) Check if `*.Status.Version` field is set properly.
tenant registry - latest version on your tenant will be reported:
``` …
```
=> Version status uses endpoints instead of image manifest

.golangci.yml, pkg/clients/dynatrace/send_event_test.go, pkg/clients/dynatrace/token_test.go, pkg/injection/codemodule/installer/url/installer.go
Add new linters:
- wastedassign - finds wasted assignment statements.
- usestdlibvars - A linter that detect the possibility to use variables/constants from the Go standard library.
unit-tests
=> Add additional linters: usestdlibvars and wastedassign

.mockery.yaml, pkg/controllers/dynakube/activegate.go, pkg/controllers/dynakube/activegate/reconciler.go, pkg/controllers/dynakube/activegate/reconciler_test.go, pkg/controllers/dynakube/activegate_test.go, pkg/controllers/dynakube/apimonitoring/reconciler.go, pkg/controllers/dynakube/connectioninfo/reconciler.go, pkg/controllers/dynakube/controller.go, pkg/controllers/dynakube/controller_system_test.go, pkg/controllers/dynakube/controller_test.go, pkg/controllers/dynakube/deploymentmetadata/deploymentmetadata_test.go, pkg/controllers/dynakube/deploymentmetadata/reconciler.go, pkg/controllers/dynakube/dtpullsecret/reconciler_test.go, pkg/controllers/dynakube/istio/reconciler.go, pkg/controllers/dynakube/oneagent/oneagent_reconciler.go, pkg/controllers/dynakube/phase_test.go, pkg/controllers/dynakube/proxy/reconciler_test.go, pkg/controllers/dynakube/version/reconciler.go, test/mocks/pkg/controllers/dynakube/istio/reconciler.go
according to the goal of the ticket we should separate the dynakube controller tests more from all the component reconcilers we are currently using in the controllers' reconcile. To not loose code coverage I introduced a system test file to test all components in concert.
I also added some unit-tests where we had little coverage.
run the unit-tests
=> Refactor Dynakube Controller Unit-Tests

pkg/controllers/dynakube/version/updater_test.go, pkg/controllers/edgeconnect/version/updater_test.go
Use `mocks.NewMockImageGetter(t)` and `mocks.NewStatusUpdater(t)` in unit tests.
This showed that some tests have unnecessary mocked functions, which I deleted.
Unit tests
=> Use mockery mock constructor in version/updater_test.go files

pkg/controllers/dynakube/oneagent/daemonset/arguments.go, pkg/controllers/dynakube/oneagent/daemonset/arguments_test.go, pkg/controllers/dynakube/oneagent/daemonset/env_vars.go, pkg/controllers/dynakube/oneagent/daemonset/env_vars_test.go, pkg/controllers/dynakube/oneagent/oneagent_reconciler_test.go, pkg/controllers/dynakube/version/healthconfig.go, pkg/controllers/dynakube/version/healthconfig_test.go
Incase a custom image is used for the OneAgent DaemonSet, then we set the `Version` and `Source` in the Dynakube's `Status` to the `custom-image` constant. 
Our version checks didn't handle this, now they do.
Also flipped the proxy env version check, so if we **don't** know the version then we **don't** use the deprecated proxy envvar.
- This was decided to be consistent with the HealthConfig logic.
- Furthermore the HealthConfig version check is checking for a newer version.
- If we don't want to do this, then IMO we need to make the HealthConfig logic consistent with it as well. 
In case the `oneAgent.image` field is set to something, everything works
=> Handle custom-image in case of version checks

assets/samples/dynakube/cloudNativeFullStack.yaml
Defaults should be the same as used for the init container when the CSI driver is used and no additional configuration is set: https://github.com/Dynatrace/dynatrace-operator/blob/137ff5b206fad284627425e50ce24ecb874f1b6a/pkg/webhook/mutation/pod_mutator/init_container.go#L52-L53
Documentation changes
=> Align requests/limits of init resources in cloud native fullstack sample

.github/workflows/dev-release.yaml
Adds workflow to automatically create `dev-latest` tag which points to the most recent commit on the most recent release branch.
Use forked repo. Push commits to `release-0.1.3` and `release-0.2.1` branches.  `dev-latest` tag should always point to the most recent commit on the `release-0.2.1` branch.
=> Adds workflow to move dev-latest tag on the most recent release branch

hack/make/go.mk, hack/make/prerequisites.mk
Several linters were introduced recently, one in particular `wsl` has its own fixer command, that we should use in the `make go/lint` command.
Also added the linting tools install/update make target as a prerequisite to the `make go/lint` command, so we don't have to think about locally updating the linters.  (it slows the command down a bit, but the golangci-lint is already dog slow, so it doesn't really matter)
run `make go/lint`
=> Adapt the local linting command to new linters

hack/make/go.mk, pkg/clients/dynatrace/communication_hosts_test.go, pkg/injection/codemodule/installer/image/installer_test.go, pkg/injection/codemodule/installer/url/installer_test.go, pkg/injection/startup/run_test.go, pkg/oci/registry/mocks/client.go
There are some problems that `wsl` command still finds, when run with `-fix` but can't actually fix themself.
Also it does not respect `nolint` (unlike `golangci-lint`), so I made the command less aggressive.
`make go/lint` => passes and no file changes
=> Run wsl linter and fix leftover problems

pkg/controllers/csi/provisioner/controller.go, pkg/controllers/csi/provisioner/install.go, pkg/controllers/csi/provisioner/install_test.go
This PR fixes issue with the problematic code: https://github.com/Dynatrace/dynatrace-operator/blob/9a3bcd1bc6b3eb9f946d056c83474efb23dde74b/pkg/controllers/csi/provisioner/install.go#L71-L97
`make test/e2e/cloudnative/codemodules`
=> fixup sha256 prefix handling error

pkg/controllers/csi/provisioner/install.go, pkg/controllers/csi/provisioner/install_test.go
cherry-pick bug fix from release-1.0 branch https://github.com/Dynatrace/dynatrace-operator/pull/2732
`make test/e2e/cloudnative/codemodules`
=> bug: fix sha256 prefix handling in csi driver

config/helm/chart/default/README.md, config/helm/chart/default/templates/_helpers.tpl, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml
Changes the default registry in the helm chart from `docker.io` to `public.ecr.aws`.
Helm tests:
```
make test/helm
```
Helm package `dynatrace-operator-9.9.9.tgz` contains fixed `_helpers.tpl` file:
```
helm package "./config/helm/chart/default/" -d "." --app-version "9.9.9" --version "9.9.9"
```
=> Changes the default registry in the helm chart from docker.io to public.ecr.aws

config/helm/chart/default/README.md, config/helm/chart/default/templates/_helpers.tpl, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml
cherry-pick from [release-1.0](https://github.com/Dynatrace/dynatrace-operator/pull/2738) to `main`
=> Changes the default registry in the helm chart from docker.io to public.ecr.aws - main

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, doc/api/dynakube-api-ref.md, pkg/api/v1beta1/dynakube/oneagent_types.go, pkg/api/v1beta1/dynakube/properties.go, pkg/api/v1beta1/dynakube/properties_test.go, pkg/controllers/dynakube/oneagent/daemonset/arguments.go, pkg/controllers/dynakube/oneagent/daemonset/daemonset_test.go, pkg/webhook/validation/dynakube/config.go, pkg/webhook/validation/dynakube/oneagent.go, pkg/webhook/validation/dynakube/oneagent_test.go
[PR for main branch](https://github.com/Dynatrace/dynatrace-operator/pull/2748)
Adds `spec.oneAgent.hostGroup` field to the Dynakube.
Prints warning when `spec.oneAgent.cloudNativeFullStack.args` is used to set host group.
`--set-host-group` argument of `daemonset.OneAgent.Containers[dynatrace-oneagent]` container is set to `oneAgent.hostGroup` value if new field is specified.
Deploy CN dynakube with `--set-host-group=oldgroup` argument and `oneagent.hostGroup=newgroup`:
```
spec:
oneAgent:
hostGroup: newgroup
args:
- "--set-host-group=oldgroup"
```
- you should see validation warning
- `Deployment status`/`OneAgents`/\<host\> `Host group:` link is set to `newgroup`
- OneAgent pods - `kctl describe daemonset.apps/dynakube-oneagent`
```
Containers:
dynatrace-oneagent: …
```
=> Adds spec.oneAgent.hostGroup field (release-1.0)

.github/actions/upload-helm/action.yaml, .github/workflows/release.yaml
Reworks how we do helm pushes to include Amazon ECR. Moves login logic from action to workflow as it is only called there, adds login to ECR steps to workflow and reuses helm upload action for ECR.
Not as convenient as I would like to: when running next release 😞 
=> Push Helm Chart to ECR on Release

pkg/controllers/edgeconnect/version/updater.go, pkg/controllers/edgeconnect/version/updater_test.go
To remain consistent with the DynaKube and avoid confusion, we will not support `autoUpdate` for custom image repositories.
This is so we can avoid requiring the `customPullSecret` for custom image registries.
We will still use the registry to get the version(digest) that allows `autoUpdate` to function.
- This is because we don't have an endpoint in the Dyntrace API to check which is the latest EdgeConnect version.
- The default registry is `docker.io`, so no `customPullSecret` is needed
I left in that if only the `imageRef.Tag` is not default we still get the digest, this is mainly an implementation detail, also its security best practice to use to digest, which is a plus.
The unit-tests are pretty straight forward.
But you can get an edgeconnect image from …
=> Only support autoUpdate for default registry in EdgeConnect

hack/make/go.mk, hack/make/images.mk, hack/make/prerequisites.mk, hack/make/tests/e2e.mk
Add missing comments in make commands
If there is no comment on the make command, `$ make` doesn't show it.
=> Add missing comments to make commands

pkg/api/v1beta1/dynakube/feature_flags.go, pkg/webhook/validation/dynakube/config.go, pkg/webhook/validation/dynakube/deprecation.go, pkg/webhook/validation/dynakube/deprecation_test.go
In this PR the deprecated feature-flag prefix `alpha.operator.dynatrace.com/feature-` and all code handling warnings if used got removed.
Set a feature flag with the deprecated prefix in the DynaKube. 
* You should NOT see a warning 
* The setting changed must not take effect (!)
=> Remove deprecated `alpha.operator.dynatrace.com/feature-` feature-flag prefix

pkg/api/v1beta1/dynakube/feature_flags.go, pkg/webhook/validation/dynakube/config.go, pkg/webhook/validation/dynakube/deprecation.go, pkg/webhook/validation/dynakube/deprecation_test.go
=> Remove deprecated alpha.operator.dynatrace.com/feature- feature-flag prefix (main)

test/testdata/network/proxy-ssl.yaml
Pin squid image for proxy with SSL `test/testdata/network/proxy-ssl.yaml`, new release 6.7 has broken `run.sh`
I've created an issue in https://github.com/b4tman/docker-squid/issues/130
`make test/e2e/cloudnative/istio`
=> pin squid image version

pkg/api/v1beta1/dynakube/properties.go, pkg/controllers/dynakube/oneagent/daemonset/arguments.go, pkg/controllers/dynakube/oneagent/daemonset/arguments_test.go, pkg/injection/startup/dtclient_builder.go, pkg/injection/startup/run.go, pkg/webhook/validation/dynakube/oneagent_test.go
[PR release-1.0 branch](https://github.com/Dynatrace/dynatrace-operator/pull/2776)
`oneAgent.hostGroup` parameter is passed to code modules in case of application monitoring mode. In such a case standalone logic adds `hostGroup` field to the ProcessModuleConfig configuration and additionally standalone dynatrace client applies `hostGroup` to requests which can use it (getProcessModuleConfig).
`oneAgent.hostGroup` parameter has higher priority then `--set-host-group` argument for all related deployment modes (having `args` field). Validation webhook print a warning every time the argument is used.
`hostGroup` is used:
1) Deploy ApplicationMonitoring dynakube
```
oneAgent:
hostGroup: appmongroup
applicationMonitoring:
useCSIDriver: false/true
```
- check init secret in a monitored namespace …
=> Use oneAgent.hostGroup in ApplicationMonitoring mode

pkg/api/v1beta1/dynakube/properties.go, pkg/controllers/dynakube/oneagent/daemonset/arguments.go, pkg/controllers/dynakube/oneagent/daemonset/arguments_test.go, pkg/injection/startup/dtclient_builder.go, pkg/injection/startup/run.go, pkg/webhook/validation/dynakube/oneagent_test.go
[PR main branch](https://github.com/Dynatrace/dynatrace-operator/pull/2772)
`oneAgent.hostGroup` parameter is passed to code modules in case of application monitoring mode. In such a case standalone logic adds `hostGroup` field to the ProcessModuleConfig configuration and additionally standalone dynatrace client applies `hostGroup` to requests which can use it (getProcessModuleConfig).
`oneAgent.hostGroup` parameter has higher priority then `--set-host-group` argument for all related deployment modes (having `args` field). Validation webhook print a warning every time the argument is used.
`hostGroup` is used:
1) Deploy ApplicationMonitoring dynakube
```
oneAgent:
hostGroup: appmongroup
applicationMonitoring:
useCSIDriver: false/true
```
- check init secret in a monitored namespace …
=> Use oneAgent.hostGroup in ApplicationMonitoring mode (release-1.0)

pkg/controllers/dynakube/activegate.go, pkg/controllers/dynakube/activegate/reconciler.go, pkg/controllers/dynakube/activegate/reconciler_test.go, pkg/controllers/dynakube/activegate_test.go, pkg/controllers/dynakube/controller.go, pkg/controllers/dynakube/controller_test.go
A reconciler should call all reconciler it depends on.
In case of the active gate reconciler this was not the case and is fixed here.
- Run dynakube with activegate and check if everything works as before
=> Move relevant reconciler calls inside ActiveGate reconciler

codecov.yml
Couldn't find the reason of never ending `Processing` state for some commits on `codecov` site. Neither was able to reproduce the problem using my forked project.
I want to use this setting to check if it simplify processing on codecov side. 
Configuration file is valid.
```
curl -X POST --data-binary @codecov.yml https://codecov.io/validate
```
=> CodeCov: never ending Processing state

.github/workflows/ci.yaml
=> Enable verbose mode of codecov-upload GH action

config/helm/chart/default/tests/Common/webhook/mutatingwebhookconfiguration_test.yaml, config/helm/chart/default/values.yaml
Increase mutatingwebhookconfiguration timeout to 10s
Deploy operator -> mutatingwebhook config should have set 10s as timeout
=> Increase mutatingwebhookconfiguration timeout to 10s

.github/scripts/create-cluster.sh, .github/scripts/destroy-cluster.sh, .github/scripts/run-test.sh, .github/workflows/run-e2e-tests.yaml
New Github action running E2E tests daily at 4:00 AM (I will update this to 00:00 AM once I remove the 'old' concourse pipeline; this is just to not overlap them).
Once this action is successfully executed overnight, I will remove the concourse pipeline.
Check previous executions (e.g. https://github.com/Dynatrace/dynatrace-operator/actions/runs/8081015061)
In that case, Openshift failed because of timeout in cluster creation, now I set the timeout to 60min.
=> Add Github action running nightly E2E tests

.github/workflows/run-e2e-tests.yaml
Tonight E2E github action failed because the cluster was still in destroying state (because of concourse E2E tests). Im setting this to 5 AM so the cluster has more time to be ready.
Also, I set `workflow_dispatch` as an event trigger, so we can trigger the E2E tests manually on any branch.
Workflow dispatch can only be tested when the changes are on the main branch.
=> Set E2E execution at 5AM and make the workflow dispatchable

hack/make/tests/e2e.mk, pkg/controllers/dynakube/version/healthconfig.go, pkg/util/dtversion/dtversion.go, pkg/util/dtversion/dtversion_test.go, test/features/publicregistry/publicregistry.go, test/helpers/components/dynakube/options.go, test/scenarios/standard/standard_test.go
Adds a e2e test for public-registry images, just to verify that the operator configures them correctly, so they start up.
- Uses the ECR public-registry
- Always uses the latest versions available on said registry
Has also a bit of a refactor for semver conversion.
run `make test/e2e/publicregistry`
=> Re-add simpler public-registry e2e test

cmd/csi/server/builder.go, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, pkg/controllers/csi/driver/server.go, pkg/controllers/csi/driver/volumes/app/publisher.go, pkg/controllers/csi/driver/volumes/app/publisher_test.go, pkg/controllers/csi/driver/volumes/host/publisher.go, pkg/controllers/csi/driver/volumes/host/publisher_test.go
The csi-server does not do requests that care about DNS while the csi-provisioner does, so the startup-probe fits there better.
(also removes some deadcode)
Deploy operator, startup-probe is on the csi-provisioner and not the server
(otherwise everything should work as expected)
=> Move startup-probe from csi-server to csi-provisioner

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml
cherry pick of #2823 (without the deadcode removal, due to conflicts)
same as #2823
=> Move startup-probe from csi-server to csi-provisioner #2823

README.md
Fix link to uninstall the dynatrace-operator on Openshift (official help page).
Doc only, verify link
=> Update README.md - change link to uninstall doc

.github/scripts/create-cluster.sh, .github/scripts/destroy-cluster.sh, .github/scripts/run-e2e-tests.sh, .github/workflows/e2e-tests.yaml, .github/workflows/run-e2e-tests.yaml
Now that we turned off Concourse pipeline, we can set the execution time to 00:00 AM.
Now, the E2E tests dispatchable workflow can be executed targeting any branch. The way it works:
- Checkout GH action reference branch
- Checkout target branch
- Use reference branch scripts to run `make test/e2e` on the checked-out target branch (this is necessary in order to not have to cherry-pick the scripts in all branches)
- Profit
[Check previous execution targeting release-1.0](https://github.com/Dynatrace/dynatrace-operator/actions/runs/8114068207)
=> Set E2E execution at 0AM and tweak dispatchable workfow

.github/workflows/e2e-tests.yaml
I noticed that on `scheduled` event trigger, the default value from workflow_dispatch is not used. This fixes it.
Wait for tomorrow
=> Fix default value in E2E action

.github/workflows/e2e-tests.yaml
Whenever the E2E tests workflow fails, send a notification to the `int-cp-operator` channel.
Tested in sandbox workspace
=> Add Slack notification when E2E fails

.github/scripts/run-e2e-tests.sh, .github/workflows/e2e-tests.yaml
Update FLC environments where we run our E2E tests. Now, we use the latest version ones.
https://github.com/Dynatrace/dynatrace-operator/actions/runs/8170692777
=> Run E2E tests in latest FLC version environments

.github/scripts/run-e2e-tests.sh
Fix API URL on Edgeconnect test secret file
///
=> Fix edgeconnect url in E2E tests

.github/workflows/e2e-tests.yaml
Missing step to be triggered always on K8s.
Follow-up user story will handle smart destroyment of clusters (not destroying them always, keeping them alive and doing the cleanup on the next execution if so).
---
=> Destroy FLC cluster after E2E execution

.github/workflows/e2e-tests.yaml
Now we also get a SUCCESS message in Slack if the E2E tests pass :smile: 
Tonight will happen
=> Add E2E tests slack notification when PASSED tests

.github/workflows/e2e-tests.yaml
Turns out is not as easy as I thought to have both FAIL and PASS notifications after E2E tests. This steps failed last night.
Falling back to only having FAIL notification, and will create a story to improve on this as it's taking more time.
Tested on previous workflow runs
=> Fallback E2E success notification

CONTRIBUTING.md, hack/build/build_image.sh
When working on ARM building for GKE test environments became a nuisance with podman. To recreate docker behaviour and override podman defaulting to local architecture I introduced an ENV var that can be set to override podman platform:
read contributing.md to see how to set up (and check the doc at the same time), then build and deploy to your cluster. 
expected outcome:
* no change if Env var not set (in CI pipelines)
* no change for Linux/Windows users that run on x86 machines
* Apple M1-3 users should build linux/amd64 images
=> Build for AMD64 clusters on ARM dev machines

.github/scripts/run-e2e-tests.sh, .github/workflows/e2e-tests.yaml, hack/make/tests/e2e.mk
e2e test results are published on the `E2E tests` workflow page.
The main e2e tests can be executed in two ways:
1. to see output on the console:
- test/e2e/standard
- test/e2e/istio
- test/e2e/release
2. to save test results to the `results/` directory:
- test/e2e/standard/publish
- test/e2e/istio/publish
- test/e2e/release/publish
Each `target` creates one file so the following files are created when tests are run by the `e2e-tests` workflow:
- standard.xml
- istio.xml
- release.xml
The workflow then collect data from all files and adds `Test Results` part to the `Summary` page.
Execute e2e tests from github actions.
=> Publish e2e test results on github

hack/build/build_image.sh
We shouldn't quote variable to avoid issue with command.
`make build`
=> fixup quotes image build

go.mod, pkg/controllers/dynakube/proxy/consts.go, pkg/controllers/dynakube/proxy/reconciler.go, pkg/controllers/dynakube/proxy/reconciler_test.go
Add scheme field in Proxy secret
- Unit tests
- Check `<dynakube>-internal-proxy` secret data -> new field "scheme"
=> Add scheme field in proxy secret

pkg/webhook/mutation/pod_mutator/dataingest_mutation/mutator.go, pkg/webhook/mutation/pod_mutator/dataingest_mutation/mutator_test.go
Set the Webhook Pod mutation kind annotation to lower case, according to DT semantic dictionary (https://bitbucket.lab.dynatrace.org/projects/DEUS/repos/semantic-dictionary/browse/source/fields/k8s.yaml)
- Unit tests
- Deploy an app workload and check its pods annotations, should contain the workload kind in lower case
=> Lower case kind annotation on webhook pod mutation

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, doc/api/dynakube-api-ref.md, pkg/api/v1beta1/dynakube/dynakube_types.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/config.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/ssl_volume.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/ssl_volume_test.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/trustedcas_volume.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/trustedcas_volume_test.go
We want ActiveGate to be able to communicate with other HTTPS servers (proxy, dynatrace server) using custom TLS certificates.
`dynakube.spec.trustedCAs` configmap is automatically mounted to the ActiveGate pod. `entrypoint.sh` script of the AG image imports all certificates and configures AG accordingly.
Unittests:
```
make go/test
```
Using a HTTPS proxy with custom certificate:
```
activeGate:                                                                                                                                                                                                                                                                                                                                                                                 
capabilities: …
```
=> Mount trustedCAs configmap to the ActiveGate pod

pkg/controllers/dynakube/version/reconciler.go, pkg/controllers/dynakube/version/reconciler_test.go, pkg/controllers/dynakube/version/updater_test.go
We don't want to block a reconciliation if we fail to refresh the version information for a given component.
So we only fail the version reconcile for a component if there is nothing to fall back to; otherwise, we log the error (for specific components that even have a condition `VerificationFailed`) and move on.
The unit test is pretty straightforward, otherwise, you can:
Deploy a Dyankube that will do some "version-reconciling","" check that I didn't break the default behavior.
Then, somehow try to break the few requests we do for version reconciling. (one way would be to lower the latest oneagent in the tenant, so the downgrade check will fail)
And notice that everything is fine because we just fallback to the previous version.
=> Version reconcile only fails if there is no version info in the status

test/features/cloudnative/codemodules/codemodules.go
Agent binary got bigger, to fix the E2E test we need to increase the storage size delta.
Failed E2E -> https://github.com/Dynatrace/dynatrace-operator/actions/runs/8444596233
We will see tonight
=> Increase codemodules storage size delta in E2E tests

.golangci.yml, pkg/api/v1alpha1/dynakube/dynakube_types.go, pkg/api/v1beta1/dynakube/dynakube_types.go
Currently our OLM make bundle script fails with: 
`/tmp/build/58f3eac1/dynatrace-operator/pkg/api/v1alpha1/dynakube/dynakube_types.go:326:1: expected comma, got "." (at <input>:1:56)
/tmp/build/58f3eac1/dynatrace-operator/pkg/api/v1alpha1/dynakube/dynakube_types.go:326:1: expected comma, got "." (at <input>:1:56)
/tmp/build/58f3eac1/dynatrace-operator/pkg/api/v1beta1/dynakube/dynakube_types.go:70:1: expected comma, got "." (at <input>:1:56)
/tmp/build/58f3eac1/dynatrace-operator/pkg/api/v1beta1/dynakube/dynakube_types.go:70:1: expected comma, got "." (at <input>:1:56)
FATA[0000] Error generating kustomize files: error getting ClusterServiceVersion base: error generating ClusterServiceVersion definitions metadata: one or more API packages had type errors 
`
make bundle
=> Fix OLM release workflow

pkg/injection/startup/dtclient_builder.go
Remove proxy value from init log, as it could result in leaking credentials
Set a proxy in the Dynakube -> look at the initContainer logs
=> Remove proxy value from init log

pkg/api/v1beta1/dynakube/certs.go, pkg/api/v1beta1/dynakube/test/certs_test.go, pkg/consts/agent_injection.go, pkg/injection/namespace/initgeneration/initgeneration.go, pkg/injection/namespace/initgeneration/initgeneration_test.go, pkg/injection/startup/dtclient_builder.go, pkg/injection/startup/dtclient_builder_test.go, pkg/injection/startup/files.go, pkg/injection/startup/files_test.go, pkg/injection/startup/run.go, pkg/injection/startup/run_test.go, pkg/injection/startup/secret.go, pkg/injection/startup/secret_test.go, pkg/webhook/mutation/pod_mutator/oneagent_mutation/config.go, pkg/webhook/mutation/pod_mutator/oneagent_mutation/containers.go, pkg/webhook/mutation/pod_mutator/oneagent_mutation/volumes.go, pkg/webhook/mutation/pod_mutator/oneagent_mutation/volumes_test.go
ActiveGate certificates and trustedCAs certificates should be used by the injected agent on application pods. There is a single file only read by the agent (`custom.pem`) which can be used for that purpose so combined certificates from the init secret are stored the file. 
The following properties have been moved to separate fields:
- data.config.trustedCAs -> data.trustedcas
- data.config.tlsCert -> data.agcerts
These fields are mounted directly to the initContainer of the app pod. 
Based on their content, the `Runner` creates `/mnt/share/custom.pem` and `/mnt/share/custom_proxy.pem` files mounted to the application container. The `/mnt/share/custom_proxy.pem` contains `trustedCAs` certificates only because AG is never an HTTP(s) proxy,
AG certs and TrustedCAs can't be combined into …
=> Combined certificates from the init secret propagated to the injected agent

pkg/controllers/dynakube/activegate/internal/proxy/reconciler.go, pkg/controllers/dynakube/activegate/internal/proxy/reconciler_test.go
Adds the default HTTP scheme to the proxy url if it's missing because otherwise `url.Parse` function fails. It returns empty `url.Host` part if there is no scheme.
Unittests.
=> Fix proxy url parsing function

.github/workflows/release.yaml, hack/build/ci/generate-release-notes.sh
Partial revert of #2948 + update to the `release` action step to make the revert actually work properly.
It was decided that the split manifests (for csi and non-csi) was more versatile. 
Running  ./hack/build/ci/generate-release-notes.sh locally should give you an idea how it looks. (the script update)
Checking the `release` action should be done in a fork.
=> Reintroduce split manifests in release note generation

.github/workflows/release.yaml, hack/build/ci/generate-release-notes.sh
cherry pick of #2950
same as #2950
=> Reintroduce split manifests in release note generation (#2950)

cmd/csi/init/builder.go, pkg/api/v1alpha1/dynakube/dynakube_types.go, pkg/api/v1alpha1/dynakube/helpers.go
Disable CSI Driver data migration until release 1.2
Fix linting issues
Unit tests
=> Disable data migration and fix linting issues

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, pkg/api/v1alpha1/dynakube/dynakube_types.go
With this the short names `dk` and `dks` are added to the dynakube CRD. They can then be used with the `kubectl get` command like for example: `kubectl get ds` for daemonset.
Deploy operator with this CRD and try out these commands:
- `kubectl get dk`
- `kubectl get dks`
=> Add short names for dynakube

.gitignore, config/helm/chart/default/templates/Common/operator/clusterrole-operator.yaml, hack/doc/role-permissions2md.py
Updated script that generates the permission table for our components to be compatible with newly added rules:
* Add mapping for Activegate and Edgeconnect
⚠️  Remove Activegate CR permission from Operator cluster role (not used).
Verify markdown permission table is correctly generated:
1. Run `make doc/permission`
2. Verify that `permissions.md` created in project directory is there and correct
If there are missing python packages run the following command (thanks @gkrenn )
```
pip3 install -r hack/requirements.txt
```
=> Add new rules to permission script and remove outdated permission

.github/workflows/ci.yaml, .github/workflows/release.yaml, pkg/arch/amd64.go, pkg/arch/arm64.go, pkg/arch/consts.go, pkg/arch/ppc64le.go, pkg/arch/s390x.go, pkg/controllers/dynakube/activegate/internal/statefulset/statefulset_test.go, pkg/controllers/dynakube/oneagent/daemonset/affinity_test.go, pkg/controllers/dynakube/oneagent/oneagent_reconciler_test.go, pkg/util/kubeobjects/node/affinity.go, pkg/util/kubeobjects/node/affinity_test.go
Adds the possibility to deploy OneAgents and ActiveGates on clusters that run on s390x nodes.
Updates the CI steps to build the Operator's image for s390x.
_Related Jira issue_: [K8S-9512](https://dt-rnd.atlassian.net/browse/K8S-9512)
If the CI passes, and manages to build the image, then that is the most we can do now. 
(otherwise you would need a a390x cluster, those are hard to come by, and another internal team are tasked to test it)
=> Add s390x build support

.github/workflows/renovate.yaml, hack/make/doc.mk, hack/make/prerequisites.mk
[Issue Link](https://dt-rnd.atlassian.net/browse/K8S-9236)
Prerequisites should be automatically installed when a command that requires python is used
Run `make doc/api-ref` and check if it is working
=> Add prerequisites installation to all python commands

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, hack/build/ci/create-manifest.sh
Operator components can be scheduled properly on `s390x` nodes:
- Added missing nodeAffinity/tolerations
- Added missing `s390x` tag to image manifest
Try to pull `s390x` image via manifest.
=> Fix s390x image

pkg/controllers/dynakube/oneagent/daemonset/volumes.go, pkg/controllers/dynakube/oneagent/daemonset/volumes_test.go
[Ticket](https://dt-rnd.atlassian.net/browse/K8S-9893)
Currently the oneagent-ignore-proxy feature flag is not considered, when the new way to mount the proxy to the agent via volume is used.
Create a dynakube with a proxy and the annotation oneagent-ignore-proxy, check if the daemonset of the agent does not have a proxy volume and volume mount
=> Fix ignore-proxy feature flag for oneAgent daemonset

pkg/util/dttoken/token.go, pkg/util/dttoken/token_test.go
This PR covers: if an error occurs, propagate it to the caller
[resolves issue](https://dt-rnd.atlassian.net/browse/K8S-9890)
unit-tests
=> Improve error handling for dt token generator

.golangci.yml, cmd/support_archive/builder.go, pkg/controllers/csi/metadata/sqlite_gorm_client_test.go, pkg/util/dttoken/token_test.go
Remove depreciation warning by replacing gomnd by mnd 
make go/lint
=> fixup: replace gomnd by mnd

config/helm/chart/default/templates/Common/operator/clusterrole-operator.yaml, pkg/api/v1alpha1/edgeconnect/properties.go, pkg/api/v1alpha1/edgeconnect/secret.go, pkg/clients/edgeconnect/client.go, pkg/clients/edgeconnect/client_test.go, pkg/controllers/edgeconnect/controller.go, pkg/controllers/edgeconnect/controller_test.go, pkg/controllers/edgeconnect/deployment/deployment.go, pkg/controllers/edgeconnect/secret/secret.go, pkg/webhook/validation/edgeconnect/host_patterns.go
1) Removes HostAlias from the EC pod.
2) Adds K8S _hostname_ as alias for accessing the K8S API in EdgeConnect provisioning mode with k8sAutomation enabled.
The hostname is constructed following this pattern
```
<edgeconnect-CR-name>.<edgeconnect-CR-namespace>.<cluster-ID>.kubernetes-automation
```
Unittests.
Install EC with `provisioner` mode and K8SAutomation enabled :
```
oauth:
provisioner: true
hostPatterns:
- '*.d.internal.org'
kubernetesAutomation:
enabled: true
```
K8S `hostname` is present on the `ShowDetails/Host Patterns` list on the UI :
```
*.d.internal.org
<CR name>.dynatrace.273ec656-603d-46c8-b5f5-5c47a6903dff.kubernetes-automation
```
Disable K8SAutomation. `Host Patterns` on the UI should contain just 1 entry now :
```
*.d.internal.org
```
=> Adopt EdgeConnect provisioning for K8S API access

pkg/consts/enrichment_injection.go, pkg/injection/startup/env.go, pkg/injection/startup/env_test.go, pkg/webhook/mutation/pod/metadata/workload.go, pkg/webhook/mutation/pod/metadata/workload_test.go
Ticket: https://dt-rnd.atlassian.net/browse/K8S-10007
Fixes the current state of the workload detection, the pod itself is always the default owner of itself, if there is a well known owner in the hierarchy, then we take the highest in line as the owner. There is no more unknown, as the default should be the pod itself
Deploy operator -> create pods with owner references and check the env vars
=> Fix workload owner detection

pkg/controllers/dynakube/activegate/internal/authtoken/conditions.go, pkg/controllers/dynakube/activegate/internal/authtoken/reconciler.go, pkg/controllers/dynakube/activegate/internal/authtoken/reconciler_test.go, pkg/controllers/dynakube/activegate/reconciler.go, pkg/controllers/dynakube/activegate/reconciler_test.go, pkg/controllers/dynakube/controller_system_test.go, pkg/util/conditions/secret.go
Adds new `ActiveGateAuthTokenSecret` condition :
```
- lastTransitionTime: "2024-05-24T10:57:12Z"
message: secret created 0 day(s) ago, token:dt0g02.ABCDEFGH
reason: SecretCreated
status: "True"
type: ActiveGateAuthTokenSecret
```    
`lastTransitionTime` field is updated if:
- token expired and new instance of the secret is created
- k8s client error occurred
- Dynatrace server error occurred
In case of an error the `message` field contains description of the error. Otherwise the message informs about token's lifetime and public part of the token. The field is updated once a day counting down the token's lifetime (it doesn't affect `lastTransitionTime` field).
For example the secret was created on Friday:
```
- lastTransitionTime: "2024-05-24T10:57:12Z" …
```
=> Add Dynakube status condition for the AG dynakube-activegate-authtoken-secret secret

hack/make/manifests/crd.mk
Currently the CRD generation is broken, since the CSI driver was enabled by default in v1.0.0, this leads to the fact that the CRD generated with `make manifests/crd/release` also has other CSI resources in it (daemonset, Roles,...)
`make manifests/crd/release` should only generate the CRD and no other resource should be in the file
=> Fix CRD generation for releases

config/helm/chart/default/questions.yml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml, config/helm/schema.yaml
After some discussions the decision was made that the limit field in the resources of the csi provisioner is not needed due to it not being used frequently enough. So it was decided to remove it.
Ticket: https://dt-rnd.atlassian.net/browse/K8S-9743
- run helm unittests
- deploy operator via helm and check resources of the csi provisioner
=> Remove resources limit field from csi provisioner

.github/workflows/e2e-tests-ondemand.yaml
Currently, if the single job fails, Github will cancel all other jobs, but they are independent, so we want to run all of them.
Also running 2 parallel jobs is a bit slow, so I've increased to 4, since every job takes ~ 2hours or so.
=> Increase matrix: max-parallel and set fail-fast: false

pkg/webhook/validation/edgeconnect/api_server_test.go, pkg/webhook/validation/edgeconnect/config.go, pkg/webhook/validation/edgeconnect/host_patterns_test.go, pkg/webhook/validation/edgeconnect/kubernetes_automation.go, pkg/webhook/validation/edgeconnect/kubernetes_automation_test.go, pkg/webhook/validation/edgeconnect/name_test.go
New validator rejects EdgeConnect CR with KubernetesAutomation enabled or customized ServiceAccountName.
ServiceAccountName is set to the default value on the CRD level so it's never empty. 
1) Unittests.
2) Try to apply EC with KubernetesAutomation enabled and/or customized serviceAccountName :
```
spec:
kubernetesAutomation:
enabled: false / true
serviceAccountName: dynatrace-edgeconnect / test-dynatrace-edgeconnect
```
3) Apply valid EdgeConnect then change value of `enabled` and/or `serviceAccountName` and try to save changes.
=> Add EC validator to reject CR with Kubernetes Automation feature enabled

.github/workflows/e2e-tests-ondemand.yaml
Because there is a configured github environment with all the secrets, and its called E2E
=> fixup ondemand env

pkg/api/v1beta1/dynakube/convert_from.go, pkg/api/v1beta1/dynakube/convert_to.go
We didn't handle the `Annotations` map safely during conversion, which can cause a panic.
Deploy a v1beta2 DynaKube, with no-annotation and `metadataEnrichment.Enabled = true`. (or any new field that would be converted from an annotation)
=> Make conversion nil safe in case of empty annotations

pkg/util/dtotel/otel.go
Setting up OTel requires a specific secret to be created.
This is totally optional, so most of the time this secret won't be there, so logging the error is a bit excessive.
Deploy the operator without having the Otel secret setup,and check the log of the operator is less scary
=> Make otel error log less scary

.github/workflows/renovate.yaml
tl;dr we should checkout from main because create PR against main, not a release-, but we should trigger using release.
rerun-workflow after merging this
=> fixup auto renovate update: we should use main branch

.github/actions/upload-image/action.yaml, .github/workflows/release.yaml, hack/build/ci/get-image-digest.sh, hack/build/ci/upload-docker-image.sh
The last run of the release pipeline failed, as skopeo has incompatible version with docker. Therefore we should try to avoid using skopeo
Fork operator repo and simulate release (or wait for the next release)
=> Avoid using skopeo in release pipeline

.github/scripts/create-cluster.sh
* Check the deployment status of FLC deployments and only continue if deployment was successful.
* Wait for proper OCP setup so teardown can clean up properly.
Run E2E tests with workflow from this branch while using a release branch to run tests against.
=> Add a wait timeout to E2E Test Setup for OCP Environments and Check Result of Deployments for all Environments

.github/workflows/release.yaml, config/helm/chart/default/templates/_platform.tpl, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/chart/default/tests/Google/application_test.yaml, config/helm/chart/default/values.yaml, hack/make/deploy/gke.mk, hack/make/manifests/config.mk, hack/make/manifests/kubernetes.mk, hack/make/tests/e2e.mk
Ticket: https://dt-rnd.atlassian.net/browse/K8S-10194
Formerly we introduced gke-autopilot as a platform to the helm chart in order remove nodeAffinity from the templates, as this caused the deployments to be rejected by warden (policy engine). Since this requierment got removed we can also remove gke-autopilot as platform.
`make manifests`
`k apply -f ~/workspace/dynatrace-operator/config/deploy/kubernetes/kubernetes.yaml`
or 
```
helm install dynatrace-operator config/helm/chart/default \
--namespace dynatrace \
--create-namespace \
--atomic \
--set installCRD=true \
--set csidriver.enabled=false \
--set image="quay.io/dynatrace/dynatrace-operator:snapshot"
```
Check if the operator components are deployed correctly on an gke-autopilot cluster
=> Remove gke-autopilot as platform from helm chart

pkg/controllers/dynakube/activegate/reconciler.go, pkg/controllers/dynakube/activegate/reconciler_test.go, pkg/controllers/dynakube/injection/reconciler.go, pkg/controllers/dynakube/istio/conditions.go, pkg/controllers/dynakube/istio/config.go, pkg/controllers/dynakube/istio/reconciler.go, pkg/controllers/dynakube/istio/reconciler_test.go
[K8S-9578](https://dt-rnd.atlassian.net/browse/K8S-9578?atlOrigin=eyJpIjoiMzk3NmZmOGU3MDQ1NGIwYjg3MjA3MzlhZGE0MTUyMzUiLCJwIjoiaiJ9)
Have conditions for the istio reconciler, for the ActiveGate and CodeModule connection-info ServiceEntry creation logic.
Have “Reasons“ for the following scenarios:
* ServiceEntries and VirualServices created/updated
* Error due to kubernetes API problems
* Run the unit-tests.
* Deploy Istio and a Dynakube with Istio enabled. Describe the DynaKube and look for the newly added conditions starting with `IstioServiceConfigurationFor*`.
=> Add Conditions for ActiveGate and CodeModules to the Istio Reconciler

pkg/webhook/validation/edgeconnect/automation_validation.go, pkg/webhook/validation/edgeconnect/automation_validation_test.go, pkg/webhook/validation/edgeconnect/config.go
see [K8S-10211](https://dt-rnd.atlassian.net/browse/)
Add validation of EdgeConnect configuration to require Provisioner Mode when enabling K8s Automation.
deploy EdgeConnect with
```
...
spec:
...
oauth:
...
provisioner: false
...
kubernetesAutomation:
enabled: true 
```
must be rejected
=> Validate EdgeConnect Automation to Require Provision Mode

pkg/clients/edgeconnect/environment_settings.go
Bump version for settings objects.
Deploy edgeconnect with automation enabled.
=> Bump version for kubernetes settings objects to 0.1.6

cmd/csi/init/builder.go, cmd/csi/provisioner/builder.go, cmd/csi/server/builder.go, cmd/operator/builder.go, cmd/troubleshoot/builder.go, cmd/webhook/builder.go, pkg/logd/logger.go
A rogue log line logging loglevels corrupts the support archive zip if written directly to stdout. Moved logging of loglevel analogous to logging of version string.
Deploy the operator and create a support archive using `--stdout`. Check if resulting zip file can be unpacked. Linux `unzip` was able to handle the corrupted zip file, so try to use other unzippers (e.g. Windows built in zip, 7Zip).
=> Remove log line from support archive zip.

pkg/controllers/csi/gc/binaries.go, pkg/controllers/csi/gc/binaries_test.go, pkg/controllers/csi/gc/reconciler.go, pkg/controllers/dynakube/istio/reconciler_test.go
https://dt-rnd.atlassian.net/browse/K8S-10338 ~(part of the fix, not all)~
Removing the whole folder may cause problems in a quick/messy uninstall.
The idea behind the change is that the `BidirectionalMountPropagation` might not be "fast enough" if we remove the whole folder that was mounted very close (ie.: almost at the same time) to the unmount then it might not get propagated properly, causing the pod with the mount to be stuck forever, and requiring manual.
1. Deploy operator + cloud-native
2. remove operator (cloud-native oneagents should get stuck `Terminating`)
3. reinstall operator (cloud-native oneagents should get unstuck)
=> Make csi-gc less aggressive

pkg/clients/edgeconnect/environment_settings.go, pkg/clients/edgeconnect/environment_settings_test.go, pkg/controllers/edgeconnect/controller.go, pkg/controllers/edgeconnect/controller_test.go
Remove `schemaVersion` from EdgeConnect settings object. It's not necessary.
- Deploy EdgeConnect with `provisioner: true` and `kubernetesAutomation.enabled: true`
- Settings object (located here https://dib18963.dev.apps.dynatracelabs.com/ui/apps/dynatrace.classic.settings/ui/settings/app:dynatrace.kubernetes.connector:connection?gf=all) should be created and deleted after CR deletion
=> Remove schemaVersion from EdgeConnect Settings object

pkg/api/v1beta2/dynakube/dynakube_types.go
Currently the release pipeline fails to generate a csv with following error:
`/tmp/build/58f3eac1/dynatrace-operator/pkg/api/v1beta2/dynakube/dynakube_types.go:71:1: expected comma, got "." (at <input>:1:56)
FATA[0000] Error generating kustomize files: error getting ClusterServiceVersion base: error generating ClusterServiceVersion definitions`
this is due to the comment ends with dot enforcement, which has already been fixed -> seems like a leftover on the release branch
Not at all
=> Fix csv generation

pkg/controllers/dynakube/injection/conditions.go, pkg/controllers/dynakube/injection/reconciler.go, pkg/controllers/dynakube/injection/reconciler_test.go, pkg/controllers/dynakube/istio/reconciler.go, pkg/injection/namespace/ingestendpoint/secret.go, pkg/injection/namespace/initgeneration/initgeneration.go, pkg/util/conditions/error.go, pkg/util/conditions/error_test.go, pkg/util/kubeobjects/secret/secret.go, pkg/util/kubeobjects/secret/secret_test.go
The dynakube conditions should show what happend in our operator.
We want to extend the conditions by the result of the injection reconciler. 
In addition we can cleanup the created secrets when needed.
[Jira Ticket](https://dt-rnd.atlassian.net/browse/K8S-9579)
- Run a dynakube with cloudnative and metrics ingest enabled => check if the 2 created conditions are there
- Remove everathing from the dynakube => check if secrets in monitored namespaces are deleted
=> Add conditions and proper cleanup to injection reconciler

config/helm/chart/default/templates/Common/extensions-controller/role-extensions-controller.yaml, config/helm/chart/default/templates/Common/extensions-controller/serviceaccount-extensions-controller.yaml, config/helm/chart/default/templates/_labels.tpl, config/helm/chart/default/tests/Common/extensions-controller/role-extensions-controller_test.yaml, config/helm/chart/default/tests/Common/extensions-controller/serviceaccount-extensions-controller_test.yaml
[K8S-10119](https://dt-rnd.atlassian.net/browse/K8S-10119)
Add EEC `ServiceAccount` and Openshift's `Role` and `RoleBinding` to Helm chart.
- `make test/helm`
- `make deploy/helm`, check that `ServiceAccount` exists. 
- `Role` and `RoleBinding` should only exist when deploying on Openshift.
=> Add EEC ServiceAccount, Role and RoleBinding to Helm chart

pkg/api/v1alpha1/edgeconnect/edgeconnect_types.go, pkg/api/v1alpha1/edgeconnect/edgeconnect_types_test.go, pkg/clients/edgeconnect/client.go, pkg/clients/edgeconnect/client_test.go, pkg/clients/edgeconnect/edgeconnect.go, pkg/clients/edgeconnect/iface.go, pkg/controllers/edgeconnect/controller_test.go, pkg/controllers/edgeconnect/secret/secret.go, pkg/controllers/edgeconnect/secret/secret_test.go, test/mocks/pkg/clients/edgeconnect/client.go
The wrong (incomplete) hostname was used for host restrictions in the EdgeConnect config file. This has been fixed. Additonally, `HostMappings` was moved to keep dependencies cleaner.
Deploy EdgeConnect wtih enabled `kuberneteAutomation` and check the EdgeConnec configuration.
=> Fix wrong hostname used for Kubernetes API in EdgeConnect configuration.

pkg/api/v1beta1/dynakube/convert_from.go, pkg/api/v1beta1/dynakube/convert_from_test.go, pkg/api/v1beta1/dynakube/convert_to.go
Currently the conversion of the replicas field of the activeGate is broken -> it is always converted to 1 (default value)
Apply a Dynakube in v1beta1 and replicas of activeGate set to > 1 -> check if the replicas are kept after conversion to v1beta2 happened
=> Fix activeGate replica conversion

config/helm/chart/default/templates/Common/extensions-opentelemetry-collector/clusterrole-extensions-opentelemetry-collector.yaml
The namespace for the ServiceAccount we are binding the ClusterRole is missing.
Run `make deploy/helm`, and it shouldn't fail
=> Add the missing ns in the service-detector CRB

pkg/oci/dockerkeychain/docker_keychain.go, pkg/oci/dockerkeychain/docker_keychain_test.go
https://dt-rnd.atlassian.net/browse/K8S-10501
The image pulling logic in the operator always expects a pull-secret to be present. Even if it doesn’t make sense. (public images) Since recently we stopped generating the default pull-secret for appmon (reasoning was that in the default scenario appmon doesn’t pull an image, but gets a zip file.)
Fixed version: 
`{"level":"info","ts":"2024-07-03T16:07:03.426Z","logger":"csi-provisioner","msg":"csi directories exist","path":"/data/asj34817"}
{"level":"info","ts":"2024-07-03T16:07:03.449Z","logger":"docker-keychain","msg":"No registry pull secret loaded","name":"dynakube-luhi-v2-pull-secret","namespace":"dynatrace","err":"secrets \"dynakube-luhi-v2-pull-secret\" not found"}
{"level":"info","ts":"2024-07-03T16:07:03.449Z","logger":"oneagent-image …
=> Fix pull secret not found error preventing codeModulesImage download

pkg/controllers/csi/provisioner/controller.go, pkg/controllers/csi/provisioner/controller_test.go
Ticket: https://dt-rnd.atlassian.net/browse/K8S-10521
If the download of the codemodule fails, the csi-driver will not do a faster requeue (ie.: retry) to try to download the codemodule again. We should do a faster reconcile in such scenarios
Deploy a Dynakube -> set a wrong image in the codeModulesImage field
=> Fix reconcile interval incase of an error when updating the agent in the provisioner

pkg/api/v1beta2/dynakube/properties.go, pkg/api/v1beta3/dynakube/properties.go, pkg/controllers/csi/provisioner/controller.go, pkg/controllers/dynakube/activegate/internal/statefulset/statefulset.go, pkg/controllers/dynakube/activegate/internal/statefulset/statefulset_test.go, pkg/controllers/dynakube/controller.go, pkg/controllers/dynakube/controller_system_test.go, pkg/controllers/dynakube/controller_test.go, pkg/controllers/dynakube/dtpullsecret/reconciler.go, pkg/controllers/dynakube/oneagent/daemonset/arguments_test.go, pkg/controllers/dynakube/oneagent/daemonset/daemonset.go, pkg/controllers/dynakube/oneagent/daemonset/daemonset_test.go, pkg/injection/codemodule/installer/image/installer.go, pkg/injection/codemodule/installer/image/installer_test.go, pkg/oci/dockerkeychain/docker_keychain.go, pkg/oci/dockerkeychain/docker_keychain_test.go
[K8S-10395](https://dt-rnd.atlassian.net/browse/K8S-10395)
All dynakube image pull secrets added to OneAgent, ActiveGate specs.
All dynakube image pull secrets used by csi.ImageInstaller.
EdgeConnect controller uses registry.Client but depends on EdgeConnect.Spec.CustomPullSecret.
dynakube.controller.registryClientBuilder is not used (~registry.Client~).
csiprovisioner.OneAgentProvisioner.registryClientBuilder is not used (~registry.Client~).
How it works:
dockerAuth(s) loaded by `configFile.LoadFromReader(...)` from different secrets are stored in a single instance of `configFile.AuthConfigs` map. `configFile.LoadFromReader(...)` basically does `map[k] = v` so it works for many secrets.
See:
- https://github.com/docker/cli/blob/master/cli/config/config.go#L106
- …
=> Add all pull secrets to all components

.github/renovate.json5, pkg/util/dtotel/otel.go
This PR resolves problem of updating manually each go-monorepo update of go.opentelemetry.io/otel/semconv/v<version>. 
It's confusing I know, but this package has different repo and different RELEASE version, thats why solution includes:
1. Upgrade main monorepo packages (go based)
2. Find and update otel.go (import version using github-release)
3. Group 2 set of changes into one
😅 😅 😅 😅 😅 
Validated in my fork https://github.com/andriisoldatenko/dynatrace-operator/pull/50/files
=> Update renovate config to automate OTEL go-monorepo update to include bump for "go.opentelemetry.io/otel/semconv/v<version>"

pkg/api/v1beta2/dynakube/validation/oneagent.go, pkg/api/v1beta2/dynakube/validation/oneagent_test.go, pkg/api/v1beta2/dynakube/validation/validation.go
see [K8S-10190](https://dt-rnd.atlassian.net/browse/K8S-10190)
The operator should reject OneAgent versions that are not conformant to major.minor.patch pattern subset of SemVer. e.g. 1.0.0
Apply a DK with OneAgent version set to an invalid version such as `latest`, `raw` or `1.296.0-raw` and to a valid one such as 1.296.0
=> Add Verification of OneAgent Version

.github/workflows/e2e-tests-ondemand.yaml
Default mode (main branch) prints an empty branch value. This fixes it.
There is no need; it's exactly the same in the working workflow `e2e-tests.yaml`.
=> Fix ondemand E2E slack message

pkg/controllers/csi/driver/volumes/host/publisher.go, pkg/controllers/csi/driver/volumes/host/publisher_test.go
If the OSAgents were removed forcefully, we might not get the unmount request, so we can't fully relay on the database, and have to directly check if its mounted or not.
Deploy OSAgents, **force** delete 1, it should be able to come back up.
=> Handle the force-delete scenario in the OS volume publisher

doc/coding-style-guide.md
This PR update style-guide accordingly to https://dt-rnd.atlassian.net/browse/K8S-10064
Read it and compare with https://github.com/Dynatrace/dynatrace-operator/pull/3451 changes
=> update style guide, accordingly to recent changes for all import changes for CR

Dockerfile
Update CSI driver sidecars to latest versions:
- registrar: #3470
- livenessprobe: #3471
CSI driver functionality works as before.
=> Update registrar to v2.11.1 and livenessprobe to v2.13.1 (release-1.3)

pkg/api/v1beta3/dynakube/properties.go, pkg/controllers/dynakube/activegate/capability/capability.go, pkg/controllers/dynakube/activegate/capability/capability_test.go, pkg/controllers/dynakube/activegate/internal/capability/service.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/serviceport.go, pkg/controllers/dynakube/activegate/reconciler_test.go
see [K8S-10118](https://dt-rnd.atlassian.net/browse/K8S-10118)
ActiveGate is also created when Extensions are enabled in the DynaKube. No other AG capabilities are needed.
1) Unittests.
2) Apply dynakubes below. ActiveGate pod should be always created.
Check enabled capabilities on the AG pod using:
```
kubectl -n dynatrace get -o yaml pod/dynakube-activegate-0 -o jsonpath="{.spec.containers[0].env[0]}"
```
a)
dynakube:
```
spec:
activeGate:
capabilities:
- routing
replicas: 1
extensions:
prometheus:
enabled: true
oneAgent:
cloudNativeFullStack: {}
```
capabilities:
```
{"name":"DT_CAPABILITIES","value":"MSGrouter,extension_controller"}
```
b)
dynakube:
```
spec:
activeGate:
replicas: 1
extensions:
prometheus:
enabled: true
oneAgent:
cloudNativeFullStack: {}
```
capabilities:
``` …
```
=> Enable ExtensionController in ActiveGate

cmd/webhook/builder.go, config/helm/chart/default/templates/Common/webhook/validatingwebhookconfiguration.yaml, config/helm/chart/default/tests/Common/webhook/validatingwebhookconfiguration_test.yaml, pkg/api/v1beta1/dynakube/dynakube_webhook.go, pkg/api/v1beta1/dynakube/validation/activegate.go, pkg/api/v1beta1/dynakube/validation/activegate_test.go, pkg/api/v1beta1/dynakube/validation/api_url.go, pkg/api/v1beta1/dynakube/validation/api_url_test.go, pkg/api/v1beta1/dynakube/validation/config.go, pkg/api/v1beta1/dynakube/validation/csi_daemonset.go, pkg/api/v1beta1/dynakube/validation/csi_daemonset_test.go, pkg/api/v1beta1/dynakube/validation/dynakube_name.go, pkg/api/v1beta1/dynakube/validation/dynakube_name_test.go, pkg/api/v1beta1/dynakube/validation/image.go, pkg/api/v1beta1/dynakube/validation/image_test.go, pkg/api/v1beta1/dynakube/validation/istio.go, pkg/api/v1beta1/dynakube/validation/istio_test.go, pkg/api/v1beta1/dynakube/validation/namespace_selector.go, pkg/api/v1beta1/dynakube/validation/namespace_selector_test.go, pkg/api/v1beta1/dynakube/validation/oneagent.go, pkg/api/v1beta1/dynakube/validation/oneagent_test.go, pkg/api/v1beta1/dynakube/validation/preview.go, pkg/api/v1beta1/dynakube/validation/preview_test.go, pkg/api/v1beta1/dynakube/validation/proxy_url.go, pkg/api/v1beta1/dynakube/validation/proxy_url_test.go, pkg/api/v1beta1/dynakube/validation/validation.go, pkg/api/v1beta1/dynakube/validation/validation_test.go
With the introduction of versioned validation logic, every DynaKube version should have it's own validation logic. 
This PR adds validation logic for v1beta1.
[Jira](https://dt-rnd.atlassian.net/browse/K8S-10056)
- Apply a v1beta1 dynakube and check if it is validated on creation or update
=> Add versioned validation logic to v1beta1

test/helpers/components/dynakube/dynakube.go, test/helpers/components/edgeconnect/edgeconnect.go, test/helpers/scheme.go, test/scenarios/istio/istio_test.go, test/scenarios/release/release_test.go, test/scenarios/standard/standard_test.go
Instead of randomly saying `<some-group-version>.AddToScheme(envConfig.Client().Resources().GetScheme())` in a function, I added a `Setup` func that does this with all our versions, similar to `pkg/api/scheme/scheme.go`, but setting it for the `envConfig` in a given test-scenario
run `make test/e2e/cloudnative/upgrade`
Sidenote:
- I had to remove my `dynatrace` repo from Helm for some reason because I got the error:
```
E0722 17:15:48.322546   84599 env.go:384] Setup failure: Error: repository name (dynatrace) already exists, please specify a different name: exit status 1
```
(repeated runs worked after)
=> Standardize scheme usage in e2e-tests

pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/config.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/eec.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/eec_test.go, pkg/controllers/dynakube/extension/consts.go, pkg/controllers/dynakube/extension/reconciler_test.go, pkg/controllers/dynakube/extension/secret.go
[K8S-10131](https://dt-rnd.atlassian.net/browse/K8S-10131)
Now, when Prometheus extension is enabled, we mount the EEC token value from the extensions secret to the ActiveGate StatefulSet.
- Apply a dynakube with Prometheus enabled
- Check volume is mounted in ActiveGate pod and that the file with its content exist (via shell, path `/var/lib/dynatrace/secrets/eec/token/eec.token`)
- Apply a dynakube with Prometheus disabled and there shouldn't be any mounts
=> Add modifier to ActiveGate StatefulSet mounting EEC token volume

pkg/util/kubeobjects/statefulset/builder.go, pkg/util/kubeobjects/statefulset/builder_test.go
This PR introduces a statefulSet builder.
> Context: we are going soon to introduce 2 similar stateful sets for OTEL and EEC, so it makes sense to have common logic inside the builder.
`make go/test`
=> Introduce statefulset inside kubeobject

pkg/util/kubeobjects/deployment/query_test.go, pkg/util/kubeobjects/internal/query/query.go
Set owner during update otherwise after an update the owner reference disappears
Wait, or make a small change (add an env) to make an update happen, and see that the owner reference is still present and if you delete the dynakube the related resource is deleted
=> Set owner during update

pkg/controllers/dynakube/apimonitoring/reconciler.go, pkg/controllers/dynakube/monitoredentities/reconciler.go, pkg/controllers/dynakube/monitoredentities/reconciler_test.go
Follow up to: https://github.com/Dynatrace/dynatrace-operator/pull/3447
Because the case of classicFullStack or applicationMonitoring without kubernetes monitoring were not covered correctly we get spammed by errors when there are no monitoredEntitiy during reconcile. Now we do not error but simply log that there are not MEs and return nil.
Apply dynakubes with:
- classicFullStack
- applicationMonitoring without k8s monitoring
- and other possible configurations (the more the better to cover more cases)
See if kubernetesClusterMEID is properly set in the dk status and if something breaks.
=> Fix empty ME case by not throwing an error

pkg/controllers/csi/gc/binaries_test.go, pkg/controllers/csi/provisioner/install.go
Since #3124 the CSI driver provisioner already uses the new tennantUUID from the status, which was planned to be changed later. This leads to issues like #3533 and breaks CSI driver mounts.
This PR reverts the change. 
[Bug Ticket](https://dt-rnd.atlassian.net/browse/K8S-10808)
- Run cloudnativefs
- Create some pods that are injected
- Pods should start up again and be monitored
=> Revert back the tenantUUID change in the CSI driver

pkg/api/v1beta2/dynakube/feature_flags.go, pkg/api/v1beta2/dynakube/properties.go
Readd feature flag to disable CSI volume for host agent in host monitoring (and cloud native fullstack)
Oneagent does not use a CSI volume and is not configured for read only mode.
Host Monitoring does not require CSI driver to be installed (oneagent volume storage required in case of readonly host filesystem):
```yaml
metadata:
annotations:
feature.dynatrace.com/oneagent-readonly-host-fs: "false"
spec:
oneAgent:
hostMonitoring:
env:
- name: "ONEAGENT_ENABLE_VOLUME_STORAGE"
value: "true"
```
Cloud native Fullstack still requires CSI driver for code module injection:
```yaml
metadata:
annotations:
feature.dynatrace.com/oneagent-readonly-host-fs: "false"
spec:
oneAgent:
env:
- name: "ONEAGENT_ENABLE_VOLUME_STORAGE"
value: "true"
```
=> Add feature flag to disable CSI volume

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, pkg/api/v1beta3/dynakube/dynakube_types.go
Value of dynakube.spec.ApiUrl can't be changed.
```
```
Apply a dynakube. Try to change `apiUrl`.
=> Adds immutability attribute to apiUrl field

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml
I used github commit suggestion to change the warning message in my previous [PR](https://github.com/Dynatrace/dynatrace-operator/pull/3570) and forgot to update crd yaml files. Sorry!
=> Updates crd yaml files after apiUrl immutable attribute was added

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, doc/api/dynakube-api-ref.md, pkg/api/v1beta3/dynakube/dynakube_types.go, pkg/api/v1beta3/dynakube/extensions.go, pkg/api/v1beta3/dynakube/log_monitoring_types.go
Jira: https://dt-rnd.atlassian.net/browse/K8S-10533
With this PR the LogAgent is introduced in the CR. It can be configured and applied. It is only added to v1beta3 and no conversion logic is needed. Further logic will be added in follow ups.
Apply dynakubes that use the newly introduced field, check if the fields are correctly set, see if everything works as before. Also read through my comments and correct if necessary.
=> Add logAgent configuration options for Operator

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, doc/api/dynakube-api-ref.md, pkg/api/v1beta3/dynakube/extensions.go, pkg/controllers/dynakube/extension/eec/reconciler_test.go, pkg/controllers/dynakube/extension/eec/statefulset.go
[K8S-10801](https://dt-rnd.atlassian.net/browse/K8S-10801)
Adds `customConfig` field to dynakube.templates.ExtensionController spec.
Specified configmap is mounted to Extension Execution Controller pod.
1) Apply dynakube without EEC custom configuration:
```
extensions:
prometheus:
enabled: true
templates:
imageRef:
repository: ...
tag: ...
```
`dynatrace-extensions-controller-0` POD is running
```
kubectl -n dynatrace describe pod/dynatrace-extensions-controller-0
```
2) Create configmap
```
kubectl -n dynatrace create configmap eec-custom-config --from-literal=runtimeConfig=aaa --from-literal=other.txt=bbb 
```
3) Apply dynakube:
```
extensions:
prometheus:
enabled: true
templates:
imageRef:
repository: ...
tag: ... …
```
=> Adds customConfig field to dynakube.templates.ExtensionController spec

pkg/api/v1beta3/dynakube/properties.go, pkg/controllers/dynakube/extension/eec/reconciler.go, pkg/controllers/dynakube/extension/eec/reconciler_test.go, pkg/controllers/dynakube/extension/eec/statefulset.go, pkg/controllers/dynakube/extension/otel/reconciler.go, pkg/controllers/dynakube/extension/otel/statefulset.go, pkg/controllers/dynakube/extension/otel/statefulset_test.go, pkg/controllers/dynakube/phase.go, pkg/controllers/dynakube/phase_test.go
[K8S-10856](https://dt-rnd.atlassian.net/browse/K8S-10856)
Dynakube deployment status (Error/Deploying/Running) depends also on state of EEC/OtelC statefulsets.
Enable Prometheus mode.
```
spec:
customPullSecret: ...
extensions:
prometheus:
enabled: true
templates:
imageRef:
repository: ...
tag: ...  
```
Deployment status is `Deploying` forever because OtelC POD is in `CrashLoopBackOff` state.
=> Adds EEC and OtelC statefulsets to status.DeploymentPhase equation

.github/actions/preflight/action.yaml, .github/workflows/release.yaml
Ticket: https://dt-rnd.atlassian.net/browse/K8S-10606
Currently we only push the -amd64 image to rhcc, but instead we should now push all architectures to rhcc and also create a manifest (with all architectures) like we do it for all other platforms. 
Do a prerelease or a release (😄 ) and check if the manifest is correctly pushed to rhcc, aswell as the openshift.yaml and openshift-csi.yaml have the correct image (registry.connect.redhat) set
=> Change release workflow to release all architectures to rhcc

.github/workflows/e2e-tests.yaml
In order to have a proper workflow for the e2e tests, we need to change the target for the notification if the tests are failing. This will allow us to run custom things, like creating jira issues etc.
Run e2e test and let the fail
=> Change slack notification target for e2e tests

pkg/controllers/dynakube/extension/eec/reconciler_test.go, pkg/controllers/dynakube/extension/eec/statefulset.go
[K8S-10973](https://dt-rnd.atlassian.net/browse/K8S-10973)
New EEC image requires some changes in the EEC statefulset.
1) Create `extensions-controller-tls` secret
```
openssl req -nodes -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj "/CN=dynakube-extensions-controller.dynatrace"
kubectl create secret tls extensions-controller-tls --cert=cert.pem --key=key.pem
```
2) Create AG `tlsSecretName` secret (use the same export password when asked for)
```
openssl req -nodes -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj "/CN=dynakube-activegate.dynatrace"
openssl pkcs12 -export -inkey key.pem -in cert.pem -out cert.p12
kubectl -n dynatrace create secret generic dynakube-ag-tls --from-file=server.p12=cert.p12 --from-file=server.crt=cert.pem …
```
=> Adapt EEC statefulset to new version of the image

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, pkg/api/v1beta2/dynakube/dynakube_status.go, pkg/api/v1beta3/dynakube/dynakube_status.go, pkg/clients/dynatrace/settings_enrichment_test.go, pkg/controllers/dynakube/metadata/rules/reconciler_test.go, pkg/webhook/mutation/pod/metadata/mutator.go, pkg/webhook/mutation/pod/metadata/mutator_test.go
[K8S-10946](https://dt-rnd.atlassian.net/browse/K8S-10946)
In the `EnrichmentRule` struct `key` was renamed to `source` and `mapping` to `target`. (because the API changed)
same as https://github.com/Dynatrace/dynatrace-operator/pull/3327, but the fields should be different(renamed) in the Status:
```
metadataEnrichment:
rules:
- enabled: true
source: cost-center
target: dt.cost.costcenter
type: LABEL
- enabled: true
source: security-context
target: dt.security_context
type: ANNOTATION
```
=> Rename fields of EnrichmentRules

pkg/controllers/dynakube/extension/eec/reconciler_test.go, pkg/controllers/dynakube/extension/eec/statefulset.go
[K8S-11020](https://dt-rnd.atlassian.net/browse/K8S-11020)
Adds `RuntimeConfigMountPath` environment variable to EEC pod definition if custom `runtimeConfig` file is used.
Changes `ActiveGateTrustedCert` path from `/var/lib/dynatrace/secrets/ag/server.crt` to   `/var/lib/dynatrace/remotepluginmodule/secrets/ag/server.crt`.
Create extensions-controller-tls secret :
```
openssl req -nodes -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj "/CN=dynakube-extensions-controller.dynatrace"
kubectl -n dynatrace create secret tls extensions-controller-tls --cert=cert.pem --key=key.pem
```
Create AG tlsSecretName secret (use the same export password when asked for) :
```
openssl req -nodes -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj …
```
=> Adds RuntimeConfigMountPath env var if custom runtimeConfig is defined

test/helpers/curl/curl.go
The e2e curl helper pod shouldn't be injected. It's only meant to check network traffic, and we shouldn't interfere with it at all.
Run e2e tests (ones that test the network, like the `istio` scenario). Check that the curl pod doesn't get injected.
=> Exclude e2e curl pod from injection

config/helm/chart/default/templates/Common/extensions-opentelemetry-collector/clusterrole-extensions-opentelemetry-collector.yaml, config/helm/chart/default/tests/Common/extensions-opentelemetry-collector/clusterrole-extensions-opentelemetry-collector_test.yaml
Prometheus extensions need more RBAC permissions.
Deploy operator and observe `prometheus-service-detector` ClusterRole. It shall look like this
```
Resources         Non-Resource URLs  Resource Names  Verbs
---------         -----------------  --------------  -----
namepsaces        []                 []              [get watch list]
pods              []                 []              [get watch list]
replicasets.apps  []                 []              [list get watch]
```
=> Add additional permissions to prometheus-service-detector ClusterRole.

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, pkg/api/v1beta2/dynakube/metada_enrichment.go
https://dt-rnd.atlassian.net/browse/K8S-10945
Change default value of metadata enrichment to false
Deploy a dynakube with metaDataEnrichment section but without the enabled flag -> metadataEnrichment should be not enabled and not working
=> Change default value of metadata enrichment

pkg/controllers/dynakube/extension/eec/reconciler_test.go, pkg/controllers/dynakube/extension/eec/statefulset.go, pkg/controllers/dynakube/extension/otel/statefulset.go, pkg/controllers/dynakube/extension/reconciler_test.go, pkg/controllers/dynakube/extension/service.go, pkg/controllers/dynakube/extension/service_test.go, pkg/controllers/dynakube/extension/servicename/naming.go, pkg/controllers/dynakube/extension/utils/naming.go
[K8S-11079](https://dt-rnd.atlassian.net/browse/K8S-11079)
We have two locations where we need the FQDName of the EEC service:
* EEC env var, where it is currently set incorrectly and fixed in this PR
* OTelC
Deploy the operator with extensions and OTelC according to [Stefans PoC docs](https://bitbucket.lab.dynatrace.org/users/stefan.hauth/repos/extensions-demo/browse):
* deploy this branch with `make deploy/helm`
* Create ActiveGate secret like in PoC
* Create TLS secret for communication between EEC and OTelC
* Create DK with Extensions and OTelC enabled like in PoC
_assuming your DK name is dynakube_
* `dynatrace/dynatrace-extensions-controller-0` Env Var `K8sExtServiceUrl` should have FQDName `dynakube-extensions-controller.dynatrace`
* `dynatrace-extensions-collector-0` container …
=> Unify construction of EEC service fully qualified domain name

.github/workflows/ci.yaml, hack/make/manifests/manifests.mk
This PR does 2 things: 
- It speeds up the deepcopy command and adds it to the manifest. This speed improvement is achieved by only searching in the relevant folders
- It adds a check to the CI to verify that the deepcopy files were updated if needed 
[Jira](https://dt-rnd.atlassian.net/browse/K8S-10776)
- change file in the api folder that generates a deepcopy file
- run `make manifests` and check if deepcopy file was updated
=> Add check for deepcopy files to CI

pkg/api/v1beta3/dynakube/properties.go, pkg/controllers/dynakube/connectioninfo/oneagent/reconciler.go, pkg/controllers/dynakube/controller.go, pkg/controllers/dynakube/controller_system_test.go, pkg/controllers/dynakube/controller_test.go, pkg/controllers/dynakube/logmodule/configsecret/conditions.go, pkg/controllers/dynakube/logmodule/configsecret/config.go, pkg/controllers/dynakube/logmodule/configsecret/reconciler.go, pkg/controllers/dynakube/logmodule/configsecret/reconciler_test.go, pkg/controllers/dynakube/logmodule/reconciler.go, pkg/controllers/dynakube/logmodule/reconciler_test.go, pkg/util/kubeobjects/labels/labels.go
[K8S-10615](https://dt-rnd.atlassian.net/browse/K8S-10615)
1. Adds a base reconciler for the LogModule section
2. Adds a small secret reconciler for the `deployment.conf` of the LogModule
Deploy a dk with `logModule.enabled=true`:
- check the conditions on the dk
- check the secret was created (`<dk>-logmodule-config`)
=> Create reconciler for LogModule deployment.conf

test/helpers/tenant/secrets.go
something is left from big removal https://github.com/Dynatrace/dynatrace-operator/pull/3653 and i found accidentally.
=> Remove obsolete OTEL secret e2e struct

pkg/webhook/mutation/pod/metadata/containers_test.go, pkg/webhook/mutation/pod/metadata/env_test.go, pkg/webhook/mutation/pod/metadata/workload.go, pkg/webhook/mutation/pod/metadata/workload_test.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/3783
same as https://github.com/Dynatrace/dynatrace-operator/pull/3783
=> Fix workload Owner lookup in case of not well-known Owner type (#3783)

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, doc/api/dynakube-api-ref.md, pkg/api/v1beta2/dynakube/dynakube_status.go, pkg/consts/enrichment_injection.go, pkg/controllers/dynakube/monitoredentities/reconciler.go, pkg/injection/startup/enrichment.go, pkg/injection/startup/enrichment_test.go, pkg/injection/startup/env.go, pkg/injection/startup/env_test.go, pkg/webhook/mutation/pod/metadata/containers.go, pkg/webhook/mutation/pod/metadata/containers_test.go, pkg/webhook/mutation/pod/metadata/env.go, pkg/webhook/mutation/pod/metadata/env_test.go, pkg/webhook/mutation/pod/metadata/mutator.go, pkg/webhook/mutation/pod/metadata/mutator_test.go
We previously considered that the "cluster-name" is the same as the `entity-id`. This is incorrect the "cluster-name" is the display name of the related entity
Check that both the cluster-name and entity-id are in the enrichment files
```
root@php-glibc-meta-c97978dcf-7rkw6:/var/www/html# cat /var/lib/dynatrace/enrichment/dt_metadata.properties
k8s.container.name=app
k8s.pod.name=php-glibc-meta-c97978dcf-7rkw6
k8s.node.name=gke-marcell-test-default-pool-934ffcd9-qz3m
dt.kubernetes.workload.kind=Deployment
prop=hello
test=test
k8s.namespace.name=php-zib50933-meta
k8s.workload.name=php-glibc-meta
dt.kubernetes.cluster.id=63599eca-d0d4-4c49-803e-c9a251b91033
boop=beep
k8s.pod.uid=abe1e0c2-d139-413d-9346-4ad409cf98ab
k8s.cluster.name=zib50933zib50933zib50933zib50933zib50933  << THIS …
```
=> Propagate both cluster-name and entity-id to enrichment files 

pkg/controllers/dynakube/activegate/reconciler.go
We create an empty configMap on first reconcile, and second reconcile we actually create it with data.
This didn't really cause any issue, as we reconcile multiple times in the initial creation, but still 😅  
Hard to properly, as the original "issue" is hard to catch (for a split second the ag connection-info configmap is empty).
Just checking that the ag connection-info configmap is created properly.
=> Reconcile AG connection-info before creating configmap from it

config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, pkg/api/v1alpha2/edgeconnect/edgeconnect_types.go, pkg/api/v1alpha2/edgeconnect/properties.go, pkg/api/v1alpha2/edgeconnect/validation/name.go, pkg/api/v1alpha2/edgeconnect/validation/name_test.go, pkg/api/v1alpha2/edgeconnect/validation/validation.go, pkg/api/v1beta2/dynakube/dynakube_types.go, pkg/api/v1beta2/dynakube/properties.go, pkg/api/v1beta2/dynakube/validation/dynakube_name.go, pkg/api/v1beta2/dynakube/validation/dynakube_name_test.go, pkg/api/v1beta2/dynakube/validation/validation.go
This reverts commit cc4809062d8933060c6ae8547111cea7ec66dbf7.
Unfortunately, the x-validation properties in the CRD is not supported in OCP 4.10 and 4.11, but the operator does support these versions. So we have to go back to checking the length by hand.
On OCP 4.10 or 4.11 cluster you can successfully apply the CRD
And on every version the name length limit is enforced by the validation
=> Revert "Move CR name length validation to kubebuilder markers (#3665)"

.github/scripts/create-cluster.sh, .github/scripts/destroy-cluster.sh
Improve how we wait for after creating/desctroying test clusters.
Notes:
1. `kubectl wait` already can do what we want:
```
kubectl --namespace dto-ocp-ondemand wait --for jsonpath='{.status.currentState}'=enviro
nment-deployed flcenvironments dto-ocp-4-12 --timeout=10s
error: timed out waiting for the condition on flcenvironments/dto-ocp-4-12
➜  dynatrace-operator git:(revert/x-validation-flags) ✗ echo $?
1
```
2. We should wait for proper status after we destroying cluster.
3. Increased default timeout because OCP clusters not always quick as we want, and extra 5 mins doesn't help much in some cases.
n/a
=> Improve how we wait for status when we create/destroy clusters

config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, pkg/api/v1alpha2/edgeconnect/edgeconnect_types.go, pkg/api/v1alpha2/edgeconnect/validation/api_server_test.go, pkg/api/v1alpha2/edgeconnect/validation/service_account.go, pkg/api/v1alpha2/edgeconnect/validation/service_account_test.go, pkg/api/v1alpha2/edgeconnect/validation/validation.go
As the kubebuilder tags do not work as we hoped they would, we decided to remove this one again.
Reverts: https://github.com/Dynatrace/dynatrace-operator/pull/3763
- run `make test/e2e/supportarchive`
- apply an `edgeconnect` with an empty `serviceAccount` name
- unit tests
=> Revert kubebuilder minimal length tag and go back to custom validation

.github/scripts/destroy-cluster.sh
Problem:
```
Patching environment 'dto-k8s-latest-flc' to 'not-deployed'
flcenvironment.asperitas.dynatrace.com/dto-k8s-latest-flc patched
+ kubectl wait --namespace dto-daily --timeout= --for 'jsonpath={.status.currentState}=environment-not-deployed' flcenvironment dto-k8s-latest-flc
error: invalid argument "" for "--timeout" flag: time: invalid duration ""
```
=> Add DEFAULT_TIMEOUT to destro_cluster to avoid error

config/helm/chart/default/templates/Common/activegate/serviceaccount-activegate.yaml, config/helm/chart/default/templates/Common/edge-connect/serviceaccount-edgeconnect.yaml, config/helm/chart/default/templates/Common/extensions-controller/serviceaccount-extensions-controller.yaml, config/helm/chart/default/templates/Common/extensions-opentelemetry-collector/serviceaccount-extensions-opentelemetry-collector.yaml, config/helm/chart/default/templates/Common/kubernetes-monitoring/serviceaccount-kubernetes-monitoring.yaml, config/helm/chart/default/templates/Common/logmodule/serviceaccount-logmodule.yaml, config/helm/chart/default/templates/Common/oneagent/serviceaccount-oneagent.yaml, config/helm/chart/default/tests/Common/activegate/serviceaccount-activegate_test.yaml, config/helm/chart/default/tests/Common/edgeconnect/serviceaccount-edgeconnect_test.yaml, config/helm/chart/default/tests/Common/extensions-controller/serviceaccount-extensions-controller_test.yaml, config/helm/chart/default/tests/Common/kubernetes-monitoring/serviceaccount-kubernetes-monitoring_test.yaml, config/helm/chart/default/tests/Common/logmodule/serviceaccount-logmodule_test.yaml, config/helm/chart/default/tests/Common/oneagent/serviceaccount-oneagent_test.yaml, config/helm/chart/default/values.yaml
The operator deploys service accounts for all components deployed in the cluster. 
This PR enables adding labels to these service accounts.
Set the rbac values in the values.yaml and check if the labels are there in the service accounts.
=> Allow to configure the annotations of service accounts within helm values

pkg/injection/namespace/mapper/mapper.go, pkg/injection/namespace/mapper/mapper_test.go
[K8S-11291](https://dt-rnd.atlassian.net/browse/K8S-11291)
Problem: When updating a DK with the annotation `feature.dynatrace.com/ignored-namespaces` to include a namespace that should NOT be injected we still inject if it was injected before.
This PR corrects this behaviour.
1. Apply a DK.
2. Deploy a sample application into a namespace `sample-ns` and make sure it get's injected.
3. Update the DK:
```
metadata:
annotations:
feature.dynatrace.com/ignored-namespaces: '["sample-ns.*", "^kube-.*", "^gke-.*", "^gmp-.*",  "dynatrace"]'
```
4. Restart the pod of the sample application.
Make sure the sample application is not injected.
=> Do not inject into ignored namespaces after adding a namespace to the annotation

.github/workflows/e2e-tests-ondemand.yaml, hack/build/ci/update-e2e-ondemand-pipeline.py
https://dt-rnd.atlassian.net/browse/K8S-11301
On-demand pipelines are running for main branch if they are run on schedule.
Check if e2e tests are run for correct release branch on schedule
=> Fix ondemand pipeline target branch if run scheduled

.github/workflows/e2e-tests-ondemand.yaml
on demand action is using release branch scripts to run e2e tests, wich is wrong
Run ondemand piplines and check if they use the correct branch
=> Fix ondemand pipeline using wrong branch for setup scripts

.github/scripts/run-e2e-tests.sh
Add wait for secret is created, before getting it for running e2e tests
you can test concept seperatly, or we can trigger e2e test from branch.
```
kubectl wait --for=create secret andrii-test-client-secret
secret/andrii-test-client-secret condition met
```
=> Add wait for secret is created, before getting it

assets/samples/edgeconnect/automation-workflows.yaml, assets/samples/edgeconnect/edgeconnect.yaml, assets/samples/edgeconnect/provisioner.yaml
Update samples for edgeconnect.
Cherry-pick of 4c94dbd26
n/a
=> Update EdgeConnect samples  (#3734)

pkg/controllers/dynakube/apimonitoring/reconciler.go, pkg/controllers/dynakube/apimonitoring/reconciler_test.go
[K8S-11513](https://dt-rnd.atlassian.net/browse/K8S-11513)
If we update the k8s settings object that already exists, for some reason causes data gaps.
We should avoid updating it, as it was done before v1.3
The diff looks a bit confusing:
- I just moved the `settings.TotalCount > 0` check(and related calls) , before the `r.dtc.CreateOrUpdateKubernetesSetting(...` call
There was a unit-test that was supposed to test for this.
- I fixed it, now it fails with the old logic
Otherwise you have to make it update, and see gaps in the collected data
=> Don't update k8s-settings object, if already present

pkg/api/v1alpha1/edgeconnect/convert_to.go, pkg/api/v1alpha1/edgeconnect/convert_to_test.go
Cherry-pick of bugfix [K8S-11404](https://dt-rnd.atlassian.net/browse/K8S-11404) https://github.com/Dynatrace/dynatrace-operator/commit/a919cae4d5680fba156e8a799e300b5e3e8d2a05
Same as https://github.com/Dynatrace/dynatrace-operator/pull/3852
=> Cherry-pick of K8S-11404 for EdgeConnect empty hostPatterns v1alpha1 to v1alpha2

pkg/api/v1beta3/dynakube/extensions_props.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/eec.go, pkg/controllers/dynakube/extension/consts/consts.go, pkg/controllers/dynakube/extension/eec/reconciler_test.go, pkg/controllers/dynakube/extension/eec/statefulset.go, pkg/controllers/dynakube/extension/otel/statefulset.go, pkg/controllers/dynakube/extension/otel/statefulset_test.go, pkg/controllers/dynakube/extension/reconciler_test.go, pkg/controllers/dynakube/extension/secret.go
Add env var `EEC_DS_TOKEN` to OTelC StatefulSet.
1. Deploy Dynakube with extensions
2. check that env var is set on OTelC pods
```
EEC_DS_TOKEN: <set to the key 'otelc.token' in secret 'ext-dk-extensions-token'>  Optional: false 
```
=> Add EEC_DS_TOKEN env var to OTelC StatefulSet.

config/helm/chart/default/templates/Common/extensions-opentelemetry-collector/clusterrole-extensions-opentelemetry-collector.yaml, config/helm/chart/default/tests/Common/extensions-opentelemetry-collector/clusterrole-extensions-opentelemetry-collector_test.yaml
[DAQ-1459](https://dt-rnd.atlassian.net/browse/DAQ-1459)
Renames the existing ClusterRole `prometheus-service-detector` to `dynatrace-extensions-prometheus`.
Renames the existing ClusterRoleBinding `prometheus-service-detector` to `dynatrace-extensions-prometheus`.
Updates the permissions as shown in the ticket.
1) `make test/helm`
2) deploy dynakube with extensions
=> Rename the existing ClusterRole prometheus-service-detector and update permissions

pkg/controllers/dynakube/activegate/internal/authtoken/reconciler.go, pkg/util/kubeobjects/secret/query.go
[DAQ-1456](https://dt-rnd.atlassian.net/browse/DAQ-1456)
Not much has changed, as this secret is rather unique in the codebase, so only small adjustments made sense,
no big noticeable (biggest one would be that the Auth-token secret now has an ownerReference)
=> Use the secret.Query in the AuthToken reconciler 

config/helm/chart/default/templates/Common/operator/role-operator.yaml, config/helm/chart/default/tests/Common/operator/role-operator_test.yaml
This PR reverts permissions to fix EdgeConnect deployment introduced in https://github.com/Dynatrace/dynatrace-operator/pull/3934: 
```
│ -01a80b9ffd27\" is forbidden: User \"system:serviceaccount:dynatrace:dynatrace-operator\" cannot update resource \"edgeconnects\" in API g │
│ roup \"dynatrace.com\" in the namespace \"dynatrace\"  
```
Deploy Edgeconnect/DK make sure no permission errors
=> Add missing permissions to fix edgeconnect e2e tests

pkg/controllers/dynakube/extension/tls/reconciler.go, pkg/controllers/dynakube/extension/tls/reconciler_test.go
[DAQ-1680](https://dt-rnd.atlassian.net/browse/DAQ-1680)
Extensions self-signed TLS Secret was getting reconciled when `spec.extensions.enabled: false`, which is wrong.
Now we check `r.dk.IsExtensionsEnabled()`, like in the rest of extension reconcilers.
I also renamed the functions for clarity.
- I added a new unit test with this case. It fails to execute it on main, and passes on this branch :heavy_check_mark: 
- To test manually, apply dynakube with `spec.extensions.enabled: false` and check that the secret `<namespace>-extensions-controller-tls` doesn't exist.
[DAQ-1680]: https://dt-rnd.atlassian.net/browse/DAQ-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Do not reconcile extensions self-signed TLS secret when `spec.extensions.enabled: false`

.github/workflows/e2e-tests-ondemand.yaml
[DAQ-1351](https://dt-rnd.atlassian.net/browse/DAQ-1351)
Change ondemand E2E execution to 3:00 AM.
Daily E2E are executed at 12:00 PM, and usually take 2-3 hours, so they shouldn't collide.
---
[DAQ-1351]: https://dt-rnd.atlassian.net/browse/DAQ-1351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Set ondemand E2E tests at 3AM

pkg/injection/startup/secret.go
https://dt-rnd.atlassian.net/browse/DAQ-1677
When using a proxy with auths, the content of username and password is logged in the initContainer logs
1. Deploy Dynatrace the Operator
2. Create Dynakube with a proxy which contains username+password
4. Apply Dynakube
5. Restart monitored application
6. Check the oneagent-init container logs and see that both username and password is logged
=> Fix proxy content logged in init-container logs

.github/actions/preflight/action.yaml, .github/renovate.json5, .github/workflows/release.yaml, config/helm/chart/default/templates/Common/extensions-opentelemetry-collector/clusterrole-extensions-opentelemetry-collector.yaml, config/helm/chart/default/tests/Common/extensions-opentelemetry-collector/clusterrole-extensions-opentelemetry-collector_test.yaml, pkg/controllers/csi/provisioner/controller_test.go, pkg/controllers/csi/provisioner/install.go, pkg/injection/codemodule/installer/image/installer.go, pkg/injection/codemodule/installer/symlink/symlink.go, pkg/injection/codemodule/installer/url/installer.go
[Jira](https://dt-rnd.atlassian.net/browse/DAQ-1361)
**Attention** 
This PR will not be merged into `main` but into `epic/csi-nodb` - our feature branch for the csi no db epic.
With this a symlink is added at the location: `/data/<dk>/latest-codemodule` that points to the codemodule directory (`/data/codemodules/<base64encodedImage/version>`) in the `provisioner` container.
It is maintained in a way that the symlink is always removed and immediatly after created again if:
- agent is being newly installed
- csi driver pod starts but agent is already installed from previous runs
This is done in order to update the codemodule directory and with that also the symlink and to avoid errors because of a mismatch between symlink and codemodule dir (happened to me! I updated the `codeModulesImage` …
=> Add symlink that points to the latest codemodule version

pkg/controllers/dynakube/logmodule/daemonset/reconciler.go, pkg/controllers/dynakube/logmodule/daemonset/reconciler_test.go, pkg/controllers/dynakube/logmodule/reconciler.go, pkg/controllers/dynakube/logmodule/reconciler_test.go
https://dt-rnd.atlassian.net/browse/DAQ-1842
Currently the Dynakube is always set to error phase if there is no kubernetesMEID (e.g because no automatic api monitoring) since the logModule Reconciler always returned an error in this case
Create a cloudNative Dynakube without `kubernetes-monitoring` and without `automatic-api-monitoring` -> check if the phase is correctly set to Runninng
=> Fix dynakube always being set to error phase

pkg/api/v1beta3/dynakube/kspm/kspm.go, pkg/api/v1beta3/dynakube/kspm/props.go, pkg/api/v1beta3/dynakube/kspm_props.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/config.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/kspm.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/kspm_test.go, pkg/controllers/dynakube/kspm/token/reconciler.go, pkg/controllers/dynakube/kspm/token/reconciler_test.go
[DAQ-1343](https://dt-rnd.atlassian.net/browse/DAQ-1343)
- [Brings the kspm api package in line](https://github.com/Dynatrace/dynatrace-operator/commit/63d6cc78cda08cc6211f90787c4a880cea0139c8)
- [Add KSPM modifier to activeGate reconciler](https://github.com/Dynatrace/dynatrace-operator/commit/e35acbb92c8b63ec473b1d00436daf7b21c4858d)
- Just adds a simple volume that contains the token generated  by the Operator, so the ActiveGate and node-configuration-collector can safely communicate
1. Deploy `DynaKube` to test:
```
kind: DynaKube
metadata:
name: dk
spec:
apiUrl: https://<tenant>.dev.dynatracelabs.com/api
kspm:
enabled: true
activeGate:
capabilities:
```
2. You see the `kspm-token` Volume/Mount on the …
=> Configure Activegate for node collector communication

pkg/api/validation/dynakube/oneagent.go, pkg/api/validation/dynakube/oneagent_test.go, pkg/api/validation/dynakube/validation.go, pkg/controllers/nodes/nodes_controller.go
https://dt-rnd.atlassian.net/browse/DAQ-1817
Add validator for OA version. Now it works only for timestamped versions.
We removed it on a previous PR but got the requirement to have it in place for 1.3.2.
Only DynaKubes with versions like this should pass the CR validation when applying:
```yaml
spec:
oneAgent:
version: 1.304.0.20240826-070516
```
=> Add OneAgent version validator

pkg/api/validation/dynakube/kspm.go, pkg/api/validation/dynakube/kspm_test.go, pkg/api/validation/dynakube/validation.go
[DAQ-1352](https://dt-rnd.atlassian.net/browse/DAQ-1352)
For the `KSPM` feature to work, an ActiveGate with the`kubernetes-monitoring` capability also needs to be deployed and configured. This can be simply validated in the webhook
- Should be allowed:
```
kind: DynaKube
metadata:
name: dk
spec:
apiUrl: https://<tenant>.dev.dynatracelabs.com/api
kspm:
enabled: true
activeGate:
capabilities:
```
- Should be rejected:
```
kind: DynaKube
metadata:
name: dk
spec:
apiUrl: https://<tenant>.dev.dynatracelabs.com/api
kspm:
enabled: true
activeGate: {}
```
[DAQ-1352]: https://dt-rnd.atlassian.net/browse/DAQ-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
=> Add simple KSPM dependency validation

.github/workflows/ci.yaml, hack/make/go.mk
https://dt-rnd.atlassian.net/browse/DAQ-1918
Unit tests are currently executed two times on CI, once on `Run unit tests - Run Unit tests and Integration tests` step and another time on `Run unit tests - check code coverage` step.
This PR removes the second execution (which was in `make go/check-coverage`)
Compare CI action executions and see that unit tests are not executed twice on this branch.
New CI -> https://github.com/Dynatrace/dynatrace-operator/actions/runs/11496876194/job/31999373500?pr=3972
Old CI  -> https://github.com/Dynatrace/dynatrace-operator/actions/runs/11495532388/job/31995247239
Code coverage should still be working fine.
=> Run unit tests only once on CI

.github/workflows/self-update-on-new-release-version.yaml, hack/build/ci/update-renovate-json5.py
[DAQ-1716](https://dt-rnd.atlassian.net/browse/DAQ-1716)
The script can't be used to read specific file in any directory. Still can be called in any CurrentWorkingDirectory but the filename is hardcoded.
I tested the `self-update-on-new-release-version.yaml` workflow using my forked repo (`release-1.0` branch exists, I am pushing `release-1.1`)  and it works as expected :
```
baseBranches: [       =>      baseBranches: [
"$default",                   "$default",
"release-1.1",                "release-1.0",
"release-1.2",                "release-1.1",
"release-1.3",             ],
],
matchBaseBranches: [    =>    matchBaseBranches: [
"$default",                   "$default",
"release-1.1",                "release-1.0",
"release-1.2",                "release-1.1",
"release-1.3", …
```
=> Remove vulnerability from the update-renovate-json5.py script

pkg/controllers/dynakube/extension/tls/conditions.go, pkg/controllers/dynakube/extension/tls/reconciler.go, pkg/controllers/dynakube/extension/tls/reconciler_test.go
https://dt-rnd.atlassian.net/browse/DAQ-1717
Add new condition `ExtensionsTLSSecret` when Extensions TLS reconciler generates a self-signed TLS secret
- Deploy Dynakube with extensions enabled and without `tlsRefName`, so the Operator generates the secret and adds the condition.
```yaml
spec:
apiUrl: https://dib18963.dev.dynatracelabs.com/api
extensions:
enabled: true
templates:
imageRef:
repository: extk8sregistry.azurecr.io/eec/dynatrace-eec
tag: 1.301.0.20240826-070516
customPullSecret: azurecr
tokens: dynakube
```
=> Add Dynakube condition for Extensions TLS reconciler

Dockerfile, go.mod
Manual dependency update to mitigate some vulnerabilities in v1.2.3
* Just run the operator and see if normal operation is fine.
=> Update go version, livenessprobe and CSI node driver registrar.

pkg/api/v1beta3/dynakube/activegate/props.go, pkg/api/v1beta3/dynakube/activegate/spec.go, pkg/api/v1beta3/dynakube/activegate_props.go
related to [DAQ-1448](https://dt-rnd.atlassian.net/browse/DAQ-1448)
In the [KSPM DaemonSet PR](https://github.com/Dynatrace/dynatrace-operator/pull/3997) there was an issue, that if no ActiveGate capability was configured that would result in the creation of a `Service` then the node-collector DaemonSet couldn't communicate with the ActiveGate
This should work: (be sure to ONLY set the `kubernetes-monitoring` capability)
```
kind: DynaKube
metadata:
name: dk
spec:
apiUrl: https://<tenant>.dev.dynatracelabs.com/api
kspm:
enabled: true
activeGate:
tlsSecretName: my-secret
capabilities:
customProperties:
value: |
[kubernetes_monitoring]
kubernetes_configuration_dataset_pipeline_enabled = true …
```
=> Create AG service if KSPM is enabled

config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, pkg/controllers/csi/config.go, pkg/controllers/csi/driver/server.go
This PR introduce:
and fixes https://dt-rnd.atlassian.net/browse/DAQ-2252
- switch journal=WAL for SQLite connection string (to avoid lock database error)
- implement rate limiter for Publish/Unpublish grpc server methods
- increase liveness probe to up-to `4s` https://github.com/Dynatrace/dynatrace-operator/pull/4018/files#diff-7e50509ea7a8d1b31acdb20b0d93c4dbb51cb3e5940a654756793cf3b4485462R216 (because under heavy load performance and small limit of CPU usage, response time increases from GRPC server).
1. Deploy Operator release-1.3 version without patch and deploy dk:
```
apiVersion: dynatrace.com/v1beta2
kind: DynaKube
metadata:
name: dynakube
spec:
apiUrl: https://<tenant>.dev.dynatracelabs.com/api
activeGate:
capabilities:
- routing
oneAgent: …
```
=> Implement rate limiter for GRPC server

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, doc/api/dynakube-api-ref.md, doc/api/edgeconnect-api-ref.md, pkg/api/v1beta3/dynakube/metada_enrichment.go
This cosmetic PR fixup e2e tests after this PR https://github.com/Dynatrace/dynatrace-operator/pull/4010
and this commit https://github.com/Dynatrace/dynatrace-operator/pull/4040/commits/ec98559323e0d31b875da787656ab9d939d000d5 updates api-ref.
ticket https://dt-rnd.atlassian.net/browse/DAQ-2310
run e2e tests `make test/e2e/standard`
=> Fixup: e2e tests after remove kubebuilder defaults PR #4010

.github/workflows/self-update-on-new-release-version.yaml, hack/build/ci/update-e2e-ondemand-pipeline.py
The script can't be used to read specific file in any directory. Still can be called in any CurrentWorkingDirectory but the filename is hardcoded.
I have tested it using my forked repo.
=> Removes vulnerability from the update-e2e-ondemand-pipeline.py script

test/features/cloudnative/init_containers.go, test/features/cloudnative/upgrade/upgrade.go
This PR adds `AssessSampleInitContainersOldDk` func to check old init container name, we need it for an upgrade e2e test scenario.
related to https://github.com/Dynatrace/dynatrace-operator/pull/4025
issue: https://dt-rnd.atlassian.net/browse/DAQ-2310
```
make test/e2e/release
```
<details>
<summary>test results</summary>
```
➜  dynatrace-operator git:(main) ✗ make test/e2e/release
go install "sigs.k8s.io/kustomize/kustomize/v5@v5.5.0"
go install "sigs.k8s.io/controller-tools/cmd/controller-gen@v0.16.5"
/Users/andrii.soldatenko/go/bin/controller-gen "crd:crdVersions=v1,maxDescLen=350,ignoreUnexportedFields=true" paths="./..." output:crd:artifacts:config=config/crd/bases
./hack/helm/generate-crd.sh /Users/andrii.soldatenko/go/bin/kustomize config/helm/chart/default//templates//Common/crd/ …
```
=> fix e2e: after rename injected init-container

pkg/controllers/dynakube/apimonitoring/reconciler_test.go, pkg/controllers/dynakube/monitoredentities/reconciler.go, pkg/controllers/dynakube/monitoredentities/reconciler_test.go
Ticket: https://dt-rnd.atlassian.net/browse/DAQ-2355
Currently instead of using the newest and more up-to-date MEID we use the most outdated one as we compare the timestamps (the bigger the more up-to-date it is) incorrectly
Have two MEs for the same clusterID -> check if the one with the bigger timestamp is used for metadata enrichment
=> Fix incorrect comparison of MEID lastSeenTimestamp

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, hack/make/manifests/config.mk, pkg/api/v1beta3/dynakube/activegate/props.go, pkg/api/v1beta3/dynakube/activegate/spec.go, pkg/api/v1beta3/dynakube/activegate_props.go, pkg/api/v1beta3/dynakube/dynakube_types.go, pkg/api/v1beta3/dynakube/otlp_props.go, pkg/controllers/dynakube/activegate/capability/capability.go, pkg/controllers/dynakube/activegate/capability/capability_test.go
[DAQ-1633](https://dt-rnd.atlassian.net/browse/DAQ-1633)
Enables the following capabilities on ActiveGate if OTLP ingest is required: 
- log_analytics_collector
- generic_ingest_enabled
- otlp_ingest
Dynakube.`EnableOtlpIngest` field is a temporary feature switch because it will be defined in follow-ups. It allows to add unit tests but can't be used directly in dynakube.yaml manifest.
:warning: OTLP feature branch is used as base branch.
```
make go/test
```
[DAQ-1633]: https://dt-rnd.atlassian.net/browse/DAQ-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Activate AG capabilities required by OtlpIngest feature

pkg/controllers/dynakube/extension/eec/statefulset.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-2685)
Adds FSGroup to podSecurityContext to allow the EEC app to write to `agent/runtime` volume if it is a PersistenVolume.
1) Deploy dynakube
```
spec:
activeGate:
tlsSecretName: ...
apiUrl: ...
customPullSecret: ...
extensions: {}
templates:
imageRef:
repository: ...
tag: 1.305.0.20241029-011002
useEphemeralVolume: false
```
2) Create a file in agent/runtime directory
```
[]$ kubectl -n dynatrace exec -it pod/dynakube-extensions-controller-0 -- /bin/bash
$ cd /var/lib/dynatrace/remotepluginmodule/agent/runtime
$ touch aaa
$ ls -l
```
3) Make sure there are no error messages in the log
```
2024-11-22 11:06:39.834 UTC [0000000e] warning [native] EventSender: Cannot change mode to reliable, because failed to …
```
=> Adds FSGroup to EEC podSecurityContext

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, pkg/api/v1beta3/dynakube/dynakube_types.go, pkg/api/validation/dynakube/api_url.go, pkg/api/validation/dynakube/api_url_test.go, pkg/api/validation/dynakube/validation.go, pkg/api/validation/dynakube/validation_test.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-2606)
Value of dynakube.spec.ApiUrl can't be changed.
```
[]$ kubectl -n dynatrace patch dynakube.dynatrace.com/dynakube  -p '{"spec":{"apiUrl":"https://<modified apiurl>"}}' --type=merge
Warning: ActiveGate specification missing memory limits. Can cause excess memory usage.
Error from server (Forbidden): admission webhook "v1beta3.dynakube.webhook.dynatrace.com" denied the request: 
1 error(s) found in the DynaKube
1. The DynaKube's specification has mutated APIURL, APIURL is immutable, please delete the CR and then apply new one
```
Apply a dynakube. Try to change apiUrl.
=> Makes ApiUrl immutable

.github/workflows/self-update-on-new-release-version.yaml
follow-up for https://github.com/Dynatrace/dynatrace-operator/pull/4106
ticket https://dt-rnd.atlassian.net/browse/DAQ-2771
```
Pushing pull request branch to 'origin/create-pull-request/update-renovate-json5-fd216618'
/usr/bin/git push --force-with-lease origin create-pull-request/update-renovate-json5-fd216618:refs/heads/create-pull-request/update-renovate-json5-fd216618
To https://github.com/Dynatrace/dynatrace-operator
! [remote rejected]   create-pull-request/update-renovate-json5-fd216618 -> create-pull-request/update-renovate-json5-fd216618 (refusing to allow a GitHub App to create or update workflow `.github/workflows/e2e-tests-ondemand.yaml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/Dynatrace/dynatrace-operator'
Error: The process …
```
=> Create-PR github action requires workflows permissions

.github/workflows/e2e-tests-ondemand.yaml
Add OpenShift 4.16 and K8S 1.30 pipelines to on-demand E2E tests
Run on-demand pipelines.
=> Add new pipelins to on-demand E2E tests.

pkg/api/validation/dynakube/oneagent.go, pkg/api/validation/dynakube/oneagent_test.go
[DAQ-2191](https://dt-rnd.atlassian.net/browse/DAQ-2191)
cherry pick of #4109
same as #4109
[DAQ-2191]: https://dt-rnd.atlassian.net/browse/DAQ-2191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove standalone logMonitoring nodeSelector validation (#4109)

hack/make/manifests/kubernetes.mk, hack/make/manifests/openshift.mk
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-2842)
The `platform` argument was set to `openshift` for both platforms:
```
[]$ make manifests/openshift
...
helm template dynatrace-operator config/helm/chart/default ... --set platform="openshift" ... > config/deploy/openshift/openshift.yaml
```
```
[]$ make manifests/kubernetes
...
helm template dynatrace-operator config/helm/chart/default ... --set platform="openshift" ... > config/deploy/kubernetes/kubernetes.yaml
```
Run `make manifests/*` commands. Check value of the `platform` argument:
```
helm template dynatrace-operator config/helm/chart/default ... --set platform="openshift" ... > config/deploy/openshift/openshift.yaml
```
`make manifests/kubernetes` sets `platform` argument to `kubernetes`
`make manifests/openshift` sets …
=> Fixes 'make manifests' bug caused by overwritten generate_manifest definition

config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml, config/helm/chart/default/templates/Common/kubernetes-monitoring/serviceaccount-kubernetes-monitoring.yaml, config/helm/chart/default/tests/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring_test.yaml, config/helm/chart/default/tests/Common/kubernetes-monitoring/serviceaccount-kubernetes-monitoring_test.yaml, pkg/api/validation/dynakube/modules.go, pkg/controllers/dynakube/kspm/daemonset/reconciler.go
https://dt-rnd.atlassian.net/browse/DAQ-2788
Currently the AG kubernetes-monitoring service account will not exist and validation will prevent KSPM from being enabled, if activeGate rbac is disabled in the helm chart. We should instead create all the resources need if someone wants to only have KSPM enabled in the helm chart, and still allow a Dynakube with a kubeMon AG, to be created.
Install the helm chart with only KSPM rbac enabled (no activeGate), try to apply a Dynakube with KSPM and activeGate with kubernetes Monitoring enabled. Check if AG is started correctly and if SA/cluster roles exist.
=> Create kubernetes-monitoring rbac's if only KSPM is enabled

config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml, config/helm/chart/default/templates/Common/kubernetes-monitoring/serviceaccount-kubernetes-monitoring.yaml, config/helm/chart/default/tests/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring_test.yaml, config/helm/chart/default/tests/Common/kubernetes-monitoring/serviceaccount-kubernetes-monitoring_test.yaml, pkg/api/validation/dynakube/modules.go, pkg/controllers/dynakube/kspm/daemonset/reconciler.go
https://dt-rnd.atlassian.net/browse/DAQ-2788
Same as in #4125
Same as in #4125
=> Create kubernetes-monitoring rbac's if only KSPM is enabled (#4125)

pkg/api/validation/dynakube/logmonitoring_test.go, pkg/api/validation/dynakube/oneagent.go, pkg/api/validation/dynakube/oneagent_test.go
[DAQ-2191](https://dt-rnd.atlassian.net/browse/DAQ-2191)
Enhances the check previously removed in https://github.com/Dynatrace/dynatrace-operator/pull/4109
- With the caveat, that we use the`apiUrl` for checking if DynaKubes use the same tenant
- this is not perfect, because of tenant aliases, but it is considered misconfiguration to use a tenant alias for 1 DynaKube and not for another one. 	
How the nodeSelector validation changed:
- 2 CloudNative (or any OneAgent) on same node with different tenant ==> ⛔  (this is not new)
- 2 LogMonitoring on same node with different tenant ==> 🆗 
- 1 LogMonitoring and 1 CloudNative(or any OneAgent) on same node with different tenant ==> 🆗 
Try recreating the scenarios from the unit-tests
[DAQ-2191]: …
=> Consider logmonitoring in the node-selector check

pkg/api/validation/dynakube/eec.go, pkg/api/validation/dynakube/eec_test.go, pkg/api/validation/dynakube/validation.go
Ticket [DAQ-1617](https://dt-rnd.atlassian.net/browse/DAQ-1617)
Currently having multiple Dynakubes with extensions enabled for the same tenant in the same K8S cluster will have unwanted side-effects. OTOH we don’t want to completely prevent this scenario.
This PR introduce warning validation check for this scenario.
unit tests/ or create 2 dks extensions enabled with same APIURLs and see no-blocking warning:
```
You are already using a Dynakube that enables extensions. Having multiple Dynakubes with '.spec.extensions' enabled can have severe side-effects on “sum” and “count” metrics and cause double-billing.
```
[DAQ-1617]: https://dt-rnd.atlassian.net/browse/DAQ-1617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRD] Warning if multiple Dyankubes with extensions are enabled for same ApiURL

.github/workflows/e2e-tests-ondemand.yaml, test/features/cloudnative/upgrade/upgrade.go, test/helpers/components/dynakube/dynakube.go, test/helpers/components/oneagent/daemonset.go, test/scenarios/release/release_test.go
Bump operator prev version in upgrade e2e test to 1.3.2.
Bonus: 
- I've fixed slack integration.
- removed redundant `WaitFromDaemonSetPrevDk` and replaced with `WaitFromDaemonset`
Run `make test/e2e/release`
=> Bump operator prev version in upgrade e2e test to 1.3.2.

pkg/api/validation/dynakube/kspm.go, pkg/api/validation/dynakube/kspm_test.go, pkg/api/validation/dynakube/validation.go
https://dt-rnd.atlassian.net/browse/DAQ-2890
KSPM only works with one ActiveGate replica. This is why here a new validation is added that validates exactly that.
Apply a dynakube with kspm enabled and play around with the `replica` section.
example:  
```
kspm: {}
activeGate:
replicas: 2
tlsSecretName: dynakube-ag-tls
capabilities:
customProperties:
value: |
[kubernetes_monitoring]
kubernetes_configuration_dataset_pipeline_enabled = true
kubernetes_configuration_dataset_pipeline_include_node_config = true
templates:
kspmNodeConfigurationCollector:
imageRef:
repository: us-central1-docker.pkg.dev/cloud-platform-207208/chmu/k8s-node-config-collector
tag: latest
```
=> Add validator to only allow 1 AG replica in combination with KSPM

pkg/clients/dynatrace/settings_logmonitoring.go, pkg/controllers/dynakube/logmonitoring/logmonsettings/conditions.go, pkg/controllers/dynakube/logmonitoring/logmonsettings/reconciler.go
https://dt-rnd.atlassian.net/browse/DAQ-2991
This fixes:
- schemaVersion. Previously it was set to `1.0.0` but it should be set to `1.0.16`, as this is the most current version
- Error handling: If there is an error in the course of getting or creating logmon settings, We now mention it in the conditions of the `DynaKube`.
I changed the version to a version that does not exist, or also used a wrong schemaID and built the image locally and had a look at the `DynaKube` status. I think this is the best way to test this properly.
=> Correct schemaVersion and improve error handling

pkg/controllers/edgeconnect/controller.go, pkg/controllers/edgeconnect/deployment/deployment.go, pkg/controllers/edgeconnect/deployment/deployment_test.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-3032)
`edgeconnect.Spec.Labels` and `edgeconnect.Spec.Annotations` are applied to `ObjectMeta` of the EC POD being created.
`deployment.ObjectMeta.Labels`, `deployment.Spec.Selector` values are calculated in the same way as in case of EEC/OTELC [statefulset](https://github.com/Dynatrace/dynatrace-operator/blob/main/pkg/controllers/dynakube/extension/eec/statefulset.go#L90).
1) unittests
```
make go/test
```
2) deploy EdgeConnect with custom labels, annotations
=> Transfer EC.Labels and EC.Annotations to the POD spec

config/helm/chart/default/templates/Common/oneagent/serviceaccount-oneagent.yaml, config/helm/chart/default/tests/Common/oneagent/serviceaccount-oneagent_test.yaml
Ticket: TBD
Incase the LogMonitoring feature is enabled within the fullstack OneAgent, then the fullstack OneAgent DaemonSet will need the kubernetes API-token (like the standalone LogMonitoring DaemonSet).
- So we enable the `automountServiceAccountToken` setting on the fullstack's ServiceAccount, if logMonitoring can be configured
Play around with the `rbac.logMonitoring.create` value in helm
`rbac.logMonitoring.create: true` ==> `automountServiceAccountToken: true`
`rbac.logMonitoring.create: false` ==> `automountServiceAccountToken: false`
=> Add automountServiceAccountToken: true to fullstack OA serviceAccount

pkg/webhook/mutation/pod/metadata/mutator.go, pkg/webhook/mutation/pod/metadata/mutator_test.go, pkg/webhook/mutation/pod/metadata/workload.go, pkg/webhook/mutation/pod/metadata/workload_test.go
Jira: [DAQ-3254](https://dt-rnd.atlassian.net/browse/DAQ-3254)
[Dynatrace semantic dictionary](https://docs.dynatrace.com/docs/discover-dynatrace/references/semantic-dictionary/fields#kubernetes) has requirements on how values should be set. `k8s.workload.kind` must always be lowercase, which we only did for the annotation and not the enrichment file.
- Inject a pod with metadata enrichment
- Check `DT_WORKLOAD_KIND` environment variable and value of `k8s.workload.kind` in `/var/lib/dynatrace/enrichment/dt_metadata.json/properties` (value should be ALL lowercase)
[DAQ-3254]: https://dt-rnd.atlassian.net/browse/DAQ-3254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Always lowercase workload kind in enrichment file

pkg/controllers/dynakube/logmonitoring/logmonsettings/reconciler.go
[DAQ-3366](https://dt-rnd.atlassian.net/browse/DAQ-3366)
e2e test failed because of the logical OR check in the if condition where we check if logmon is enabled. I removed it but kept the MEID check inside the if condition.
Run the e2e tests
[DAQ-3366]: https://dt-rnd.atlassian.net/browse/DAQ-3366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix e2e test by splitting up extensive if condition

README.md
The way how operator manifests have to be used changed.
Update README.
n/a
=> Mention new behavior of operator manifests

Dockerfile
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-4171)
Bumps versions of livenessprobe and csi-node-driver-registrar.
```
make images/build
```
=> Bump versions of livenessprobe and csi-node-driver-registrar on release-1.4 branch

Dockerfile
These `--platform` flags have been removed because the GitHub actions linting issued warnings for them, but without them the image just doesn't work, so they are back.
- This is mainly a problem because we use `podman` to build locally, and it seems like the behaviour is not the same
The built image should NOT have `exec /usr/local/bin/entrypoint: exec format error` when ran
=> Add --platform to Dockerfile

pkg/api/validation/dynakube/eec_test.go, pkg/api/validation/dynakube/extensions.go, pkg/api/validation/dynakube/extensions_test.go, pkg/api/validation/dynakube/validation.go
The ActiveGate capability `kubernetes_monitoring` is mandatory for using extensions. We don't want to do any auto-enabling magic behind the scenes, though. 
But we need to make sure, that the DynaKube is configured properly. So this PR adds a validation webhook that ensure that `kubernetes_monitoring` is enabled.
* Deploy a DynaKube with extensions but without `kubernetes_monitoring`
```
kind: DynaKube
...
spec:
extensions: {}
templates:
imageRef:
repository: public.ecr.aws/dynatrace/dynatrace-eec
tag: 1.305.98.20250114-172617
```
This DynaKube should be rejected.
* Deploy a Dynakube with extensions and `kubernetes_monitoring`
```
kind: DynaKube
...
spec:
activeGate:
capabilities:
- routing
- …
```
=> Ensure that `kubernetes_monitoring` is activated in ActiveGate when extensions are used

cmd/csi/init/cmd.go, cmd/csi/provisioner/cmd.go, cmd/csi/server/cmd.go, cmd/operator/builder.go, cmd/standalone/standalone.go, cmd/webhook/builder.go
Most of the operator subcommands are invoked by hardcoded pod commands. When these commands fail, a usage description is printed. This is unnecessary and causes confusion in the logs, so the print statements should be removed for subcommands that are not directly called by the user.
Example of confusing log: 
```
{"level":"info","ts":"2024-10-09T13:16:50.592Z","logger":"injection-startup","msg":"CONTAINER_INFO environment variable is missing"}
Usage:
dynatrace-operator init [flags]
Flags:
-h, --help   help for init
```
[Jira](https://dt-rnd.atlassian.net/browse/DAQ-2912)
Make the init container fail with an error, it should only log the error.
=> Remove command descriptions in case the whole application is failing

pkg/controllers/dynakube/logmonitoring/daemonset/container.go, pkg/controllers/dynakube/logmonitoring/daemonset/container_test.go, pkg/controllers/dynakube/logmonitoring/daemonset/reconciler.go, pkg/controllers/dynakube/logmonitoring/daemonset/volumes.go, pkg/controllers/dynakube/logmonitoring/daemonset/volumes_test.go
This PR resolves [DAQ-4044](https://dt-rnd.atlassian.net/browse/DAQ-4044) by making log agent host path static and use dynamic subpath.
```
volumeMounts:
- name: dynatrace-lib
subPath: logmonitoring-<tenant>
mountPath: /var/lib/dynatrace
volumes:
- name: dynatrace-lib
hostPath:
path: /tmp/dynatrace
type: ""
```
unit-tests
how to test on GKE:
1. Create GKE autopilot cluster 
2. Apply custom `WorkloadAllowlist` (ask @andriisoldatenko  for sample which includes custom dev image patch)
```
matchingCriteria:
containers:
- name: main
image: ^(docker.io\/dynatrace\/dynatrace-logmodule|gcr.io\/dynatrace-marketplace-prod\/dynatrace-logmodule|public.ecr.aws\/dynatrace\/dyn>
image: ^(us-central1-docker.pkg.dev\/cloud-platform-207208\/chmu\/logmodule|docker.io\/dynatrace\/dynatrace-logmodule|gcr.io\/d …
```
=> Make Log agent host path static

pkg/controllers/dynakube/logmonitoring/daemonset/args.go, pkg/controllers/dynakube/logmonitoring/daemonset/env.go, pkg/controllers/dynakube/logmonitoring/daemonset/env_test.go
This PR makes use of the Log Agent argument value from env var to prevent dynamic strings.
resolves bug [DAQ-4261](https://dt-rnd.atlassian.net/browse/DAQ-4261)
unit tests
detailed instruction of how to test using GKE can be found here https://github.com/Dynatrace/dynatrace-operator/pull/4323
[DAQ-4261]: https://dt-rnd.atlassian.net/browse/DAQ-4261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Log agent args must not contain dynamic strings

pkg/api/validation/dynakube/extensions.go, pkg/api/validation/dynakube/extensions_test.go
Make sure that `feature.dynatrace.com/automatic-kubernetes-api-monitoring` is not set to false when extensions are enabled.
1) Deploy the following Dynakube:
```
kind: DynaKube
metadata:
name: dynakube
annotations:
feature.dynatrace.com/activegate-authtoken: "true"
feature.dynatrace.com/automatic-kubernetes-api-monitoring: "false"
spec:
...
activeGate:
capabilities:
- routing
- dynatrace-api
- metrics-ingest
...
extensions: {}
templates:
imageRef:
repository: public.ecr.aws/dynatrace/dynatrace-eec
tag: 1.305.98.20250114-172617
```
This Dynakube shall be rejected.
2) Deploy the following Dynakube:
```
kind: DynaKube
metadata:
name: dynakube …
```
=> Make automatic K8S monitoring mandatory for extensions.

pkg/api/validation/dynakube/kspm.go, pkg/api/validation/dynakube/kspm_test.go
Cherry-pick: #4332
See #4332 
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-4344)
=> Ensure that automatic-kubernetes-api-monitoring is not disabled if KSPM is enabled

config/helm/chart/default/templates/Common/csi/role-csi.yaml, config/helm/chart/default/tests/Common/csi/role-csi_test.yaml, doc/api/feature-flags.md, pkg/api/v1beta3/dynakube/feature_flags.go, pkg/controllers/dynakube/logmonitoring/daemonset/volumes_test.go
This PR adds `codemodules.oneagent.dynatrace.com/remoteImageDownload: true` as feature flag. 
In addition permissions for creating jobs are added to the CSI driver. 
These changes are the first step to enabled remote docker image downloads.
[Jira](https://dt-rnd.atlassian.net/browse/DAQ-3990)
Just look at the permissions and the feature flags code
=> Add flag and permissions to enable pod provisioning

test/features/extensions/extensions.go
This PR fixes extension e2e tests in release branch
`make test/e2e/extensions`
```
=== RUN   TestStandard
default.go:52: istio enabled: false
=== RUN   TestStandard/extensions-components-rollout
=== RUN   TestStandard/extensions-components-rollout/create_AG_TLS_secret
=== RUN   TestStandard/extensions-components-rollout/created_tenant_secret
=== RUN   TestStandard/extensions-components-rollout/'dynakube'_dynakube_created
I0124 17:16:10.816788    4551 warning_handler.go:65] "ActiveGate specification missing memory limits. Can cause excess memory usage." logger="KubeAPIWarningLogger"
=== RUN   TestStandard/extensions-components-rollout/'dynakube'_dynakube_phase_changes_to_'Running'
=== RUN   TestStandard/extensions-components-rollout/active_gate_pod_is_running
=== RUN …
```
=> Fix extensions E2E test

pkg/controllers/csi/driver/server.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-4525)
Adds debug messages to the CSI Server handlers
- GetPluginCapabilities
- GetPluginInfo
- Probe
Add `LOG_LEVEL=debug` environment variable to the CSI Server container and check logs.
=> Add debug messages to CSI identity services handlers

pkg/controllers/dynakube/oneagent/daemonset/arguments.go, pkg/controllers/dynakube/oneagent/daemonset/arguments_test.go, pkg/controllers/dynakube/oneagent/daemonset/daemonset_test.go, pkg/util/prioritymap/map.go, pkg/util/prioritymap/map_test.go
Multiple occasions of command line arguments for OneAgent shall be avoided. Exceptions are only `--set-host-property` and `--set-host-tag`. Host tags shall not be provided multiple times with the same value.
Deploy a Dynakube with custom OneAgent arguments and make sure that the custom arguments take precedence in the OneAgent daemon set and that no duplications show up (besidd the exceptions)
=> Fix OneAgent command line arguments

cmd/csi/init/cmd.go, cmd/csi/provisioner/cmd.go, cmd/csi/server/cmd.go, cmd/operator/builder.go, cmd/support_archive/builder.go, cmd/webhook/builder.go, pkg/api/v1beta1/dynakube/convert_from.go, pkg/api/v1beta1/dynakube/convert_from_test.go, pkg/api/v1beta2/dynakube/convert_from.go, pkg/api/v1beta2/dynakube/convert_from_test.go, pkg/util/installconfig/modules.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-4465)
At startup, the operator immediately issues a log line :
```
{"level":"info","ts":"2025-01-27T14:02:26.877Z","logger":"install-config","msg":"envvar content read and set","envvar":"modules.json","value":"..."} 
PK^C^D^T...
```
which precedes the first ZIP header so the package can't be unpacked by some implementations of zip command. 
Changes: 
- removed global initialization of the Modules from v1beta1(2)/convert_from packages to fix support_archive command
- GetModules function  is called by all operator subcommands to put the message at the beginning of a log file
```
kubectl exec -n dynatrace deployment/dynatrace-operator -- dynatrace-operator support-archive --stdout > operator-support-archive.zip
```
`operator-support-archive.zip` …
=> Removes a log message that corrupts support_archive zip package

pkg/api/v1beta3/dynakube/telemetryservice/props.go, pkg/api/v1beta3/dynakube/telemetryservice/spec.go, pkg/api/v1beta3/dynakube/telemetryservice_props.go, pkg/api/validation/dynakube/telemetryservice.go, pkg/api/validation/dynakube/telemetryservice_test.go, pkg/api/validation/dynakube/validation.go, pkg/consts/otelc.go, pkg/controllers/dynakube/extension/service.go, pkg/controllers/dynakube/otelc/reconciler.go, pkg/controllers/dynakube/otelc/service/conditions.go, pkg/controllers/dynakube/otelc/service/config.go, pkg/controllers/dynakube/otelc/service/reconciler.go, pkg/controllers/dynakube/otelc/service/reconciler_test.go, pkg/util/kubeobjects/labels/labels.go, pkg/util/kubeobjects/service/builder.go, pkg/util/kubeobjects/service/builder_test.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-1367)
Adds Otel collector service reconciler. 
The service is created if dynakube.spec.telemetryService!=nil and  telemetryService.serviceName == "".
Operator neither checks if telemetryService.serviceName service exists nor verifies it's ports.
1. unittests
2. install dynakube
```
spec:
apiUrl: https://....  
telemetryService: {}
```
3. check services
```
[]$ kubectl -n dynatrace get services
NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                     AGE
dynakube-telemetry   ClusterIP   3.....           <none>        4317/TCP,4318/TCP,9411/TCP,14250/TCP,6832/TCP,6831/TCP,14268/TCP,8125/TCP   4m41s
```
4. check conditions
```
[]$ kubectl -n dynatrace describe …
```
=> Automate creation of Otel collector Service

test/features/cloudnative/network_problems/network_problems.go
A new FF was introduced to configure the timeout.
The old feature-flag is only converted in case an actual conversion happens (from v1beta2 to v1beta3)
`make test/e2e/cloudnative/resilience/`
=> Fix resilience e2e test

pkg/api/v1beta3/dynakube/oneagent_props.go, pkg/api/validation/dynakube/oneagent.go, pkg/api/validation/dynakube/oneagent_test.go, pkg/api/validation/dynakube/validation.go
Makes sure that there are
* no duplicate arguments for OneAgent are allowed (except for `--set-host-property` and `--set-host-tag`
* no duplicate host-tags are allowed
* `--set-host-id-source` is not allowed for cloud native fullstack
```
oneAgent:
args:
- --set-host-property=prop1
- --set-host-property=prop2
- --set-host-tag=tag1
- --set-server=foo
- --set-server=bar
Error from server (Forbidden): error when creating "cloudNativeFullStack-v1beta3.yaml": admission webhook "v1beta3.dynakube.webhook.dynatrace.com" denied the request:
1 error(s) found in the DynaKube
1. --set-server has been provided multiple times. Only --set-host-property and --set-host-tag arguments may be provided multiple times.
```
```
oneAgent:
args:
- …
```
=> Add validations for OneAgent arguments (release-1.4)

pkg/controllers/dynakube/otelc/statefulset/reconciler.go
This PR follow up for this rename I made recently https://github.com/Dynatrace/dynatrace-operator/pull/4312.
Related to original story with rename of SA [DAQ-3329](https://dt-rnd.atlassian.net/browse/DAQ-3329)
via e2e tests or just deploy dynakube with extensions:
```
make test/e2e/extensions
```
[DAQ-3329]: https://dt-rnd.atlassian.net/browse/DAQ-3329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> follow up: rename SA for extensions to dynatrace-opentelemetry-collector

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml
This PR fixes bug [DAQ-4645](https://dt-rnd.atlassian.net/browse/DAQ-4645)
1. helm unit tests
2. deploy dk with CSI driver enabled:
```
apiVersion: dynatrace.com/v1beta2
kind: DynaKube
metadata:
name: dynakube
spec:
apiUrl: https://*****.dev.dynatracelabs.com/api
oneAgent:
applicationMonitoring:
useCSIDriver: true
```
If you run, you will see that after this PR 
server **doesn't have** liveness probe port declaration
```
{
"args": [
"csi-server",
"--endpoint=unix:/csi/csi.sock",
"--node-id=$(KUBE_NODE_NAME)"
],
...
"name": "server",
"ports": [
{
"containerPort": 8080,
"name": "metrics",
"protocol": "TCP"
}
],
...
}
```
and liveness-probe container has it:
```
k get pods dynatrace-oneagent-csi-driver-44888 -n dynatrace -o jsonpath='{.spec.
containers[3]}' | jq
{ …
```
=> misleading declaration of healthz port between server and liveness-probe

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml
Reverts Dynatrace/dynatrace-operator#4390
=> Revert "misleading declaration of healthz port between server and liveness-probe"

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml
This PR resolves bug https://dt-rnd.atlassian.net/browse/DAQ-4864
helm unit tests
=> Increase CSI driver server container livenessProbe default timeouts (release-1.4)

pkg/controllers/dynakube/logmonitoring/daemonset/volumes.go, pkg/controllers/dynakube/logmonitoring/daemonset/volumes_test.go
With this PR we add a new mount to `/var/log` to the `logAgent`. Also other mounts' type got changed to `Directory` as we do not want to create a directory if it does not exist on host filesystem.
[Ticket](https://dt-rnd.atlassian.net/browse/DAQ-4838)
Deploy logAgent and have a look at the `volumes` and the `volumeMounts`
Should look like this:
```
volumeMounts:
- mountPath: /var/log/journal
name: var-log-journal
readOnly: true
...
volumes:
- name: var-log-journal
hostPath:
path: /var/log
type: Directory
```
=> Add `/var/log` mount to log agent

.github/workflows/e2e-tests-ondemand.yaml
```
➜  ~ kubectl get flcenvironments --namespace dto-ocp-ondemand
NAME           PLATFORM   PLATFORMVERSION   TENANT   ENVIRONMENTSTATE
dto-ocp-4-10   ocp4       4.10              none     environment-not-deployed
dto-ocp-4-11   ocp4       4.11              none     environment-not-deployed
dto-ocp-4-12   ocp4       4.12              none     environment-not-deployed
dto-ocp-4-13   ocp4       4.13              none     environment-not-deployed
dto-ocp-4-14   ocp4       4.14              none     environment-not-deployed
dto-ocp-4-15   ocp4       4.15              none     environment-not-deployed
dto-ocp-4-16   ocp4       4.16              none     environment-not-deployed
dto-ocp-4-17   ocp4       4.17              none     environment-not-deployed
➜  ~ kubectl get flcenvironments …
```
=> update e2e tests ondemand according to available clusters

pkg/api/validation/dynakube/oneagent.go, pkg/api/validation/dynakube/oneagent_test.go, pkg/api/validation/dynakube/validation.go
In #4346 we implemented a validation that rejected `dynakubes` that have configured a custom image and a mode that uses `readOnly` `oneAgents`. After some discussion we came to the conclusion that an error is too harsh and now we only give a warning.
Same as in #4346 with the difference that now the `dk` should not be rejected but allowed with a warning.
=> Change readonly oneAgent + custom image validation to a warning

doc/api/feature-flags.md, pkg/api/v1beta3/dynakube/feature_flags.go
All other feature-flags we use are use `-` instead of camelCase.
[Same as original PR](https://github.com/Dynatrace/dynatrace-operator/pull/4392), BUT
- Use the renamed FF: `codemodules.oneagent.dynatrace.com/remote-image-download: true`
=> Follow naming pattern of previous feature-flags for Job feature-flag

pkg/api/consts.go, pkg/controllers/dynakube/extension/eec/reconciler_test.go, pkg/controllers/dynakube/extension/eec/statefulset.go, pkg/controllers/dynakube/otelc/statefulset/reconciler.go, pkg/controllers/dynakube/otelc/statefulset/reconciler_test.go, pkg/controllers/dynakube/otelc/statefulset/volumes.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-3223)
Mounts TLS secret to OtelC POD. 
`extensions-collector` POD is restarted if the secret is changed (added `ts-secret-hash` template annotation).
1) unittests
2) dynakube
create secret
```
openssl req -nodes -x509 -newkey rsa:4096 -keyout key.pem -out crt.pem -days 5 -subj "/CN=test"
kctl create secret tls ts --cert=crt.pem --key=key.pem
```
deploy dynakube
```
apiUrl: ...
activeGate:
capabilities:
extensions: {}
customPullSecret: ...
telemetryService:
tlsRefName: ts
templates:
imageRef:
repository: ...
tag: ...
```        
check `dynakube-extensions-collector-0` spec.volumes
=> Mount telemetryService.TlsRefName secret to OtelC POD

pkg/controllers/dynakube/logmonitoring/daemonset/volumes.go
This corrects the volume name and path introduced in  #4413 to `var-log` and `/var/log` respectively.
Same as in  #4413
=> Fix volume path and name to use correct one

pkg/controllers/dynakube/logmonitoring/daemonset/volumes.go
~Fixes the conflict between the readOnly `/var/log` and the emptyDir `/var/log/dynatrace`, by making `/var/log/dynatrace` be mounted from the `/tmp/dyntrace` hostMount using a `subPath`.~
~So on the host FS `/tmp/dynatrace` will look like:~
~- `/tmp/dynatrace/logmonitoring-<tenant>`: we already had this, this translates to `/var/lib/dynatrace`~
~- `/tmp/dynatrace/logmonitoring-logs-<tenant>`: this is now the "new" `/var/log/dynatrace`~
The above mentioned solution doesn't work, it only worked during my initial tests, because folders/mounts were already created by previous fix attempts on the host, and my guess these were reused during my testing.
However when you try it on a "fresh" host FS it will fail the same way as if we were using an `emptyDir`
So now are going to mount the …
=> Make the `/var/log` volumeMount not readOnly

.github/workflows/e2e-tests-ondemand.yaml
Return back the ability to trigger the on-demand pipeline from GH ui.
the button is back.
=> add back ability to trigger ondemand on latest release branch

config/helm/chart/default/templates/_helpers.tpl
Deployment of the operator failed when a string was assigned to the debug flag. The process should be more lenient and accept string values as well.
[Jira](https://dt-rnd.atlassian.net/browse/DAQ-5538)
This should work now: 
```
helm upgrade dynatrace-operator config/helm/chart/default \
--install \
--namespace dynatrace \
--create-namespace \
--atomic \
--set installCRD=true \
--set csidriver.enabled=$(ENABLE_CSI) \
--set manifests=true \
--set image="$(IMAGE_URI)" \
--set debug=""
```
=> Fix helm upgrade if debug field is string

pkg/injection/codemodule/installer/image/unpack.go
[DAQ-3546](https://dt-rnd.atlassian.net/browse/DAQ-3546)
If the `codeModulesImage` was built with OCI media type. (ie.: not docker), then we would get the following error:
```
"stacktrace":"OCILayer is not implemented"
```
- this is just in our code, nothing more specific then that.
as it turns out, when it comes to our needs, the docker media type function the same as the OCI media type
Using Operator 1.4.1 (or earlier), try using the `quay.io/dynatrace/dynatrace-bootstrapper:snapshot-add-ruxit` as `codeModulesImage` (**without** the `codemodules.oneagent.dynatrace.com/remote-image-download: "true"` feature-flag)
- in the provisioner's logs you will see the `OCILayer is not implemented` error
Using the same `codeModulesImage`, but for this branch:
- you should see no errors
- and on the …
=> Support OCI `codeModulesImage` as well

doc/api/feature-flags.md, doc/e2e/features.md, hack/doc/gen_e2e_features.sh, hack/doc/gen_feature_flags.sh, pkg/api/v1beta3/dynakube/activegate/props.go, pkg/api/v1beta3/dynakube/activegate/spec.go, pkg/api/v1beta3/dynakube/activegate_props.go, pkg/api/v1beta3/dynakube/certs.go, pkg/api/v1beta3/dynakube/feature_flags.go, pkg/controllers/dynakube/activegate/internal/capability/reconciler.go, pkg/controllers/dynakube/activegate/internal/capability/reconciler_test.go, pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/certs.go, pkg/controllers/dynakube/activegate/internal/tls/conditions.go, pkg/controllers/dynakube/activegate/internal/tls/config.go, pkg/controllers/dynakube/activegate/internal/tls/reconciler.go, pkg/controllers/dynakube/activegate/internal/tls/reconciler_test.go, pkg/controllers/dynakube/activegate/reconciler.go, pkg/controllers/dynakube/activegate/reconciler_test.go, pkg/controllers/dynakube/extension/eec/reconciler_test.go, pkg/controllers/dynakube/extension/eec/statefulset.go, pkg/controllers/dynakube/extension/tls/reconciler.go, pkg/controllers/dynakube/oneagent/daemonset/volumes.go, pkg/controllers/dynakube/oneagent/daemonset/volumes_test.go, pkg/util/certificates/certificates.go, test/features/cloudnative/codemodules/codemodules.go, test/features/cloudnative/container.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-1357)
Operator creates ActiveGate TLS certificate (using PEM format) if TrustedCAs certificates are used. IP address of the AG service is also added to the AlternativeNames.
It solves the problem with OneAgents which use single `custom.pem` file to store TrustedCAs and AG certificates. A common scenario is that custom DynatraceServer certificate is  provided forcing the creation of AG certificate because OA verifies all TLS certificates if `custom.pem` file exists.
OSAgent (running in the OneAgent POD) needs IP address to connect to AG because is not able to resolve `<name>.<namespace>` hostname.
The `feature.dynatrace.com/automatic-tls-certificate` opt-in feature flag has to be used because AG>=1.307 only supports PEM format.
regarding
- …
=> Creates AG TLS certificate (pem) if trustedCAs are used and tlsSecretName is empty

pkg/controllers/dynakube/kspm/daemonset/reconciler.go, pkg/controllers/dynakube/kspm/daemonset/reconciler_test.go, pkg/controllers/dynakube/logmonitoring/daemonset/reconciler.go, pkg/controllers/dynakube/logmonitoring/daemonset/reconciler_test.go, pkg/util/kubeobjects/daemonset/builder.go
[Jira](https://dt-rnd.atlassian.net/browse/DAQ-5776)
Currently when defining a `nodeSelector` for `logMonitoring` and `KSPM` we do not pass it from the `DynaKube` to the `DaemonSet`.
Now this should be fixed.
Deploy a `DynaKube` that defines `logMonitoring`/`KSPM` with a `nodeSelector`. Check the `DaemonSet`, have a look if it has a `nodeSelector` and if it was considered when creating `Pods`.
=> Respect custom nodeSelector when building logMon/KSPM DaemonSet

pkg/controllers/dynakube/otelc/statefulset/env.go, pkg/controllers/dynakube/otelc/statefulset/reconciler_test.go
same as https://github.com/Dynatrace/dynatrace-operator/pull/4425
[DAQ-4975](https://dt-rnd.atlassian.net/browse/DAQ-4975)
same as https://github.com/Dynatrace/dynatrace-operator/pull/4425
[DAQ-4975]: https://dt-rnd.atlassian.net/browse/DAQ-4975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> cherry pick remove obsolete OTLP token

.github/workflows/release.yaml
To use a binary installed via `go install` in an action, you need the `actions/setup-go` step to be done before, otherwise you will get a `... command not found`.
` make release/gen-sbom` will do a `go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod` so we need that step.
Test on fork
=> Add setup-go to `build` step in release workflow

pkg/controllers/dynakube/otelc/secret/reconciler.go, pkg/controllers/dynakube/otelc/secret/reconciler_test.go
The endpoint for the OpenTelemeteryCollector in case of public AG was created wrong. It contained the tenantUUID twice.
Also if `telemetryIngest` was deployed standalone without AG or OA, it was still depending on the status field of AG or OA although it's not needed because the tenantUUID is already part of the apiURL set in the DynaKube
Deploy Dynakube that has only `telemeterIngest` activated and nothing else.
=> Fix exporter endpoint and add unit tests.

pkg/controllers/dynakube/logmonitoring/daemonset/args.go, pkg/controllers/dynakube/logmonitoring/daemonset/args_test.go, pkg/controllers/dynakube/logmonitoring/daemonset/container.go, pkg/controllers/dynakube/logmonitoring/daemonset/volumes.go, pkg/controllers/dynakube/logmonitoring/daemonset/volumes_test.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-5544)
Backport for 1.4.2
Same as in #4522
Same as in #4522
Please test properly!
=> Backport: Mount /var/log as read only to standalone logmonitoring #4522

pkg/controllers/dynakube/kspm/daemonset/container.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-4042)
Node config collector should no longer run with a privileged user, therefor we need to update the securityContext of the container.
Deploy kspm and see if everything runs and works.
check the securityContext of the kspm pods, should look like this:
```
securityContext:
allowPrivilegeEscalation: false
capabilities:
add:
- DAC_OVERRIDE
drop:
- ALL
privileged: false
readOnlyRootFilesystem: true
runAsGroup: 65532
runAsNonRoot: true
runAsUser: 65532
```
=> Update securityContext for node config collector container

pkg/api/v1beta4/dynakube/telemetryingest/props.go, pkg/api/validation/dynakube/telemetryservice.go, pkg/api/validation/dynakube/telemetryservice_test.go, pkg/api/validation/dynakube/validation.go, pkg/controllers/dynakube/otelc/service/reconciler.go, pkg/controllers/dynakube/otelc/service/reconciler_test.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-6015)
Operator uses 
```
app.kubernetes.io/component: dynatrace-opentelemetry-collector
app.kubernetes.io/created-by: <dynakube  name>
```    
labels to find previous instance of the service if `telemetryIngest.serviceName` is changed and to delete the actual service if dynakube is undeployed.
0) unittests
1) deploy dynakube
```
metadata:
name: dynakube
spec:                                                                                                                                                                                                                                                                                                                   
apiUrl: ...
activeGate: …
```
=> Use `.spec.telemetryIngest.serviceName` as name for telemetry ingest service

pkg/webhook/mutation/pod/v1/metadata/config.go, pkg/webhook/mutation/pod/v1/oneagent/config.go, pkg/webhook/mutation/pod/v1/oneagent/env.go, pkg/webhook/mutation/pod/v2/attributes.go, pkg/webhook/mutation/pod/v2/attributes_test.go, pkg/webhook/mutation/pod/v2/common/arg/arg.go, pkg/webhook/mutation/pod/v2/common/volumes/volumes.go, pkg/webhook/mutation/pod/v2/init.go, pkg/webhook/mutation/pod/v2/init_test.go, pkg/webhook/mutation/pod/v2/metadata/config.go, pkg/webhook/mutation/pod/v2/metadata/containers.go, pkg/webhook/mutation/pod/v2/webhook.go, pkg/webhook/mutation/pod/v2/webhook_test.go
[DAQ-4190](https://dt-rnd.atlassian.net/browse/DAQ-4190)
[DAQ-4187](https://dt-rnd.atlassian.net/browse/DAQ-4187)
Adds the following to the init-container of during the bootstrapper injection (follow up for https://github.com/Dynatrace/dynatrace-operator/pull/4576)
- `--attribute-container`
- `--attributes`
- `--config-directory`
- `--input-directory`
Doing this, we have feature parity with the `v1` webhook.
- every feature (metadata-enrichement, etc) should work
Some notable differences: 
- we mainly configure the bootstrapper with `args` and not `envs`
- so metadata annotation propagation is done with `--attributes` instead of an `env` 
Setup is same to https://github.com/Dynatrace/dynatrace-operator/pull/4576
- `make deploy/no-csi`
- create your sample NAMESPACE (this is a limitation …
=> Configure attributes for bootstrapper injection

cmd/support_archive/builder.go, cmd/support_archive/resource_query.go, test/features/support_archive/files.go, test/helpers/kubeobjects/event/list.go
Addresses [DAQ-1936](https://dt-rnd.atlassian.net/browse/DAQ-1936)
fixing after this one https://github.com/Dynatrace/dynatrace-operator/pull/4533
`make test/e2e/supportarchive`
or run some other tests before so emulate CI:
```
go test -v -tags "e2e" -timeout 20m -count=1  ./test/scenarios/standard -args --feature "app-monitoring-without-csi|public-registry-images|support-archive"
```
[DAQ-1936]: https://dt-rnd.atlassian.net/browse/DAQ-1936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: supportarchive e2e test, wrong field selector

config/helm/chart/default/templates/Common/csi/role-csi.yaml, config/helm/chart/default/tests/Common/csi/role-csi_test.yaml, pkg/controllers/csi/provisioner/controller.go, pkg/injection/codemodule/installer/job/bootstrapper.go, pkg/injection/codemodule/installer/job/bootstrapper_test.go, pkg/util/kubeobjects/job/builder.go
In OCP to add an owner-reference you need to be able to update the finalizer of the owner
[DAQ-6457](https://dt-rnd.atlassian.net/browse/DAQ-6457)
OCP is more strict when it comes to doing things, so I had to:
- [Add role to update dynakube finalizer](https://github.com/Dynatrace/dynatrace-operator/commit/f379ab96788f7e6a445c3cd9c8330fba1407df73)
- [Use the provisioner serviceAccount for download job](https://github.com/Dynatrace/dynatrace-operator/commit/9f56a86809117a67fb5b89d8b9bc545488b676f9)
- [Sync job securityContext with provisioner container](https://github.com/Dynatrace/dynatrace-operator/pull/4631/commits/639b667ed374e4ea4fc92269dc18dd84ff54c895)
~(it is a draft so I can build an arm image in peace, so I can test it in `crc`)~
- on `crc` there is some weird error
- works on …
=> Make Job installer work on OCP

config/helm/chart/default/templates/Common/csi/role-csi.yaml, config/helm/chart/default/tests/Common/csi/role-csi_test.yaml
The `provisioner` needs the `watch` permission for Job since I added `Owns(&batchv1.Job{})`
- everything is functioning without it, or seems so, but we get random error logs
see no error logs in the `provisioner`
=> Add watch permission for provisioner

pkg/controllers/dynakube/logmonitoring/daemonset/container.go, pkg/controllers/dynakube/logmonitoring/daemonset/container_test.go
[DAQ-6362](https://dt-rnd.atlassian.net/browse/DAQ-6362)
On OCP, there strict restriction to touch `hostPath` volumes, so on OCP the standalone-logmon DaemonSet needs to be privileged.
On OCP, (can be `crc`), deploy standalone logmonitoring
[DAQ-6362]: https://dt-rnd.atlassian.net/browse/DAQ-6362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make standalone logmon privileged with FF

pkg/controllers/dynakube/otelc/configuration/reconciler.go, pkg/controllers/dynakube/otelc/statefulset/env.go, pkg/controllers/dynakube/otelc/statefulset/env_test.go, pkg/otelcgen/exporters.go, pkg/otelcgen/otelcgen.go, pkg/otelcgen/otelcgen_test.go, pkg/otelcgen/services.go, pkg/otelcgen/testdata/exporters_only.yaml, pkg/otelcgen/testdata/full_config.yaml, pkg/otelcgen/testdata/services_only.yaml, pkg/otelcgen/testdata/services_statsd_only.yaml, pkg/otelcgen/testdata/services_zipkin_only.yaml
The env vars to control proxy usage (`HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY`) are now set.
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-6174)
Deploy this Dynakube
```
kind: DynaKube
metadata:
name: dynakube
annotations:
feature.dynatrace.com/activegate-authtoken: "true"
spec:
apiUrl: https://....../api
proxy:
value: http://squid.proxy.svc.cluster.local:3128
activeGate:
capabilities:
- routing
replicas: 1
resources:
requests:
cpu: 1000m
memory: 1.5Gi
limits:
cpu: 1000m
memory: 1.5Gi
extensions: {}
telemetryIngest:
protocols:
- otlp
templates:
imageRef:
repository: public.ecr.aws/dynatrace/dynatrace-eec
tag: 1.307.61.20250226-155505
```
Check the env vars on the otel collector …
=> Sets proxy env variables for otel collector

doc/e2e/features.md, hack/make/tests/e2e.mk, pkg/controllers/dynakube/logmonitoring/configsecret/conditions.go, pkg/controllers/dynakube/logmonitoring/configsecret/reconciler.go, pkg/controllers/dynakube/logmonitoring/configsecret/reconciler_test.go, pkg/controllers/dynakube/logmonitoring/daemonset/conditions.go, pkg/controllers/dynakube/logmonitoring/daemonset/reconciler.go, pkg/controllers/dynakube/logmonitoring/daemonset/reconciler_test.go, pkg/controllers/dynakube/logmonitoring/logmonsettings/conditions.go, pkg/controllers/dynakube/logmonitoring/logmonsettings/reconciler.go, test/features/consts/consts.go, test/features/logmonitoring/logmonitoring.go, test/helpers/components/dynakube/options.go, test/helpers/kubeobjects/daemonset/wait.go, test/scenarios/no_csi/no_csi_test.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-5586)
Adds LogMonitoring e2e test.
It is part of `standard` group of tests and there is new make target to run it
```
make test/e2e/logmonitoring
```
The test checks `dynakube.status.conditions` related to LogMonitoring
- LogMonitoringConfig - if secret has been created
- LogMonitoringDaemonSet - if daemonset has been created
- LogMonitoringSettings - if GetSettings and/or CreateSettings have been successful
Uses LogAgent images from ECR public registry.
k8s and ( OpenShift or crc )  cluster
```
make test/e2e/logmonitoring
```
=> Add LogMonitoring e2e test

go.mod, go.sum, pkg/webhook/mutation/pod/v2/attributes.go, pkg/webhook/mutation/pod/v2/attributes_test.go, pkg/webhook/mutation/pod/v2/init.go, pkg/webhook/mutation/pod/v2/init_test.go, pkg/webhook/mutation/pod/v2/metadata/containers.go, pkg/webhook/mutation/pod/v2/oneagent/containers_test.go, pkg/webhook/mutation/pod/v2/oneagent/init.go, pkg/webhook/mutation/pod/v2/oneagent/volumes.go
It is mainly a cosmetic change.
Somethings were fixed in v1.0.2 of the dynatrace-bootstrapper, and I knew that it would break a few imports, so I didn't wait for renovate.
No change in actual behavior, we just use less consts, because we import them
=> Update dynatrace-bootstrapper to v1.0.2

pkg/clients/edgeconnect/client.go, pkg/clients/edgeconnect/environment_settings_test.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-6704)
EdgeConnect client properly processes Settings API server error. 
1) unittest
2) Break the operator to get 404 response from server
```
func (c *client) GetConnectionSettings() ([]EnvironmentSetting, error) {
...
q.Add("schemaIds", KubernetesConnectionSchemaID+"error") <-- invalid schema or
q.Add("scopes", KubernetesConnectionScope+"error")       <-- invalid scope
```
3) Deploy EdgeConnect Automation
```
spec:
apiServer: <api>
oauth:
...
kubernetesAutomation:
enabled: true
```
4) Check operator log.
```
error getting server response data: response error, can't unmarshal json response 404: json: cannot unmarshal object into Go value 
```
5) Apply the fix.
6) Check operator log.
``` …
```
=> Fix Settings API server error handler of EdgeConnect client.

doc/e2e/features.md, hack/make/tests/e2e.mk, pkg/api/v1beta4/dynakube/oneagent/props.go, pkg/api/v1beta4/dynakube/oneagent/props_test.go, pkg/api/validation/dynakube/oneagent.go, pkg/api/validation/dynakube/oneagent_test.go, pkg/controllers/csi/metadata/correctness.go, pkg/controllers/csi/provisioner/cleanup/hostmounts.go, pkg/controllers/csi/provisioner/controller.go, pkg/controllers/dynakube/oneagent/daemonset/daemonset.go, pkg/controllers/dynakube/oneagent/daemonset/env_vars.go, pkg/controllers/dynakube/oneagent/daemonset/volumes.go, pkg/controllers/dynakube/oneagent/daemonset/volumes_test.go, test/features/cloudnative/default/default.go, test/features/hostmonitoring/without_csi.go, test/helpers/components/dynakube/options.go, test/scenarios/istio/istio_test.go, test/scenarios/no_csi/no_csi_test.go, test/scenarios/standard/standard_test.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-5862)
CloudNativeFullStack and HostMonitoring run without CSI driver.
1) unittests
2) deploy operator with and without CSI driver
```
make deploy
make deploy/no-csi
```
check Volumes / VolumeMounts for HostMonitoring / CloudNativeFullStack
```
spec:
oneAgent:
#hostMonitoring:
storageHostPath: /var/opt/dynacn
```
=> Configure host volumes for host agent without CSI driver

doc/e2e/features.md, pkg/controllers/dynakube/otelc/consts/consts.go, pkg/controllers/dynakube/otelc/endpoint/conditions.go, pkg/controllers/dynakube/otelc/endpoint/config.go, pkg/controllers/dynakube/otelc/endpoint/reconciler.go, pkg/controllers/dynakube/otelc/endpoint/reconciler_test.go, pkg/controllers/dynakube/otelc/reconciler.go, pkg/controllers/dynakube/otelc/secret/conditions.go, pkg/controllers/dynakube/otelc/secret/reconciler.go, pkg/controllers/dynakube/otelc/secret/reconciler_test.go, pkg/controllers/dynakube/otelc/statefulset/env.go, pkg/controllers/dynakube/otelc/statefulset/env_test.go, test/features/telemetryingest/telemetryingest.go, test/scenarios/no_csi/no_csi_test.go
The value for `DT_ENDPOINT` doesn't need to be stored in a secret as it's public anyway. With storing it in a ConfigMap we get the benefit, that it's picked up by the support archive automatically.
Also E2E tests are updated to check that the ConfigMap is created.
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-6815)
* deploy a DK with telemetryIngest:
```
kind: DynaKube
metadata:
name: dynakube
spec:
apiUrl: https://..../api
telemetryIngest:
protocols:
- zipkin
```
* check OTel collector pod, value for env var `DT_ENDPOINT` shall be taken from ConfigMap `dynatrace-telemetry-api-endpoint`
```
- name: DT_ENDPOINT
valueFrom:
configMapKeyRef:
key: DT_ENDPOINT
name: dynatrace-telemetry-api-endpoint
```
* pull support archive, make sure the …
=> Uses ConfigMap instead of Secret for DT API endpoint.

pkg/controllers/dynakube/kspm/daemonset/certs.go, pkg/controllers/dynakube/kspm/daemonset/certs_test.go, pkg/controllers/dynakube/kspm/daemonset/volumes_test.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-6918)
The secret name fixed. 
unittests
deploy kspm
```
spec:                                                                                                                                                                                                                                                                                                                                                                                         
apiUrl: ...
activeGate:
capabilities:
- routing
kspm: {}
templates: …
```
=> Fix kspm cert volume related to AG TLS secret

go.mod, go.sum
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-6934)
Bumps x/oauth2 version to fix CVE-2025-22868.
e2e test (EdgeConnect)
=> Bump x/oauth2 to 0.28.0

.github/actions/build-image/action.yaml
The docker-build has an output of `digest`, but because we have the docker-build in a composite action, we have to expose it ourself aswell.
([see example](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action#creating-an-action-metadata-file))
=> Expose the output of the docker build

.github/workflows/release.yaml, config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, doc/api/dynakube-api-ref.md, doc/api/edgeconnect-api-ref.md
Due to changes in how we build images, we have to store the manifests digests now separately for every platform as it differs. 
Run the release action
=> Store manifest digests separately per platform in GitHub actions 

config/helm/chart/default/templates/Common/operator/allowlistsynchronizer.yaml, config/helm/chart/default/templates/_platform.tpl, config/helm/chart/default/tests/Common/activegate/serviceaccount-activegate_test.yaml, config/helm/chart/default/tests/Common/edgeconnect/serviceaccount-edgeconnect_test.yaml, config/helm/chart/default/tests/Common/extensions/clusterrole-extensions-prometheus_test.yaml, config/helm/chart/default/tests/Common/extensions/role-extensions-controller_test.yaml, config/helm/chart/default/tests/Common/extensions/serviceaccount-extensions-controller_test.yaml, config/helm/chart/default/tests/Common/kspm/clusterrole-kubernetes-monitoring_test.yaml, config/helm/chart/default/tests/Common/kspm/serviceaccount-node-config-collector_test.yaml, config/helm/chart/default/tests/Common/logmonitoring/clusterrole-logmonitoring_test.yaml, config/helm/chart/default/tests/Common/logmonitoring/serviceaccount-logmonitoring_test.yaml, config/helm/chart/default/tests/Common/oneagent/clusterrole-oneagent_test.yaml, config/helm/chart/default/tests/Common/oneagent/serviceaccount-oneagent_test.yaml, config/helm/chart/default/tests/Common/opentelemetry-collector/clusterrole-telemetry-endpoints_test.yaml, config/helm/chart/default/tests/Common/opentelemetry-collector/serviceaccount-opentelemetry-collector_test.yaml, config/helm/chart/default/tests/Common/operator/allowlistsynchronizer_test.yaml, config/helm/chart/default/tests/Common/webhook/poddisruptionbudget-webhook_test.yaml
DAQ-1491 
Customers using GKE-Autopilot can apply exceptions to GKE-Autopilot allowing workloads with higher privileges like the standalone logagent and csi driver.  The PR adds an AllowlistSynchronizer (if supported) which automatically applies the Allowlist. 
Some assertions were also fixed along the way.
If the helm chart is applied on a GKE Autopilot cluster >= 1.32 an AllowlistSynchronizer CR should be deployed additionally. This also allows the csi-driver and a standalone logagent to be rolled out, if enabled.
=> Add built-in GKE Autopilot Allowlistsynchronizer

pkg/controllers/dynakube/injection/reconciler.go, pkg/controllers/dynakube/processmoduleconfigsecret/conditions.go, pkg/controllers/dynakube/processmoduleconfigsecret/reconciler.go, pkg/controllers/dynakube/processmoduleconfigsecret/reconciler_test.go, pkg/injection/namespace/bootstrapperconfig/bootstrapperconfig.go, pkg/injection/namespace/bootstrapperconfig/bootstrapperconfig_test.go, pkg/injection/namespace/bootstrapperconfig/conditions.go, pkg/injection/namespace/bootstrapperconfig/endpoints.go, pkg/injection/namespace/bootstrapperconfig/pmc.go, pkg/injection/namespace/bootstrapperconfig/replicate.go
partial fix for [DAQ-7199](https://dt-rnd.atlassian.net/browse/DAQ-7199)
Use a unique Condition for the bootstarpper config secret.
- Only ping the Dynatrace API every now and then (or if the secret is missing)
Deploy dk with `node-image-pull: true` and see that we do not ping the Dynatrace API every reconcile.
Also should fix the "continues reconcile"
[DAQ-7199]: https://dt-rnd.atlassian.net/browse/DAQ-7199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Use conditions properly in bootstrapper config reconciler

pkg/clients/dynatrace/processmoduleconfig.go, pkg/clients/dynatrace/processmoduleconfig_test.go, pkg/injection/namespace/bootstrapperconfig/pmc.go
This PR resolves https://dt-rnd.atlassian.net/browse/DAQ-7199
unit tests, or deploy DK with 
```
kind: DynaKube
metadata:
name: lupl-bhd-1-5-0-autopilot
annotations:
feature.dynatrace.com/node-image-pull: "true"
feature.dynatrace.com/k8s-app-enabled: "true"
spec:
apiUrl: https://****.dev.dynatracelabs.com/api
networkZone: lupl-bhd-1-5-0-autopilot
metadataEnrichment:
enabled: true
oneAgent:
applicationMonitoring:
codeModulesImage: quay.io/dynatrace/dynatrace-bootstrapper:snapshot
activeGate:
capabilities:
- routing
resources:
requests:
cpu: 500m
memory: 1.5Gi
limits:
cpu: 1000m
memory: 1.5Gi
templates:
imageRef:
repository: hvq8020d.dev.dynatracelabs.com/linux/dynatrace-eec
tag: …
```
=> Preserver sorting of keys inside pmc properties

pkg/clients/dynatrace/processmoduleconfig.go, pkg/clients/dynatrace/processmoduleconfig_test.go, pkg/injection/namespace/bootstrapperconfig/pmc.go
fix for [DAQ-7199](https://dt-rnd.atlassian.net/browse/DAQ-7199)
same as #4744
same as #4744
[DAQ-7199]: https://dt-rnd.atlassian.net/browse/DAQ-7199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Preserver sorting of keys inside pmc properties (#4744) cherry-pick

config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring-full.yaml, config/helm/chart/default/tests/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring-full_test.yaml, config/helm/chart/default/values.yaml
The Helm switch `rbac.kubernetesMonitoringFull` is renamed to `preview.fullObjectCoverage`
* Helm unit tests
* Deploy operator with Helm and `--set preview.fullObjectCoverage.enabled=true` and check if ClusterRole(Binding) `kubernetes-monitoring-full` is created
* Deploy operator with Helm without the switch and the switch set to false and check that the ClusterRole is not created
=> Rename Helm switch kubernetes monitoring full

pkg/controllers/csi/metadata/correctness.go, pkg/controllers/csi/metadata/correctness_test.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-7546)
Directory names contain a trailing "=", the split removed this and therefore the list of directories to be kept was wrong. Hence still used directories have been deleted.
Here's a sample of an overlay mount that is used to find directories to keep:
```
overlay on /var/lib/kubelet/pods/509b7e32-38ff-4b40-a67d-8ba8036196a0/volumes/kubernetes.io~csi/oneagent-bin/mount type overlay (rw,relatime,lowerdir=/data/codemodules/cXVheS5pby9keW5hdHJhY2UvZHluYXRyYWNlLWJvb3RzdHJhcHBlcjpzbmFwc2hvdA==,upperdir=/data/appmounts/csi-a3dd8a9ab6e64e92efca99a0d180da60ab807f0e31a04e11edb451311130211c/var,workdir=/data/appmounts/csi-a3dd8a9ab6e64e92efca99a0d180da60ab807f0e31a04e11edb451311130211c/work,uuid=on)
```
Use the node image pull feature.
Deploy a …
=> Fix cleanup of unused agent versions.

.github/actions/build-push-image/action.yaml, .github/workflows/ci.yaml, fips.Dockerfile, hack/make/deploy/deploy.mk
[DAQ-6750](https://dt-rnd.atlassian.net/browse/DAQ-6750)
Adds a new step to the CI that builds a FIPS compliant version of the Operator.
This step only builds amd64 on PRs, and all other archs for protected-branches
The CI runs AND the created image works.
[DAQ-6750]: https://dt-rnd.atlassian.net/browse/DAQ-6750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add fips build to CI

pkg/controllers/csi/metadata/correctness.go, pkg/controllers/csi/metadata/correctness_test.go
[DAQ-7546](https://dt-rnd.atlassian.net/browse/DAQ-7546)
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/4783
same as https://github.com/Dynatrace/dynatrace-operator/pull/4783
[DAQ-7546]: https://dt-rnd.atlassian.net/browse/DAQ-7546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix cleanup of unused agent versions. (#4783)

cmd/operator/manager.go, cmd/operator/manager_test.go
There is bug in the webhook certificate management.
We don't renew them in the default scenario.
- This is bad, because they get outdated after 7 days
We renew them in the OLM scenario.
- This is bad, because in case of OLM, the webhook expects different certs, which we break with our renewed ones.
This only comes up in 2 cases:
- OLM deployments (here it will come up quickly)
- longer running deployments, when the generated certs gets outdated
These are ways to configure the Operator deployment to let the error surface.
in the `values.yaml` add the olm-annotation to the Operator
```yaml
operator:
annotations:
olm.operatorNamespace: beep
```
__IMPORTANT__: in a correct OLM scenario, both the Webhook and Operator would have this annotation, and the Webhook would also behave differently, …
=> Setup the cert controller properly

test/scenarios/release/release_test.go
We released 1.5.1 https://github.com/Dynatrace/dynatrace-operator/releases/tag/v1.5.1 so we want to enable e2e test for it. 
run release upgrade e2e tests:
```
make test/e2e/release
```
=> bump release tag for e2e tests to 1.5.1

test/helpers/components/operator/installation.go
Small improvement to print std.error from make deploy during running e2e tests:
After this change:
```
err: Error: Unable to continue with install: ClusterRoleBinding "dynatrace-extensions-prometheus" in namespace "" exists and cannot be imported
into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm";
annotation validation error: missing key "meta.helm.sh/release-name": must be set to "dynatrace-operator"; annotation validation error: missing
key "meta.helm.sh/release-namespace": must be set to "dynatrace"
make[1]: *** [deploy] Error 1
```
Before:
```
exit 2
```
Deploy operator using OLM or non HELM way, cleanup (manually not everything) and run e2e tests.
=> Improve error logging on e2e test helm

config/helm/chart/default/templates/Common/edge-connect/clusterrole-edgeconnect.yaml, config/helm/chart/default/tests/Common/edgeconnect/clusterrole-edgeconnect_test.yaml, doc/e2e/features.md, test/features/edgeconnect/edgeconnect.go, test/helpers/components/operator/installation.go, test/testdata/edgeconnect/custom-service-account.yaml
[DAQ-8310](https://dt-rnd.atlassian.net/browse/DAQ-8310)
A ClusterRole (similar what we do for other components) for EdgeConnect is missing, that allows the default ServiceAccount of EdgeConnect to use the nonroot SCC, due to the SecurityContext using the user/group 1000 
On CRC:
```
make test/e2e/edgeconnect
```
- ~2 out the 3 tests should pass~
- ~the 1 that is not passing is because of the custom ServiceAccount, needs to be fixed later/separatly~
all test should pass
[DAQ-8310]: https://dt-rnd.atlassian.net/browse/DAQ-8310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add clusterrole for EC in case of OCP

pkg/controllers/dynakube/oneagent/daemonset/daemonset.go, pkg/controllers/dynakube/oneagent/daemonset/daemonset_test.go
https://dt-rnd.atlassian.net/browse/DAQ-5871
Adds `cluster-autoscaler.kubernetes.io/enable-ds-eviction=false` to OneAgent DaemonSet Pods.
- Deploy DynaKube and check that the OneAgent DaemonSet Pod template has the annotation, and also the Pods.
=> Add `enable-ds-eviction` annotation in OneAgent DaemonSet

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-8563)
New implementations can be enabled with values.yaml :
```
csidriver:
livenessprobe:
builtIn: true
registrar:
builtIn: true
```
1) Genuine commands
- deploy operator
```
make deploy
```
- check csi.livenessprobe and csi.registrar containers (image, command, args)
2) Commands provided by the operator
- set values.yaml
```
csidriver:
livenessprobe:
builtIn: true
registrar:
builtIn: true
```
- deploy operator
```
make deploy
```
- check csi.livenessprobe and csi.registrar containers (image, command, args)
=> Makes livenessprobe and csi-node-driver-registrar commands provided by the operator opt-in

.github/workflows/fips-ci.yaml
https://dt-rnd.atlassian.net/browse/DAQ-6753
In #4849 we added checks to speed up the CI, I wrongly used `Dockerfile` and not `fips.Dockerfile` in the fips-ci. This is fixed now.
same as in #4849
=> Fix: Use correcrt dockerfile in case of fips

pkg/api/v1beta4/dynakube/convert_to.go, pkg/api/v1beta4/dynakube/convert_to_test.go
Fix https://dt-rnd.atlassian.net/browse/DAQ-8775
`spec.telemetryIngest` converter from beta4 to latest was missing.
- Unit tests :heavy_check_mark: 
- Deploy DK with `telemetryIngest` field on main and on this branch, check that on main the field is gone once deployed, and on this branch it is converted nicely.
```yaml
kind: DynaKube
metadata:
name: dynatrace-otel
spec:
apiUrl: https://pap94091.dev.dynatracelabs.com/api
telemetryIngest:
protocols:
- "otlp"
- "zipkin"
- "jaeger"
- "statsd"
tlsRefName: ""
serviceName: dynatrace-otel-telemetry-ingest
tokens: dynakube
```
=> Fix missing telemetryIngest converter from beta4 to latest

cmd/bootstrapper/cmd.go, cmd/bootstrapper/cmd_test.go, cmd/main.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-7409)
Adds `bootstrap` command.
Create a unittest which downloads an agent image.
Please use your own `<tenant url>` and `<token>`.
cmd/bootstrapper/cmd_live_test.go :
```
func TestBootstrapCmd(t *testing.T) {
t.Run("live test", func(t *testing.T) {
fs := afero.Afero{Fs: afero.NewMemMapFs()}
cmd := newCmd(afero.Afero{Fs: fs})
cmd.SetArgs([]string{
"bootstrap",
"--config-directory=/mnt/config",
"--input-directory=/mnt/input",
"--attribute-container={\"container_image.registry\":\"docker.io\"}",
"--source=/opt/dynatrace/oneagent",
"--target=/mnt/bin",
"--install-path=/opt/dynatrace/oneagent-paas",
"--technology=java",
"--technologies=java",
"--version=1.316.0.20250505-212724",
"--attribute=k8s.cluster.name=dynakube",
})
config := …
```
=> Add bootstrap subcommand

pkg/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/serviceport.go
[DAQ-8962](https://dt-rnd.atlassian.net/browse/DAQ-8962)
`serviceName` was added to Activegate Statefulset to provide a [more stable network ID](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id), but it's unclear whether that is currently the best approach and what exactly the implications of adding it will be. We'll remove it for now as it causes problems during upgrade (immutable field in Statefulset spec)!
1. Install Operator v1.5.1: `helm install dynatrace-operator oci://public.ecr.aws/dynatrace/dynatrace-operator --atomic --create-namespace -n dynatrace`
2. Apply Dynakube with Activegate present (any capability is fine)
3. Upgrade to local Operator: `make deploy`
[DAQ-8962]: https://dt-rnd.atlassian.net/browse/DAQ-8962?atlOrigin=eyJpIjoiNWRkNTlj …
=> Remove serviceName from Activegate Statefulset

pkg/clients/dynatrace/activegate_auth_token.go, pkg/clients/dynatrace/activegate_connection_info.go, pkg/clients/dynatrace/dynatrace_client.go, pkg/clients/dynatrace/dynatrace_client_test.go, pkg/clients/dynatrace/image.go, pkg/clients/dynatrace/oneagent_connection_info.go
If Dynatrace (or some proxy) returns non-JSON objects to the client (like `<!doctype html><html>hi</html>` for example), the following error message is currently returned:
```
response error, can't unmarshal json response 403: invalid character '<' looking for beginning of value
```
Now, this error message is more descriptive:
```
Server returned status code 403; can't unmarshal response (content-type: text/html): <!doctype html><html>hi</html>
```
Addresses [DAQ-2762](https://dt-rnd.atlassian.net/browse/DAQ-2762)
* Run unit tests in `pkg/clients/dynatrace/dynatrace_client_test.go`
[DAQ-2762]: https://dt-rnd.atlassian.net/browse/DAQ-2762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Improve error verbosity in the Dynatrace client

hack/make/tests/e2e.mk
`test/scenarios/no_csi` was moved to `test/scenarios/nocsi` in commit 09e69c07. Adapt the Makefile accordingly to fix our e2e tests.
Run e2e tests :)
=> Fix e2e tests after #4983

test/features/bootstrapper/without_csi.go
Resolves some left overs from https://github.com/Dynatrace/dynatrace-operator/pull/4923
`make test/e2e/applicationmonitoring/bootstrapper-no-csi`
=> test: fixup e2e test after refactroing node-image-pull secret split

pkg/controllers/csi/provisioner/controller_test.go, pkg/controllers/csi/provisioner/install.go
[DAQ-10243](https://dt-rnd.atlassian.net/browse/DAQ-10243)
The pull-secret created by the Operator (`dtpullsecret` package) is not needed in any way for the Jobs.
- This pull-secret is only meant for talking with the tenant registry
- The Jobs only get images from private/public registries
No warning: `Warning   FailedToRetrieveImagePullSecret`, when using a dynakube (CSI-driver needs to be used) such as:
```yaml
kind: DynaKube
metadata:
name: dynakube
annotations:
feature.dynatrace.com/node-image-pull: "true"
spec:
apiUrl: <some-url>
activeGate:
capabilities:
- routing
metadataEnrichment:
enabled: true
oneAgent:
applicationMonitoring: 
codeModulesImage: <some-image>
```
[DAQ-10243]: …
=> Only provide the custom-pull-secret to the download jobs

pkg/controllers/dynakube/logmonitoring/daemonset/container.go, pkg/controllers/dynakube/logmonitoring/daemonset/container_test.go
For the main container: [JIRA](https://dt-rnd.atlassian.net/browse/DAQ-10368)
For the init container: [JIRA](https://dt-rnd.atlassian.net/browse/DAQ-10370)
dk.templates.logMonitoring.resources field is used to set value of LogMonitoring main AND init container resources.
unittests
=> Use dk.templates.logMonitoring.resources to set value of main and init container resources

pkg/webhook/mutation/pod/register.go
Resolves bug https://dt-rnd.atlassian.net/browse/DAQ-10374
Short test-case:
1. Install operator
2. Deploy dk + deploy php sample apps ( all is working)
3. undeploy dk + remove php samples
4. deploy php-samples with manual label for ns [dynakube.internal.dynatrace.com/instance]`(http://dynakube.internal.dynatrace.com/instance): no-existent`
webhook will panic (more details in bug report)
Or an advanced realistic test from the ticket also.
repeat with release-1.6 and patch, after patch you should see no panic but instead warning event:
=> initialize recorder correctly

pkg/controllers/csi/driver/server.go
In #4062, we introduced a new environment variable, allowing users to control the value of `maxGrpcRequests`:
https://github.com/Dynatrace/dynatrace-operator/blob/ce77dbefd7834cb5c6f2e752f3584e62c12e725f/pkg/controllers/csi/driver/server.go#L106
This value is then cast to `int32` and used for configuring the gRPC server:
https://github.com/Dynatrace/dynatrace-operator/blob/ce77dbefd7834cb5c6f2e752f3584e62c12e725f/pkg/controllers/csi/driver/server.go#L111
The problem with this approach is that we don't ensure the value provided actually fits into `int32`. `strconv.Atoi` assumes the value to be of type `int`, not `int32` (see [golang docs](https://pkg.go.dev/strconv#ParseInt)).
ℹ️ This PR addresses [DTSEC-18257](https://dt-rnd.atlassian.net/browse/DTSEC-18257).
Configure the environment …
=> Fix potential integer overflow in the CSI gRPC server

pkg/controllers/dynakube/activegate/reconciler.go, pkg/controllers/dynakube/activegate/reconciler_test.go
The automatic-tls-certificate doesn't get deleted if AG is turned off in the DynaKube.
This PR resolves this problem https://dt-rnd.atlassian.net/browse/DAQ-9986
1. Deploy DK with AG is enabled
```
kind: DynaKube
metadata:
name: dynakube
spec:
apiUrl: https://****.dev.dynatracelabs.com/api
activeGate:
capabilities:
- routing
oneAgent:
cloudNativeFullStack: {}
```
2.  Check secret is created:
```
k get secrets -n dynatrace | grep tls
dynakube-activegate-tls-secret                       Opaque                           3      77s
```
3. Change dynakube to disable AG:
```
spec:
activeGate: {}
```
4. List all secrets, make sure tls secret deleted.
```
k get secrets -n dynatrace
NAME …
```
=> bug: remove automatic-tls-certificate when disable AG

config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, pkg/controllers/dynakube/activegate/internal/statefulset/statefulset.go, pkg/util/kubeobjects/topology/constraint.go
This PR adds the `nodeTaintsPolicy: Honor` flag to all the `NodeTaintsPolicy`. The reason is that otherwise the ActiveGate scaling could be blocked by tainted nodes (if the number of worker nodes is less than the number of replicas required). 
With the flag set, tainted nodes are respected correctly. 
This affects the
- ActiveGate sts
- Webhook pods
- EEC & Otel Collector
[Jira](https://dt-rnd.atlassian.net/browse/DAQ-11421)
- Taint a node
- create more ActiveGate pods than worker nodes 
- some nodes should have multiple ActiveGates / nothing is blocked
=> Add NodeTaintsPolicy to TopologySpreadConstraints

pkg/api/latest/dynakube/oneagent/props.go, pkg/clients/dynatrace/client.go, pkg/clients/dynatrace/endpoints.go, pkg/clients/dynatrace/settings.go, pkg/clients/dynatrace/settings_enrichment_test.go, pkg/clients/dynatrace/settings_kubernetes_test.go, pkg/clients/dynatrace/settings_test.go, pkg/controllers/dynakube/activegate_test.go, pkg/controllers/dynakube/apimonitoring/reconciler.go, pkg/controllers/dynakube/apimonitoring/reconciler_test.go, pkg/controllers/dynakube/controller_system_test.go, pkg/controllers/dynakube/controller_test.go, pkg/controllers/dynakube/injection/reconciler.go, pkg/controllers/dynakube/injection/reconciler_test.go, pkg/controllers/dynakube/k8sentity/conditions.go, pkg/controllers/dynakube/k8sentity/config.go, pkg/controllers/dynakube/k8sentity/reconciler.go, pkg/controllers/dynakube/k8sentity/reconciler_test.go, pkg/controllers/dynakube/logmonitoring/reconciler.go, pkg/controllers/dynakube/logmonitoring/reconciler_test.go, pkg/controllers/dynakube/monitoredentities/conditions.go, pkg/controllers/dynakube/monitoredentities/reconciler.go, pkg/controllers/dynakube/monitoredentities/reconciler_test.go, pkg/controllers/dynakube/token/feature.go, pkg/controllers/dynakube/token/tokens_test.go, pkg/util/conditions/time.go, pkg/util/conditions/token.go, test/mocks/pkg/clients/dynatrace/client.go
[DAQ-10641](https://dt-rnd.atlassian.net/browse/DAQ-10641)
Replace the `GetMonitoredEntitiesForKubeSystemUUID` that used the `entities.read` scope with `GetK8sClusterME` that uses `settings.read` scope to get the same thing.
- It lists the `builtin:cloud.kubernetes` settings, that have a `scope` which is the ID of the entity we are looking for
- Only 1 such setting exists per tenant per Kubernetes cluster, and the `label` of the setting is the Name of the entity 
`GetK8sClusterME` is bit hard to parse at first, I added all the docs strings to help with that.
- Writing `GetKubernetesClusterMonitoredEntity` was IMO way worse
- The term "ME" is a common Dynatrace term we already use it in the status, see `kubernetesClusterMEID`
`GetK8sClusterME` (as the rename suggest) assumes a few things: …
=> Remove `entities.read` scope usage and replace it with `settings.read`

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml
This PR resolves https://dt-rnd.atlassian.net/browse/DAQ-11106
It is mostly based on https://github.com/Dynatrace/dynatrace-operator/pull/5072, but it does not allow configuration (it requires some extra work and updates, so it will be done in future PRs if necessary).
```
- --probe-timeout={{- .Values.csidriver.livenessprobe.probeTimeout }}
```
kudos to @oihanitrz 
unit-tests
=> Add liveness probe config of csi daemonset in helm values

hack/build/bundle.sh
When it comes to releasing on the marketplaces we have to generate these bundles that are then added to the respective repos of the marketplaces. There we set the supported versions of OCP as `4.9-` but this is not correct anymore. We always had to update this upfront which is kind of annyoing. This PR fixes this as the marketplaces now want it to have set to `4.10`
Have a look at the latest PR to [community operators for example](https://github.com/redhat-openshift-ecosystem/certified-operators/pull/6212)
Here we had to update the annotations.yaml to get the pipeline running https://github.com/redhat-openshift-ecosystem/certified-operators/pull/6212/commits/93a3afd6013d50fddd5c8d0f8879b435c0655e74
Have a look at the PRs I linked
- run the bundle.sh and see if the versions field in …
=> Fix supported versions in bundle generation

test/helpers/components/dynakube/dynakube.go
resolves https://dt-rnd.atlassian.net/browse/DAQ-11804
`WaitForPhase ` waits 5 mins before this PR and fails from time to time because we wait for OneAgent to start to set phase to running.
my experiment shows that we achieve it faster in 2 mins or so ( status running i mean) but because we can't control that OneAgent will start quickly ( or even we don't know how fast) I extend default value to 8 mins. Also on CI in logs it takes more than 5 mins (300 seconds) .
```
NAMESPACE   NAME       APIURL                                       STATUS    AGE
dynatrace   dynakube   https://hbc47170.dev.dynatracelabs.com/api   Running   117s
NAMESPACE   NAME       APIURL                                       STATUS    AGE
dynatrace   dynakube   https://hbc47170.dev.dynatracelabs.com/api   Running   2m …
```
=> e2e: increase wait for dk status

config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml, config/helm/chart/default/tests/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring_test.yaml
Kubernetes monitoring Activegate requires additional permissions for the K8s smartscape feature and for this I updated respective ClusterRole.
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-11915)
Helm unittests
Deploy the operator and check the `clusterrole` (`dynatrace-kubernetes-monitoring`)
=> Extend ActiveGate ClusterRole permissions

pkg/controllers/dynakube/logmonitoring/daemonset/container.go, pkg/controllers/dynakube/logmonitoring/daemonset/container_test.go
Co-authored-by: Marcell Sevcsik <marcell.sevcsik@dynatrace.com>
same as https://github.com/Dynatrace/dynatrace-operator/pull/5065
same as https://github.com/Dynatrace/dynatrace-operator/pull/5065
=> Use dk.templates.logMonitoring.resources to set value of main and init container resources (#5065)

pkg/webhook/mutation/pod/common/metadata/annotations.go, pkg/webhook/mutation/pod/common/metadata/annotations_test.go
Ticket: https://dt-rnd.atlassian.net/browse/DAQ-12297
Currently the operator is not copying all annotations with "metadata.dynatrace.com/" prefix from the pod to the enrichment file, only the ones that are copied from the namespace (either with prefix or by specified rule). Example: If there is a pod that has metadata.dynatrace.com/someannotation: annotation set when its scheduled, this will not land in the enrichment file, even though it is expected land there.
Deploy a `DynaKube` without or with NodeImagePull enabled (both should work), aswell as metadataEnrichment enabled.
```
metadataEnrichment:
enabled: true
```
Schedule a pod within a namespace that has an annotation set with prefix "metadata.dynatrace.com/", check if this annotation incl. value is ending up in the enrichment file
=> Fix metadataEnrichment not adding prefixed pod annotations to enrichment files

pkg/controllers/dynakube/extension/eec/statefulset.go, pkg/controllers/dynakube/extension/service.go, pkg/controllers/dynakube/otelc/service/reconciler.go, pkg/controllers/dynakube/otelc/statefulset/reconciler.go
Currently, `app.kubernetes.io/version` is set to `0.0.0` for the EEC + OTelC components, which can be misleading.
☑️ Addresses [DAQ-12251](https://dt-rnd.atlassian.net/browse/DAQ-12251)
Unit tests
[DAQ-12251]: https://dt-rnd.atlassian.net/browse/DAQ-12251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove incorrect app version labels

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, pkg/api/v1beta1/dynakube/dynakube_types.go, pkg/api/v1beta2/dynakube/dynakube_types.go
https://dt-rnd.atlassian.net/browse/DAQ-12588
v1beta1 and v1beta2 are no longer served.
- Apply a Dynakube with either v1beta1 or v1beta2
- You should see:
```sh
❯ k apply -f ~/dev/playground/dynakubes/beta2-CNFS.yaml
error: resource mapping not found for name: "dynakube" namespace: "dynatrace" from "/home/local_albertogildedios/dev/playground/dynakubes/beta2-CNFS.yaml": no matches for kind "DynaKube" in version "dynatrace.com/v1beta2"
ensure CRDs are installed first
```
=> Do not serve v1beta1 and v1beta2

pkg/controllers/dynakube/dtpullsecret/reconciler.go, pkg/controllers/dynakube/dtpullsecret/reconciler_test.go, pkg/util/conditions/secret.go, pkg/util/conditions/suffix.go
This PR refactors dtpull secret reconciler and resolves [DAQ-1457](https://dt-rnd.atlassian.net/browse/DAQ-1457)
a) unit-tests
b) deploy operator and simple DK,
- find `<dk-name>-pull-secret` via:
```
k get secrets | grep "\-pull-secret"
dynakube-pull-secret                                 kubernetes.io/dockerconfigjson   1      8m19s
```
so make sure it;s created;
- Also, you can check the condition on DK, which we use to make sure it gets updated in time:
```
Last Transition Time:  2025-08-21T07:45:40Z                                                                                              │
│     Message:               dynakube-pull-secret updated                                                                                      │
│     Reason:                SecretUpdated …
```
=> refactor dtpull secret

pkg/controllers/dynakube/otelc/endpoint/reconciler.go, pkg/controllers/dynakube/otelc/endpoint/reconciler_test.go, pkg/util/kubeobjects/configmap/query.go
This PR resolves https://dt-rnd.atlassian.net/browse/DAQ-12249 by refactoring `./otelc/endpoint/reconciler.go` the way we want all similar reconcilers to work, except it's configmap and not a secret.
a) unit tests or
b) deploy dk like in official docu:
```
kind: DynaKube
metadata:
name: dynakube
spec:
apiUrl: https://****.dev.dynatracelabs.com/api
activeGate:
capabilities:
replicas: 1
resources:
requests:
cpu: 500m
memory: 1.5Gi
limits:
cpu: 1000m
memory: 1.5Gi
telemetryIngest:
protocols:
- jaeger
- zipkin
- otlp
- statsd
templates:
otelCollector:
imageRef:
repository: public.ecr.aws/dynatrace/dynatrace-otel-collector
tag: 0.34.0
```
- check the content of the configmap: 
```
k get configmaps …
```
=> bugfix(otelc): telemetry ingest endpoint config map is not updated

.github/workflows/e2e-tests-ondemand.yaml
Make sure latest K8s versions are tested.
n/a
=> Add K8S 1.33 and 1.34 pipelines to on-demand tests.

pkg/webhook/mutation/pod/init_test.go, pkg/webhook/mutation/pod/mutator/oneagent/config.go, pkg/webhook/mutation/pod/mutator/oneagent/init.go, pkg/webhook/mutation/pod/mutator/oneagent/init_test.go
https://dt-rnd.atlassian.net/browse/DAQ-13021
Same as #5308
=> cherry-pick: Fix wrong init-container runAsNonRoot value on OCP (#5308)

test/scenarios/istio/istio_test.go
This PR fixes [DAQ-12605](https://dt-rnd.atlassian.net/browse/DAQ-12605)
some leftovers after https://github.com/Dynatrace/dynatrace-operator/pull/5196/files#diff-2f7cca8cafba0692289e73986528a8e6794530308949a9a1390c383054afe155L58-L59
`make test/e2e/cloudnative/codemodules-with-proxy-custom-ca-auto-ag-cert`
[DAQ-12605]: https://dt-rnd.atlassian.net/browse/DAQ-12605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add missing httpsProxy setting to istio tests

doc/coding-style-guide.md, pkg/injection/codemodule/installer/image/unpack.go, pkg/injection/codemodule/installer/symlink/symlink_test.go, test/features/cloudnative/codemodules/codemodules.go, test/features/cloudnative/networkproblems/network_problems.go, test/features/edgeconnect/edgeconnect.go, test/features/extensions/extensions.go, test/features/logmonitoring/logmonitoring.go, test/features/supportarchive/support_archive.go, test/features/telemetryingest/telemetryingest.go, test/helpers/components/oneagent/uninstall.go, test/helpers/kubeobjects/namespace/istio.go, test/helpers/proxy/proxy.go, test/helpers/sample/app.go, test/helpers/tenant/secrets.go, test/helpers/tenant/secrets_test.go, test/helpers/tls/tls.go, test/project/project.go
Outcome of discussion [here](https://github.com/Dynatrace/dynatrace-operator/pull/5335#discussion_r2315838554)
* Use `path/filepath` for all filesystem path operations. Turns out `path` was use in a lot of places.
* Mention this guideline in the docs
* fly-by: Fix outdated link in the docs
The behavior is unchanged for Linux/OSX, so unit tests should suffice.
Windows may need to run e2e tests to properly verify.
=> Use path/filepath for filesystem paths

pkg/webhook/mutation/pod/config.go, pkg/webhook/mutation/pod/init.go, pkg/webhook/mutation/pod/init_test.go, pkg/webhook/mutation/pod/mutator/oneagent/config.go, pkg/webhook/mutation/pod/mutator/oneagent/init.go, pkg/webhook/mutation/pod/mutator/oneagent/init_test.go
[DAQ-13355](https://dt-rnd.atlassian.net/browse/DAQ-13355)
There was a bug found, when somehow setting the `podSecurityContext`'s user to `0` causes a problem, that we still think it is "non root", the unit tests make it look that everything is fine.
- Added a lot more unittests, on different levels
- Fixed the `IsNonRoot` check, to check what is actually kubernetes will check
- If the `RunAsUser` is `0`, it is `RunAsNonRoot: false`
- If the `RunAsUser` is anything but `0`, it will be `RunAsNonRoot: true`
-   `RunAsGroup` has not effect, user takes precedence
- Only `RunAsGroup` is set, and it is `0`,  it will be `RunAsNonRoot: true`
Inject into a Pod with a PodSecurityContext like:
```
securityContext:
runAsUser: 0
```
[DAQ-13355]: …
=> Improve RunAsNonRoot check

test/features/logmonitoring/logmonitoring.go, test/helpers/components/dynakube/dynakube.go, test/helpers/tenant/secrets.go, test/testdata/secrets-samples/single-tenant.yaml
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-13598)
PR adds functions to install dynakube and/or apiToken without settings scopes.
All tests use normal apiToken which has `settings` scopes granted.
The `logmonitoring.WithOptionalScopes` test first install dynakube and ApiToken without optional scopes. Next the token secret is updated and following steps are performed.
`ApiTokenNoSettings` token shouldn't have the following scopes:
- settings.read
- settings.write
- entities.read
We can remove `entities.read` from the official `ApiTokenNoSettings` token after this fix is back-ported to all branches that are still tested and use this [logic](https://github.com/Dynatrace/dynatrace-operator/blob/v1.7.0/test/helpers/tenant/secrets.go#L113).
Create testdata/secrets/single-tenant.yaml
``` …
```
=> Fix failing test/e2e/release test (failing if launched locally).

cmd/operator/manager.go, cmd/operator/manager_test.go, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/values.yaml, pkg/clients/dynatrace/agent_version.go, pkg/clients/dynatrace/agent_version_test.go, pkg/clients/dynatrace/client.go, pkg/clients/dynatrace/client_test.go, pkg/clients/dynatrace/dynatrace_client.go, pkg/clients/dynatrace/dynatrace_client_test.go, pkg/clients/dynatrace/endpoints.go, pkg/clients/dynatrace/send_event.go, pkg/clients/dynatrace/send_event_test.go, pkg/consts/host_availability.go, pkg/controllers/dynakube/controller_test.go, pkg/controllers/dynakube/token/feature.go, pkg/controllers/dynakube/token/tokens_test.go, pkg/controllers/nodes/cache.go, pkg/controllers/nodes/cache_test.go, pkg/controllers/nodes/config.go, pkg/controllers/nodes/nodes_controller.go, pkg/controllers/nodes/nodes_controller_test.go, pkg/controllers/nodes/oneagent_dao.go, pkg/util/envvars/envvars.go, pkg/util/envvars/envvars_test.go, test/features/supportarchive/files.go, test/mocks/pkg/clients/dynatrace/client.go
same as https://github.com/Dynatrace/dynatrace-operator/pull/5426
same as https://github.com/Dynatrace/dynatrace-operator/pull/5426
=> [main] Reintroduce “Mark for termination” event to improve graceful node shutdown detection for setups using autoscaling (#5426)
