Dynatrace/dynatrace-operator

config/manifests/deployment-operator.yaml, controllers/kubemon/statefulset.go, controllers/kubemon/statefulset_test.go
* Use Quay image for dev deployments.
* Add resources limits to deployments.
* Remove command line argument from deployment and environment variable with the name, since they are unused.
* Use ParallelPodManagement for the StatefulSet deployment, allowing the StatefulSet to redeploy Pods even if they aren't ready.
=> Miscellaneous fixes

controllers/kubemon/statefulset.go, controllers/kubemon/statefulset_test.go
Once the StatefulSet has been created, selector labels can't be updated anymore, so let's not include the custom ones there. We don't need them there anyway.
=> Don't include custom labels on selectors

controllers/customproperties/reconciler.go, controllers/kubemon/reconciler.go, controllers/kubemon/reconciler_test.go, controllers/kubemon/statefulset.go, controllers/kubemon/statefulset_test.go
On this PR,
* The custom.properties file is mounted into the correct location.
* If there are changes, Pods get restarted, including,
* Changes on `.value`
* Changes on the secret being pointed by `.valueFrom` (checked each reconciliation, so there may be a delay.)
=> Restart Pods when custom.properties change

config/manifests/clusterrole-kubernetes-monitoring.yaml
Added the API group 'config.openshift.io' with the resource 'clusterversions' to query the Openshift cluster version
=> Extend clusterrole for clusterversions resource

controllers/dtpullsecret/generate.go, controllers/dtpullsecret/generate_test.go, controllers/dtpullsecret/reconciler_test.go, controllers/dtversion/docker.go, controllers/dtversion/docker_config.go, controllers/dtversion/docker_config_test.go, controllers/dtversion/docker_test.go, controllers/kubemon/reconciler.go
* Recognize skipCertCheck when looking for the image hash/version. The container runtimes still need to be updated for them to be able to pull images.
* Fix the generation of the Dynatrace's Pull Secret for ActiveGate/Managed API URLs (i.e., only put the domain as the registry.)
=> Recognize skipCertCheck when looking for the image hash/version

.gitignore, Makefile
There are few steps needed when deploying the Operator in dev clusters.
In particular, if using the dev images built from branches, it needs to be updated on the Deployment, and soon other places. I've updated the Makefile to,
* Create namespace/project if it doesn't exist.
* Create a temporary kustomization.yaml in "config/deploy" to make changes on.
* Set the image to the one that gets published for the branch on the CI pipeline to Quay.
The temporary kustomization.yaml file is inside .gitignore as well to avoid dirtying the directory.
The idea is that you can run `make deploy` and things will be deployed as they should, assuming that the image has been built already by the CI pipeline.
I also added `make deploy-ocp` for when using OpenShift.
=> Use branch image in make deploy

webhook_bootstrapper.go, webhook_server.go
We're currently using the same as the OneAgent Operator's and there are conflicts.
=> Use webhook lock names different than OneAgent Operator's

.travis.yml, controllers/namespace/init.sh.test-sample, controllers/namespace/init.sh.tmpl, controllers/namespace/namespace_controller.go, controllers/namespace/namespace_controller_test.go, go.mod
With Go 1.16, we can finally move the scripts to their own files. Remember to upgrade your Go installation if needed.
=> Migrate to Go 1.16, and use embedded files for init.sh script

HACKING.md
Also removing the instructions to build custom images, since they don't work as they are there. If you're a developer at Dynatrace, create a branch on this repository, and commits will autogenerate an image.
=> Use correct instructions to deploy development builds

.travis.yml, build/deploy.sh, cmd/csidriver/main.go, cmd/operator/main.go, version/version.go
We just logged the version. This PR logs a few things,
```json
{"level":"info","ts":"2021-03-11T09:28:01.276Z","logger":"dynatrace-operator.version","msg":"Dynatrace Operator","version":"snapshot-feature-commit-version","gitCommit":"b86e8496baeb550ff715e4df65f49668f6713e5e","buildDate":"2021-03-11 09:22:10+00:00","goVersion":"go1.16.1","platform":"linux/amd64"}
```
=> Include Git commit hash and build date in Operator version log

controllers/capability/labels.go, controllers/capability/reconciler.go, controllers/capability/reconiler_test.go, controllers/capability/routing/service.go, controllers/capability/routing/service_test.go, controllers/capability/statefulset.go, controllers/capability/statefulset_test.go
changed labels on the four locations again
- Label of sts
- match label of sts
- label of pod template
- selector of service
Example of labels: 
```
dynatrace.com/component: activegate
operator.dynatrace.com/feature: msgrouting
operator.dynatrace.com/instance: dynakube
```
only for the stateful set as it is immutable, we need to destroy it by hand, if the labels are not correct
=> Service selector for routing matches all instances - new keys

controllers/capability/routing/reconciler.go, controllers/capability/routing/reconiler_test.go, controllers/capability/routing/service.go, controllers/dynakube/dynakube_controller.go, controllers/dynakube/dynakube_controller_test.go
Fix 2 bugs where msg routing service not deleted: 
- After deletion of dynakube object, msgrouting not destroyed
- After disabling of routing in CR-file, msgrouting not destroyed
=> Fix message routing service not delete

controllers/oneagent/oneagent_controller.go
Update installer url for oneagent
`ONEAGENT_INSTALLER_TOKEN` was just renamed, as this variable is no longer required
=> Remove token from installer url parameter

cmd/csidriver/main.go, config/kubernetes/csi/daemonset-csi.yaml
The CSI driver process/container lacks a health check. This PR adds a liveness probe to the driver container in addition to the liveness-probe sidecar container.
=> Add CSI driver health probe

Makefile
When running `make deploy` for a local branch the image tag is set to an invalid value. This PR fixes the corresponding `sed` command.
=> Fix building the image tag for branch deployments

HACKING.md
Current docs is at https://sdk.operatorframework.io/docs/installation.
(The last known version was at: https://github.com/operator-framework/operator-sdk/blob/b448429687fd7cb2343d022814ed70c9d264612b/doc/user/install-operator-sdk.md)
=> Updated link to Operator SDK user guide

controllers/activegate/statefulset.go, controllers/activegate/statefulset_test.go
ARM64 node affinity selector for ActiveGate based capabilities like KubeMon causes pods to fail on this architecture. Therefore removed the unsupported architecture from the node affinity selector.
Fixes #139
=> Remove unsupported architecture ARM64 from ActiveGate node affinity selector

Makefile
Solved problem with make deploy from a branch:
`Makefile:19: *** unterminated call to function 'shell': missing ')'.  Stop.`
=> fixup! Fix building the image tag for branch deployments (#136)

deploy/install.sh
In addition to the cluster name we now also check if the Kubernetes endpoint is already registered at Dynatrace and stop proactively.
=> Add check for existing cluster endpoint

Makefile
```
$ make test
...
source /home/michal/workspace/dynatrace-operator/testbin/setup-envtest.sh; fetch_envtest_tools /home/michal/workspace/dynatrace-operator/testbin; setup_envtest_env /home/michal/workspace/dynatrace-operator/testbin; go test ./... -coverprofile cover.out
/bin/sh: 1: source: not found
/bin/sh: 1: fetch_envtest_tools: not found
/bin/sh: 1: setup_envtest_env: not found
ok      github.com/Dynatrace/dynatrace-operator/api/v1alpha1    0.007s  coverage: 8.0% of statements
?       github.com/Dynatrace/dynatrace-operator/cmd/csidriver   [no test files]
?       github.com/Dynatrace/dynatrace-operator/cmd/operator    [no test files]
...
```
Makefile uses `sh` as the default shell, on ubuntu:
```
$ ls -l `which sh`
lrwxrwxrwx 1 root root 4 lut  6 12:03 /usr/bin/sh -> dash
```
`dash` …
=> Makefile explicitly uses bash instead of sh

config/common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml
Add explicit nonResourceURLs endpoints in kubernetes-monitoring cluster role:
- readyz
- healthz
- version
=> APM-308295 Add explicit nonResourceURLs endpoints for kubernetes-monitoring

deploy/install.sh
Issue #160
Host Group parameter not applied
Modify the host group in install.sh file, remove the double quotes.
OLD:
- --set-host-group="${CLUSTER_NAME}"
NEW:
- --set-host-group=${CLUSTER_NAME}
=> Removed quotes around ${CLUSTER_NAME} in host group parameter.

cmd/csidriver/main.go, controllers/csi/provisioner/reconciler.go
We are still using os in /controllers/csi/driver/mount.
This won't change as the Mount struct in "k8s.io/utils/mount" assumes we use a real file system.
=> Replace os with afero

deploy/install.sh
dataIngest AG POD will be deployed by install.sh once https://github.com/Dynatrace/dynatrace-operator/releases/latest/download/kubernetes.yaml is updated to the current (master) version.
```
pod/dynakube-data-ingest-0
pod/dynakube-kubemon-0
pod/dynakube-routing-0
```
Right now nothing happens
```
pod/dynakube-kubemon-0
pod/dynakube-routing-0 
```
=> install.sh prepared to deploy dataIngest AG POD

api/v1alpha1/zz_generated.deepcopy.go, controllers/csi/gc/binaries.go, controllers/csi/gc/binaries_test.go, controllers/csi/gc/controller.go, controllers/csi/gc/logs.go, controllers/csi/gc/logs_test.go
To prevent filling up the storage on the CSI driver with logs we implemented a garbage collector.
The logs are stored in `/tmp/data/<tenant>/log/<podUID>`
If a pod gets deleted (or dies) the folder gets persisted on the CSI driver.
To identify the folders created by non-existing pods we get the pod references files (which are stored under `/tmp/data/<tenant>/gc/<agentVersion>/<podUID>`) used for the binary garbage collector, diff them against all the existing folders within the log folder and create the delta, which are considered as dead folders.
Those will eventually get deleted when the following conditions are met:
1. the folder is older than 14 days **and**
2. the size of the overall log folder is bigger than 300MB **or**
3. the amount of log folders of dead pods is bigger than 1000
=> Implement log garbage collector for CSI driver

controllers/csi/driver/server.go, controllers/csi/driver/server_test.go, go.mod
To not have a bunch of 0 values for no longer used version labels in `agentsVersionsMetric`, now it deletes these labels
=> Cleaner metrics

controllers/namespace/init.sh.test-sample, controllers/namespace/init.sh.tmpl
Cloud Native FullStack == codeModules + infraMonitoring enabled
init.sh gets created if codeModules enabled
`${host_tenant}" != ""` is true when infraMonitoring is enabled
==> This change is simple
=> Adds is isCloudNativeFullStack into the conf file when cloud native full stack mode is on

troubleshoot/README.md
* Script has be run via `bash` and not `sh`
=> Fix troubleshoot script usage

config/openshift3.11/operator/deployment-operator-patch.yaml, controllers/activegate/reconciler/capability/reconciler.go, controllers/activegate/reconciler/capability/reconciler_test.go, controllers/activegate/reconciler/statefulset/affinity.go, controllers/activegate/reconciler/statefulset/affinity_test.go, controllers/activegate/reconciler/statefulset/reconciler.go, controllers/activegate/reconciler/statefulset/reconciler_test.go, controllers/activegate/reconciler/statefulset/statefulset.go, controllers/activegate/reconciler/statefulset/statefulset_test.go, controllers/dynakube/dynakube_controller.go, controllers/kubeobjects/affinity.go, controllers/kubeobjects/affinity_test.go, controllers/kubesystem/version_provider.go, controllers/kubesystem/version_provider_test.go, controllers/oneagent/daemonset/affinity_test.go, controllers/oneagent/daemonset/daemonset.go, controllers/oneagent/daemonset/daemonset_test.go, controllers/oneagent/oneagent_controller.go, controllers/oneagent/oneagent_controller_test.go
implemented adding beta-os and beta-arch node affinities if deployed on openshift 3.11
=> fix: re-added affinity support for openshift 3.11

controllers/csi/daemonset.go, controllers/csi/daemonset_test.go
* Move `driver` limits/requests to same constant
* Add default resource requests/limits to `registrar` and `liveness-probe` container
If no mismatched values are configured via the `csi-resources` annotation, the csi driver pod now gets the `qosClass` of `Guaranteed`
=> Add resources to all csi driver containers

controllers/csi/daemonset.go, controllers/csi/daemonset_test.go
* Raise registrar and liveness-probe container memory requests/limits to 15M
=> Raise memory limits for CSI driver containers

config/openshift/kustomization.yaml, config/openshift/operator/deployment-operator-patch.yaml, controllers/oneagent/daemonset/env_vars.go
* OneAgent installer environment variables were missing in case of non-immutable image
* Remove `RELATED_IMAGE` environment variable being set per default on Openshift (set in CSV anyway)
=> Add oneagent installer environment variables when needed

webhook/mutation/pod_mutator.go, webhook/mutation/pod_mutator_test.go
* `IfNotPresent` only pulls image if it is not already present on the node
=> Change ImagePullPolicy to IfNotPresent for init container

webhook/mutation/pod_mutator.go
This was removed accidentally during the namespaceSelector rework.
This annotation could be set on both the namespace or the pod, but after the namespaceSelector was introduced, it no longer made sense to look for it on the namespace, but it still make sense to do it for the pod.
=> Reintroduce annotationInject for pods only

config/common/operator/deployment-operator.yaml, config/common/webhook/deployment-webhook.yaml
**Recreate** strategy introduces service interruptions (i.e. pod startup fails or injection does not happen) if adjustments are made to the deployment. To avoid that, .spec.strategy should be set to the default **RollingUpgrade**.
=> Change update strategy to RollingUpgrade for Operator/Webhook Deployment

cmd/operator/csi_driver.go, cmd/operator/debug.go, cmd/operator/main.go, cmd/operator/operator.go, cmd/operator/webhook.go, controllers/certificates/webhook_reconciler.go, controllers/dynakube/dynakube_controller.go
* Add 2nd manager to create and add certificates to CRD/webhook configurations on initial run
* Start remaining controllers after successful bootstrapper run
* Refactor subcommands in `main.go` to use switch
=> Add bootstrap manager for certificates

troubleshoot/README.md, troubleshoot/troubleshoot.sh
Add checks for dependencies that are needed in order for the troubleshootscript to work on MacOS
=> Update troubleshootscript for MacOS

controllers/oneagent/daemonset/daemonset.go, controllers/oneagent/oneagent_controller_test.go, integrationtests/oneagent_controller_integration_test.go
- Remove deploymenttype name from ds and pod name
- Add new static label `operator.dynatrace.com/agenttype=os` for ds and pod template matching
=> Removed deploymentType name from DaemonSet and pod name

controllers/kubeobjects/daemonset.go
* `CreateOrUpdateDaemonSet` is used in a different context than the csi driver now
=> Update misleading log message

controllers/oneagent/oneagent_controller.go
With the removal of the feature from the daemonset name, the old daemonset with the feature in the name would never be removed and block the new pods
=> Remove old classic daemonset if exists

config/kubernetes/kustomization.yaml, config/openshift/kustomization.yaml
This PR changes the operator image on the release branch, to "snapshot-release-0-3" instead of "snapshot", so kustomize (-k) can be used to apply the operator
=> Change image tag for K8s and OCP on 0.3.0 branch

.travis.yml
Release branch images on quay shouldn't expire
=> Removes expire on release branch images

controllers/csi/driver/bind_config.go, controllers/csi/driver/bind_config_test.go, controllers/csi/driver/server_test.go, controllers/csi/metadata/correctness.go, controllers/csi/metadata/correctness_test.go, controllers/csi/metadata/fakes.go, controllers/csi/metadata/metadata.go, controllers/csi/metadata/sqlite.go, controllers/csi/metadata/sqlite_test.go, controllers/csi/provisioner/reconciler.go, controllers/csi/provisioner/reconciler_test.go
The name `tenants` for the CSI driver database is no longer correct.
Since the `namespaceSeletor` change,  the key for the `tenants` table needed to be changed to the dynakube name from the tenantUUID. 
The current name is confusing and we should change it as soon as possible to avoid db migrations.
=> Renames tenants table to dynakubes

config/crd/patches/webhook_in_dynakubes.yaml
During an upgrade from a crd version `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1` there is some kind of kubernetes conversion voodoo magic that sets `preserveUnknownFields` to true which is not compatible with the conversion webhook. So we have to set it to false, after which the field is magically removed by kubernetes :shrug:
=> Adds preserveUnknownFields to webhook patch

README.md, config/samples/applicationMonitoring.yml, webhook/validation/validation.go, webhook/validation/validation_test.go
As applicationMonitoring should only be in beta state, if the CSI Driver is used, then the beta warning should also only be shown if the mentioned conditions are met and not for all applicationMonitoring configurations. Additionally this is mentioned in the readme now.
=> Change beta warning condition for applicationMonitoring

README.md, config/samples/applicationMonitoring.yml, config/samples/classicFullStack.yml, config/samples/cloudNativeFullstack.yml, config/samples/hostMonitoring.yml, config/samples/multipleDynakubes.yml
`data-ingest` is not supported in 0.3.0 release, so example usages are removed from config samples.
=> Remove data-ingest from docs

config/samples/applicationMonitoring.yml
In order for the applicationMonitoring sample to work, we have to create a yaml object explicitly
=> Update applicationMonitoring sample to create yaml object explicitly

troubleshoot/troubleshoot.sh
Troubleshoot script should also use activeGate image version, as it currently checked always only for 'latest' and did not take the version set in the CR into consideration.
=> Update troubleshoot script with activegate version check

README.md
The readme should indicate, that OCP 3.11 is not support by the next release v0.3.0 anymore
=> Update support-matrix to remove OCP 3.11 from v0.3.0

controllers/csi/provisioner/processmoduleconfig.go
When there is no api we need (clusters with older versions) we receive nil from the `dtclient`,  `addHostGroup` doesn't check for this
=> Fixes nil pointer issue during processmoduleconfig update

build/release.sh
Missing `#!/bin/bash` causes script to be interpreted incorrectly
=> Use bash in script

troubleshoot/troubleshoot.sh
With this every form of tenant (managed or not, port given or not) should be parsed correctly:
- The image (oneagent and activegate)
- The Version of the images
- The registry
=> Add support for managed tenant api url to troubleshoot script

api/v1beta1/activegate_types.go, api/v1beta1/oneagent_types.go, config/crd/bases/dynatrace.com_dynakubes.yaml
Updating the comments which describe, where the ActiveGate and the OneAgent are per default (Registry on the tenant
=> Update comments for OneAgent and ActiveGate image location

api/v1beta1/oneagent_types.go, config/crd/bases/dynatrace.com_dynakubes.yaml
Previous wording was confusing, so this PR clarifies that the field is used to enable autoUpdate (which is enabled by default)
=> Clarify autoUpdate comment

config/common/webhook/deployment-webhook.yaml
`kubectl.kubernetes.io/default-logs-container` is deprecated and was replaced by `kubectl.kubernetes.io/default-container`
(we already use it here https://github.com/Dynatrace/dynatrace-operator/blob/master/config/common/csi/daemonset.yaml#L17)
=> Replaces deprecated logs annotation from webhook deployment

config/common/operator/clusterrole-operator.yaml, controllers/certificates/webhook_reconciler.go, controllers/certificates/webhook_reconciler_test.go
the `client.Client` uses a cache in the background that needs clusterwide list/watch permissions for resources that we get via `client.Get`. (why? I don't know, its an issue in the controller-runtime)
Cache is not needed for the certificate controller because it only runs every 3 hours (on success).
So this introduces an `apiReader` to be used for getting the resources. (the `client.Client` is still needed for updating resources)
=> Simplify the permissions for the certificate generation

api/v1alpha1/zz_generated.deepcopy.go, api/v1beta1/zz_generated.deepcopy.go, controllers/activegate/internal/consts/consts.go, controllers/activegate/reconciler/capability/reconciler.go, controllers/activegate/reconciler/capability/reconciler_test.go, controllers/activegate/reconciler/capability/service.go, controllers/activegate/reconciler/capability/service_test.go
If service mesh is used, http rest endpoint is preferred over https.
=> AG service: port redirection 80->9998 added

src/controllers/csi/metadata/path_resolver.go, src/controllers/csi/provisioner/agent.go
```
I have no name!@java-glibc-56978775fb-rbpfs:/$ ls -l opt/dynatrace/oneagent-paas/agent/bin/
total 16
drwxr-xr-x 6 root root 4096 Jan  3 15:14 1.233.1.20211231-040645
drwxr-xr-x 2 root root 4096 Jan  3 15:14 any
lrwxrwxrwx 1 root root   23 Jan  3 15:24 current -> 1.233.1.20211231-040645     <== ADDS THIS SYMLINK 
drwxr-xr-x 2 root root 4096 Jan  3 15:14 linux-musl-x86-64
drwxr-xr-x 2 root root 4096 Jan  3 15:14 linux-x86-64
```
=> Creates symlink for current version in CSI driver in the agent bin

src/controllers/csi/provisioner/agent.go
If multiple Dynakubes are used, symlink creation can fail because the target already exists.
=> Skip symlink creation if folder exists already

.github/workflows/ci.yml, Dockerfile, build/deploy_local.sh
When using the `deploy_local.sh` the images that is builds are broken. The following error can be seen in the cluster:
```
> k logs -n dynatrace dynatrace-operator-5d4db8759d-cm47c 
/usr/local/bin/entrypoint: line 3: /usr/local/bin/dynatrace-operator: No such file or directory
```
Since the change https://github.com/Dynatrace/dynatrace-operator/pull/412 the `Dockerfile` changed a bit.
The important part:
```
RUN CGO_ENABLED=1 go build -ldflags "${GO_BUILD_ARGS:1:-1}" -o ./build/_output/bin/dynatrace-operator ./src/cmd/operator/
```
🔍  ENHANCE!!: (the problematic part)
```
${GO_BUILD_ARGS:1:-1}
```
🔍  ENHANCE!! : (the weird part)
```
:1:-1
```
This is somehow necessary for the github actions to work. (removing the first and last character from the build args)
Why? No idea. (github actions …
=> Fixes deploy_local.sh to work with 'new' Dockerfile

.github/workflows/ci.yml
- We need to update the package cache on the github action runner before installing the packages, otherwise the index could reference to no longer existing package locations.
=> Update dependencies before install of packages in GitHub actions

config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml
When testing the deployment via GKE deployer image, the deployer job ran into an error when no value for .Values.olm was given.
Adding a default value fixes this error.
=> Fixed error when deploying via GKE deployer image

README.md, config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/questions.yml, config/helm/chart/default/tests/Common/customresource-modules/customresource-dynakube_activegate_test.yaml, config/samples/applicationMonitoring.yaml, config/samples/classicFullStack.yaml, config/samples/cloudNativeFullStack.yaml, config/samples/hostMonitoring.yaml, config/samples/multipleDynakubes.yaml, src/api/v1alpha1/zz_generated.deepcopy.go, src/api/v1beta1/activegate_types.go, src/api/v1beta1/zz_generated.deepcopy.go, src/controllers/activegate/capability/capability.go, src/controllers/activegate/capability/capability_test.go, src/controllers/dynakube/dynakube_controller_test.go, src/ingestendpoint/secret.go, src/ingestendpoint/secret_test.go, src/webhook/validation/activegate_test.go, src/webhook/validation/validation_test.go
AG's capability renamed from `data-ingest` to `metrics-ingest`
`data-ingest` remains valid in terms of injection type
=> AG capability renamed from 'data-ingest' to 'metrics-ingest'

src/api/v1beta1/properties.go, src/controllers/dynakube/oneagent/daemonset/volumes.go, src/controllers/dynakube/oneagent/daemonset/volumes_test.go, src/initgeneration/config.go, src/initgeneration/init.sh.test-sample, src/initgeneration/init.sh.tmpl, src/initgeneration/initgeneration.go, src/initgeneration/initgeneration_test.go, src/webhook/mutation/pod_mutator.go
If `tlsSecretName` is set in the activeGate section then the value of the `server.crt` key in the provided secret will be propagated into
the oneagent Daemonset, and to the standalone agents. 
The value is put into `/var/lib/dynatrace/oneagent/agent/customkeys/custom.pem`.
=> Propagates tls cert to oneagents

Makefile, config/helm/chart/default/templates/Common/webhook/validatingwebhookconfiguration.yaml, src/api/v1beta1/properties.go, src/ingestendpoint/secret.go, src/webhook/validation/activegate_test.go, src/webhook/validation/config.go, src/webhook/validation/csi_daemonset_test.go, src/webhook/validation/oneagent_test.go, src/webhook/validation/preview.go, src/webhook/validation/preview_test.go, src/webhook/validation/validation.go, src/webhook/validation/validation_test.go
When `metrics-ingest` is configured in the activegate section a warning will tell the user that its a preview feature
There were some minor mistakes in the codebase that it also fixes, regarding the validation webhook yaml and `IsActiveGateMode` function
=> Adds preview warning for metrics-ingest (+minor fixes)

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/operator/clusterrole-operator.yaml, src/agproxysecret/secret.go, src/api/v1beta1/properties.go, src/controllers/activegate/reconciler/capability/reconciler_test.go, src/controllers/activegate/reconciler/statefulset/config.go, src/controllers/activegate/reconciler/statefulset/reconciler_test.go, src/controllers/activegate/reconciler/statefulset/statefulset.go, src/controllers/activegate/reconciler/statefulset/statefulset_test.go, src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynakube_controller_test.go
DT_INTERNAL_PROXY variable may contain plain text username and password and is displayed for instance by kubectl describe command. To avoid that operator creates intermediate secret 'dynatrace-activegate-internal-proxy' mounted as a volume on activegate container.
=> Store activegate proxy in secret instead of environment variable

src/api/v1beta1/feature_flags.go, src/mapper/mapper.go
The ignored namespace feature-flag now gets its default value based on the dynakube so the extra check in the mapper can be safely removed.
=> Enables the monitoring of the operator's namespace via feature-flag

config/crd/bases/dynatrace.com_dynakubes.yaml, config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/samples/applicationMonitoring.yaml, config/samples/classicFullStack.yaml, config/samples/cloudNativeFullStack.yaml, config/samples/hostMonitoring.yaml, src/api/v1beta1/activegate_types.go, src/controllers/activegate/reconciler/statefulset/statefulset.go, src/controllers/activegate/reconciler/statefulset/statefulset_test.go
Adds the DNSPolicy option the the `Dynakube.Spec.ActivGate` section.
Updates the yamls accordingly.
Updates the `statefulset_test.go` to use not use the now deprecated `Dynakube.Spec.Routing` section.
=> Adds DNSPolicy to the ActiveGate section

.github/workflows/ci.yml, .golangci.yml, src/controllers/dynakube/dtclient_reconciler.go, src/controllers/dynakube/dtclient_reconciler_test.go, src/controllers/dynakube/dynakube_controller_test.go, src/dtclient/client.go, src/dtclient/tenant.go
In case of select activeGate features the apiToken needs special scopes, if these are not present we notify the user
Automatic kubernetes api monitoring need:
`entities.read`
`entities.write`
Metrics ingest need:
`metrics.ingest`
=> Adds token scope check for activeGate features

src/api/v1beta1/dynakube_conversion.go, src/api/v1beta1/dynakube_conversion_test.go
`env` section was ignored during conversion
=> Add missing conversion of env section

config/samples/applicationMonitoring.yaml, config/samples/classicFullStack.yaml, config/samples/hostMonitoring.yaml
For samples that are using a non-preview mode, the `metrics-ingest` capability should be disabled by default as it's in preview.
It's now only enabled for samples with `cloudNativeFullStack`.
=> Remove metric-ingest capability from non-preview samples for 0.4

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/customresource-dynakube.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/secret.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/tests/Common/customresource-modules/customresource-dynakube_applicationmonitoring_test.yaml, config/helm/chart/default/tests/Common/customresource-modules/customresource-dynakube_cloudnativefullstack.yaml, config/helm/chart/default/tests/Common/customresource-modules/customresource-dynakube_hostmonitoring_test.yaml, config/helm/chart/default/values.yaml
- Adds the `dataIngestToken` in the `values.yaml`
- Makes resource limit/requests setting logic nil safe
- classicFullStack in no longer on by default (causes too much confusion)
- Updates tests accordingly
=> Brings helm up-to-speed

config/samples/classicFullStack.yaml, config/samples/hostMonitoring.yaml
The comment, that the default image registry is docker or redhat.connect in the samples is wrong, as the default location from which oneAgent images are pulled is the DT cluster.
=> Update image default registry in sample comments

README.md
* Combine duplicate install/uninstall instruction
* default is now Kubernetes, with link to official docs for Openshift instructions
* Fixed outdated links
* Add `v0.4.0` to version table
* Update instructions for required scopes and add `dataIngestToken`
=> Adapt readme for v0.4.0 changes

src/webhook/config.go, src/webhook/mutation/pod_mutator.go
#509 
(cherry picked from commit 247076f8820cb6046096c2eb81294e4e876caf75)
=> Add flavor pod annotation

src/controllers/dynakube/oneagent/daemonset/volumes.go
The oneagents deployed via a daemonset store their config on the root path of the node
=> Moves the tls in the correct postion for oneagent daemonset

.github/workflows/ci.yml, Dockerfile, build/deploy_local.sh
* Update package path from `github.com/Dynatrace/dynatrace-operator/version` to `github.com/Dynatrace/dynatrace-operator/src/version`
* Move `-ldflags` to build args
Verify by checking for build information in the logs:
```
❯ kubectl logs deployment/dynatrace-operator
{"level":"info","ts":"2022-01-31T17:46:21.231Z","logger":"dynatrace-operator-version","msg":"dynatrace-operator","version":"latest","gitCommit":"4301342975c97392ca2bc878bd0653e1451c67a7","buildDate":"2022-01-31T17:39:11+00:00","goVersion":"go1.17.6","platform":"linux/amd64"}
```
=> Include build information in image

src/controllers/dynakube/oneagent/daemonset/volumes.go
(cherry picked from commit f54630c7e424de8c8651fa2e50175d7cbfe16cff)
=> Moves the tls in the correct postion for oneagent daemonset 

src/controllers/csi/driver/config.go, src/controllers/csi/driver/server.go, src/webhook/mutation/pod_mutator.go, src/webhook/mutation/pod_mutator_test.go
There was no way to to differentiate what kind of volume (app or host) is mounted in the NodePublishVolume request of the CSI driver. This is now handled by adding VolumeAttributes within the webhook to the csi volume. These attribute is now checked in the PublishVolume request.
=> Add VolumeAttribute to csi volume

src/api/v1beta1/activegate_types.go, src/api/v1beta1/feature_flags.go, src/api/v1beta1/properties.go, src/controllers/activegate/capability/capability.go, src/controllers/activegate/capability/capability_test.go, src/controllers/activegate/internal/consts/consts.go, src/controllers/activegate/reconciler/capability/reconciler.go, src/controllers/activegate/reconciler/capability/reconciler_test.go, src/controllers/activegate/reconciler/capability/service.go, src/controllers/activegate/reconciler/capability/service_test.go, src/controllers/activegate/reconciler/statefulset/container_eec.go, src/controllers/activegate/reconciler/statefulset/container_eec_test.go, src/controllers/activegate/reconciler/statefulset/container_statsd.go, src/controllers/activegate/reconciler/statefulset/container_statsd_test.go, src/controllers/activegate/reconciler/statefulset/statefulset.go, src/controllers/activegate/reconciler/statefulset/statefulset_test.go, src/webhook/validation/config.go, src/webhook/validation/preview.go
Extracted `statsd-ingest` capability from `metrics-ingest` and removed feature flag to control `statsd-ingest`.
=> Separate statsd-ingest capability from metrics-ingest

src/controllers/nodes/nodes_controller.go
Apparently we send the mark for termination event, also for nodes which we cached, but then could not be found in the cluster after sometime, therefor, we need to check and send the event, when the cache is periodically checked for outdated nodes aswell.
=> Send Mark for termination event also, when node is not found in the cluster anymore

src/agproxysecret/secret.go
We currently log everytime reconciliation is called, that we deleted the agProxySecret, when its not in use. This is blowing up our logs. Therefore I changed the logging condition, that the log is only written, when the Secret is really removed
=> Change logging condition when ensuring agProxySecret is deleted

src/ingestendpoint/secret.go, src/webhook/mutation/pod_mutator.go, src/webhook/mutation/pod_mutator_test.go
New field DT_METRICS_INGEST_API_TOKEN added to "secret/dynatrace-data-ingest-endpoint"
>    "data": {
>       "DT_METRICS_INGEST_API_TOKEN": "ZHQwYzA...",
>        "endpoint.properties": "RFRfT..."
>    },
where
- endpoint.properties field contains two properties
> DT_METRICS_INGEST_URL=https://dk...
> DT_METRICS_INGEST_API_TOKEN=dt...
and is mounted to "/var/lib/dynatrace/enrichment/endpoint" path
- "DT_METRICS_INGEST_API_TOKEN" field is referenced by a secret reference.
=> Value of DT_METRICS_INGEST_API_TOKEN environment variable defined by a secret reference instead of plain text

src/ingestendpoint/secret.go, src/webhook/mutation/pod_mutator.go, src/webhook/mutation/pod_mutator_test.go
Removes following environment variables from injected pods:
* `DT_METRICS_INGEST_URL`
* `DT_METRICS_INGEST_API_TOKEN`
These values will only exist on the pod in the `endpoint.properties` file going forward.
=> Remove dataingest environment variable from pod injection

src/controllers/activegate/reconciler/statefulset/container_eec.go, src/controllers/activegate/reconciler/statefulset/container_eec_test.go, src/controllers/activegate/reconciler/statefulset/container_statsd.go, src/controllers/activegate/reconciler/statefulset/container_statsd_test.go, src/controllers/activegate/reconciler/statefulset/statefulset.go, src/controllers/activegate/reconciler/statefulset/statefulset_test.go
ActiveGate offers the option to collect a support archive remotely from Debug UI (or the user-facing UI). It is useful when there is no log monitoring enabled in the cluster.
This PR links relevant directories between ActiveGate, Extension Controller and StatsD data source containers using volume mounts so that ActiveGate automatically picks up EEC/StatsD logs when a support archive is generated.
=> Adds Extension Controller/StatsD logs to the ActiveGate support archive

src/controllers/activegate/reconciler/statefulset/container_eec.go, src/controllers/activegate/reconciler/statefulset/container_eec_test.go, src/controllers/activegate/reconciler/statefulset/container_statsd.go, src/controllers/activegate/reconciler/statefulset/container_statsd_test.go, src/kubeobjects/address_of/address_of.go, src/kubeobjects/address_of/address_of_test.go, src/kubeobjects/security_context.go
This changeset implements security architecture review remarks regarding the hardening of `statsd-ingest`-related containers in ActiveGate (EEC and StatsD). In particular, `privileged` and `allowPrivilegeEscalation` are disabled for both containers, and all capabilities are dropped by default.
=> Adds security context for EEC and StatsD containers (statsd-ingest)

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, src/controllers/dynakube/dtclient_builder.go, src/controllers/dynakube/dtversion/docker.go, src/controllers/dynakube/dtversion/docker_config.go, src/controllers/dynakube/updates/version.go, src/dtclient/client.go
Fixes the bug that custom certificates were not taken into account when sending requests to the image registry.
Resolves #583
=> Add import for CA before sending request to registry

.github/workflows/ci.yml, src/testing/e2e/integrationtests/envutils_test.go
Our unit-tests use outdated cached packages.
To mitigate this we removed the caches for now.
=> Remove caches from github actions

troubleshoot/troubleshoot.sh
- The previous comparison was a direct comparison between the registry and the oneagent/activegate registry. This did not work for managed tenants, so I changed the comparison to a 'contains' check, where i check, whether the registry string is contained in the oneagent/activegate registry string.
=> Changed direct comparison to 'contains' approach

Makefile
I often run linting and formatting steps long before a commit takes shape. This is in particular useful when resolving conflicts during a rebase.
This changeset introduces a Makefile target to group all formatting, vetting and linting:
```
make lint
```
=> Adds `lint` target to Makefile

src/api/v1beta1/feature_flags_resources.go, src/api/v1beta1/feature_flags_resources_test.go, src/controllers/activegate/reconciler/statefulset/container_eec.go, src/controllers/activegate/reconciler/statefulset/container_eec_test.go, src/controllers/activegate/reconciler/statefulset/container_statsd.go, src/controllers/activegate/reconciler/statefulset/container_statsd_test.go, src/controllers/activegate/reconciler/statefulset/statefulset_test.go
This changeset interprets feature flags similar to:
```
annotations:
"alpha.operator.dynatrace.com/feature-activegate-statsd-resources-requests-memory": "500M"
```
to corresponding container resource requests or limits.
Valid flags:
- `alpha.operator.dynatrace.com/feature-activegate-statsd-resources-requests-cpu`
- `alpha.operator.dynatrace.com/feature-activegate-statsd-resources-requests-memory`
- `alpha.operator.dynatrace.com/feature-activegate-statsd-resources-limits-cpu`
- `alpha.operator.dynatrace.com/feature-activegate-statsd-resources-limits-memory`
- `alpha.operator.dynatrace.com/feature-activegate-eec-resources-requests-cpu`
- `alpha.operator.dynatrace.com/feature-activegate-eec-resources-requests-memory`
- `alpha.operator.dynatrace.com/feature-activegate-eec-resources-limits-cpu` …
=> Maps certain StatsD-related annotations to EEC/StatsD container resource requests or limits

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/templates/Openshift/operator/securitycontextconstraints.yaml, config/helm/chart/default/templates/Openshift/webhook/securitycontextconstraints.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/chart/default/values.yaml
For openshift you should provide an SCC if you have a securityContext set on your stuff
Also default apparmor breaks to many things, so this removes it and makes it optional
Deploy it on openshift, it should just work.
=> Add openshift scc for operator and webhook

src/webhook/validation/config.go, src/webhook/validation/csi_daemonset_test.go, src/webhook/validation/oneagent_test.go, src/webhook/validation/preview.go, src/webhook/validation/preview_test.go, src/webhook/validation/validation_test.go
- Removed the preview warnings in every deployment mode where the csi driver is inclued (i.e. cloudNativeFullstack, applicationMonitoring)
- Apply a dynakube which either uses cloudNativeFullstack or applicationMonitoring with CSIDriver. Other than before, there will not pop up a preview warning message
=> Remove preview warning from CSI driver

config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/operator/role-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/tests/Common/operator/role-operator_test.yaml, config/helm/chart/default/values.yaml
apparmor setting now can be turned on/off per deployment in helm
.Values.operator.apparmor: true should only set the apparmor annotation on the operator deployment
same for the webhook
=> Makes apparmor setting more flexible in helm

src/dtclient/kubernetes_settings.go, src/dtclient/kubernetes_settings_test.go
Revert pre-generation of Kubernetes ME Id introduced in #569 because this check is already done on the cluster.
Dynakube with automatic api monitoring enabled should correctly register the Kubernetes Cluster to Dynatrace.
=> Revert pre-generation of Kubernetes ME Id

src/api/v1beta1/feature_flags.go, src/webhook/validation/config.go, src/webhook/validation/oneagent.go, src/webhook/validation/oneagent_test.go
Added a dynakube annotation `alpha.operator.dynatrace.com/feature-multiple-osagents-on-node` allowing multitenant hostMonitoring (defaults to `"false"`).
OneAgent mounts:
* node's root fs as read-only volume
* csi volume as read-write, unique per tenant
If dynakube annotation `alpha.operator.dynatrace.com/feature-multiple-osagents-on-node` == `true`, `nodeSelector` validation is disabled.
2+ dynakube objects with `hostMonitoring` enabled (or `cloudNativeFullStack` with `namespaceSelector` set so that there is no namespace monitored by more than one dynakube).
OneAgent pods are expected to have running status.
Note: currently OneAgent prevents two instances from running on the same host.
=> Multiple osagents on the same node

src/controllers/csi/metadata/sqlite.go, src/controllers/csi/metadata/sqlite_test.go
In some cases (node restart) kubelet might ask to mount a previously mounted volume (volumeID is the same), which causes a clash in the database. 
On node restart everything should work
=> Update volume entry if exists

src/api/v1beta1/properties_test.go, src/webhook/validation/api_url.go, src/webhook/validation/api_url_test.go
This changeset fixes webhook API URL validation if tenant URL is defined without domain (it was rejected before and is accepted from now on).
Define a DynaKube with API URL similar to `https://dynakube-activegate/e/tenant/api` (with implicit domain).
=> Allows domainless tenant urls

src/webhook/mutation/pod_mutator.go, src/webhook/mutation/pod_mutator_test.go
On OLM the namespaceSelector in the `MutatingWebhookConfiguration` is ignored. This leads to the Webhook intercepting Pod Creation for every pod in the Cluster, independent of the namespaceSelector in the Dynakube and the corresponding label on the namespace managed by the Operator.
The failurePolicy is set to ignore, with a timeout of 2s, but since the Webhook returns an error response before the 2s are up, the pod is blocked from being created.
No matter what, the webhook will not stop the scheduling of a pod because of an error, instead the error's text should be in the message.
=> Removes admission.Errored responses from podmutator webhook

src/api/v1beta1/properties.go, src/api/v1beta1/properties_test.go, src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynakube_controller_test.go, src/controllers/dynakube/oneagent/daemonset/daemonset.go, src/controllers/dynakube/oneagent/oneagent_reconciler.go, src/controllers/dynakube/oneagent/oneagent_reconciler_test.go, src/testing/e2e/integrationtests/envutils_test.go, src/testing/e2e/integrationtests/oneagent_controller_integration_test.go
The oneagent reconciler references the wrong daemonset and therefore never updates the phase field.
Deploy full stack monitoring and watch the phase field. => Should be "Running" after dynakube reconciliation.
=> Fix phase field not updating

src/api/v1beta1/properties.go, src/controllers/activegate/capability/capability.go, src/controllers/activegate/capability/capability_test.go, src/controllers/activegate/reconciler/capability/reconciler.go, src/controllers/activegate/reconciler/capability/service.go, src/controllers/activegate/reconciler/capability/service_test.go, src/controllers/dynakube/dynakube_controller.go
This changeset solves the problem deploying ActiveGate with capabilities which require a `ClusterIP` service (`routing`, `dynatrace-api`) but without `metrics-ingest`. 
Before that, defining `routiung` and/or `dynatrace-api` without `metrics-ingest` caused deployment failure due to AG service not exposing HTTP(S) ports, with stack trace similar to:
```
{"error":"Service \"***-activegate\" is invalid: spec.ports: Required value","level":"error","logger":"main.controller.dynakube","msg":"Reconciler error","name":"***","namespace":"dynatrace","reconciler group":"dynatrace.com","reconciler kind":"DynaKube","stacktrace":"Service \"***-activegate\" is invalid: spec.ports: Required value …
```
=> Enables relevant ActiveGate service ports based on capability requirements

src/controllers/csi/provisioner/processmoduleconfig.go, src/dtclient/processmoduleconfig.go, src/dtclient/processmoduleconfig_test.go
this bug was introduced when the extraction/rework of the installer in the csi driver happend. If the processmoduleconfig endpoint is not present on the tenant we would get a nil panic in the csi provisioner no matter what. 
In a new cluster, with a tenant that doesn't have the processmoduleconfig endpoint, deploy cloudNative, the csi driver should not panic and should mount the volume successfully. (if hostGroup is used it should be added to the ruxitagentproc.conf)
=> Fix nil panic introduced by installer rework

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, src/api/v1beta1/feature_flags.go, src/controllers/activegate/reconciler/statefulset/statefulset.go, src/controllers/activegate/reconciler/statefulset/statefulset_test.go, src/controllers/dynakube/dynakube_controller.go
Added a feature flag called `AnnotationFeatureEnableActivegateRawImage`. (=`false` by default).
It allows customer to opt-in to use raw AG image.
1. Create dynakube with AG spec
2. check if it works with no annotation
3. add `AnnotationFeatureEnableActivegateRawImage = "false"`, operator should work as in point 1
4. change `AnnotationFeatureEnableActivegateRawImage = "true"` and check if `<dynakube>-activegate-tenant-secret` is created and if it's mounted in a pod as:
- token secret: `/var/lib/dynatrace/secrets/tokens/tenant-token`
- env vars: `DT_SERVER`, `DT_TENANT`
=> Added opt-in feature flag AnnotationFeatureEnableActivegateRawImage

src/controllers/csi/driver/volumes/app/publisher.go, src/controllers/csi/metadata/metadata.go, src/controllers/csi/provisioner/controller.go
The host oneagent csi-storage doesn't get mounted while the standalone agent binary is not downloaded, which is not optimal.
To decouple these two:
The "LatestVersion" field of the Dynakube database entry is not needed for the oneagent-storage,
so now we add the Dynakube entry to the database while the "LatestVersion" is not set.
Therefore we can still stop the mount of the standalone agents if the version not set, 
but we can move forward with mounting the oneagent-storage
Deploy cloudNative and see that the host oneagents get there containers created before the standalone binary is donwloaded (sample apps are still waiting).
Also there is a new error message in the sample app's event while the binary is downloading `version is not yet set, csi-provisioner hasn't finished setup yet for …
=> Decouple standalone and oneagent csi storage

config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/customresource-dynakube.yaml, config/helm/chart/default/templates/Openshift/activegate/securitycontextconstraints.yaml, config/helm/chart/default/values.yaml, src/api/v1beta1/feature_flags.go, src/controllers/activegate/capability/config.go, src/controllers/activegate/reconciler/statefulset/container_eec.go, src/controllers/activegate/reconciler/statefulset/container_eec_test.go, src/controllers/activegate/reconciler/statefulset/statefulset.go, src/controllers/activegate/reconciler/statefulset/statefulset_test.go, src/kubeobjects/slice.go
All changes related to ActiveGate container:
1) the root filesystem is mounted ReadOnly.
2) security context added:
>  privileged: false
>  allowPrivilegeEscalation: false
>  readOnlyRootFilesystem: true *
>  runAsNonRoot: true
>  capabilities:
>    drop: ["all"]
* enabled by "alpha.operator.dynatrace.com/feature-activegate-readonly-fs":"true" annotation 
3) seccompProfile is set to:
>    type: RuntimeDefault 
4)  AppArmor is enabled via AG pod annotation *
>  container.apparmor.security.beta.kubernetes.io/activegate: runtime/default 
* enabled by "alpha.operator.dynatrace.com/feature-activegate-apparmor":"true" annotation
=> SecurityContext added to ActiveGate container

src/controllers/csi/provisioner/controller.go
In case a new dynakube was encountered by the csi driver, it would insert it twice duo to a logic oversight.
This issue flew under the radar as it fixed it self, but still it puts a scary error into the log.
Create a dynakube that is new to the cluster, you should see no errors in the log of the CSI driver
=> Fixes double insert to dynakube table

config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml
Helm configuration for Webhook is invalid. AppArmor annotation "container.apparmor.security.beta.kubernetes.io/dynatrace" indicates to non-existent container.The right name is "webhook".
Install DO using helm command. Values.yaml file should contain:
```
webhook:
apparmor: true
```
=> Webhook AppArmor annotation fixed

src/api/v1beta1/properties.go, src/controllers/dynakube/oneagent/daemonset/daemonset.go, src/controllers/dynakube/oneagent/daemonset/volumes.go, src/controllers/dynakube/oneagent/daemonset/volumes_test.go, src/initgeneration/initgeneration.go, src/webhook/mutation/pod_mutator.go
OneAgent expects ActiveGate CA cert to be mounted here: `/mnt/dynatrace/certs/activegate/`
1. Create dynakubre `cloudNativeFullstack` monitoring enabled
2. `kubectl patch -ndynatrace dynakubes.dynatrace.com dynakube --type=json -p='[{"op":"replace", "path":"/spec/activeGate
/tlsSecretName", "value":"dk-certs"}]'`
3. OneAgent pods should be in Running state eventually
=> ActiveGate webserver's CA mounted properly in OneAgents pods

src/controllers/csi/provisioner/controller_test.go
Mock client expected specific flavor in request which is only valid on amd architecture.
Run unit tests on ARM.
=> Fix mock client for ARM architecture

src/controllers/csi/gc/logs_test.go, src/controllers/dynakube/oneagent/daemonset/daemonset.go, src/controllers/dynakube/oneagent/daemonset/labels.go, src/kubeobjects/daemonset.go, src/kubeobjects/daemonset_test.go, src/kubeobjects/secret_test.go
The match labels shouldn't change between deployment modes or the operator will throw errors in case the mode is changed on the dynakube and the oneagent daemonset will not change unless deleted by hand.
1. Deploy the operator
2. Deploy a dynakube with a mode that creates a oneagent daemonset
3. Update the dynakube to switch to a different mode
The labels should change, but not the matchLabels
=> Simplifies the matchLabels for Oneagent daemonset

src/controllers/activegate/reconciler/statefulset/statefulset.go, src/controllers/activegate/reconciler/statefulset/statefulset_test.go, src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/oneagent/daemonset/arguments.go, src/controllers/dynakube/oneagent/daemonset/arguments_test.go, src/controllers/dynakube/oneagent/daemonset/daemonset.go, src/controllers/dynakube/oneagent/daemonset/labels_test.go, src/controllers/dynakube/oneagent/daemonset/volumes_test.go, src/controllers/dynakube/oneagent/oneagent_reconciler.go, src/controllers/dynakube/oneagent/oneagent_reconciler_test.go, src/deploymentmetadata/deploymentmetadata.go, src/deploymentmetadata/deploymentmetadata_test.go, src/webhook/mutation/pod_mutator.go
We currently have the problem, that the mark for termination event is not send, because our node cache is not filled with the nodes, where the oneAgent is deployed on. To understand how the node cache is filled, you need to know that we store the instances of a oneAgent pod in the Dynakube-Status. Every 5 Minutes if the DK is reconciled, we query the cluster for oneAgent pods with defined labels on it. If those labels are not matching, then the pods are not received. 
The case was now, that we had a label missmatch and the pods were not correctly stored in the DK Status. Therfore we were not able to query the DK for a node, when a node got reconciled. As a result, the mark for termination Event never got sent.
Why did this happen?
The labels which are set on the daemonset (in detail the …
=> Mark for termination Event was not sent correctly, because of wrong labels on Daemonset

src/controllers/csi/gc/binaries.go
Improve log message when the CSI driver never downloaded anything and therefore did not have anything to gargab collect. The log message made it sound like an error occured, even if nothing needed to be done.
For this log to show up:
* operator needs to be running with the CSI driver deployed
* only Dynakubes that don't need the CSI driver need to be on the cluster (e.g. `classicFullStack`)
=> Improve info log when `bin` folder does not exist in CSI driver

.github/workflows/ci.yml, .golangci.yml, src/dtclient/client_test.go
The lint action broke suddenly for no known reason, trying to up the version in hopes that it will fix it. 😅 
if the github actions passed then all is well
=> Fix lint github action

.github/workflows/ci.yml, .golangci.yml, config/helm/chart/default/templates/Common/customresource-dynakube.yaml, config/helm/chart/default/tests/Common/customresource-modules/customresource-dynakube_activegate_test.yaml, src/dtclient/client_test.go
When using a multi line string for `customproperties.value` in the values file, invalid yaml was generated by helm.
Use a values file that contains a multi line string in this section:
```yaml
activeGate:
capabilities:
customProperties:
value: |
[kubernetes_monitoring]
key=value
```
Run the following command:
```
helm install dynatrace-operator config/helm/chart/default -f values.yaml --create-namespace -n dynatrace --dry-run
```
=> Fix `activegate.customproperties.value` when multi line string is used

config/samples/applicationMonitoring.yaml, config/samples/classicFullStack.yaml, config/samples/cloudNativeFullStack.yaml, config/samples/hostMonitoring.yaml, config/samples/multipleDynakubes.yaml
Samples on GitHub enable metrics-ingest capability by default. This can cause issues as the certificate used for the endpoint is self-signed. Therefore they should not be added by default.
Just documentation changes, no need to test
=> Remove metrics-ingest from samples as it can cause certificate issues

config/samples/applicationMonitoring.yaml, config/samples/classicFullStack.yaml, config/samples/cloudNativeFullStack.yaml, config/samples/hostMonitoring.yaml
Cherry Pick of https://github.com/Dynatrace/dynatrace-operator/pull/693
No tests needed, just documentation changes
=> Exclude `metrics-ingest` from samples

Makefile, config/deploy/openshift/openshift-all.yaml
`make manifests` added csi driver to the olm mainfests instead of the openshift manifests by mistake.
Run `make manifests`, `openshift-all.yaml` should include csi driver manifests.
=> Readd csi driver to openshift manifests

src/api/v1beta1/properties.go, src/api/v1beta1/properties_test.go
This PR truncates the build date of a supplied OneAgent version when used as a tag for the immutable image.
It implements the change for the `ImmutableOneAgentImage()` DynaKube property.
When the OneAgent version is set in the custom resource and the CSI driver is used, the image cannot be pulled since the version has the wrong format for the image.
The CSI driver expects the version to be in a format like "1.231.288.20220218-170442". If the version is not in this format, the CSI driver cannot download it from the API since the version has to include the build date.
However, the same version field is used to overwrite the version tag for the oneagent images that are used. These image tags do not contain the build date.
Therefore, the version can only be correct for either the API or the …
=> Fixes using wrong tag for immutable image when version is set

src/cmd/operator/main.go
If the users pod has `automountServiceAccountToken: false` then the standalone init will fail.
Probably because https://github.com/Dynatrace/dynatrace-operator/blob/master/src/cmd/operator/main.go#L55-L60 will run which needs these tokens it.
However the standalone init does not use this config.
Deploy a pod were we would inject with the standalone init that has the `automountServiceAccountToken: false` set.
=> Gets kubeconfig only when subcommand needs it

config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/templates/Common/webhook/poddisruptionbudget-webhook.yaml, config/helm/chart/default/values.yaml
Introduces a new option for the webhook. The flag is called enableHighAvailability and can be found in the helm charts in the values.yaml file. Changes the replicas of the webhook deployment from 1 to 2 and also introduces a PodDisruptionBudget with minAvailable set to 1. Also topologySpreadConstraints are set.
Set the flag to true, render a chart and apply the output file.
=> Add highavailability option for webhook via helm

src/controllers/activegate/capability/config.go, src/controllers/activegate/reconciler/statefulset/statefulset.go, src/controllers/activegate/reconciler/statefulset/statefulset_test.go
AG fails to start if RO filesystem is enabled and custom TLS secret is set. In such a case new RW volume is mounted on /var/lib/dynatrace/gateway/ssl directory and the launching script of AG image is able to copy the certificate to the 'ssl' directory.
-create tls secret `kubectl -n dynatrace create secret generic dk-cert --from-file=server.p12=cert.p12` 
-add it to your CR
```
spec:
activegate:
tlsSecretName: dk-cert
```
- check out AG logs `kctl logs pod/<your CR name>-activegate-0`
- the following message is reported at the very beginning of the log
```
Copying /var/lib/dynatrace/secrets//tls/server.p12 certificate file to /var/lib/dynatrace/gateway/ssl/server.p12
```
=> Add RW volume for AG tls certificate

src/standalone/run.go, src/standalone/run_test.go
If securityContext with user/group is used on a user's pod that we inject a csi volume into, then the standalone-init will fail as it doesn't have the permissions to update the `ruxitagentproc.conf` file.
This happens because the csi-driver creates/updates that file with a different user/group then what the user's pod's securityContext has which is used by the standalone-init.
Have cloud-native and inject into a sample app that has a securityContext with a user/group that is different from the one that the csi-driver is using. The sample app should just work.
For bonus-points: Have app-monitoring WITHOUT csi-driver, deploy the same sample app, check that its running, and check if the `ruxitagentproc.conf` was updated.
- under `opt/dynatrace/oneagent-paas/agent/conf/` in the injected …
=> Update agent config during init only in case of installer mode

config/helm/chart/default/templates/Common/customresource-dynakube.yaml, src/api/v1beta1/feature_flags.go, src/api/v1beta1/feature_flags_resources.go, src/controllers/activegate/reconciler/capability/eec_runtime_config.go, src/controllers/activegate/reconciler/capability/eec_runtime_config_test.go, src/controllers/activegate/reconciler/statefulset/container_eec_test.go, src/controllers/activegate/reconciler/statefulset/container_statsd_test.go, src/controllers/activegate/reconciler/statefulset/statefulset_test.go, src/controllers/dynakube/dtclient_reconciler_test.go, src/controllers/dynakube/dynakube_controller_test.go, src/mapper/dynakube_test.go, src/mapper/namespaces_test.go, src/webhook/validation/deprecation.go, src/webhook/validation/deprecation_test.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/723
look at original pr: https://github.com/Dynatrace/dynatrace-operator/pull/723
=> Makes the deprecated feature-flag warning more precise (#723)

.github/workflows/ci.yml
Comparing `repo.full_name` was not viable, so we check the `repo.fork` flag to find out if the event was fired from a fork.
Pull Request is created to this repository from a fork.
=> Check `fork` flag on `pull_request` event

.github/workflows/ci.yml, Dockerfile, go.mod
Follow-up of https://github.com/Dynatrace/dynatrace-operator/pull/651
go version is set to 1.18.1.
Some problems with linters may occur when using generics. It should be addressed when working with generics.
- build image
- execute unit tests
=> Bump go version to ^1.18

config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml
If helm is deployed with `values.yaml` with no `webhook.highAvailability` set, upgrade to `release-0.6` fails.
```
$ helm upgrade dynatrace-operator config/helm/chart/default/ --reuse-values --atomic --namespace dynatrace -v3
Error: UPGRADE FAILED: template: dynatrace-operator/templates/Common/webhook/deployment-webhook.yaml:24:62: executing "dynatrace-operator/templates/Common/webhook/deployment-webhook.yaml" at <1>: invalid value; expected bool
```
1. deploy `release-0.5` - https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/set-up-k8s-monitoring-with-helm
2. `helm upgrade dynatrace-operator config/helm/chart/default/ --reuse-values --atomic --namespace dynatrace`
=> Fix check for empty high availability flag

src/controllers/dynakube/dynakube_controller.go
When using automatic api monitoring, the kubernetes cluster was never registered.
Deploy a Dynakube with the `feature.dynatrace.com/automatic-kubernetes-api-monitoring=true` and the `kubernetes-monitoring` capability enabled.
Request should happen and cluster should show up in the UI.
=> Fix automatic kubernetes api monitoring usage being skipped

src/controllers/activegate/capability/capability.go, src/controllers/activegate/reconciler/capability/reconciler.go, src/controllers/activegate/reconciler/capability/service.go, src/controllers/activegate/reconciler/capability/service_test.go
When updating the operator from a version with the old labels, the activegate service was not updated because the ports did not change. With this change the service will be updated if there is a mismatch in ports, labels or selector.
Update from an older version of the operator (before v0.6.0) to this version:
* service should match the new activegate pods correctly
=> Fix activegate service not updating when labels mismatch

src/controllers/csi/provisioner/agent.go, src/controllers/csi/provisioner/processmoduleconfig.go
Install agent binaries when installed version is `""` (empty), but the `<tenant>/bin/<target version>` directory exists. This means the previous attempt to install agent failed (e.g. OOM during unzip), only created the `bin` folder but did not update the database with the correct version.
Dynakube that needs CSI driver is deployed:
1. CSI driver crashes during unzip (after creating `bin` folder with version)
2. CSI driver restarts and tries to update `ruxitagentproc.conf` without an installed version
=> Skip cache removal when file does not exist

.github/workflows/ci.yml
If Github actions are triggered by PR, the wrong branch name was used. This PR should fix the problem. 
Run the action and check quay for the correct version
=> Fix github action to use correct branch name in ci.yaml

src/controllers/csi/provisioner/processmoduleconfig.go
When removing invalid `revision.json` files the file is deleted even if it doesn't exist. Connected to #754 
Similar as #754
=> Improve logs for `ruxitagentproc.conf` cache deletion

src/installer/installer.go, src/installer/symlink/config.go, src/installer/symlink/symlink.go, src/installer/symlink/symlink_test.go
Inspired by #729 
When there's a mismatch between latest version on the Dynakube and the version of the binaries download, the symlink would point to a different version than existed on the file system.
Check `current` symlink on injected pods and verify it's valid.
=> Create symlink from filesystem instead of latest version on Dynakube

Makefile, config/helm/chart/default/templates/Common/activegate/clusterrole-activegate.yaml, config/helm/chart/default/templates/Common/activegate/clusterrolebinding-activegate.yaml, config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml
ActiveGate need new SecurityContextConstraints, but just linking the ServiceAccount with the SCCs is not enough to have the corresponding permissions, when generating the CSV. Therefore if a an activeGate is deployed via OperatorHub, the statefulset cannot create pods, as it violates SCCs. ClusterRole and RoleBinding for dynatrace-activegate SA are only created if generated for OLM.
```
make bundle VERSION=0.X.X PLATFORM=openshift
```
Should also include now SCCs for `dynatrace-activegate` and `dynatrace-kubernetes-monitoring`
=> Add ClusterRoles for OLM activegate

Makefile, config/helm/chart/default/templates/Common/activegate/clusterrole-activegate.yaml, config/helm/chart/default/templates/Common/activegate/clusterrolebinding-activegate.yaml, config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml
Cherrypick of #759 
```
make bundle VERSION=0.X.X PLATFORM=openshift
```
Should also include now SCCs for `dynatrace-activegate` and `dynatrace-kubernetes-monitoring`
=> Add ClusterRoles for activegate serviceaccounts to generate correct CSV

src/arch/consts.go, src/arch/installer_params_amd.go, src/arch/installer_params_arm.go, src/controllers/csi/provisioner/agent.go, src/controllers/csi/provisioner/arch/amd.go, src/controllers/csi/provisioner/arch/arm.go, src/controllers/csi/provisioner/controller_test.go, src/controllers/dynakube/dtversion/version_info.go, src/dtclient/agent_version.go, src/dtclient/agent_version_test.go, src/dtclient/client.go, src/dtclient/dynatrace_client_test.go, src/dtclient/endpoints.go, src/installer/installer_test.go, src/standalone/env.go, src/webhook/mutation/pod_mutator.go, src/webhook/mutation/pod_mutator_test.go
The latest agent version endpoint we use can't be trusted to give us a version that we can actually download. (it provides the latest version for a different kind of installer).
So instead of that we use the get all versions endpoint and find the latest from that.
Deploy cloudnative on a cluster where
`/deployment/installer/agent/unix/paas/latest/metainfo` returns a version that is not present in 
the output `/deployment​/installer​/agent​/versions​/unix/paas` 
and it shouldn't error anymore.
=> Replace the latest oneagent version endpoint to use the versions endpoint

.github/workflows/ci.yml
Push image step should not trigger on `pull_request`. Check was implemented incorrectly in #743
Pull request should not trigger push image.
=> Check for fork correctly

src/api/v1beta1/properties.go, src/api/v1beta1/properties_test.go, src/controllers/csi/gc/binaries.go, src/controllers/csi/gc/binaries_test.go, src/controllers/csi/gc/controller.go, src/controllers/csi/gc/images.go, src/controllers/csi/gc/images_test.go, src/controllers/csi/gc/logs_test.go, src/controllers/csi/provisioner/agent_test.go
The image cache needs to be cleaned up otherwise the we can flood the node's filesystem with many 200MB+ image dirs.
This deletes any cached image that haven't been pulled for 2 weeks.
Every pull for an image changes its `index.json` even if the image was already cached, so its a good indicator of usage.
Well this is kinda hard, as for the "thing" to happen you need to wait for 2 weeks.
What you can do is change the time locally to 10 mins or something, 
build the operator and use it, then create a dynakube that has `codeModulesImage` set.
=> Updates csi garbage-collector logic to work with images

config/helm/repos/stable/index.yaml, config/helm/repos/stable/index.yaml.previous
Upgrade `index.yaml` to include latest version of the helm chart.
Helm upgrade to and install of `v0.6.0` works.
=> Update index for `v0.6.0` release

.github/workflows/ci.yml
ARM builds stopped working in our Github Actions. Upgrading qemu and buildx actions fix this problem. 
Additionally, explicitly trigger push event only on release and master branch.
Look onto arm action step and check if it run successfully.
=> Update qemu and buildx actions in ci.yaml

config/deploy/openshift/openshift-all.yaml
Removes the ´DEPLOYED_VIA_OLM` environment variable from normal deployment manifests.
Both `kubernetes-all.yaml` and `openshift-all.yaml` should deploy the Operator and Webhook without the `DEPLOYED_VIA_OLM` environment variable.
=> Fixes unintentional introduction of DEPLOYED_VIA_OLM environment variable

.gitignore, Makefile, config/deploy/kubernetes/kubernetes-all.yaml
Basic refactoring of Makefile around yamls generation
- use variables
- remove temp variables
- better targets granularity
- ~`grep -v` replaced with `sed`~
- more descriptive yaml filenames
- no more overriding of `kubernetes.yaml`
`make manifests`
=> Improve yamls generation in Makefile 

config/samples/classicFullStack.yaml, config/samples/cloudNativeFullStack.yaml, config/samples/hostMonitoring.yaml, config/samples/multipleDynakubes.yaml
Starting with k8s 1.24 nodes will now have two taints (master and control-plane), therefore we need to add both to the samples in order to support k8s 1.24. Read more https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md#design-details
Setup a Cluster with 1.24 and apply one of the changed samples. oneAgent pods should be scheduled on all nodes including master. Also if the k8s version is < 1.24 and only have the `master` taint, they schould also get scheduled on all nodes.
=> Add tolerations for k8s 1.24 to samples

src/api/v1beta1/feature_flags.go, src/webhook/mutation/config.go, src/webhook/mutation/pod_mutator.go, src/webhook/mutation/pod_mutator_test.go
In order to support istio, we need to give customer the possibility to set `DT_INITIAL_CONNECT_RETRY_MS` via the webhook to their containers, in order to delay the startup of the agent. It was decided that it should be a feature flag, rather than tightly coupling it with the `enableIstio` field in the CR. Therefore I introduced the `feature.dynatrace.com/oneagent-initial-connect-retry-ms` feature flag, where customers can set the preferred value.
Create a Dynakube (either with applicationMonitoring or cloudNative) and add the annotation `feature.dynatrace.com/oneagent-initial-connect-retry-ms: "<value>"` to it. Any pod which is injected now should get the env var `DT_INITIAL_CONNECT_RETRY_MS` set to its containers, with the according value.
=> Add feature flag for setting `DT_INITIAL_CONNECT_RETRY_MS` env-var to webhook injected containers

src/standalone/run.go, src/standalone/run_test.go
Currently our error masking within the standalone runner is broken. The runner always logs that an error has been masked even though there is no error. This happened because, in the check for masking the error `consumeErrorIfNecessary()`, we do not check for the error itself but for the pointer, which is never nil. Additionally the defer function set the wrong variable to nil because `defer` runs a function **after** the return statement but **before** the function is actually returned, thus enabling modify returned results, but only named return results can be accessed normally. This caused that the error was set to nil, but not actual returned error, because go already evaluated the return result.
More here: https://stackoverflow.com/questions/48680222/what-is-the-difference-between-name …
=> Fix error masking in standalone runner

Makefile, config/crd/bases/dynatrace.com_dynakubes.yaml, config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/generated/dynatrace-operator-crd.yaml, src/api/v1beta1/dynakube_types.go
CRD was generated using an outdated version of `controller-gen`.
Removed `+kubebuilder:validation:MaxProperties=1` annotation for `OneAgentSpec` which as incompatible.
Upgrade `controller-gen` and check if the generated CRD is the same:
1. `go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.0`
2. `make manifests`
=> Update `controller-gen` to `v0.9.0`

src/api/v1beta1/feature_flags.go, src/dtclient/agent_tenant_info_test.go, src/kubeobjects/consts_test.go, src/kubeobjects/env.go, src/kubeobjects/env_test.go, src/kubeobjects/labels_test.go, src/kubeobjects/secret_test.go, src/kubeobjects/slice.go, src/mapper/dynakubes.go, src/mapper/mapper.go, src/mapper/namespaces.go, src/webhook/mutation/namespace_mutator.go, src/webhook/mutation/pod_mutator.go, src/webhook/mutation/pod_mutator_test.go, src/webhook/validation/deprecation_test.go
Reinvocation of the webhook for already injected pods was disabled by default.
This change enables it by default.
* Create a cluster and install Istio
* Deploy the operator and a dynakube
* Create a test-namespace and label it with `istio-injection=enabled` so that istio injects into pods
* Deploy a sample app
* Pods of your sample app should have an `install-oneagent` init container that includes an environment variable `CONTAINER_X_NAME` with the name of the istio sidecar as a value. E.g. `CONTAINER_2_NAME:      istio-proxy`
* Annotate the dynakube with the `feature.dynatrace.com/disable-webhook-reinvocation-policy: true` annotation
* Delete the pods of your sample app
* Pods of your sample app should have the mentioned environment variable missing
=> Changes reinvocation policy to be enabled by default

hack/make/manifests/config.mk
`controller-gen` produces an error that `crdVersions` is not recognized.
This is due to the prefix `crd:` missing.
`make install` must run successfully
=> Fixes missing "crd:" prefix for crd options

hack/build/push_image.sh, hack/build/test.sh, hack/do_env_variables_exist.sh, hack/e2e/install-kuttl.sh, hack/helm/google-marketplace/upload_test.sh, hack/helm/google-marketplace/verify.sh, hack/troubleshoot/troubleshoot.sh
Added missing shebang.
Changed `#!/bin/bash` to `#!/usr/bin/env bash` in shell scripts.
When using `zsh`:
```shell
$ make test/kuttl/activegate                                                                                                                                                                                                                                                                                                                 
hack/do_env_variables_exist.sh "APIURL APITOKEN PAASTOKEN" …
```
=> Add missing shebang; fix hardcoded /bin/bash path

src/controllers/nodes/cache.go, src/controllers/nodes/config.go, src/controllers/nodes/nodes_controller.go, src/controllers/nodes/nodes_controller_test.go, src/controllers/nodes/oneagent_dao.go
Replaces all the `client.Get(...)` to use an `apiReader` instead. 
This is necessary because the `client` uses a cache when getting resources which is useful, 
however it does a bad job at keeping that cache up to date, 
which is important for us to act accordingly and also to avoid errors such as:
```
{"level":"info","ts":"2022-06-01T09:06:17.266Z","logger":"nodes-controller","msg":"Removing unfound cached node from cluster","node":"at-k8s-1-21-sd-flc-containerd-worker--i-0a3e305680f9b7abc"}
{"error":"Operation cannot be fulfilled on configmaps \"dynatrace-node-cache\": the object has been modified; please apply your changes to the latest version and try again","level":"error","logger":"main.controller.node","msg":"Reconciler error","name":"at-k8s-1-21-sd-flc-containerd-master--i-0c9e7891 …
```
=> Use apiReader in nodes controller where possible

src/api/v1beta1/properties.go, src/controllers/dynakube/dynakube_controller.go, src/ingestendpoint/secret.go, src/ingestendpoint/secret_test.go
1. Secret `dynatrace-data-ingest-endpoint` is now always generated nevertheless which ingestions are enabled.
If no ingestion is enabled, secret's data contains an empty string, as expected.
2. Fixed bug causing permanent reconciliation which was caused by comparing `nil` and an empty map, assuming it's equal.
Check if `dynatrace-data-ingest-endpoint` secret in `deafult` namespace contains expected content.
Dynakubes to be used:
1. default one, with no annotation
2. with AG `statsd-ingest` capability enabled
Maniulate dynakubes with:
1. `k -ndynatrace annotate dynakubes.dynatrace.com dk --overwrite feature.dynatrace.com/disable-metadata-enrichment=false` - no change should be observed
2. `k -ndynatrace annotate dynakubes.dynatrace.com dk --overwrite …
=> Fix data-ingests's `endpoint.properties` secret handling

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/chart/default/values.yaml
The `highAvailability `flag in the `values.yaml` file in the helm charts is switched to true, which should be the default for now.
Simply switch to this branch, run make manifests and take a look at the `kubernetes.yaml`. Apply it and check for the changed things like `topologySpreadConstraints` in the webhook deployment and so on.
=> Switched highAvailability mode to true as new default

Makefile
After recent Makefile refactoring, `SHELL = bash` disappeared.
By default `sh` is used and it lacks of bashisms like `source` which is used in e.g. `go/test` target:
```shell
$ make go/test
...                                                                               
source /home/michal/workspace/dynatrace-operator//testbin/setup-envtest.sh; fetch_envtest_tools /home/michal/workspace/dynatrace-operator//testbin; setup_env
test_env /home/michal/workspace/dynatrace-operator//testbin; go test ./... -coverprofile cover.out                                                                         
/bin/sh: 1: source: not found                                                                                                                                                            
/bin/sh: …
```
=> Set `bash` shell as preferred for make

.github/workflows/build-dockerimage.yaml, hack/build/ci/download-go-build-deps.sh
licenses in our docker image are never updated, as the cache is never invalidated. 
There are 2 problems that caused that behaviour: 
- In our action step where we download the licenses, restore-keys were set. Therefore if no exact cache match was found, our fall back option prevented our bash check (`-d ./third_party_licenses`) to ever become true.
- Installing binaries with `go get` is no longer supported. - Has to be updated to `go install`
Look into the docker image build by our ci and check if the licenses were updated.
=> Fix never invalidated license cache in GitHub actions

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/chart/default/values.yaml
Currently nodeSelector and tolerations can only be set on the operator pod in our helm-chart values file. 
We want to extend that to all other components as well.
Install our helm chart into your cluster, with nodeSelector and tolerations yamls set. It should apply them to our components.
=> Add tolerations and nodeSelectors

config/helm/chart/default/questions.yml, config/helm/chart/default/templates/_helpers.tpl, config/helm/chart/default/tests/Common/csi/clusterrole-csi_test.yaml, config/helm/chart/default/tests/Common/csi/clusterrolebinding-csi_test.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/tests/Common/csi/role-csi_test.yaml, config/helm/chart/default/tests/Common/csi/rolebinding-csi_test.yaml, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/chart/default/values.yaml, config/helm/schema.yaml, hack/make/manifests/kubernetes.mk, hack/make/manifests/openshift.mk
Setting the `image` for the deployments when using helm now is less weird, as the while you already could set the `image` for the deployments, you had to do it with `operator.image` which is a bit confusing when it also updates the image used by the CSI and webhook.
Set the `image` field when deploying(or generating yamls) via helm, then check that it was used in the deployments/daemonset.
Also try what is described in https://github.com/Dynatrace/dynatrace-operator/blob/master/config/helm/README.md.
=> Rename `.Values.operator.image` to `.Values.image`

src/api/v1beta1/feature_flags.go, src/api/v1beta1/properties.go, src/controllers/dynakube/oneagent/daemonset/daemonset.go
Added new feature flag which allows the oneagent container to run as privileged
Apply this feature flag and check whether the oneagent container is ran in a privileged context.
=> Added feature flag to run oneagent as privileged

src/controllers/csi/driver/volumes/app/publisher_test.go, src/controllers/csi/driver/volumes/bind_config_test.go, src/controllers/csi/driver/volumes/host/publisher_test.go, src/controllers/csi/metadata/correctness_test.go, src/controllers/csi/metadata/fakes.go, src/controllers/csi/metadata/metadata.go, src/controllers/csi/metadata/sqlite.go, src/controllers/csi/metadata/sqlite_test.go, src/controllers/csi/provisioner/controller_test.go
Add new `UsesImage` column to the Dynakube table to be used by CSI server and provisioner. Migration of existing databases to updated schema with new column should happen automatically.
No change in functionality when using the CSI driver:
* existing data is migrated to new schema without data loss
* new value is currently not used, so no changes expected
=> Add `UsesImage` column to Dynakube metadata table

README.md
Since Openshift 3.11 falls out of the normal support lifecycle, we should mention it explicitly in the support lifecycle expalnation.
=> Add Openshift 3.11 exception to support lifecycle

Makefile, config/helm/chart/default/Chart.yaml, hack/make/bundle.mk, hack/make/deploy/kubernetes.mk, hack/make/deploy/openshift.mk, hack/make/go.mk, hack/make/helm/version.mk, hack/make/manifests/config.mk, hack/make/manifests/crd.mk, hack/make/manifests/kubernetes.mk, hack/make/manifests/manifests.mk, hack/make/manifests/openshift.mk
Set helm development version to:
- 0.0.0 if master is the current branch
- < ver > if release-< ver > is the current branch
- otherwise Chart.yaml version/appVersion fields are not changed
Execute `make bundle` command on the following branches:
- master
- release-9.99.999
- feature/set-helm-version
Chart.yaml version/appVersion fields should be updated according to the requirements.
=> Helm development version is set to appropriate version.

.github/workflows/openssf-scorecards.yaml, .github/workflows/scorecards.yml
Add OpenSSF scorecard workflow to github actions.
It's triggered manually for the moment. It will be switched to be triggered on `push`, `pull_request` and `schedule` in the next PR.
1. Locally: `act -j analysis`
2. On githbub - verify if CI executes given workflow and its results
=> Add OpenSSF scorecard workflow

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/generated/dynatrace-operator-crd.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml
Adds default tolerations for the csi-driver so that they can be scheduled on master nodes.
Try helm install (with csi enabled) and it should deploy the csi-driver with the default tolerations
Try the generated manifests files, it should also deploy the csi-driver with the default tolerations
=> Adds default tolerations for the csi driver

src/initgeneration/initgeneration.go, src/initgeneration/initgeneration_test.go
The `proxy` field in the init secret was moved under the `config` field (which is a json).
This broke how the webhook injects the `DT_PROXY` envvar to the customer's pod.
And to avoid the need to directly read the secret in the webhook during injection, this adds the `proxy` field back as its separate field.
This duplicates the `proxy` value inside the init secret, however this is a far nicer way than reading the secret for every pod injection.
Use a dynakube that has proxy set, and you can check:
- the `dynatrace-dynakube-config` in the sample app namespace has the `proxy` field
- exec into the sample pod, check if `DT_PROXY` is set
- everything works as normal
=> Readds separate proxy key to the init secret

config/manifests/bases/dynatrace-operator.clusterserviceversion.yaml, hack/build/bundle.sh
Supported versions for bundle is updated to reflect correct state.
Operator bundle should only show up in OCP v4.8-v4.10 clusters
=> Update supported Openshift versions for Bundle

config/helm/chart/default/generated/dynatrace-operator-crd.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrole-oneagent-unprivileged.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrolebinding-oneagent-unprivileged.yaml, config/helm/chart/default/templates/_helpers.tpl, config/manifests/bases/dynatrace-operator.clusterserviceversion.yaml, config/olm/README.md, hack/build/bundle.sh, hack/make/bundle.mk, hack/setup_olm_catalog.sh
Add unprivileged oneagent Serviceaccount on Kubernetes and update bundle testing script for Kubernetes.
Generate bundle and deploy on OLM following instructions:
```sh
make bundle PLATFORM=kubernetes OLM_IMAGE=quay.io/dynatrace/dynatrace-operator:snapshot-release-0-7 VERSION=0.7.0 && make test/olm VERSION=0.7.0 PLATFORM=kubernetes TAG=test-0.7.0 CREATE_SUBSCRIPTION=true
```
=> Update bundle generation to include onagent unprivileged Serviceaccount

src/controllers/csi/metadata/path_resolver.go, src/controllers/csi/provisioner/agent.go, src/controllers/csi/provisioner/agent_test.go, src/controllers/csi/provisioner/controller.go, src/controllers/csi/provisioner/events.go, src/installer/common/consts.go, src/installer/image/installer.go, src/installer/image/source.go, src/installer/image/unpack.go, src/installer/symlink/symlink.go, src/installer/url/download.go, src/installer/url/installer.go, src/installer/url/installer_test.go, src/installer/url/unpack.go, src/installer/zip/gzip.go, src/installer/zip/zip.go, src/processmoduleconfig/update.go, src/processmoduleconfig/update_test.go
The current way we download/cache and unpack  `codeModulesImage` is not perfect when it comes to node storage usage, as it extracts the image for every tenant.
This PR changes how the provisioner prepares the node for the driver.
The image is downloaded to `/cache/<image-ingest>` and gets unpacked to `data/codemodules/<image-digest>`.
We only download/unpack if the digest changes (or its a new digest), we store the digest in the `dynakubes` table in the metadata database on the node.
After we unpack to `data/codemodules/<image-digest>` then `/cache/<image-ingest>` gets cleaned up as its no longer needed for anything.
Because of the shared nature of the agent "binary" we can't update the `ruxitagentproc.conf` at 
`data/codemodules/<image-digest>`, so we instead create a …
=> Reworks imageInstaller to extract into a shared dir

src/controllers/csi/config.go, src/controllers/csi/driver/volumes/app/publisher.go, src/controllers/csi/driver/volumes/app/publisher_test.go, src/controllers/csi/driver/volumes/bind_config.go, src/controllers/csi/driver/volumes/bind_config_test.go, src/controllers/csi/driver/volumes/host/publisher.go, src/controllers/csi/metadata/path_resolver.go
Adapt OverlayFS creation when image digest is used:
- Binary directory pointing to image tag
- Config directory pointing to tenant specific configuration
Using changes in #834 to add `ImageDigest` to database when used the lowerdir is setup correctly:
- both binary and config are passed to the `mount` command
=> Add separate config/binary directory when using code modules image

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml
The containers of the CSI driver were using a write-able filesystem.
These changes lock the containers root filesystem to be read-only.
An ephemeral storage volume is mounted at the points where some components need to write transient data.
* Deploy the Operator with the CSI driver
* Exec into containers of a CSI driver pod
* Navigate to any place __excluding__
*  `/csi`
* `/registration`
* `/var/lib/kubelet/plugins/csi.oneagent.dynatrace.com`
* These directories are mounted volumes that do have write permissions
* Try to create a file, e.g.: `touch test.txt`
* An error should occur, e.g.: `touch: cannot touch 'test': Read-only file system`
* Use a mode that uses the CSI driver such as cloud-native fullstack or app-only.
* Injection should work as usual
* CSI driver should download …
=> Changes csidriver containers to use read-only filesystem

.gitignore, hack/build/bundle.sh, hack/make/manifests/config.mk, hack/make/manifests/kubernetes.mk
The makefile generated wrong manifest names for kubernetes-csi.yaml and openshift-csi.yaml. This is especially important for the release pipeline and the attached manifests for it.
`make manifest` should generate the two files with the right name
=> Adapt makefile to generate correct names for csi manifests

hack/make/bundle.mk
Creating bundle only touches platform files and other manifests.
Run `make bundle/kubernetes && make bundle/openshift`:
- kubernetes manifests should not include openshift changes
=> Split bundle step for different platforms

.github/dependabot.yml
Dependencies are currently manually updated.
The PR enables dependabot to do that for us.
Fork this PR and start dependabot there.
=> Setup automatic dependency updates for go and docker in dependabot config

Dockerfile, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml
We want to run our operator and webhook with the same UID and GID specified in our dockerfile. 
Therefore the IDs are explicitly set in our deployments. 
Setting them in our CSI driver is not possible due to required privileges for accessing the CSI driver sockets.
Additionally fixed wrong /tmp path for CSI driver
Deploy the operator in the cluster, exec into operator/webhook pod and check the UID and GID.
=> Set uid and gid explicitly in operator and webhook deployment

src/standalone/files.go
Removes unnecessary `"` in conf in case of cloudNative mode
Deploy something while having cloudNative enabled.
=> Remove unnecessary char in `container.conf`

src/standalone/config.go, src/standalone/env.go, src/standalone/env_test.go, src/standalone/run.go
The architecture used in the standalone binary download defaults to `X86` in case the environment variable is missing. Setting this via environment variable also doesn't make sense, since it's easier to load during runtime.
Deploy sample app on ARM node without CSI driver and check injection works correctly.
=> Fix arch used in standalone binary download

.gitignore, config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/generated/dynatrace-operator-crd.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/templates/_helpers.tpl, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, hack/make/manifests/config.mk, hack/make/manifests/kubernetes.mk
In gke autopilot version 1.23x the `nodeAffinity` specifying the arch for the node is very picky, and only supports a single value which is `amd64` so having it would just complicate things.
So on gke-autopilot we will not have them.
Added `google-autopilot` as a new possible platform, if used no `nodeAffinity` will be set for checking the arch.
Deploy to a `rapid` channel autopilot cluster, while setting the platform to `google-autopilot`. (remember autopilot doesn't support CSI driver)
=> Adds google-autopilot as a new platform to helm

config/helm/repos/stable/index.yaml, config/helm/repos/stable/index.yaml.previous
Upgrade `index.yaml` to include latest version of the helm chart.
Helm upgrade to and install of `v0.7.0` works.
=> Update index for v0.7.0 release

src/controllers/csi/metadata/correctness_test.go, src/controllers/csi/metadata/fakes.go, src/controllers/csi/metadata/sqlite_test.go, src/controllers/csi/provisioner/controller_test.go, src/webhook/mutation/pod_mutator/pod_mutator_test.go
Refactors test objects to be created by functions instead of being stored in global variables.
This change breaks up dependencies between tests.
Since these changes do not affect production code, if the unit tests run through and everyone is happy with the changes, it just works.
=> Refactors test objects from being global variables to being created in functions

src/controllers/csi/provisioner/agent.go, src/controllers/dynakube/version/version.go, src/dockerconfig/docker_config.go, src/dockerconfig/docker_config_test.go, src/dockerconfig/system_context.go
The `NewDockerConfig` constructor will not setup the `Auths`, that is done in `SetupAuths` method.
This is a small optimisation so in case something needs the dockerConfig but requires no authentication, we will no longer force to use the default pull secret. (Also its nicer for testing)
When you use `codeModulesImage` that points to a registry that doesn't need `customPullSecret`, it should work
=> Reworks dockerConfig auth setup

config/helm/chart/default/questions.yml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/chart/default/values.yaml, config/helm/schema.yaml
`customPullSecret` moved to the root and is used for every deployment that the helmchart deploys
closes https://github.com/Dynatrace/helm-charts/pull/190
Set `values.customPullSecret`, then see if the deployment of the operator and webhook + the daemonset of the csi-driver uses it.
=> Moves the customPullSecret to the root of the values files

src/standalone/files.go
Changes the filemode to `0444` so that no matter the user defined in the container or in the security context, everyone can read the `container.conf` created by the standalone init.
Deploy something that injects codemodules.
In an injected sample app check the permissions:
```
$ ls -la /var/lib/dynatrace/oneagent/agent/config/container.conf 
-r--r--r--    1 1006     1006           274 Jun 28 11:12 /var/lib/dynatrace/oneagent/agent/config/container.conf
```
=> Changes codemodules container.conf file's filemode

src/webhook/validation/proxy_url.go, src/webhook/validation/proxy_url_test.go
Clients use proxies with empty proxy password. A CR is accepted by the proxy_url validator if proxy password is empty.
How can this be tested?
Use empty password in the Proxy Url (proxy.value, proxy secret) and try to apply your CR - should be accepted.
=> Allow to use empty proxy password (backport to release-0.7)

.github/pre-commit
ZERO WIDTH SPACE UTF-8 characters are reported as errors by bash so they are removed. No changes in the script logic.
Linter and unit tests are performed before the actual commit.
=> Remove ZERO WIDTH SPACE characters from the pre-commit script

.github/pre-commit, hack/make/go.mk
Using flags for `gci` calls is deprecated. Subcommands should be used. Altered all calls to `gci` makefiles and pre-commit hook. No logic changed.
- [ n/a] Unit tests have been updated/added
=> Remove deprecation warning from gci and errors from pre-commit script.

src/controllers/csi/provisioner/agent.go, src/controllers/csi/provisioner/agent_test.go, src/controllers/csi/provisioner/controller.go, src/installer/url/download.go, src/installer/url/installer.go, src/installer/url/installer_test.go, src/standalone/run.go
Bug: 
1. csi-provisioner tries to download version X
2. create targetDir for version X
3. gets OOM killed
4. retries, but "targetDir for version X" already exists ==> doesn't retry
1. Reduce csi-driver's resource limits, so it gets OOM killed
2. After an OOM, check if the provisioner created the directory `/data/<tenant>/bin/<version>`, make sure its empty
3. Raise the csi-driver's resource limits, so it doesn't get OOM killed
4. The csi-driver should download the targetVersion X (`/data/<tenant>/bin/<version>` is no longer empty, and sample starts up)
=> Improves isAlreadyDownloaded check

src/cmd/csi/config.go, src/standalone/config.go, src/standalone/env.go, src/standalone/env_test.go, src/standalone/files.go, src/standalone/run.go, src/standalone/run_test.go, src/webhook/mutation/pod_mutator/config.go, src/webhook/mutation/pod_mutator/init_container.go, src/webhook/mutation/pod_mutator/init_container_test.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator_test.go, src/webhook/mutation/pod_mutator/oneagent_mutation/volumes.go, src/webhook/mutation/pod_mutator/pod_mutator.go
The injection-info volume was not fully moved to the oneagent-mutator.
Right now the injection-info volume-mount for the init container is defined in the main pod-mutator, which is incorrect.
This causes an error when wanting to only use the dataingest-mutator, as the injection-info volume will not be present.
Furthermore the injection-info's clusterID field is used by the standalone init part of the dataingest mutation, which is not necessary, because that can be set as an env in the webhook.
Doing so the 2 mutators (dataingest and oneagent) can be independent as they were meant to be.
Inject into a:
- pod that has data-ingest disabled
- pod that has oneagent disabled
- pod that has both disabled
=> Fixes standalone init and webhook integration

src/cmd/standalone/standalone.go, src/installer/zip/zip.go
Installing codemodules without the CSI driver had multiple problems.
1. The unix mask 0000 was only set in the CSI driver (we should set the mask in the standalone init aswell)
2. Modifying the `agent/conf` dir's filemode caused permissions errors for creating files inside it. (so we should only modify the filemode inside the dir)
Deploy codemodules with and without the csi-driver.
Check that no error happens during install, and check that the filemode on in the `.../agent/conf` is the following:
```
drwxr-xr-x 3 1001 1001   4096 Jul  4 15:23 .
drwxr-xr-x 7 1001 1001   4096 Jul  4 15:23 ..
-rw-r--r-- 1 1001 1001   3420 Jul  4 15:23 _ruxitagentproc.conf (if codeModulesImage is used, this is not present)
drwxrwxrwx 3 1001 1001   4096 Jul  4 15:23 runtime
-rw-rw-rw- 1 1001 1001   5059 Jul  4 …
```
=> Fixes codemodules install permissions

src/controllers/dynakube/oneagent/daemonset/daemonset.go, src/controllers/dynakube/oneagent/daemonset/daemonset_test.go
Oneagent installer needs to be run as unprivileged user.
Deploy cloud native fullstack on Openshift.
=> Set unprivileged user/group for oneagent securitycontext

src/api/v1beta1/feature_flags.go, src/mapper/mapper.go, src/mapper/namespaces.go, src/mapper/namespaces_test.go, src/webhook/mutation/pod_mutator/dataingest_mutation/mutator.go, src/webhook/mutation/pod_mutator/dataingest_mutation/mutator_test.go, src/webhook/mutation/pod_mutator/init_container.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator_test.go, src/webhook/mutation/pod_mutator/pod_mutator.go, src/webhook/mutator.go
Added feature flag `feature.dynatrace.com/automatic-injection` to disable automatic injection for a dynakube. If set to `false`, pods nominated for injection need to be manually annotated with `oneagent.dynatrace.com/inject=true`. Default value for the feature flag is `true`.
- Set the annotation `feature.dynatrace.com/automatic-injection: "false"` on a dynakube
- Create a pod or restart one in a namespace that is associated with the used dynakube
- Check that there is no injection happening on the pod.
- Add the annotation `oneagent.dynatrace.com/inject: "true"` to the pod spec and make sure the pod restarts
- Check that there is injection happening on the pod.
=> Add feature flag to opt-into injection per pod 

config/helm/chart/default/Chart.yaml
Using `>=1.21` does not include pre releases, https://github.com/helm/helm/issues/3810
Install helm chart on Cluster using `x.x.x-x` version.
=> Include prereleases in chart version

src/controllers/dynakube/oneagent/daemonset/daemonset.go, src/controllers/dynakube/oneagent/daemonset/daemonset_test.go
Unprivileged user/group should not be used for classic fullstack.
Deploy classic fullstack and use privileged oneagent feature flag.
=> Only set user/group when csi driver is used

src/controllers/dynakube/oneagent/daemonset/daemonset.go
The `feature.dynatrace.com/oneagent-privileged: "true"` flag always added the `runAsUser` and `runAsGroup` that brakes the `classicFullStack` mode
Deploy `classicFullStack` on a cgroup v2 cluster, while having the `feature.dynatrace.com/oneagent-privileged: "true"` feature-flag
=> Fixes oneagent privileged flag

src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynakube_controller_test.go, src/controllers/dynakube/istio/reconciler.go, src/controllers/dynakube/istio/reconciler_test.go, src/dtclient/communication_hosts.go, src/dtclient/communication_hosts_test.go, src/testing/e2e/integrationtests/istio_integration_test.go
The Istio reconciliation only start after the tokens have been checked for validity.
The validity check is done using an API call which is blocked if Istio is started in REGISTRY_ONLY mode.
This PR fixes that circular dependency by first reconciling Istio objects if the flag is enabled.
Then reconciling the dynakube custom resource.
* Create a cluster
* Install Istio with outboundTraffic mode being set to REGISTRY_ONLY
* Deploy the operator
* Label dynatrace namespace and test namespaces with `kubectl label namespace <namespace> istio-injection=enabled`
* Apply a Dynakube with the enableIstio flag being set to true
* The logs should show that service entries and virtual services are being created
* One set is created even without tokens for the specified API url
* For other communication …
=> Fixes Istio reconciliation depending on a token check that depends on Istio reconciliations

config/helm/chart/default/Chart.yaml
Adds a dash to the kubeVersion property of the Helm chart to also match version with a build version
Run `make manifests`.
If it succeeds, it works.
=> Fixes kubeversion property in Chart.yaml

src/controllers/csi/metadata/fakes.go, src/controllers/csi/metadata/metadata.go, src/controllers/csi/metadata/sqlite.go, src/controllers/csi/metadata/sqlite_test.go, src/controllers/csi/provisioner/agent.go, src/controllers/csi/provisioner/agent_test.go, src/controllers/csi/provisioner/controller.go, src/installer/image/installer.go, src/installer/image/installer_test.go
The `ImageInstaller`'s check  `isAlreadyDownloaded` didn't consider that there might have been other `Dynakubes` that have already downloaded the image, which caused unnecessary downloads.
Have 2 Dynakubes, both use the same `codeModulesImage`.
1. Dynakube gets reconciled by the csi-driver provisioner ==> image gets downloaded
2. Dynakube gets reconciled by the csi-driver provisioner ==> image DOESN'T get downloaded, because its already present
=> Improves isAlreadyDownloaded for ImageInstaller

src/webhook/mutation/pod_mutator/dataingest_mutation/workload.go, src/webhook/mutation/pod_mutator/dataingest_mutation/workload_test.go
(cherry picked from commit 72799e66a44908e4c2bd00494717aa6db6a4b5d7)
See https://github.com/Dynatrace/dynatrace-operator/pull/988
See https://github.com/Dynatrace/dynatrace-operator/pull/988
=> Use kind "Pod" when owner reference is empty

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml
The Helm chart for the CSI driver daemon set did not correctly use the values file for resource limits.
Fixed Helm chart and added Helm unit test.
- Adopt resource limit values in the values.yaml to some arbitrary values.
- Turn on CSI driver in values.yaml
- Install operator via Helm using the adopted values file.
- Check the installed daemonset manifest, Your values should be used for resource limits.
=> Resource limits in values.yaml not correctly used.

hack/helm/install-unittest-plugin.sh, hack/make/prerequisites.mk
(cherry picked from commit 2d98dc3c97413fd57d4a8f4ae3a4b33a99da1f2e)
See https://github.com/Dynatrace/dynatrace-operator/pull/1001
See https://github.com/Dynatrace/dynatrace-operator/pull/1001
=> Installs Helm unittest plugin explicitly (#1001)

src/api/v1beta1/dynakube_status.go, src/api/v1beta1/properties.go, src/controllers/dynakube/status/status.go, src/dtclient/processmoduleconfig.go, src/dtclient/processmoduleconfig_test.go
When an Operator =< 0.7.2 is deployed, the cache in `revision.json` is not updated correctly.
Furthermore, the formatted endpoints are never set in the dynakube and therefore not set in the `ruxitagentproc.conf`
This PR fixes handling the cache and extends the Dynakube status with the endpoints
* On a fresh cluster
* Deploy DTO on `release-0.8`
* Deploy an application-only dynakube
* Deploy sample apps
* The `revision.json` should have an or multiple empty `serverAddress` properties
* The Dynakube state should not have an `Formatted Communication Endpoints` property
* Deploy DTO from this branch
* Delete and redeploy Dynakube
* `revision.json` should be fixed
* `Formatted Communication Endpoints` property should exist in the Dynakube status
=> Fixes codemodules cache not being updated correctly

config/crd/bases/dynatrace.com_dynakubes.yaml, config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/generated/dynatrace-operator-crd.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrole-oneagent-privileged.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrolebinding-oneagent-privileged.yaml, config/helm/chart/default/templates/Common/oneagent/serviceaccount-oneagent-privileged.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Openshift/oneagent/securitycontextconstraints-privileged.yaml, src/api/v1beta1/properties.go, src/api/v1beta1/properties_test.go, src/controllers/dynakube/oneagent/daemonset/arguments.go, src/controllers/dynakube/oneagent/daemonset/arguments_test.go, src/controllers/dynakube/oneagent/daemonset/daemonset.go, src/controllers/dynakube/oneagent/daemonset/daemonset_test.go, src/controllers/dynakube/oneagent/daemonset/env_vars.go, src/controllers/dynakube/oneagent/daemonset/env_vars_test.go, src/controllers/dynakube/oneagent/daemonset/volumes.go, src/controllers/dynakube/oneagent/daemonset/volumes_test.go
see https://github.com/Dynatrace/dynatrace-operator/pull/993
see https://github.com/Dynatrace/dynatrace-operator/pull/993
=>  Fixes OneAgent daemonset not having a separate service account for privileged mode

src/controllers/csi/provisioner/controller.go
The connection info used in the CSI provisioner was still missing a tenant token.
Since the token must not be stored in the Dynakube status, the connection info is now queried directly from the API.
* Deploy DTO from this branch
* Setup application monitoring dynakube and sample apps
* The `ruxitagentproc.conf` must have a `tenant`, a `serverAddress` and a `tenantToken` property
+ the csi provisioner needs to be refactored to allow for sensible unit tests
=> Set correct connection info

.gitignore, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/templates/_helpers.tpl, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/chart/default/tests/Google/application_test.yaml, config/helm/chart/default/values.yaml, hack/make/deploy/gcr.mk, hack/make/manifests/config.mk, hack/make/manifests/kubernetes.mk
Changing "google-marketplace" to "gke-marketplace".
- Run  `make manifests/kubernetes/gke-autopilot` and check if correct manifest are generated
=> Renamed helm-chart platform value google-marketplace to gke-marketplace

.github/workflows/build-dockerimage.yaml, .github/workflows/ci.yaml, .github/workflows/codeql-analysis.yaml, .github/workflows/preflight.yaml, .github/workflows/publish-images.yaml, .github/workflows/upload-dockerimage.yaml
GITHUB_TOKEN permissions should be restricted as much as possible. 
The whole CI should work as always (images published, scans performed).
=> Restrict the token permissions

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/csi/priority-class.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml
Currently our CSI Pod cant be scheduled in certain scenarios, because of lacking resources on the cluster. However if the customer uses a deployment mode, which relies on the CSI Driver Pod to be there and handle volumes, it then leads to the situation that every pod gets the CSI Volume added by the webhook, but the CSI Pod can not handle those requests because he is simply not there. In consequence the application pod, which gets the CSI Volume cannot start and will fail.
Therefor I added a new priorityClass, which is set to a high priority by default, in order to make sure our CSI Pods can be scheduled
- deploy our operator manifests
- check if the CSI Pod has set the correct priorityClass and correct priority
=> Add priorityClass to CSI Pods

.github/workflows/publish-images.yaml
Matrix did not match registries correctly:
* `arm64` pushed was skipped for all registries
* `registry-url` was not set correctly
=> Fix registry name matching in matrix

src/controllers/activegate/reconciler/statefulset/statefulset.go
Labels defined in `activegate.labels` (or one of the deprecated sections) were not passed to the pods.
Define custom activegate labels and check they are added to the statefulset/pods:
```yaml
...
activeGate:
capabilities:
- routing
labels:
custom: test
```
=> Fix custom activegate labels in Dynakube

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml
If a cluster is configured to use auto scaling and a the cluster auto scaler decides to scale down a node, he deletes every pod from the node and afterwards shuts down the node. However he also tries to schedule pods from a deployment for example to another node, but if the old replica can not be deleted because it can not unmount the csi volume it will stay in terminating phase until the node gets deleted and the pod forcefully deleted.  This can be prevented by annotating the CSI Pod with `cluster-autoscaler.kubernetes.io/enable-ds-eviction: "false"` for cluster-autoscaler version 1.22+ and for lower versions tolerating the `ToBeDeletedByClusterAutoscaler` taint.
Create a cluster with auto-scalling and create applications to make the autoscaler scale up, afterwards reduce the load of …
=> Ensure csi driver availability on node scale-down

src/controllers/activegate/capability/capability.go, src/controllers/csi/metadata/path_resolver.go, src/controllers/csi/metadata/path_resolver_test.go, src/controllers/csi/provisioner/agent.go, src/controllers/csi/provisioner/controller.go, src/dtclient/client.go, src/installer/image/installer.go, src/installer/image/installer_test.go, src/installer/image/unpack.go, src/installer/url/installer.go, src/installer/url/installer_test.go, src/installer/url/unpack.go, src/installer/zip/extractor.go, src/installer/zip/gzip.go, src/installer/zip/gzip_test.go, src/installer/zip/testing.go, src/installer/zip/zip.go, src/installer/zip/zip_test.go, src/version/semantic.go, src/webhook/mutation/namespace_mutator/mutator.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/1031
same as https://github.com/Dynatrace/dynatrace-operator/pull/1031
=> Makes the csi extract archives into a tmp folder (#1031)

src/controllers/csi/provisioner/processmoduleconfig.go, src/installer/url/config.go, src/installer/url/installer.go, src/installer/url/installer_test.go, src/installer/zip/zip.go, src/standalone/run.go
`/mnt/bin/` != `mnt/bin/`. This makes the standalone download think the agent is already downloaded.
Deploy `applicationMonitoring` without CSI driver
Deploy sample app
=> Make extractor handle standalone usecase

src/cmd/main.go
The operator is missing the fist log line in all of our pods, which usually printed the commit hash, operator version and other infos.
Deploy, then check first line in the log to be something like:
```
{"level":"info","ts":"2022-08-03T12:24:32.051Z","logger":"dynatrace-operator-version","msg":"dynatrace-operator","version":"v0.7.2","gitCommit":"ed89e3e390eb12a49ca2d21de08b4c33ede49a09","buildDate":"2022-07-13T07:51:51+00:00","goVersion":"go
1.18.4","platform":"linux/amd64"} 
```
=> Readds the version log to the top of the logs

src/installer/image/installer.go
The `/data/codemodules` directory is not created, and the `os.Rename` is not smart enough to move a dir from `/data/tmp_zip` to `/data/codemodules/<image-digest>`
This causes that the CSI driver can't finish the download if `codeModulesImage` is used
Deploy the operator on a fresh cluster (where `/data/codemodules` doesn't exist)
and create a Dynakube that uses the CSI driver with `codeModulesImage`
=> Creates the shared image dir so `os.Rename` can work

Dockerfile
As ubi9-micro has some problems running on specific hardware and together with some container runtimes, we should switch back to ubi8-micro to be on the safe side.
Should work as before and all operator components should run, if they are deployed
=> Switch back to ubi8-micro

src/installer/image/installer.go
cherry-pick of https://github.com/Dynatrace/dynatrace-operator/pull/1103
same as https://github.com/Dynatrace/dynatrace-operator/pull/1103
=> Creates the shared image dir so `os.Rename` can work (#1103)

src/config/enrichment_injection.go, src/standalone/env.go, src/webhook/mutation/pod_mutator.go, src/webhook/mutation/pod_mutator_test.go
See #1074 and #1086 
In case of owner that is not well-known, the kind would be set to Pod, while the name couldn't be set because .metadata.name is empty at this point. The empty kind/name is correct in this case and should not block the init container.
Inject into a pod that has owner reference set to something of unknown kind, i.e. not Deployment, ReplicaSet, ..., but a separate API.
=> [0.7 backport] Fix pod with owner of unknown workload kind

.github/actions/build-image/action.yaml, .github/actions/create-manifests/action.yaml, .github/actions/preflight/action.yaml, .github/actions/sign-image/action.yaml, .github/actions/upload-image/action.yaml, .github/workflows/ci.yaml, .github/workflows/publish-images.yaml
Images pushed to Dockerhub and GCR are signed using `cosign` both with a private key and the experimental keyless way ([cosign docs](https://docs.sigstore.dev/cosign/sign)).
Push a tag and watch action trigger, see [fork for working example](https://github.com/chrismuellner/dynatrace-operator/actions/workflows/publish-images.yaml).
CI should still work, checkout/login actions were moved out of composite action because of duplication.
=> Sign images on release

.github/workflows/ci.yaml, .github/workflows/publish-images.yaml
Change `ci.yaml` to similar matrix based structure as `publish-images.yaml`:
- reuse build action for amd/arm
- separate push/manifest jobs
- only push arm image and combined manifest on protected branches (release + master)
CI should run correctly on all branches!
=> Fix arm build on protected branch

hack/build/bundle.sh
Supported Openshift versions in Bundle set to v4.9-v4.11.
Build bundle
- make bundle
- check if config/olm/openshift/bundle-0.0.1.Dockerfile contains the com.redhat.openshift.versions label set to v4.9-v4.11
- check if config/olm/openshift/0.0.1/metadata/annotations.yaml contains the com.redhat.openshift.versions annotation set to v4.9-v4.11
=> Bump supported Openshift versions in Bundle to v4.9-v4.11

src/api/v1beta1/properties.go, src/api/v1beta1/properties_test.go, src/webhook/validation/config.go, src/webhook/validation/oneagent.go, src/webhook/validation/oneagent_test.go
When the OneAgent is deployed with the `ONEAGENT_ENABLE_VOLUME_STORAGE` environment variable set to `true` while being used on a system with a read-only host filesystem, it fails its initialization procedure. Added a validation that this combination is rejected for `cloudNativeFullstack` and hostMonitoring setups. Also added a warning if the feature flag `oneagent-readonly-host-fs` is used in `classicFullstack` where it doesn't have any effects.
- create a `cloudNativeFullstack` configuration with FF `oneagent-readonly-host-fs = true` and `ONEAGENT_ENABLE_VOLUME_STORAGE` env variable added in `oneAgent` spec.
- when applying the config, an error shall be displayed, that this combination is not accepted.
=> Adds validation that volume storage env setting isn't used in read-only mode

.github/workflows/ci.yaml
`github.ref_protected` is a `boolean` and not a `string`.
CI has to trigger on protected branch, like master or release branches.
=> Fix check for protected branch status

.github/actions/build-image/action.yaml, .github/workflows/ci.yaml, .github/workflows/publish-images.yaml, Dockerfile, hack/build/ci/prepare-build-variables.sh, hack/build/create_cgo_cflags.sh, hack/build/push_image.sh
Too complex wiring between actions makes them difficult to understand.
To make it easier to work with, following parameters usage is changed:
- `CGO_CFLAGS` - embedded in Dockerfile, there is no need to make it configurable
- `go-version` - deduced from `go.mod` file instead of explicitly declaring it as input parameter
- `GO_LINKER_ARGS` - moved to `build-image` action, so now there is no need to pass it's value through multiple actions
- CI
- locally `make build`
=> Removes unnecessary wiring around image build on CI

src/api/v1beta1/image_paths.go, src/api/v1beta1/properties.go, src/controllers/dynakube/activegate/capability/capability.go, src/controllers/dynakube/activegate/capability/capability_test.go, src/controllers/dynakube/activegate/consts/consts.go, src/controllers/dynakube/activegate/internal/capability/reconciler.go, src/controllers/dynakube/activegate/internal/capability/service.go, src/controllers/dynakube/activegate/internal/capability/service_test.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/certs.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/config.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/config_test.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/customprops.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/eec.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/kubemon.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/kubemon_test.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/serviceport.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/serviceport_test.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/statsd.go, src/controllers/dynakube/activegate/internal/statefulset/statefulset.go, src/controllers/dynakube/activegate/internal/statefulset/statefulset_test.go, src/controllers/dynakube/activegate/reconciler.go, src/controllers/dynakube/dtclient_reconciler.go, src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/version/version.go, src/ingestendpoint/secret.go
Simplifies the `capability` package so it now only has the values necessary to support the current `multiCapability` and the deprecated separate capabilities.
Converted anything possible into modifiers.
Refactored some parts for consistency.
No new feature/behaviour, the activegate creation should work the same as before
=> Refactors capabilities into modifiers

src/api/v1beta1/properties.go, src/controllers/csi/provisioner/controller.go, src/controllers/csi/provisioner/controller_test.go
In case we can't access the Dynatrace tenant the operator can't update the connection info on the dynakube which makes it impossible for the csi provisioner to create the metadata entry in the db.
To counteract that, we can determine the tenantUUID from the apiUrl.
Disable connection to the dynatrace tenant (use a network policy)
deploy a dynakube with csi-driver usage
deploy sample apps.
the sample apps should start up with a dummy volume after exceeding the max mount attempts
=> Make provisioner to get tenantUUID from url

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/generated/dynatrace-operator-crd.yaml, config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml, config/helm/chart/default/tests/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring_test.yaml, config/helm/chart/default/values.yaml
Removes the `additionalPermissions.pvcMonitoring ` so the additional permissions are turned on by default
Deploy/look-at the manifests
=> Makes additional kubemon permission default

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml, config/helm/chart/default/tests/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring_test.yaml, config/helm/chart/default/values.yaml
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/1164
same as https://github.com/Dynatrace/dynatrace-operator/pull/1164
=> Makes additional kubemon permission default (#1164)

src/webhook/mutation/pod_mutator/config.go, src/webhook/mutation/pod_mutator/init_container.go, src/webhook/mutation/pod_mutator/init_container_test.go, src/webhook/mutation/pod_mutator/pod_mutator_test.go
We didn't took enough precautions when determining the `SecurityContext` of the injected init-container.
Removing `SeccompProfile` as it causes problems on openshift with the SCCs
`RunAsNonRoot ` is only set if the finalised `SecurityContext` is not using the root user/group 
Deploy applicationMonitoring with sample apps that have a variety of `SecurityContext` set.
Priority of user/group to be used: (in order of least to max priority)
- default
- `PodSecurityContext`
- "1. container's" `SecurityContext`
=> Makes the securityContext copying safer

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/questions.yml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml, config/helm/schema.yaml
Currently only the provisioner container's resources and limits are configurable through helm, however also the other containers should be configurable, as some customers have a need to change them, because their clusters is bigger than average. 
Edit the values.yaml file with your preferred -> run make manifests or make install -> check if the correct limits from the values file is inside the csi-pod.
=> Make csi limits and resources configurable with helm

src/controllers/csi/driver/volumes/app/publisher.go
In a stress test we noticed that during unmount a portion of the sample apps got stuck, the amount differed after each try, but it was never 0.
The logs are pointing to that "dummy" volumes are getting unmounted even-though none were mounted.
Context: A dummy volume is mounted in case there was too many failed attempts by the csi-driver to mount.
Looking at the database after unmount showed that the volumes table was empty, so every unmount happened.
Looking at the database before we unmounted showed the possible culprit.
The `MountAttempt` column was not always 0, which should be the case for none-dummy volumes.
The `Version` field was always set, which means every mount happened correctly, no dummy was actually mounted.
TLDR: The `Version` field is a more reliable way to determine if a …
=> Safer check for dummy volume

hack/build/bundle.sh
Add OLM support for 4.8
Deploy the operator on Openshift 4.8 and check if your versions is installable through OLM
=> Add OLM support for 4.8

hack/make/deploy/gcr.mk, hack/make/images.mk, hack/make/manifests/manifests.mk
Makes the whole suffix part of the SNAPSHOT_SUFFIX
Make commands still work
=> Makes SNAPSHOT_SUFFIX safer

src/controllers/csi/provisioner/agent.go, src/controllers/csi/provisioner/agent_test.go
Some parts of the provisioner used the `dynakube.TenantUUID()` function to determine the `tenantUUID` while others used the `dynkube.Status.ConnectionInfo.TenantUUID` property, which causes inconsistent results in case the apiUrl is an alias.
`dynkube.Status.ConnectionInfo.TenantUUID` is more accurate as we ask the dynatrace tenant to get it, however using this would break the timeout feature of the CSI-driver. (We wouldn't be able to do anything in case we couldn't access the tenant)
So using `dynakube.TenantUUID()` is more reliable when it comes to resilience.
Deploy dynakube with a apiURL that has an alias, and it should work as expected. (same without alias)
=> Makes tenantUUID usage consistent in provisioner

src/kubeobjects/secret.go
Users can limit how many secrets can be created in their namespaces.
However, if that limit is reached and our namespace secret is already in the namespace, our update mechanism fails. 
Because we try to create a new secret and would expect a `Already Exists` error, but in such case, we get an `alreadyLimit` reached error back, which crashes our logic.
Example resource quota:
```
apiVersion: v1
kind: ResourceQuota
metadata:
name: secret-quota
namespace: test
spec:
hard:
count/secrets: "2"
```
Use a dyankube that would inject into the namespace that has the quota. Wait for an update. Should not fail. (the secret number may change depending what you deploy 😬 )
=>  Only try create secret if not present

src/controllers/dynakube/dtclient_reconciler.go
The token checking logic only checked if the feature-flag is present or not, and in 0.9 it became default, so it always required it, even though you may not even want to deploy activeGates 
Use a token without the `activeGateTokenManagement.create` scope
Deploy a dynakube without ActiveGates => should work
Deploy a dynakube with ActiveGates => should complain about the tokens
- ~[x] Unit tests have been updated/added~
=> Only require the activeGate token scope if activeGates are used

.github/workflows/publish-images.yaml
`rhcc` is missing from `registry` array, leading to incorrect values being used for push to RHCC registry.
see #1196 
push a new tag 😄
=> Add rhcc registry to matrix

src/cmd/troubleshoot/builder.go, src/cmd/troubleshoot/dynakube.go, src/cmd/troubleshoot/logger.go
Cherrypick of https://github.com/Dynatrace/dynatrace-operator/pull/1233
See https://github.com/Dynatrace/dynatrace-operator/pull/1233
~~- [ ] Unit tests have been updated/added~~ 
- The changes are too small to warrant tests
=> Enhances troubleshoot error message

src/controllers/certificates/certificate_secret.go, src/controllers/certificates/certificate_secret_test.go, src/controllers/certificates/webhook_cert_controller.go, src/controllers/certificates/webhook_cert_controller_test.go
When the webhook certificate exists on the cluster the `caBundle` field of the CRD conversion webhook was never updated.
1. Install Operator (Webhook should be running without error logs)
2. Delete `.spec.conversion.webhook.clientConfig.caBundle`
3. Restart Operator pod
CRD should be updated to include correct `caBundle`!
=> Update CRD `caBundle` if certificate secret is up to date

src/config/agent_injection.go, src/standalone/env.go, src/standalone/env_test.go, src/standalone/run.go, src/webhook/mutation/pod_mutator/oneagent_mutation/annotations.go, src/webhook/mutation/pod_mutator/oneagent_mutation/annotations_test.go, src/webhook/mutation/pod_mutator/oneagent_mutation/containers_test.go, src/webhook/mutation/pod_mutator/oneagent_mutation/env.go, src/webhook/mutation/pod_mutator/oneagent_mutation/env_test.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator_test.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/1232
same as https://github.com/Dynatrace/dynatrace-operator/pull/1232
=> Use version in application monitoring without CSI (#1232)

src/api/v1beta1/feature_flags.go, src/api/v1beta1/properties.go, src/api/v1beta1/properties_test.go, src/controllers/dynakube/oneagent/daemonset/daemonset.go
`classicFullStack` does not require privileged container in call cases. By default it should use capabilities, only when the feature flag is set the container is privileged.
Deploy oneagent with the following configurations:
- without privileged oneagent feature flag: oneagent security context should use capabiilties
- with privileged oneagent feature flag: oneagent security context should be privileged
=> Fix unconfigurable onegent classic privileged container

config/crd/bases/dynatrace.com_dynakubes.yaml, config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/generated/dynatrace-operator-crd.yaml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/_csidriver.tpl, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, src/controllers/csi/driver/server.go, src/controllers/csi/metadata/correctness.go, src/controllers/csi/metadata/metadata.go
The CSI-driver can get stuck if it mounted volumes recently and then got restarted.
This happens due to some unexpected behaviour when using the same volume for 2 volumeMounts in a container while having `mountPropagation` on both volumeMounts.
Also fixes a misleading error that happens on restart.
Deploy a Dynakube that uses the CSI-driver, deploy sample apps. 
After they are done deploying, restart the CSI-driver,  it should restart without problem.
=> Fixes csi-driver stuck in Terminate after restart

src/installer/zip/gzip.go
When using the `codeModulesImage` the operator needs to unzip a gzip to create the directory that will be mounted to customer pods.
During this unzip process we don't respect the fileMode of the folders.
Use `codeModulesImage`
Easy way to see this the `./codemodules/<image-hash>/log` folder has incorrect permissions it should be
`drwxrwxrwx` but currently we have it as `drwxr-xr-x`
=> Respects folder fileMode during gzip unzip

Dockerfile
Bump version of CSI liveness-probe and registrar.
Run e2e tests and validate everything is running as expected.
=> Update registrar to v2.6.0 and livenessprobe to v2.8.0

.github/actions/build-image/action.yaml, .github/actions/upload-image/action.yaml, .github/dependabot.yml, .github/workflows/ci.yaml, hack/build/ci/prepare-build-variables.sh
GitHub Actions deprecated the use of `echo ::set-output`.
These changes are made according to their migration guide here: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* This PR is used to test the actions' workflow
=> Replaces `::set-output` by using output env var

assets/samples/applicationMonitoring.yaml, assets/samples/classicFullStack.yaml, assets/samples/cloudNativeFullStack.yaml, assets/samples/hostMonitoring.yaml
Having the https in the proxy examples is probably a mistake and confusing, as 
HTTPS proxies are rare and not widely supported and don't really make sense for a kubernetes environment.
Read 🙃 
=> Removes https proxy in samples

src/api/v1beta1/properties.go, src/controllers/dynakube/activegate/internal/capability/reconciler.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/statsd.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/statsd_test.go, src/controllers/dynakube/activegate/reconciler.go, src/controllers/dynakube/activegate/reconciler_test.go
The ActiveGate service used to expose ports of an ActiveGate deployment was only created if one of the following capabilities was enabled.
* routing
* kubernetes-monitoring
* dynatrace-api
This lead to no service being created if only the statsd capability was enabled and ports not being correctly exposed on the container.
* Create a cluster and deploy the operator
* Deploy a dynakube using one of the following ActiveGate capabilities
* routing
* kubernetes-monitoring
* dynatrace-api
* The created ActiveGate service should expose the ports 80 and 443
* Deploy a dynakube using the statsd capability
* The created ActiveGate service should expose the port 18125
* Deploy a dynakube with one of the previous capabiltiies in addition with the statsd capability
* The created ActiveGate service …
=> Fixes statsd ports not being exposed correctly if only statsd is enabled

src/standalone/env.go, src/standalone/env_test.go
Environment variables set for pod-name, -uid, and namespace name are not correctly evaluated in the standalone init.
These changes add evaluation for common environment variables to the data ingest environment and the oneagent environment.
* Deploy the operator and a application monitoring or cloudnative dynakube
* Deploy a sample deployment with the `oneagent.dynatrace.com/inject: "false"` annotation set
* Exec into the pod and check that all fields are set in `/var/lib/dynatrace/enrichment/dt_metadata.properties`
=> Adds missing properties for data enrichment

src/controllers/dynakube/activegate/internal/statefulset/reconciler.go, src/controllers/dynakube/activegate/internal/statefulset/reconciler_test.go
Cherrypick of https://github.com/Dynatrace/dynatrace-operator/pull/1331
Same as https://github.com/Dynatrace/dynatrace-operator/pull/1331
=> Fixes an issue where the ActiveGate's statefulset is deleted and recreated if labeled manually

test/activegate/activegate_test.go, test/appmon/dataingest.go, test/appmon/labelversiondetection.go, test/cloudnative/network_problems.go, test/operator/installation.go, test/setup/setup.go
A quick temporary solution to run the e2e tests against Openshift clusters, by setting the `PLATFORM` envvar to `openshift`
Run the e2e tests against a Openshift cluster, by setting the `PLATFORM` envvar
=> Adds basic openshift support for the e2e tests

src/controllers/csi/gc/unmounted.go
Currently the default time to garbage collect old agent log files is 14 days, however this was introduced due to the fact that the agent itself is doing that on other platforms. This might not fit on containerised environments.
Create a Dynakube with CSI Driver usage
Create sample apps and let injection happen
Delete the sample apps
The Logs from the agent should be collected after 7 Days
=> Lower default csi gc interval to 7 days

hack/make/tests/e2e.mk
adds a `make` target for classic e2e tests
`make test/e2e/classic`
=> Adds make target for classic e2e test case

.github/workflows/publish-images.yaml, hack/build/ci/upload-docker-image.sh
`scan.connect.redhat.com` registry was deprecated and replaced with `quay.io`.
Release with updated Secrets.
=> Remove deprecated `scan.connect.redhat.com` registry

.gitignore, hack/make/tests/e2e.mk, test/activegate/activegate_test.go, test/appmon/dataingest.go, test/appmon/labelversiondetection.go, test/bash/bash.go, test/bash/bash_test.go, test/classic/install_test.go, test/cloudnative/cloudnative_test.go, test/cloudnative/codemodules.go, test/cloudnative/install.go, test/cloudnative/network_problems.go, test/kubeobjects/environment/environment.go, test/kubeobjects/pod/execute.go, test/operator/pods.go, test/setup/setup.go, test/shell/shell.go, test/shell/shell_test.go, test/support_archive/install.go, test/support_archive/support_archive_test.go
Add E2E tests for the support-archive subcommand recently added in #1343.
`make test/e2e/supportarchive`
=> Add support-archive E2E test.

Dockerfile
Bump version of registrar to v2.6.2.
CSI driver registers correctly.
```
[]# kctl logs -cregistrar  pod/dynatrace-oneagent-csi-driver-q5z6t 
I1205 16:08:39.347839       1 main.go:166] Version: v2.6.2
I1205 16:08:39.446130       1 main.go:167] Running node-driver-registrar in mode=registration
I1205 16:08:39.846732       1 node_register.go:53] Starting Registration Server at: /registration/csi.oneagent.dynatrace.com-reg.sock
I1205 16:08:39.946770       1 node_register.go:62] Registration Server started at: /registration/csi.oneagent.dynatrace.com-reg.sock
I1205 16:08:40.146075       1 node_register.go:92] Skipping HTTP server because endpoint is set to: ""
I1205 16:08:40.270407       1 main.go:102] Received GetInfo call: &InfoRequest{}
I1205 16:08:40.270575       1 main.go:109] "Kubelet …
```
=> update csi registrar to 2.6.2

src/controllers/csi/gc/reconciler.go, src/controllers/csi/provisioner/controller.go, src/controllers/csi/provisioner/controller_test.go
If only hostMonitoring was enabled, then the csi provisioner didn't do anything, which caused the csi server to be unable to complete the request for oneagent volumes
Dynakube with hostMonitoring works as expected now.
=> Fixes hostMonitoring mode with csi volume

src/controllers/csi/driver/volumes/app/publisher.go, src/controllers/csi/driver/volumes/app/publisher_test.go
If there are a lot of pods that request a volume at the same time (only managed to reproduce it with > 50 pods), then some pods are failing to write the correct info into the database, because its locked by other write attempts. Due to this, the pod will be mounted and can start without a problem. 
During unmount the CSI Driver thinks the pod has a dummy volume, which is actually wrong, as the database is wrong. This leads to the fact that the CSI Driver does not unmount the volume and the pod is stuck in terminating.
1. Create a DynaKube setup with cloudNative or applicationMonitoring with CSI Driver
2. Schedule sample apps (> 50) on a single node
3. Check that the CSI Driver has problems writing a mounted pod into the DB
4. After deleting the sample apps, they might get stuck
=> Make mounting of pods more safe

.github/workflows/publish-images.yaml
Docker metadata is only added to dev images and not during release.
Same logic as is already in use in CI
=> Add dynamic docker labels on release

src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/config.go
Activegate-statsd container definition was added twice to AG statefulset spec if statsd-ingest capability was enabled. The PR removes duplication of activegate-statsd container definition.
Deploy dynakube with ActiveGate having statsd capability enabled.
=> Removed duplication of activegate-statsd container definition in AG statefulset

src/cmd/support_archive/config.go, src/cmd/support_archive/logs.go, src/cmd/support_archive/operator_version.go, test/scenarios/support_archive/support_archive_test.go
E2E tests for log collection in support archive (see #1386)
Run E2E tests in total or selectively with
`make manifests/branch test/e2e/supportarchive`
=> E2E test for support archive log collection.

src/controllers/csi/metadata/path_resolver.go, src/installer/zip/extractor.go, src/installer/zip/gzip.go, src/installer/zip/zip.go
Originally the image in `codeModulesImage` was expected to have all its relevant contents in the root of the image, so when we unzip it we can just move the contents and nothing is left behind.
But the codemodule-images built by the pipeline is a bit different, it has all the relevant content under `/opt/dynatrace/oneagent`.
So we have to support both variants.
Test 'original' image, where everything is at root: 
Set `codeModulesImage` to  `quay.io/dynatrace/codemodules:1.246.0.20220627-183412`
Test 'official' image, where everything is at `/opt/dynatrace/oneagent`:
Set `codeModulesImage` to  `quay.io/dynatrace/codemodules:1.259.0.20230103`
- ~[ ] Unit tests have been updated/added~ (the relevant parts are testing the "move" logic, which doesn't work with `afero`)
=> Adds support for official codemodules image

.github/actions/preflight/action.yaml, .github/actions/upload-image/action.yaml, .github/workflows/publish-images.yaml, hack/build/ci/preflight.sh, hack/build/ci/upload-docker-image.sh
Fix image push to RHCC with incorrect `-amd64` suffix:
- Move check whether suffix is needed to separate, optional parameter
- Push `<version>` image instead of `<version>-<platform` image in case of RHCC
- Split RHCC image push from GCR/Dockerhub image push
- Sign image for GCR/Dockerhub
- Run preflight for RHCC
- Update preflight tool to `1.4.3`
Normal behavior should not change for pushes/PRs, but release image push to RHCC should now use correct image:
- Check successful run in fork: https://github.com/chrismuellner/dynatrace-operator/actions/runs/3831691590
=> Remove platform suffix from RHCC release image

config/helm/chart/default/templates/application.yaml
Use the version set in the Chart.yaml.
This makes it easier during release, so we don't have to do magic to update the version here
Set the AppVersion in the Chart.yaml to something
Set the platform in the values.yaml to google-marketplace
Run helm template (or generate the manifests)
Check if the application.yaml version has been updated
=> Use chart version in `application.yaml`

Dockerfile
Update registrar and livenessprobe to latest versions.
Change registry to `registry.k8s.io` from `k8s.gcr.io`
CSI driver functionality works.
=> Update registrar/livenessprobe to `v2.7.0`/`v2.9.0`

Dockerfile
#1447 
Revert registry change for bugfix release.
#1447
=> [0.10] Update registrar/livenessprobe to `v2.7.0`/`v2.9.0` (#1447)

.gitignore, go.mod, go.sum
the sqlite library's version was raised to 2.0.3 by accident by the creators of the package so its invalid.
check that the csi-driver works as expected
=> Fix sqlite library version

src/ingestendpoint/secret.go
log.Info function call has been fixed. Number of  `creations`/`updates` is printed earlier.
```
{"level":"info","ts":"2023-01-13T09:10:52.087Z","logger":"ingestendpoint","msg":"reconciling data-ingest endpoint secret for","dynakube":"dynakube"}
...
{"level":"info","ts":"2023-01-13T09:10:52.093Z","logger":"ingestendpoint","msg":"reconciled secret for multiple namespaces","name":"dynatrace-data-ingest-endpoint","creationCount":0,"updateCount":0}
{"level":"info","ts":"2023-01-13T09:10:52.093Z","logger":"ingestendpoint","msg":"done updating data-ingest endpoint secrets"}
```
No stacktrace messages related to the log.Info call in the operator log
```
{"level":"dpanic","ts":"2023-01-13T09:10:52.093Z","logger":"ingestendpoint","msg":"odd number of arguments passed as key-value pairs for …
```
=> Fixed log.Info function call arguments

config/helm/chart/default/templates/Openshift/activegate/securitycontextconstraints.yaml
Security Context Constraint helm template for the Activegate needs an update because  `activeGate.readOnlyFs` value can't be configured in the helm values.
The obsolete value has been removed from Activegate SCC and the current state is
```
readOnlyRootFilesystem: false
```
It's correct setting for AG pod with writable file system and read only filesystem.
Deploy the following dynakube on an OpenShift cluster
```
metadata:
#annotations:
name: dynakube
spec:
apiUrl: https://<APIURL>/api
activeGate:
capabilities:
- routing
#- kubernetes-monitoring
```
enable/disable commented out annotations and capabilities and check what SCC is used by AG pod:
```
oc get pod dynatrace-activegate-0 -o "custom-columns=POD NAME:.metadata.name,SCC:.metadata.annotations.openshift\.io/scc,SE …
```
=> Add SecurityContextConstraint for ActiveGate with read-only root filesystem

hack/build/ci/preflight.sh
Preflight for the RHCC image fails on upload due to the checks running before the upload.
Fixed by removing the artifacts after generation. 
Run the publish image action.
=> Fix failing RHCC image preflight scan upload

hack/make/deploy/kubernetes.mk, hack/make/deploy/openshift.mk, test/operator/installation.go, test/scenarios/activegate/installation.go, test/scenarios/applicationmonitoring/dataingest.go, test/scenarios/applicationmonitoring/labelversiondetection.go, test/scenarios/cloudnative/network_problems.go, test/setup/setup.go
This should change the installation process in the e2e tests regarding the operator. With this change the make command will be used to install the operator.
Simply run the e2e tests.
=> Installs operator in e2e tests via make

test/operator/installation.go
`runBuildAndManifests` did the followings:
- build the image
- this should not be done during the e2e test run, because it then wouldn't work well in a pipeline (also just no 😅 )
- if you want to test local changes build the image separately 
- create the manifests
- this is unnecessary as the `make deploy/...` will not use the manifests that were created 
run any e2e test, now it should be faster :)
=> Removes unnecessary step in the e2e operator installation

hack/build/ci/prepare-build-variables.sh
the title explains it pretty well already :D
run `make deploy/kubernetes` on the main branch, the image in the yamls should be `snapshot` and not `snapshot-`
=> Fixes the image tag creation logic to work with main

config/helm/chart/default/templates/Openshift/activegate/securitycontextconstraints.yaml, src/controllers/dynakube/activegate/consts/consts.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/kubemon.go, src/controllers/dynakube/activegate/internal/statefulset/statefulset.go, src/controllers/dynakube/activegate/internal/statefulset/statefulset_test.go
ActiveGate containers i.e.  `activegate` regular container and `certificate-loader` init container should have the same securityContext. Additionally the securityContext should have `runAsUser` and `runAsGroup` fields set to the same value as it is specified by ActiveGate Dockerfile (`USER`).
Deploy DynaKube with `kubernetes-monitoring` capability enabled on:
- a Kubernetes cluster
- an OpenShift cluster.
=> Add runAsUser/runAsGroup fields to ActiveGate SecurityContext

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, src/api/v1beta1/dynakube_status.go
We should follow the rest of our statusfields and keep the lower case convention for status fields.
1. Apply a DynaKube
2. Check if the status fields are named and set correctly
=> Rename dynatrace-api related status fields in DynaKube to lowercase

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/csi/priority-class.yaml, config/helm/chart/default/templates/_csidriver.tpl, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/tests/Common/csi/priority-class_test.yaml, config/helm/chart/default/values.yaml
Allow to precise existing priorityclass instead of creating a dedicated one.
We use higher priority than the maximum user created one, which makes this DS have less priority than our "cluster" priority class. This makes the DS not able to provision on some nodes.
- Set `.Values.csidriver.existingPriorityClassName` to an existing priority class name.
=> Allow the use of a existing priorityclass

src/dtclient/activegate_auth_token.go, src/dtclient/client.go, src/dtclient/connection_info.go, src/dtclient/dynatrace_client.go, src/dtclient/dynatrace_client_test.go, src/dtclient/kubernetes_settings.go, src/dtclient/processmoduleconfig.go, src/dtclient/send_event.go, src/dtclient/token.go, test/kubeobjects/manifests/installation.go
Currently each response body needs to be closed after its not needed anymore. However we have to make sure that response and body are not nil, before calling the close function on it.
Everything should work as before
=> Make usage of response.Body.Close() more convinient

src/controllers/certificates/certificate_secret.go, src/controllers/certificates/certificate_secret_test.go, src/controllers/certificates/webhook_cert_controller.go, src/controllers/certificates/webhook_cert_controller_test.go, src/controllers/dynakube/activegate/internal/authtoken/reconciler.go, src/controllers/dynakube/activegate/internal/customproperties/reconciler.go, src/controllers/dynakube/activegate/internal/proxy/reconciler.go, src/controllers/dynakube/activegate/internal/proxy/reconciler_test.go, src/controllers/dynakube/activegate/reconciler.go, src/controllers/dynakube/connectioninfo/reconciler.go, src/controllers/dynakube/deploymentmetadata/reconciler.go, src/controllers/dynakube/dtpullsecret/reconciler.go, src/controllers/dynakube/token/reader_test.go, src/kubeobjects/configmap.go, src/kubeobjects/configmap_test.go, src/kubeobjects/secret.go, src/kubeobjects/secret_test.go
`OwnerReferences` field of the `dynatrace-webhook-certs` secret  is set to `dynatrace-webhook` Deployment to allow k8s  automatically remove the secret when the operator is uninstalled.
Additionally `OwnerReferences` of the `dynatrace-activegate-internal-proxy` secret is set to `<Dynakube>`.
Deploy operator on a cluster.
Install `<dynakube>` with ActiveGate enabled and proxy.
Check `OwnerReferences` of `dynatrace-activegate-internal-proxy` and `dynatrace-webhook-certs` secrets.
Delete the `<dynakube>` and uninstall the operator.
Both secrets should be automatically removed.
=> Add OwnerReferences to the "dynatrace-webhook-certs" secret

src/api/v1beta1/feature_flags.go, src/controllers/dynakube/oneagent/daemonset/daemonset.go, src/controllers/dynakube/oneagent/daemonset/daemonset_test.go
Currently it's not possible to set a different seccompProfile for the OneAgent. Setting seccomp profile via annotation is deprecated starting with kubernetes 1.27 and other changes are overwritten by the operator. To make it possible `feature.dynatrace.com/oneagent-seccomp-profile: <name>` feature flag is added. 
The seccomp profile has to be stored on nodes in the `/var/lib/kubelet/seccomp/` directory. Specify the relative path. For instance:
```
feature.dynatrace.com/oneagent-seccomp-profile: "custom-seccomp-profile.json" 
```
means the `/var/lib/kubelet/seccomp/custom-seccomp-profile.json` file has to exist. No check/verification by the operator is done.
- deploy cluster
- copy `custom-seccomp-profile.json` to the `/var/lib/kubelet/seccomp/` directory on your nodes 
```
{ …
```
=> Add feature flag to configure custom seccomp profile for oneagent

config/deploy/kubernetes/kustomization.yaml, config/deploy/openshift/kustomization.yaml, config/manifests/bases/dynatrace-operator.clusterserviceversion.yaml
We cant deploy the csi driver's daemonset using OLM so we should not put all the related stuff into the bundle, as they provide no value.
The `config/deploy/${platform}/kustomization.yaml` are only used during the bundle generation, so its ok to change it.
Run `make bundle PLATFORM=kubernetes VERSION=1.2.3` and `make bundle PLATFORM=openshift VERSION=1.2.3` and check if the generated bundle has all the things we need. (and no csi driver components)
=> Use csi less target for OLM bundle generation

.golangci.yml, config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, hack/helm/generate-crd.sh, hack/make/manifests/config.mk, hack/make/manifests/crd.mk, src/api/v1alpha1/dynakube_types.go
Adds `make` target to generate only the CRD for the `dynatrace` namespace.
Meant to be used for releases
Try `make manifests/crd/release` and check if the `config/deploy/dynatrace-operator-crd.yaml` is correct.
Try `make manifests` and see if it works as expected. (it should produce the same as before)
- ~[x] Unit tests have been updated/added~
=> Improves crd generation

config/helm/chart/default/values.yaml
The comment in our values file is wrong as the default is 7 days, which is correctly stated in our documentation. We should remove the comment in order to avoid maintaining two locations.
Just a docu update
=> Remove comment of wrong default value for MAX_UNMOUNTED_VOLUME_AGE

hack/make/tests/e2e.mk
Currently our e2e tests fail on Openshift, because the classicFullStack tests has some leftovers, which need to be cleaned up properly in a seperate ticket. However for now, to make the tests work we should run the classicFullstack test as last one in order to limit side issues.
Run the e2e tests on an openshift cluster and check if they are working
=> Change order of e2e tests by adding prefix to classsicFullStack test

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, src/controllers/csi/gc/unmounted.go
=> Adapt usage of maxUnmountedVolumeAge in helm values

config/helm/chart/default/templates/_helpers.tpl
This change solves a bug in the definition of the `dynatrace-operator.image` for the `google-marketplace` platform in the Helm Chart.
This close #1562 
Set the platform to `google-marketplace` in the values file and render the Helm Chart. A valid image should be generated.
=> GH-1562: Fix dynatrace-operator.image for google-marketplace

src/cmd/support_archive/config.go, src/cmd/support_archive/resources.go, src/cmd/support_archive/resources_test.go
Currently the support archive collects kubernetes objects as json, but we should collect them as yaml manifests, as its easier to read and a more native approach
1. Deploy the operator
2. Run support archive `kubectl exec -n dynatrace deployment/dynatrace-operator -- /usr/local/bin/dynatrace-operator support-archive`
3. Check if the generated archive has the correct manifests stored as .yaml and check if the content is right
=> Collect `.yaml` instead of `.json` manifests in support archive

src/cmd/support_archive/builder.go, src/cmd/troubleshoot/builder.go, src/kubeobjects/env.go
Uses the same logic to determine the default namespace when running the supportarchive and troubleshoot command
Run the troubleshoot/support archive command 
=> Unify the default namespace for supportachive and troubleshoot command

src/cmd/support_archive/logs.go
Currently, collection of the support archive often produces warnings like this:
`previous terminated container "server" in pod "dynatrace-oneagent-csi-driver-78m44" not found`
These warnings are perfectly normal as often "previous" logs do not exist when the containers in pods didn't crash and restart. Nevertheless, this can be alarming to the unknowing user and we should therefore remove this warning.
1. Deploy the operator
2. Run support archive `kubectl exec -n dynatrace deployment/dynatrace-operator -- /usr/local/bin/dynatrace-operator support-archive`
3. Check if the logs have a note about previous container logs not found (they should not have one)
- [] Unit tests have been updated/added
=> Remove `previous log not found` warning in support archive logs

src/cmd/troubleshoot/builder.go, src/cmd/troubleshoot/builder_test.go, src/cmd/troubleshoot/checks.go, src/cmd/troubleshoot/checks_test.go, src/cmd/troubleshoot/config.go, src/cmd/troubleshoot/context.go, src/cmd/troubleshoot/crd.go, src/cmd/troubleshoot/dynakube.go, src/cmd/troubleshoot/dynakube_test.go, src/cmd/troubleshoot/image.go, src/cmd/troubleshoot/image_test.go, src/cmd/troubleshoot/logger.go, src/cmd/troubleshoot/logger_test.go, src/cmd/troubleshoot/namespace.go, src/cmd/troubleshoot/namespace_test.go, src/cmd/troubleshoot/oneagentapm.go, src/cmd/troubleshoot/proxy.go, src/cmd/troubleshoot/proxy_test.go, src/cmd/troubleshoot/testutils.go
This PR is a preparation for running the troubleshoot command within the support archive command.
First, it gets rid of the hidden log singleton in troubleshoot. This is needed so that the support archive command can provide an own logger to grab all output into a file. With this, logging had to be reworked a bit to keep separate subtest loggers with dedicated names.
Furthermore, formatting log lines seems to be implemented overly complicated, this has been simplified along the way.
Build the operator, deploy it and run the troubleshoot command. Everything should work as before.
=> Simplify logging and get rid of log singleton

src/cmd/support_archive/builder.go, src/cmd/support_archive/operator_version_test.go, src/cmd/support_archive/troubleshoot.go, src/cmd/support_archive/troubleshoot_test.go
The troubleshoot command is now automatically executed when a support archive is created. The output is added to `troubleshoot.txt` in the root of the support archive.
Build and deploy the operator, run the `support-archive` subcommand and check the result for the newly added `troubleshoot.txt` file. It should contain a typical troubleshoot output. As a cross check you could run the `troubleshoot` command and compare results.
=> Run troubleshoot command and collect output into support archive.

.github/actions/build-image/action.yaml, Dockerfile, hack/build/build_image.sh, hack/build/ci/prepare-build-variables.sh, hack/build/create_go_build_tags.sh, hack/make/go.mk, hack/make/tests/e2e.mk
We had inconsistent use of our go build tags, so this moves it into a shell script that is used all over the codebase to get the correct build tags.
you can run `./hack/build/create_go_build_tags.sh true` to check the tags (the `true` arg is for if we need the e2e tag or not)
=> Moves go build tags to a common location

test/scenarios/support_archive/install.go
E2E test failed because it was surprised by the new `troubleshoot.txt` file.
Run support archive E2E test.
=> Fix support archive E2E test.

src/api/v1beta1/feature_flags.go, src/webhook/mutation/pod_mutator/init_container.go, src/webhook/mutation/pod_mutator/init_container_test.go
Currently the failure policy environment variable is set via pod annotations. With this the logic should be changed to an approach where the environment variable can be set via a feature flag in the dynakube.
Deploy the operator and inject into sample apps and check their respective environment variables.
=> Adds feature flag to configure failure policy per dynakube

src/cmd/support_archive/resources.go, src/cmd/support_archive/resources_test.go, test/scenarios/support_archive/install.go
Currently some manifests are stored with the kind as prefix, which is uppercase. We should commonly store the with lowercase names.
Deploy an operator pod and execute the support archive subcommand
the resulting manifests should be named properly in lowercase letters.
=> Make support archive manifest names lowercase

test/scenarios/cloudnative/codemodules.go
Previously the test did check precisely whether the disk usage changed or not. This did fail every now and then, which resulted in the test to be flaky. Now there is no exact check for equality but rather a check whether the difference of the disk usage is below a threshold. After many tests locally I think 100 as a value for the difference proved sufficient.
Run `make test/e2e/cloudnative`
=> Fixes e2e test which checks for disk usages in codeModules injection test

assets/calico/activegate-policy.yaml, src/controllers/dynakube/activegate/consts/consts.go, src/controllers/dynakube/activegate/internal/capability/reconciler_test.go, src/controllers/dynakube/activegate/internal/capability/service.go, src/controllers/dynakube/activegate/internal/capability/service_test.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/serviceport.go, src/controllers/dynakube/activegate/internal/statefulset/statefulset.go, src/controllers/dynakube/activegate/reconciler_test.go
Removes http ports from the ActiveGate:
- `9998` on the ActiveGate container
- `80` on the ActiveGate service
These are not necessary, so we shouldn't keep them.
Deployed ActiveGates work as expected
=> Removes unnecessary http port for activegates

src/installer/image/installer.go, src/installer/image/installer_test.go, src/installer/image/source.go, src/installer/image/source_test.go
Currently we request the docker manifest for the codeModulesImage in each reconcile within the CSI Driver's provisioner, in order to get the image digest and check if it updated and if we need to redownload the image. However this can cause a lot of traffic for a image registry as this request is done once each 5 minutes per node per dynakube. 
Deploy the operator and check following scenarios:
1. Deploy a dynakube with a codeModulesImage set without a digest e.g yourrepo/image:tag
Digest should be retrieved from registry by getting the manifest -> as before
2. Deploy a dynakube with a codeModulesImage set with a digest e.g yourrepo/image@sha256:digest
Digest should be taken from the image directly and no call should be made to the registry
3. Deploy a dynakube with a codeModulesImage set …
=> Lower request amount for image manifest if codeModulesImage provides digest

src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/readonly.go, test/helpers/components/dynakube/dynakube.go, test/helpers/steps/assess/dynakube.go, test/scenarios/activegate/installation.go
ReadOnly modifier - removed statsd related conditions.
ActiveGate e2e test (no proxy) performs additional steps to verify readonly ActiveGate:
- dynakube is updated with `activegate-readonly-fs` annotation
- next step waits until dynakube is reconciled and ActiveGate pod is running
- verification if InitContainer and Container RootFilesystems are ReadOnly
- verification if appropriate Volumes are added
- verification if appropriate VolumeMounts are added
Use the following command to start the test
```
make test/e2e/activegate
```
=> Adapt activegate e2e test for operator deployment with readonly active gate

src/controllers/csi/driver/volumes/app/publisher.go, src/controllers/csi/driver/volumes/app/publisher_test.go, src/controllers/csi/driver/volumes/bind_config.go, src/controllers/csi/driver/volumes/bind_config_test.go, test/scenarios/cloudnative/codemodules.go
Some logic was changed during the status rework, where the provisioner would not set the version field in the database in case codeModulesImage was used, which caused the server to be unable to know that it can mount stuff, when imageDigest is present.
Related to the same change the e2e log check is not correct as we no longer log the tag of the downloaded image, but the whole repo:tag@digest (if the image was provided via a tag)
run `make test/e2e/cloudnative`
=> Fixes csi-server "archive-is-available" logic

hack/e2e/run_all.sh, hack/make/tests/e2e.mk, test/helpers/kubeobjects/environment/environment.go
Added `test/e2e/%/debug` target to start a test and skip `teardown` steps if it fails. The `--fail-fast` flag is appended to the test command arguments if `debug` target is used.
The `%/debug` target is ignored by the `run_all.sh` script.
Launch any e2e test in the debug mode and manually remove operator deployment
```
terminal 1: make test/e2e/cloudnative/debug
`=== RUN   TestActiveGate/activegate-capabilities/operator_started`
terminal 2: kubectl -n dynatrace delete deployment.apps/dynatrace-operator 
```
The test will fail but `service/dynatrace-webhook`, `deployment.apps/dynatrace-webhook` should exist.
=> Add a CLEANUP option for the e2e tests

.github/actions/sign-image/action.yaml, .github/workflows/publish-images.yaml
`COSIGN_EXPERIMENTAL` flag removed and additionally `cosign` version bumped to v2.0. Changes must be made in  one go because the flag changes behavior of the command and just removing the flag would break the pipeline. Additionally new arguments and permissions are needed: 
- new arguments: `-y`
- new permissions: `id-token: write`
I tested the changes using my forked project.
=> Bump sigstore/cosign to v2.0.0 in /.github/actions/sign-image (sigstore/cosign-installer from v2.8.1 to v3.0.1)

hack/make/tests/e2e.mk, test/helpers/components/dynakube/dynakube.go, test/helpers/proxy/proxy.go, test/helpers/sampleapps/curl.go, test/scenarios/activegate/installation.go, test/scenarios/cloudnative/network_problems.go, test/scenarios/cloudnative/proxy/proxy.go, test/testdata/network/dynatrace-kube-system-approval.yaml, test/testdata/network/dynatrace-openshift-approval.yaml, test/testdata/network/proxy-approval.yaml
Added test steps to make sure the network is cut off. Bi-directional traffic between `dynatrace` and `kube-system`+`openshift-*`  namespaces is allowed (otherwise the operator doesn't work). Additionally bi-directional traffic between `dynatrace` namespace and the proxy POD is allowed .  
Make sure NetworkPolicy is supported by your cluster. Use the following commands to start tests:
```
make test/e2e/activegate/proxy
make test/e2e/cloudnative/proxy
```
=> Check network cut off works in e2e tests

config/helm/chart/default/Chart.yaml, config/helm/chart/default/templates/Common/webhook/poddisruptionbudget-webhook.yaml
API versions of Kubernetes resources may change without underlying functionality changing. We want to apply the correct version of the resource depending on the resource that is available.
Currently the only version that changed since 1.19 is `PodDisruptionBudgets` - Version `v1` was added in k8s 1.21.
This PR adds a helm check to this version and sets the min kubernetes version to 1.19.
- helm install can be done 
- on 1.19
- on 1.26 without problems
- `make install` always deploys version v1
=> Add check for poddisruptionbudget

Dockerfile
Currently we do not know if a dependency in the docker file has a newer image with the same tag or not, with this change, dependabot will care about notifying us and also open a PR is there is a new image for the same tag
`make build` should run successfully
=> Update image tags in Dockerfile to use tag and digest

.github/actions/sign-image/action.yaml, .github/workflows/publish-images.yaml, hack/build/ci/get-image-digest.sh
Adds an extra step for `publish-image` to get the digest of the published image and use that as well with cosign.
I used cosign v2.0.1
I tested it on my fork by adding the new steps to the basic CI workflow so the signing also happens on pull-requests 
https://github.com/0sewa0/dynatrace-operator/pull/97/files#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddR169-R182
Example successful run:
https://github.com/0sewa0/dynatrace-operator/actions/runs/4744096685/jobs/8424677189
=> Add digest to image signing

hack/make/images.mk
Currently its possible to run make build on the main branch, which pushes snapshot images to quay. 
This can cause interference with the e2e pipelines, as local builds do not support multi arch.
This PR adds a check to prevent accidental push of snapshot tags to the makefile.
`make build` - should fail when on main branch (however, setting the tag manually works)
=> Add safety check to prevent snapshot push from make command

src/webhook/mutation/pod_mutator/init_container.go, src/webhook/mutation/pod_mutator/init_container_test.go
When the initResources are nil then you basically do a `*nil` which causes the webhook to crash. (the webhook itself does not crash, but it will fail to do the injection)
run `make test/e2e/applicationmonitoring`
=> Fix disappearing init container incase of nil resources

.github/renovate.json
Updates renovate pod config to avoid updates indirect dependencies
Can't be tested directly, Observe incoming renovate PRs.
=> Avoid updates of indirect go dependencies

.github/renovate.json
For k8s.io/client.go the use of v0.x.y is recommended for K8S >= 1.17.
Check created PRs
=> Limit k8s.io/client-go to v0.x.y

src/controllers/dynakube/activegate/internal/statefulset/statefulset.go, src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynakube_controller_test.go, src/controllers/dynakube/version/activegate.go, src/controllers/dynakube/version/activegate_test.go, src/controllers/dynakube/version/codemodules.go, src/controllers/dynakube/version/codemodules_test.go, src/controllers/dynakube/version/image_hash.go, src/controllers/dynakube/version/image_hash_test.go, src/controllers/dynakube/version/oneagent.go, src/controllers/dynakube/version/oneagent_test.go, src/controllers/dynakube/version/reconciler.go, src/controllers/dynakube/version/reconciler_test.go, src/controllers/dynakube/version/synthetic.go, src/controllers/dynakube/version/synthetic_test.go, src/controllers/dynakube/version/updater.go, src/controllers/dynakube/version/updater_test.go
As the tenant-registry is not made to be used with digest, this change goes back to the previous solution of using the build-label on the images of the tenant-registry in order to determine the version, so we can update the oneagent/activegate when necessary.
deploy oneagents/activegates
check if the `image` field only uses the tag, and check that the version label on the statefulset and daemonset is set.
=> Revert digest usage for tenant-registry images

src/controllers/dynakube/version/reconciler.go, src/controllers/dynakube/version/reconciler_test.go
Currently the behaviour of the oneAgent daemonset changes is a bit weird, as if you change a custom image in the DynaKube, the operator has a timeout of changing the dynakube status between 1-15 mins depending on when the last request was made. 
This is now improved by not only checking if the digest changed of the manifest we pull, but also check if the image/version value in the spec itself changed.
So now if the image/version in the `dynakube` spec changes, then we overrule the timestamp and update the version status earlier.
1. Choose a mode where you can set `version`(example: applicationMonitoring) or `image` (example: classicFullstack).
2. Set the chosen custom field to a value that works.
3. Wait for the dynakube's status to update, (and also the resources to be deployed if …
=> Adds additional check for custom fields during version status creation

src/controllers/dynakube/activegate/internal/statefulset/statefulset.go, src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynakube_controller_test.go, src/controllers/dynakube/version/activegate.go, src/controllers/dynakube/version/activegate_test.go, src/controllers/dynakube/version/codemodules.go, src/controllers/dynakube/version/codemodules_test.go, src/controllers/dynakube/version/image_hash.go, src/controllers/dynakube/version/image_hash_test.go, src/controllers/dynakube/version/oneagent.go, src/controllers/dynakube/version/oneagent_test.go, src/controllers/dynakube/version/reconciler.go, src/controllers/dynakube/version/reconciler_test.go, src/controllers/dynakube/version/synthetic.go, src/controllers/dynakube/version/synthetic_test.go, src/controllers/dynakube/version/updater.go, src/controllers/dynakube/version/updater_test.go
cherry pick of #1741
same as #1741
=> Revert digest usage for tenant-registry images (#1741)

src/controllers/dynakube/version/reconciler.go, src/controllers/dynakube/version/reconciler_test.go
This reverts commit 6056b657d674d9f70c01cffa1135804fe3d5b8d8.
Revert #1748 on release branch
=> Revert "Adds additional check for custom fields" on release-0.11 branch

.github/workflows/ci.yaml
With this the CI is altered in a way, such that if a PR is created from a fork it does not fail anymore. Previously it failed because of missing access tokens. These steps are now skipped.
Create a fork with the change to the CI. Then create a fork from the fork and create a PR and take a look at the steps that are triggered by the CI.
For example already done here: https://github.com/aorcholski/dynatrace-operator/pull/2
=> Skip pushing image and manifest when creating a PR from a fork

test/scenarios/classic/install.go
Our e2e test for classicFullStack runs flaky, as the oneAgent needs more time to startup properly, than our sample apps come up. The problem is that the agent reports its ready state as ready, even though its not yet 100% ready to inject.
run the classic e2e test (`make test/e2e/classic`)
=> Remove injected check for classicFullstack e2e test

hack/build/bundle.sh
This PR adds OCP 4.13 as supported version for OLM
make bundle -> annotiations.yaml should have 4.8-4.13 set properly
=> Add OCP 4.13 as supported version for OLM

src/installer/image/installer.go
Improves the error message when the provided image reference for the image installer does not have a digest.
This happens in case the image for the code-modules is in a registry that is not accessible by the operator, to set the status of the dynakube correctly (by getting and storing the digest), which will cause the operator to fall back to the "raw" text version of the provided image, which tends to be specified with a tag instead of a digest.
Try to reproduce the above mentioned scenario (with a proxy, or something).
And now the error message should be more specific
=> Improves error for unexpected type for image ref in image installer

src/api/v1beta1/feature_flags.go, src/webhook/mutation/pod_mutator/init_container.go, src/webhook/mutation/pod_mutator/init_container_test.go
Currently our initContainer does not have a seccomp profile set by default, which is caused by the fact that OCP < 4.11 does not allow seccomp profiles with its default restricted SCC. However we should add the option to configure it on DynaKube level in order to support [PodSecurityStandards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) properly
- Deploy the operator
- Create a Dynakube with the feature flag: `feature.dynatrace.com/init-container-seccomp-profile: "true"`
- Deploy sample apps
- Check if the initContainers security context has properly set the seccomp profile runtime default
=> Adds feature flag to set seccomp profile for initContainer

src/controllers/dynakube/connectioninfo/reconciler.go
The `communicationHosts` should not be appended to the already present `communicationHosts` in the `Status`.
We have to override them, otherwise the list will be infinitely growing.
check the `communicationHost` are present in the status,
check that it does not grow(with duplicates) after reconciling that status again,
=> Fixes growing number of communicationHosts in Status

src/api/v1beta1/dynakube_status.go, src/controllers/dynakube/activegate/internal/authtoken/reconciler.go, src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynakube_controller_test.go, src/controllers/dynakube/oneagent/oneagent_reconciler_test.go, src/controllers/dynakube/version/activegate.go, src/controllers/dynakube/version/oneagent.go, src/controllers/dynakube/version/synthetic.go, src/controllers/dynakube/version/updater.go, src/controllers/dynakube/version/updater_test.go
This PR should fix the problem that a new ressource (daemonset, statefulset) is rolled out, in case of an HTTP error from the registry, we try to get the manifest from. This call is expected to fail if the dynakube has a proxy fail, since the library is not aware of that. 
Install the Operator
Create a Dynakube
Use a wrong image that does not exist as e.g oneAgent image
Check if a that no daemonset is rolled out
=> Prevent update of dynakube image status incase of error during registry call

config/helm/chart/default/templates/Common/webhook/validatingwebhookconfiguration.yaml
- sets timeout of validating webhook to 10s after diskussion to allow for completion of initialization procedure on K8s systems.
- deploy an operator and check if the validating webhooks `timeoutSeconds` is set to `10s`
=> increases timeout of validating webhook configuration to 10s

.github/workflows/codeql-analysis.yaml, .github/workflows/openssf-scorecards.yaml
Currently scorecard fails to upload the sarif file with the following message:
`Unable to upload "results.sarif" as it is not valid SARIF:`
According to the Github issue: https://github.com/ossf/scorecard/issues/3063 this is a general problem
After merging this PR, the main branch CI should run successfull again
=> Fix scorecard action by pinning `github/codeql-action` to `2.3.3`

test/scenarios/cloudnative/proxy/cloudnative_test.go
you have to first `Get` the testEnvironment before you can do anything with it. (otherwise you will get a nil pointer error)
run `make test/e2e/cloudnative/proxy`
=> Fix nilpointer in cloudnative-proxy e2e istio pre-check

.github/renovate.json5
- fixed the regex for the golang version in the dockerfile to enable renovate to update golang
1. fork the repo
2. setup renovate
3. run renovate
=> fixed renovate regex for dockerfile golang version

Makefile
If the e2e make target is longer than 35 char then the `make help` command will have an output for that make target where the color code is right next to the name of the target.
This is a problem for the `hack/e2e/run-all.sh` as it will try to run a make target that has an color code at the end, which wont exist, so make will complain that "target does not exist".
The best part is that this will not show up in the command line and does not affect every shell. (no problem on Mac and Fedora)
To double check the issue, you could modify the `hack/e2e/run-all.sh` to instead of calling the make target, just put the name of the target into a file. (as it will not show up in the command line)
```
#!/usr/bin/env bash
tests=$(make help | grep -oE "test\/e2e\/\S*" | grep -v "%\/debug")
result=0
for …
```
=> Add space between target name and color code

.github/workflows/ci.yaml
It's enough to build images with `amd64` to verify build/push works correctly. All remaining architectures will be built on merge to default branch.
Check build on this PR.
=> Build only `amd64` image on feature branches

config/helm/chart/default/templates/Openshift/activegate/securitycontextconstraints.yaml
Setting `runAsUser` to `MustRunAs` is rather fragile as the moment something gets injected to a pod (with probably a different user) the SCC will no longer match, therefor the pod will not come up. 
Run `make PLATFORM=openshift test/e2e/activegate/proxy` againts an openshift cluster, this will use istio to limit the dynatrace namespace, so the istio sidecar will be injected into every pod, which has the userid 1337.
If the tests passes then everything works as expected.
=> Make activegate SCC less fragile

hack/make/prerequisites.mk, src/dtclient/activegate_auth_token.go, src/dtclient/dynatrace_client.go, src/dtclient/dynatrace_client_test.go, src/dtclient/image.go, src/dtclient/kubernetes_settings.go
refactored the code to introduce a basic 15m timeout to requests of the dynatrace client.
- run unit-tests
- debug code an verify timeout/deadline of context
=> introduce dtclient basic request timeout

hack/make/prerequisites.mk, src/dtclient/activegate_auth_token.go, src/dtclient/client.go, src/dtclient/dynatrace_client.go, src/dtclient/dynatrace_client_test.go, src/dtclient/image.go, src/dtclient/kubernetes_settings.go
Undoes the previous commit about using the `NewRequestWithContext` with a quick work around timeout, as it cause unexplainable problems (1 specific request always got its context immediately canceled)
So now we just set a default timeout on the client itself
Run e2e test, and they should all pass.
- [ x] Unit tests have been updated/added
- [ x] PR is labeled accordingly
- [ x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)
=> Simplify dtclient timeout logic

src/controllers/dynakube/activegate/capability/capability.go, src/controllers/dynakube/activegate/capability/capability_test.go, src/controllers/dynakube/activegate/internal/proxy/reconciler.go, src/controllers/dynakube/activegate/internal/proxy/reconciler_test.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/proxy.go, src/controllers/dynakube/activegate/reconciler_test.go, src/controllers/dynakube/dynakube_controller_test.go
fixed the race condition of multiple dynakubes configured with and without proxy interfering with each others proxy secret by segmenting proxy secrets. this results in each dynakube handling it's own secrets only. 
- each dynakube will only handle it's own secrets.
- fixes #1825
- create two dynakubes where one has a proxy configured while the other has not.
- change the dynakube without proxy so it gets reconciled
- the secret of the dynakube with proxy should not be touched
=> Fix the race condition of multiple dynakubes configured with and without a proxy

assets/samples/classicFullStack.yaml, assets/samples/cloudNativeFullStack.yaml, assets/samples/hostMonitoring.yaml
Previously the image field in the samples was invalid as it was empty but not an empty string. As it is of type string it has to be set to an empty string in order to not be invalid when applying the dynakube. 
NOTE: I also did the same with the version fields as they are also of type string.
=> Fix dynakube sample image and version fields by setting empty string

src/controllers/csi/provisioner/controller.go, src/dtclient/processmoduleconfig.go, src/standalone/run.go, src/standalone/run_test.go
Incase the Dynatrace Environment api has an alias, then the operator will use the alias as the tenantUUID, however the customised oneagent archive downloaded from the tenant will have the actual non-aliased tenantUUID in the `ruxitagentproc.conf`. 
Deploy the operator with application monitoring, and in the csi-driver or in an injected pod check the agent conf directory's ruxitagentproc.conf and _ruxitagentproc.conf. When using a Dynatrace Environment with an alias, the 2 files should have a different entry in the [general] section for [tenant]
=> Overwrite the tenantUUID in the ruxitagentproc.conf

hack/build/ci/create-manifest.sh
Manifest should contain additional supported architecture, `ppc64le`, if images are built in CI.
Push multi platform image and create manifest using `create-manifest.sh`
=> Add ppc64le to image manifest on release

src/controllers/csi/provisioner/agent_test.go, src/dockerconfig/docker_config.go, src/dockerconfig/docker_config_test.go
For the image library to use TrustedCAs they need to be stored on the filesystem and provide the directory to the library before contacting the registry.
There was a recent refactor in that area of the code, that broke the filepath, causing the provided path to be a file instead of a directory.
You need a registry that needs a trustedCA, and provide said trustedCA to the operator and everything should work
=> Fix trustedCA handling for image registries

config/helm/chart/default/templates/Common/activegate/clusterrole-activegate.yaml, config/helm/chart/default/templates/Common/csi/clusterrole-csi.yaml, config/helm/chart/default/templates/Common/csi/csidriver.yaml, config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrole-oneagent-privileged.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrole-oneagent-unprivileged.yaml, config/helm/chart/default/templates/Common/operator/clusterrole-operator.yaml, config/helm/chart/default/templates/Common/webhook/clusterrole-webhook.yaml, config/helm/chart/default/templates/_platform.tpl, hack/make/manifests/kubernetes.mk, hack/make/manifests/openshift.mk
As we have removed the custom SCCs, we should also remove the openshift or OLM check, as there is no need for it anymore. We can just check for the platform everywhere anyway.
`make manifests` creates the correct manifests
=> Removes openshiftOrOlm check in helm manifests

assets/samples/applicationMonitoring.yaml, assets/samples/classicFullStack.yaml, assets/samples/cloudNativeFullStack.yaml, assets/samples/hostMonitoring.yaml, assets/samples/multipleDynakubes.yaml
Updated the sample yaml files.
Fixes #1857 
- deploy a dynakube from the sample.
- the k8s cluster should be visible in the tenant ui automatically.
=> Add automatic k8s cluster monitoring annotation to dynakube samples

test/scenarios/support_archive/install.go
On older kubernetes versions (like 1.20) the `"kubernetes.io/metadata.name"` label is not present on namespaces, so we don't rely on them during the support-archive e2e test. (it fails otherwise)
Also removed the assert for unexpected files, so if am unexpected restart happens this test will not break.
Run `make test/e2e/supportarchive/debug` on a kubernetes 1.20 cluster
=> Add unique label to e2e test namespace for support archive test

src/version/semantic.go, test/scenarios/cloudnative/specific_agent_version/specific_agent_version.go
The `specific-agent-version` e2e test needs 2 different versions to simulate an update. Update happens if versions relate to different sprints or different releases in the same sprint, otherwise versions are considered  equal by the update mechanism and no action is performed.
For example:
- 1.256.0.11112233-445566 and 1.256.0.11112233-778899 are "equal"
- 1.256.0.11112233-445566 and 1.256.1.11112233-778899 are different
- 1.256.0.11112233-445566 and 1.257.0.11112233-778899 are different
The lower version returned by `specificAgentVersion` function meets the above requirement now. The test fails if such a different version can not be found.
The `specific-agent-version` e2e test should PASS started by our pipelines. 
=> Fixed specific agent version e2e test (old version equal new version)

.github/workflows/release.yaml
Adds correct version comment for trivy action without the v prefix, as trivy creates tags without the v.
This currently prevents renovate to get the correct digest for that version: see [Error Logs](https://developer.mend.io/github/Dynatrace/dynatrace-operator/-/job/fffc50e4-8836-41a1-9309-f3e4482ab344)
=> Adds correct version comment for trivy action to release workflow

src/cmd/support_archive/builder.go, src/cmd/support_archive/builder_test.go, src/cmd/support_archive/logs.go, src/cmd/support_archive/logs_test.go, src/cmd/support_archive/resource_query.go, src/cmd/support_archive/resource_query_test.go, src/cmd/support_archive/resources.go, src/cmd/support_archive/resources_test.go
Replace the hardcoded filter `app.kubernetes.io/name=dynatrace-operator` for operator components by using the label value from the pod the support archive sub command is running in.
Install the operator via helm using a custom name, run the support archive subcommand and see if operator pod logs and operator manifests are collected correctly.
=> Use pod label to filter for operator components in support archive

README.md
Currently the link the the support lifecycle page is broken within our Readme.
This has been discovered by #1904
=> Fixes broken link to support lifecycle in readme.md

hack/make/images.mk
- changed the images.mk to use a digest if passed by caller
- only via release pipeline in concourse
=> Adds optional digest parameter for operator image to makefile 

src/webhook/mutation/pod_mutator/init_container.go, src/webhook/mutation/pod_mutator/init_container_test.go, src/webhook/mutation/pod_mutator/pod_mutator_test.go, src/webhook/mutation/pod_mutator/request_test.go
Fix #1894 
Always set `RunAsNonRoot` explicitly on webhook's init container. Before it was only set when its value was `true`.
This caused `Init:CreateContainerConfigError` status on some cases.
- Deploy the operator in cloudNativeFullStack or applicationMonitoring
- Deploy the deployment sample below
- Check the pods status (kubectl get pod php-musl-.. -n sample -o yaml
- See the error message
<details>
<summary>Deployment sample</summary>
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app: php-musl
name: 02-php-musl
namespace: sample
spec:
replicas: 2
selector:
matchLabels:
app: php-musl
strategy:
type: Recreate
template:
metadata:
annotations:
oneagent.dynatrace.com/technologies: php
oneagent.dynatrace.com/flavor: musl
oneagent.dynatrace.com/failure-policy: fail
labels: …
```
=> Always set 'RunAsNonRoot' explicitly on init container

assets/calico/activegate-policy.yaml, src/controllers/dynakube/activegate/consts/consts.go, src/controllers/dynakube/activegate/internal/capability/service.go, src/controllers/dynakube/activegate/internal/capability/service_test.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/serviceport.go, src/controllers/dynakube/activegate/internal/statefulset/statefulset.go, src/controllers/dynakube/activegate/internal/statefulset/statefulset_test.go, src/controllers/dynakube/activegate/reconciler_test.go, src/ingestendpoint/secret.go, src/ingestendpoint/secret_test.go, test/helpers/sampleapps/curl.go, test/scenarios/activegate/installation.go
ActiveGate HTTP port is opened if `metrics-ingest` capability is enabled. 
Changes applied to the `activegate` container:
- added DT_HTTP_PORT environment variable
- added TCP port 9998
Changes applied to the AG service:
- added HTTP port (80)
Run `test/e2e/activegate` test. The test uses `curl` command to get AG status from the HTTP endpoint.
=> Enable Activegate http endpoint for metrics-ingest capability

src/webhook/validation/activegate_test.go, src/webhook/validation/config.go, src/webhook/validation/preview.go, src/webhook/validation/validation_test.go
The `metrics-ingest` capability is no longer in the PREVIEW stage. Related warning message has been removed.
Deploy a Dynakube with ActiveGate and `metrics-ingest` capability enabled. No warning related to `metrics-ingest` is printed.
=> Removes metrics-ingest preview warning

config/helm/chart/default/templates/Common/activegate/clusterrole-activegate.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrole-oneagent.yaml, config/helm/chart/default/tests/Common/activegate/clusterrole-activegate_test.yaml, config/helm/chart/default/tests/Common/oneagent/clusterrole-oneagent_test.yaml, hack/make/manifests/openshift.mk
Fix #1921
In case of Openshift we need additional permissions to use Security Context Constraints, which are currently generated twice, once in the openshift.yaml and once in the openshift-csi.yaml. This PR removes this duplicity.
Check out open [Github Issue on this topics](https://github.com/Dynatrace/dynatrace-operator/issues/1921):
- Generate manifests using `make manifests/openshift`
- Check openshift-csi.yaml
- CSI specific configuration contains Activegate and Oneagent ClusterRole(Binding)
=> Fix duplicated ClusterRole for Openshift

src/cmd/main.go, src/cmd/startup_probe/builder.go
Added new `startup-probe` subcommand which tries to resolve `https://kubernetes.default.svc.cluster.local` hostname to make sure the DNS service is properly configured and running.
In case of success no message is printed.
Create a deployment having:
- image: the operator image
- command: bash sleep command
- DNS configuration: for example invalid IP address of DNS server
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: dns-setup
spec:
selector:
matchLabels:
test: dns-setup
replicas: 1
revisionHistoryLimit: 0
template:
metadata:
labels:
test: dns-setup
spec:
containers:
- name: test
image: IMAGE URL
imagePullPolicy: Always
command:
- /bin/bash
args:
- -c
- "counter=1 ; while [ ${counter} -lt 10000 ] ; do echo ${counter} ; counter=$((counter + 1)) ; sleep 1 ; done"
startupProbe: …
```
=> Adds startup-probe command

config/helm/chart/default/templates/Common/webhook/clusterrole-webhook.yaml, config/helm/chart/default/tests/Common/webhook/clusterrole-webhook_test.yaml, src/webhook/mutation/pod_mutator/dataingest_mutation/mutator.go, src/webhook/mutation/pod_mutator/dataingest_mutation/mutator_test.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator_test.go
Due to performance reasons POD mutators shouldn't create `data-ingest-endpoint` or `dynatrace-dynakube-config` secrets. These secrets are created by the namespace webhook or the operator in the reconciliation loop.
POD mutating process should be generally much faster but in rare cases creation of an application POD may take a few minutes.
Deploy CloudNative and a sample application. Application POD should be created either immediately or after a few minutes at most. An event similar to this one should be reported on the application POD in such a case:
`
Warning FailedMount 30s (x8 over 93s) kubelet MountVolume.SetUp failed for volume "injection-config" : secret "dynatrace-dynakube-config" not found
`
Such a scenario also can be easily reproduced if `dynatrace-dynakube-config` secret and …
=> Removes creation of secrets by POD mutators

.github/renovate.json5
Updates for UBI9 base images weren't happening as RedHat changed their naming to x.y instead of x.y.z 
Changed renovate config to only require at least two digits for versions in Dockerfile.
Also make sure that versions with and without 'v' prefix are accepted (e.g. v2.10.0 and 2.10.0)
Can only be tested on a fork. 
* Install renovate on fork
* Copy changes of renovate config to fork
* Decrease used versions of _all_ dependencies in Dockerfile (golang, UBI9, liveness, registrar)
* Check Dependency Dashboard and PRs on fork to see if all dependencies get updated again
You can see this change in action here: https://github.com/StefanHauth/dynatrace-operator/issues/4
=> Reduce allowed version in Dockerfile to require only two digits

.github/renovate.json5, .github/workflows/ci.yaml
Currently we updating golangci-lint only in makefiles, this PR updates logic, so we update it in GH version too.
Please include some guiding steps on how to test this change during a review.
Tested in my fork:
https://github.com/andriisoldatenko/dynatrace-operator/pull/5
=> Add golangci-lint gh action to renovate

config/helm/chart/default/templates/Common/webhook/clusterrole-webhook.yaml, config/helm/chart/default/tests/Common/webhook/clusterrole-webhook_test.yaml, src/webhook/mutation/pod_mutator/dataingest_mutation/mutator.go, src/webhook/mutation/pod_mutator/dataingest_mutation/mutator_test.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator_test.go
This reverts commit e4687783fd07489c86bef07dd7acf86883b3609f.
The commit cause  the sample app pod to be stuck in init for 30 minutes.
Deploy CloudNative and a sample application. Application POD should be created immediately. `FailedMount` errors do not happen
`
Warning FailedMount 30s (x8 over 93s) kubelet MountVolume.SetUp failed for volume "injection-config" : secret "dynatrace-dynakube-config" not found
`
=> Revert "Secrets are not created by dataingest/oneagent mutators (#1936)"

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/values.yaml
Makes the seccomp field in the security context of our components configurable via helm
Play with the seccomp fields in the values.yaml.
=> Make seccomp field configurable for components

src/dtclient/endpoints.go
When we skip the metadata when downloading a codemodule, the resulting zip will not contain the information necessary for the codemodule to connect to the Dynatrace Environment.
In https://github.com/Dynatrace/dynatrace-operator/pull/1954 we already made it that we override this information when mounting it to the user container, so we can safe space and download amount.
2 things you can test:
- ApplicationMonitoring mode **without** CSI driver, not that much benefit here, but it should still "just" work
- Cloudnative or ApplicationMonitoring mode with CSI driver
- Before testing, make sure you don't have anything under `/data/codemodules` on the nodes, just to make sure you don't have something there from a previous download
-  After deploying the dynakube and the csi driver finished …
=> Request raw codemodules from deployment API

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/_helpers.tpl, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml
This PR adds startupProbe to csi-provisioner and operator pod
**what is startupProbe?**
> A startup probe verifies whether the application within a container is started. Startup probes run before any other probe, and, unless it finishes successfully, disables other probes. If a container fails its startup probe, then the container is killed and follows the pod’s restartPolicy.
> This type of probe is only executed at startup, unlike readiness probes, which are run periodically.
> The startup probe is configured in the spec.containers.startupprobe attribute of the pod configuration.
Deploy current branch to cluster and see new startupProbe:
```
k get pods dynatrace-oneagent-csi-driver-qr8wg -o jsonpath={.spec.containers} | jq -r '.[].startupProbe'
{
"exec": {
"command": [ …
```
=> Add startupProbe to csi-provisioner and operator pod

go.mod, go.sum
Updates bugfix versions of dependencies, which should be included with 0.12.1
Everything should work as before
=> Update dependencies for 0.12.1 release

config/helm/chart/default/templates/Common/oneagent/clusterrole-oneagent-unprivileged.yaml
With #1867 we removed the OpenshiftOrOLM check, however it got reintroduced, but due to cherry-pick conflict, we missed the oneAgent unprivileged clusterrole. This PR changes the check to the old format for this clusterrole
`make manifests` creates the correct manifests
=> Add missing service account for OLM installations

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, src/api/v1beta1/activegate_types.go, src/api/v1beta1/dynakube_status.go, src/api/v1beta1/dynakube_types.go, src/api/v1beta1/oneagent_types.go
- Update dynakube CRD descriptions to align with the [official documentation](https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/get-started-with-kubernetes-monitoring/dto-parameters-k8s). 
- Replace "Optional:" and "Deprecated:" text with the respective Kubebuilder annotations `+optional` and `+kubebuilder:deprecatedversion:warning=""`.
- Add missing descriptions on all dynakube.status fields. 
`kubectl explain dynakube.spec` and all subpaths
`kubectl explain dynakube.status` and all subpaths
=> Refactor existing and add missing CRD annotations

src/controllers/csi/provisioner/controller.go, src/dtclient/processmoduleconfig.go, src/initgeneration/initgeneration.go, src/initgeneration/initgeneration_test.go, src/standalone/run.go, src/standalone/run_test.go, src/standalone/secret_test.go
The `connectionInfo` we get from the cluster already contains the tenantUUID, and its the actual correct one, and not the one that we parse out of the apiURL, which caused problem if the apiURL was an alias of a tenant.
(Sidenote: most of the changes are related to rewriting the 22 months old tests 😅  )
When using an apiURL that points to a tenant using an alias, setup cloudNativeFullStack (or application monitoring with CSI driver), check that the agents can communicate. (if alias is used in as the tenant, then the agents will complain about not being able to connect, this should not happen)
=> Use correct tenantUUID

test/helpers/components/codemodules/codemodules.go, test/scenarios/applicationmonitoring/read_only_csi_volume.go, test/scenarios/cloudnative/basic/install.go, test/scenarios/cloudnative/codemodules/codemodules.go
This PR updates e2e test with new check.
```
make test/e2e/cloudnative
make test/e2e/applicationmonitoring
```
=> Update e2e tests for unconfigured codemodules scenarios

test/helpers/steps/assess/dynakube.go, test/helpers/steps/assess/operator.go, test/helpers/steps/teardown/operator.go, test/helpers/steps/teardown/uninstall.go, test/scenarios/activegate/installation.go, test/scenarios/applicationmonitoring/labelversiondetection.go, test/scenarios/applicationmonitoring/without_csi.go, test/scenarios/classic/switch_modes/install.go, test/scenarios/cloudnative/switch_modes/install.go
We currently have the problem that the switchmode e2e test cases mess with the outcome of other tests ran after them.
In the switchmode e2e test cases we have to be extra careful when it comes to clean up.
As we are using both classic and cloudnative we have to clean up:
- the csi driver's filesystem due to the cloudnative part
- not doing this might cause unpredictable behaviour in tests coming after this one 
- the run the uninstall.sh because of the classic part
- this is extra important on CRIO (so mainly openshift) because not running the uninstall.sh here will cause other tests just to fail straight out.
Sidenote: The current "helpers" for generalizing the steps were not really designed for this, so I had to do some quick modifications there, but now they feel a bit like …
=> Clean up better in switchmode e2e tests

.github/workflows/release.yaml
Generate manifests failed due to whitespaces in the commands. 
This PR removes them.
Run generate manifests step in the CI
=> Fix generate manifests step in pre release action

src/initgeneration/initgeneration.go, src/initgeneration/initgeneration_test.go
Fixes the use of `feature.dynatrace.com/oneagent-ignore-proxy: "true"` in case of application-monitoring without CSI driver.
We already respect this in the daemonset of the agent and the csi-driver.
Set the `feature.dynatrace.com/oneagent-ignore-proxy: "true"`
Set a proxy in the dynakube
Deploy application-monitoring without CSI-driver
Check that the sample app's ruxitagentproc.conf contains empty proxy field
=> Respect oneagent-no-proxy feature-flag in application monitoring

src/api/v1beta1/feature_flags.go, src/api/v1beta1/feature_flags_test.go, src/webhook/mutation/pod_mutator/oneagent_mutation/containers_test.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator_test.go
As the label version detection was default turned off and we switched it to on in the current dev version, it caused problems in the UI by grouping containers differently when enabled. This could potentially break custom rules aswell and therefore it was decided to leave it turned off for now.
Deploy a DynaKube without this feature flag set to true -> nothing should happen and no envs vars should be set on your workloads when injected (DT_RELEASE_PRODUCT, DT_RELEASE_VERSION)
=> Disable label-version-detection feature by default

src/api/v1beta1/dynakube/feature_flags.go, src/api/v1beta1/dynakube/feature_flags_test.go, src/webhook/mutation/pod_mutator/oneagent_mutation/containers_test.go, src/webhook/mutation/pod_mutator/oneagent_mutation/mutator_test.go
=> Disable label-version-detection feature by default (#2011)

.github/workflows/release.yaml, config/helm/chart/default/templates/Common/csi/csidriver.yaml, config/helm/chart/default/tests/Common/csi/csidriver_test.yaml
Currently the CSI manifests on OCP are missing the "csi-ephemeral-volume-profile" label. The check is wrong to add it, when the manifests are generated, as the check expects "partial" to be false, but it actually is "csi" in case of openshift-csi.yaml.
make manifests -> should generate an openshift-csi.yaml that has the CSIDriver resource and the label on it
=> Adds volume-profile label in openshift-csi manifest

config/helm/chart/default/templates/Common/csi/csidriver.yaml, config/helm/chart/default/tests/Common/csi/csidriver_test.yaml
Same as in #2010
Same as in #2010
=> Adds volume-profile label in openshift-csi manifest (#2010)

test/scenarios/classic/switch_modes/install.go, test/scenarios/cloudnative/switch_modes/install.go
In all cloudnative tests where we use a sample app we create the sample app's namespace before deploying the `dynakube` to avoid a race condition to happen, which could cause our tests to run longer then we would want and sometimes timing out.
The new `switchmodes` tests however do not follow this pattern, and therefore are flaky.
Run:
- `make test/e2e/classic/switchmodes`
-  `make test/e2e/cloudnative/switchmodes`
=> Make switch modes tests more reliable

src/controllers/dynakube/activegate/internal/statefulset/statefulset.go, src/controllers/dynakube/oneagent/daemonset/arguments.go, src/controllers/dynakube/oneagent/daemonset/arguments_test.go, src/controllers/dynakube/oneagent/daemonset/env_vars_test.go
change the ordering of environment and argument processing in statefulset and ActiveGate to always have customer arguments and env vars take highest precedence.
ActiveGate:
- override any of the following arguments should be reflected in the OneAgent: tenant, server, network-zone, operator-version, proxy
statefulset:
- set env vars and verify: DT_GROUP, DT_NETWORK_ZONE, DT_HTTP_PORT
=> Make Dynakube args and env vars override default operator values on main branch

doc/coding-style-guide.md
As it came up multiple times recently, I added to the code style guide how we should order our parameters of our functions.
Read it 😅 
=> Add code-style section about func param ordering

config/helm/chart/default/templates/Common/csi/clusterrole-csi.yaml, config/helm/chart/default/tests/Common/csi/clusterrole-csi_test.yaml
Currently our CSI Driver clusterrole lacks access to the privileged SCC, which blocks creation of CSI pods. The problem is that the check for adding the privileged SCC access is wrong an excludes the case where partial is set to csi.
Run make manifests and check openshift-csi.yaml if it contains the correct permissions for accessing the privileged SCC
=> Change check for adding scc permission to csi clusterrole

.github/workflows/ci.yaml, hack/make/go.mk
Enable CodeCov on the repository.
- CodeCov app has been added to the dynatrace-operator repo
- CODECOV_TOKEN has been added aswell
[More details about the setup here](https://app.codecov.io/gh/Dynatrace/dynatrace-operator/new)
CodeCov action is executed and passed on the PR
=> Enable CodeCov GitHub action

.gitignore, hack/make/go.mk
With a previous PR, we changed the output unit tests file from `cover.out` to `coverage.txt`. We missed adding it to gitignore.
---
=> Replace cover.out occurrences with new coverage.txt
