api/v1alpha1/zz_generated.deepcopy.go, controllers/activegate/activegate_controller.go, controllers/activegate/dtclient_builder.go, controllers/activegate/token_parser.go, controllers/customproperties/reconciler.go, controllers/dtpullsecret/find.go, controllers/dtpullsecret/find_test.go, controllers/dtpullsecret/generate.go, controllers/dtpullsecret/reconciler.go, controllers/dtversion/docker_config.go, controllers/kubemon/reconciler.go, controllers/kubemon/statefulset.go, dtclient/activegate_query.go, dtclient/client.go, dtclient/cluster.go, dtclient/dynatrace_client.go, dtclient/send_event.go, dtclient/tenant.go, dtclient/token.go, dtclient/token_test.go, go.mod, logger/error_prettify.go, logger/error_prettify_test.go, logger/logger.go
adds a "prettyfier" to the default logger and wraps some errors with a stacktrace
=> better stacktraces

README.md
=> Use correct path for cr.yaml

config/common/kustomization.yaml, config/common/msgrouting/serviceaccount-msgrouting.yaml, config/common/operator/role-operator.yaml, controllers/capability/routing/service.go, controllers/capability/routing/service_test.go
Looks like leftovers after #60's reviews.
=> Add missing Kubernetes objects, fix Service selector

config/samples/cr.yaml
For ActiveGates we need to inform the customer to enable the option mentioned in the comment
=> Add docu for networkZone enablement

controllers/capability/reconciler.go, controllers/capability/reconiler_test.go
deleteStatefulSetIfOldLabelsAreUsed now generally compares if the labels have changed
=> Update deleteStatefulSet to compare with desired labels

controllers/oneagent/daemonset.go, controllers/oneagent/daemonset_test.go
Set the variable `--set-host-id-source=auto` if in infra monitoring mode
=> Updated set-host-id-source parameter

api/v1alpha1/zz_generated.deepcopy.go, controllers/csi/driver/bind_config.go, controllers/csi/driver/bind_config_test.go, controllers/csi/driver/server.go, controllers/csi/driver/server_test.go, controllers/csi/driver/volume_config.go, controllers/csi/driver/volume_config_test.go
Testing NodePublishVolume function of csi/driver/server.go along with necessary refactoring
=> Test NodePublishVolume

api/v1alpha1/zz_generated.deepcopy.go, controllers/csi/driver/mount.go, controllers/csi/driver/mount_test.go
A set of unit tests for BindMount and BindUnmount functions of the CSI driver with some refactoring
=> test BindMount and BindUnmount

controllers/csi/driver/server_test.go, controllers/csi/provisioner/agent.go, controllers/csi/provisioner/agent_test.go, controllers/csi/provisioner/reconciler.go, go.mod, go.sum
Added tests for oneagent provisioner and did some refactoring
=> Testing agent provisioner

controllers/activegate/statefulset.go, controllers/activegate/statefulset_test.go
DT_DEPLOYMENT_METADATA environment variable added
=> DT_DEPLOYMENT_METADATA env var added to AG PODs

config/openshift/csi/securitycontextconstraints-csidriver.yaml, config/openshift/oneagent/securitycontextconstraints-unprivileged.yaml, config/openshift/oneagent/securitycontextconstraints.yaml
Change apiVersion for SecurityContextConstraints
=> Adapt apiVersion for SecurityContextConstraints

cmd/csidriver/main.go, controllers/csi/daemonset.go
Add readiness probe to csi driver daemonset
=> CSI driver readiness probe

controllers/csi/driver/bind_config.go, controllers/csi/driver/server.go, controllers/csi/gc/controller.go
Changed log levels from error to info in order to avoid printing unnecessary stack traces
=> Changed log levels

config/common/csi/daemonset-csi.yaml
(couldn't push to main repo for some reason)
=> Moves CSI driver content to plugins directory

Makefile, config/crd/default/bases/dynatrace.com_dynakubes.yaml, config/manifests/bases/dynatrace-operator.clusterserviceversion.yaml, config/olm/openshift/0.2.1/manifests/dynatrace-operator.v0.2.1.clusterserviceversion.yaml, config/olm/openshift/0.2.1/manifests/dynatrace.com_dynakubes.yaml, config/olm/openshift/0.2.1/metadata/annotations.yaml, config/olm/openshift/bundle-0.2.1.Dockerfile, config/olm/openshift/kustomization.yaml, config/openshift/kustomization.yaml, config/openshift/oneagent/clusterrole-oneagent-unprivileged.yaml, config/openshift/oneagent/clusterrole-oneagent.yaml, config/openshift/oneagent/clusterrolebinding-oneagent-unprivileged.yaml, config/openshift/oneagent/clusterrolebinding-oneagent.yaml
also appended makefile to do some additional configuration automatically
=> appended makefile to include extra service accounts

Makefile, build/deploy.sh, build/deploy_local.sh, cmd/operator/csi_driver.go, cmd/operator/main.go, cmd/operator/webhook_server.go, config/common/csi/daemonset-csi.yaml
Instead of having two ~50MB executables we have one ~50MB executable.
Also, some reordering, to clean it up.
=> Merges the operator and csidriver executables into one

controllers/oneagent/env_vars.go
Now we pass the proxy even if the users use the immutable image
=> Always pass the proxy to the oneagent

controllers/nodes/nodes_controller.go, controllers/nodes/nodes_controller_test.go
* Return error in case of dtclient error (timeout)
* Add unit test for error case
=> Fix missing mark for termination event

controllers/csi/daemonset_lifecycle.go
`error` should be returned last
=> Fixes lint on createCSIDaemonSet

controllers/csi/daemonset.go, controllers/csi/daemonset_test.go
csi driver now uses:
```yaml
requests:
cpu: 200m
memory: 100Mi
limits:
cpu: 200m
memory: 100Mi
```
=> Add resource requests and limits to CSI DaemonSet

controllers/csi/daemonset.go, controllers/csi/daemonset_test.go
```yaml
requests:
cpu: 50m
memory: 50Mi
limits:
cpu: 200m
memory: 100Mi
```
=> Lower csi driver resource requests

config/openshift/kustomization.yaml
=> Remove non-existing validation folder from OpenShift kustomization

troubleshoot/README.md, troubleshoot/troubleshoot.sh
Add troubleshooting script for operator setup. Checks the following:
* namespace `dynatrace` exists (name overwrite-able via parameter)
* custom resource definition exists
* custom resource `dynakube` exists (name overwrite-able via parameter)
* secret with the same name as dynakube or defined in `token` exists
* api url ends on `/api`
* secret for `customPullSecret` exists if defined
* tenant is reachable from operator pod
* using same parameters as operator (proxy, certificate, ...)
* image is reachable from operator pod
* using registry from (custom) pull secret, or docker hub
Add instructions on usage in `/troubleshoot`
=> Add troubleshoot script

controllers/certificates/webhook_reconciler.go, controllers/certificates/webhook_reconciler_test.go
* Check webhook configurations for certificate (and not just secret)
* Add unit test to check scenario
=> Fix webhook certificates with existing secret

api/v1alpha1/zz_generated.deepcopy.go, config/crd/default/bases/dynatrace.com_dynakubes.yaml, config/crd/ocp311/bases/dynatrace.com_dynakubes.yaml, controllers/csi/daemonset.go, controllers/csi/daemonset_test.go
* Improve QoS for CSI Driver by setting same values on limits/requests (same as: #224)
* Update manifests to match code
=> Set resource limits/requests for csi daemonset to same values

controllers/csi/driver/bind_config.go, controllers/csi/driver/server.go, controllers/csi/gc/controller.go, controllers/csi/metadata/correctness.go, controllers/csi/metadata/correctness_test.go, controllers/csi/metadata/fakes.go, controllers/csi/metadata/metadata.go, controllers/csi/metadata/sqlite.go, controllers/csi/metadata/sqlite_test.go, controllers/csi/provisioner/agent.go, controllers/csi/provisioner/agent_test.go, controllers/csi/provisioner/reconciler.go, controllers/csi/provisioner/reconciler_test.go, controllers/dynakube/dtclient_builder.go, controllers/dynakube/dtclient_builder_test.go, controllers/dynakube/dtclient_reconciler.go, controllers/dynakube/dynakube_controller.go, controllers/dynakube/dynakube_controller_test.go
* Fix duplicate Dynakubes with same Tenant monitoring different namespace
=> Change tenant primary key to Dynakube

controllers/oneagent/daemonset/daemonset.go, controllers/oneagent/oneagent_controller_test.go, integrationtests/oneagent_controller_integration_test.go
(cherry picked from commit e88d9d417336e1cef72ee966de44a2ec667de45a)
=> Removed deploymentType name from DaemonSet and pod name

config/samples/applicationMonitoring.yml, config/samples/cloudNativeFullstack.yml
(cherry picked from commit 0b3a52c00252b0fc123e0eb7b38447e057e6cd0b)
=> Add limitation of namespaceSelector to samples

mapper/dynakubes.go, webhook/validation/validation.go, webhook/validation/validation_test.go
(cherry picked from commit 2eccff8a303e1cad21b5eef30fb1ed24dfa4e913)
=> Adds namespaceSelector conflict validation check

controllers/kubeobjects/daemonset.go
(cherry picked from commit 36772453e1dd0571f47a4ca910ef44c0313af3c5)
=> Update misleading log message

controllers/oneagent/oneagent_controller.go
(cherry picked from commit 736d7d5330a9ae6bdcb14f1eb24d696c7a87de69)
=> Remove old classic daemonset if exists

.travis.yml
(cherrypick of https://github.com/Dynatrace/dynatrace-operator/pull/346)
=> Removes expire on release branch images

.travis.yml
* Remove arm build for snapshots
* Update expression to exclude snapshots build on release branch
=> Update travis to remove expiration date

.travis.yml
* Replaces `snapshot-release-0.3` with `snapshot-release-0-3` for release branch image
=> Adjust release branch image

config/crd/default/patches/webhook_in_dynakubes.yaml
same as https://github.com/Dynatrace/dynatrace-operator/pull/360
=> Adds preserveUnknownFields to webhook patch

README.md, config/samples/applicationMonitoring.yml, webhook/validation/validation.go, webhook/validation/validation_test.go
Cherry pick from this [PR](https://github.com/Dynatrace/dynatrace-operator/pull/363)
=> Adjust usage of beta label on release branch

api/v1beta1/properties.go, controllers/csi/metadata/fakes.go, controllers/csi/metadata/path_resolver.go, controllers/csi/metadata/sqlite_test.go, controllers/csi/provisioner/agent.go, controllers/csi/provisioner/processmoduleconfig.go, controllers/csi/provisioner/processmoduleconfig_test.go, controllers/csi/provisioner/reconciler.go, controllers/csi/provisioner/reconciler_test.go, dtclient/client.go, dtclient/mock_client.go, dtclient/processmoduleconfig.go, dtclient/processmoduleconfig_test.go, initgeneration/init.sh.test-sample, initgeneration/init.sh.tmpl, initgeneration/initgeneration.go, initgeneration/initgeneration_test.go, processmoduleconfig/update.go, processmoduleconfig/update_test.go
Cherry picks of
1. https://github.com/Dynatrace/dynatrace-operator/pull/366
2. https://github.com/Dynatrace/dynatrace-operator/pull/375
3. https://github.com/Dynatrace/dynatrace-operator/pull/381
=> Adds ruxitagentproc.conf update mechanism (+ hostGroup injection) for CSI driver

README.md
Cherry Pick from https://github.com/Dynatrace/dynatrace-operator/pull/373
=> Update support matrix 0.3.0

controllers/csi/provisioner/processmoduleconfig.go
cherry-pick of: https://github.com/Dynatrace/dynatrace-operator/pull/383
=> Checks if the hostgroup is present before adding (#383)

cmd/operator/csi_driver.go, controllers/csi/driver/config.go, controllers/csi/driver/server.go, controllers/csi/driver/server_test.go, controllers/csi/gc/binaries.go, controllers/csi/gc/binaries_test.go, controllers/csi/gc/config.go, controllers/csi/gc/controller.go, controllers/csi/gc/logs.go, controllers/csi/metadata/config.go, controllers/csi/metadata/correctness.go, controllers/csi/metadata/correctness_test.go, controllers/csi/metadata/sqlite.go, controllers/csi/provisioner/agent.go, controllers/csi/provisioner/agent_test.go, controllers/csi/provisioner/config.go, controllers/csi/provisioner/processmoduleconfig.go, controllers/csi/provisioner/processmoduleconfig_test.go, controllers/csi/provisioner/reconciler.go
Moves logger to the `config.go` in each package, and have the logger on a per package level.
Also log messages should always start with lowercase.
=> Refactors logging in the csi packages

troubleshoot/troubleshoot.sh
Updating the activeGate section like it was previously done with the oneagent section.
=> Add support for managed tenants

build/release.sh
=> Explicitly use bash in release script

config/common/csi/clusterrole-csi.yaml, config/common/csi/role-csi.yaml, config/common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml, config/common/operator/role-operator.yaml, config/common/webhook/clusterrole-webhook.yaml
(operator cluster role is not present, updated in other PR https://github.com/Dynatrace/dynatrace-operator/pull/398)
=> Unifies yaml role formats

CONTRIBUTING.md
Any suggestions are welcome :)
=> Adds coding style guide to CONTRIBUTING.md

README.md
Update readme to point at correct samples
=> Update readme to point at correct samples

README.md
Using a link to a specific branch causes problems on other branches.
=> Use relative path for samples

build/deploy_local.sh
Removes licenses from local build to save build time on dev machine
=> Remove licenses from local build

.gitignore, Makefile, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, src/cmd/operator/main.go, src/cmd/operator/operator.go, src/cmd/operator/webhook.go
this is a draft till https://github.com/Dynatrace/dynatrace-operator/pull/430 is merged
=> Disables cert generation incase of OLM deployment

src/api/v1beta1/feature_flags.go, src/controllers/dynakube/dynakube_controller.go, src/ingestendpoint/secret.go, src/ingestendpoint/secret_test.go, src/webhook/mutation/pod_mutator.go
The new feature flag overrules the pod annotation to enable/disable metadata enrichment.
=> Adds dynakube feature flag to disable metadata enrichment

.golangci.yml, config/crd/bases/dynatrace.com_dynakubes.yaml, config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, src/api/v1beta1/dynakube_status.go, src/api/v1beta1/dynakube_types.go, src/controllers/dynakube/dtclient_reconciler.go, src/controllers/dynakube/dtclient_reconciler_test.go, src/controllers/dynakube/dynakube_controller_test.go, src/dtclient/client.go, src/dtclient/tenant.go
#461 #466
(cherrypicked from 6d54d36baf60fda9978dc2e6d45756af0e9b3fdb, 70fe98df4a9055ce8e0f7f0aa2a19d6b6f4384df)
=> Add missing token scope checks

src/api/v1beta1/feature_flags.go, src/mapper/mapper.go
#453
(cherry picked from commit ee1d5ee87e587514f033b237734510159132b928)
=> Allow monitoring of operator namespace via feature flag

Makefile, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, src/api/v1alpha1/zz_generated.deepcopy.go, src/api/v1beta1/zz_generated.deepcopy.go, src/cmd/operator/main.go, src/cmd/operator/operator.go, src/cmd/operator/webhook.go, src/controllers/dynakube/oneagent/daemonset/arguments_test.go, src/controllers/dynakube/oneagent/daemonset/daemonset.go, src/controllers/dynakube/oneagent/daemonset/env_vars.go, src/controllers/dynakube/oneagent/daemonset/volumes_test.go, src/kubesystem/kubesystem.go
#440
(cherry picked from commit fc19af6f8e97b4ba2489193511780a24c6a315b0)
=> Remove RELATED_IMAGE environment variable for OLM

.github/workflows/ci.yml, Makefile, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/testing/lint.sh, config/helm/testing/test.sh
#459 #460
(cherrypicked from 242a882c48c0cefabd47c685bc13e99eac275add, 390bd56dcf8c1af9d1967189ecc9b5125fdb009b)
=> Improve helm commands, Add linting/unit tests for helm manifests

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/customresource-dynakube.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/secret.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/tests/Common/customresource-modules/customresource-dynakube_applicationmonitoring_test.yaml, config/helm/chart/default/tests/Common/customresource-modules/customresource-dynakube_cloudnativefullstack.yaml, config/helm/chart/default/tests/Common/customresource-modules/customresource-dynakube_hostmonitoring_test.yaml, config/helm/chart/default/values.yaml
Cherry-pick of https://github.com/Dynatrace/dynatrace-operator/pull/484
=> Brings helm up-to-speed

src/dtclient/agent_version.go, src/dtclient/communication_hosts.go, src/dtclient/dynatrace_client.go, src/dtclient/endpoints.go, src/dtclient/kubernetes_settings.go, src/dtclient/processmoduleconfig.go, src/dtclient/send_event.go, src/dtclient/tenant.go, src/dtclient/token.go
All dtclient enpoints that we use now are present in 1 place so its easier to see what we use
=> Moves all the dtclient enpoints into one place

config/helm/chart/default/Chart.yaml, config/helm/chart/default/README.md, config/helm/chart/default/questions.yml, config/helm/chart/default/templates/application.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/schema.yaml
Cherrypick 933d69a430a3f842bc5b26ea40a2f6d77c56163b from release branch back to master
=> Updates version related files for helm

README.md
Cherrypick 3a8937648fbc408a884f392cba8000b26d09b29a from release branch to master
=> Adapt readme for v0.4.0 changes

src/webhook/config.go, src/webhook/mutation/pod_mutator.go
Allow different flavor per pod when downloading installer per pod.
=> Add flavor pod annotation

src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynakube_controller_test.go
#505 
(cherrypick of commit 290b87df16f0e77d1653c1072d608e1c059eb1a8)
=> Fix daemonset deletion issue

src/controllers/dynakube/dtclient_reconciler.go, src/controllers/dynakube/dtclient_reconciler_test.go, src/dtclient/client.go, src/dtclient/kubernetes_settings.go
- Fixes a bug when trying to unmarshal an error response while creating a settings object
- Improves the log message for unauthorized or forbidden api access
=> Add missing scopes for automatic API monitoring

src/controllers/dynakube/dtclient_reconciler.go, src/controllers/dynakube/dtclient_reconciler_test.go, src/dtclient/client.go, src/dtclient/kubernetes_settings.go
* Automatic API monitoring bugfix
- Fixes a bug when trying to unmarshal an error response while creating a settings object
- Adds formatting and removes unnecessary log info
(cherry picked from commit dbe81faf646cdfa74eb1c982f65a37c20c91f12a)
=> Update required scopes for automatic api monitoring

.github/workflows/ci.yml, Dockerfile, build/deploy_local.sh
(cherry picked from commit 01a91c796c591e16f0ca622b06919fa9960d0b4d)
=> Include build information in image

.github/workflows/ci.yml
* non-existant variable was referenced
=> Fix branch check for master branch

src/controllers/dynakube/dtclient_reconciler.go, src/controllers/dynakube/dtclient_reconciler_test.go, src/controllers/dynakube/dynakube_controller_test.go, src/dtclient/client.go, src/testing/e2e/integrationtests/envutils_test.go
cherry pick from: https://github.com/Dynatrace/dynatrace-operator/pull/548
=> Removes unnecessary scopes for API Token

.github/workflows/ci.yml
(cherrypicked from b1f2b183050ab5a780f21384d7e5ee7c5178d351 and 6804aeacd9e9a07749bb84d078b160ee18593a91)
=> Fix image version for CI build

src/agproxysecret/secret.go
(cherry picked from commit b91a86cdc3a6d6bd0f1ea3eb7514589794da2912)
=> Change logging condition

src/ingestendpoint/secret.go, src/webhook/mutation/pod_mutator.go, src/webhook/mutation/pod_mutator_test.go
Co-authored-by: adam.orcholski <adam.orcholski@dynatrace.com>
(cherry picked from commit ab3e33677941fe3e49997371fa5140008e6a2291)
=> Secret reference instead of plain text

config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml
Replace equals check for `metadata` with specific equals check for `name` and `namespace` and contains for the labels.
=> Remove version from helm unittest

config/helm/chart/default/Chart.yaml, config/helm/schema.yaml, config/olm/kubernetes/0.4.2/manifests/dynatrace-activegate_v1_serviceaccount.yaml, config/olm/kubernetes/0.4.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, config/olm/kubernetes/0.4.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, config/olm/kubernetes/0.4.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, config/olm/kubernetes/0.4.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, config/olm/kubernetes/0.4.2/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, config/olm/kubernetes/0.4.2/manifests/dynatrace-operator.clusterserviceversion.yaml, config/olm/kubernetes/0.4.2/manifests/dynatrace-webhook_v1_service.yaml, config/olm/kubernetes/0.4.2/manifests/dynatrace.com_dynakubes.yaml, config/olm/kubernetes/0.4.2/metadata/annotations.yaml, config/olm/kubernetes/bundle-0.4.2.Dockerfile, config/olm/openshift/0.4.2/manifests/dynatrace-activegate_v1_serviceaccount.yaml, config/olm/openshift/0.4.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, config/olm/openshift/0.4.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, config/olm/openshift/0.4.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, config/olm/openshift/0.4.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, config/olm/openshift/0.4.2/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, config/olm/openshift/0.4.2/manifests/dynatrace-operator.clusterserviceversion.yaml, config/olm/openshift/0.4.2/manifests/dynatrace-webhook_v1_service.yaml, config/olm/openshift/0.4.2/manifests/dynatrace.com_dynakubes.yaml, config/olm/openshift/0.4.2/metadata/annotations.yaml, config/olm/openshift/bundle-0.4.2.Dockerfile
#571
(cherrypicked from `release-0.4` branch: 751ed76a6cb501cc9883992e072cd31044b6213f)
=> Add v0.4.2 CSV files

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/csi/role-csi.yaml
* Remove duplicate `securityContext` in daemonset
* Remove incorrect character in Role
=> Fix CSI driver daemonset

src/api/v1beta1/properties.go, src/api/v1beta1/properties_test.go, src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynakube_controller_test.go, src/controllers/dynakube/oneagent/daemonset/daemonset.go, src/controllers/dynakube/oneagent/oneagent_reconciler.go, src/controllers/dynakube/oneagent/oneagent_reconciler_test.go, src/testing/e2e/integrationtests/envutils_test.go, src/testing/e2e/integrationtests/oneagent_controller_integration_test.go
(Cherry-picked commit 3b75dad99696a0fcad853c33ee21fdd0016b6ae7 from #614)
=> Fix phase field not updating

Dockerfile, config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/csi/daemonset.yaml
=> Update livenessprobe/registrar binaries

Makefile, PROJECT, config/helm/chart/default/templates/Common/operator/clusterrole-operator.yaml, config/helm/chart/default/templates/Common/webhook/clusterrole-webhook.yaml, config/manifests/bases/dynatrace-operator.clusterserviceversion.yaml, src/api/v1beta1/activegate_types.go, src/api/v1beta1/dynakube_types.go
Cherrypick of: https://github.com/Dynatrace/dynatrace-operator/pull/633
Please include some guiding steps on how to test this change during a review.
See original PR
=> Cherrypick: Adapt Makefile to exclude CSI and add v1beta1 changes to CSV 

config/samples/applicationMonitoring.yaml, config/samples/classicFullStack.yaml, config/samples/cloudNativeFullStack.yaml, config/samples/hostMonitoring.yaml, config/samples/multipleDynakubes.yaml
Updating our sample files to include default resources for activate gate containers.
Apply a sample file and check if resources are set on the active gate containers.
=> Add default limits to sample yamls

Makefile, config/deploy/openshift/openshift-all.yaml
#696
(cherry picked from commit 11a025e)
=> Readd csi driver to openshift manifests

src/cmd/operator/main.go
cherry-pick of https://github.com/Dynatrace/dynatrace-operator/pull/715
see original pr
=> Gets kubeconfig only when subcommand needs it

.github/workflows/codeql-analysis.yml
Update CodeQL action:
* explicitly add required write scopes
* update actions to v2
CodeQL action is triggered and reports results correctly
=> Update CodeQL action with required scopes

src/controllers/csi/provisioner/processmoduleconfig.go, src/controllers/csi/provisioner/processmoduleconfig_test.go
#734 
Same behavior as described in #734
=> Correct handling of revision.json file

src/api/v1beta1/feature_flags.go, src/api/v1beta1/properties.go, src/controllers/activegate/reconciler/statefulset/statefulset.go, src/controllers/activegate/reconciler/statefulset/statefulset_test.go, src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynakube_controller_test.go, src/controllers/dynakube/oneagent/daemonset/arguments.go, src/controllers/dynakube/oneagent/daemonset/arguments_test.go
#737 
Same behavior as described in #737
=> Add feature flag for proxy usage on oneAgent and activeGate

config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml
cherry-pick of https://github.com/Dynatrace/dynatrace-operator/pull/747
=> Fixed invalid value in (.Values.webhook).highAvailability (#747)

.github/workflows/ci.yml
=> Build arm image on tag

config/deploy/kubernetes/kustomization.yaml, config/deploy/openshift/openshift-all.yaml
see: #771
`make test`
`./hack/helm/test.sh`
=> Clean up leftovers

config/helm/chart/default/questions.yml, config/helm/chart/default/templates/_helpers.tpl, config/helm/chart/default/tests/Common/csi/clusterrole-csi_test.yaml, config/helm/chart/default/tests/Common/csi/clusterrolebinding-csi_test.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/tests/Common/csi/role-csi_test.yaml, config/helm/chart/default/tests/Common/csi/rolebinding-csi_test.yaml, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/chart/default/values.yaml, config/helm/schema.yaml, hack/make/manifests/kubernetes.mk, hack/make/manifests/openshift.mk
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/823
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/823
=> Rename `.Values.operator.image` to `.Values.image` (#823)

README.md, config/helm/chart/default/README.md
Providing a support matrix is misleading when our official stance is either N-2 or 9 months whichever is longest.
Replaced with support lifecycle describing this change.
=> Update support lifecycle

src/api/v1beta1/feature_flags.go, src/api/v1beta1/properties.go, src/controllers/dynakube/oneagent/daemonset/daemonset.go
cherry-pick of #827 
cherry-pick of #827
=> Added feature flag to run oneagent as privileged (#827)

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/Chart.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/836
same as https://github.com/Dynatrace/dynatrace-operator/pull/836
=> Adds default tolerations for the csi driver

config/helm/chart/default/generated/dynatrace-operator-crd.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrole-oneagent-unprivileged.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrolebinding-oneagent-unprivileged.yaml, config/helm/chart/default/templates/_helpers.tpl, config/manifests/bases/dynatrace-operator.clusterserviceversion.yaml, config/olm/README.md, hack/build/bundle.sh, hack/make/bundle.mk, hack/setup_olm_catalog.sh
(cherry picked from commit f5c35a005e05db84a4a4427b4d71053152ee3aff and 8146c58d52856ee24276761e92a6ae9e051accc0)
=> Update Bundle for Kubernetes and supported versions

src/initgeneration/initgeneration.go, src/initgeneration/initgeneration_test.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/839
same as https://github.com/Dynatrace/dynatrace-operator/pull/839
=> Readds separate proxy key to the init secret

README.md
Update CSI driver requirement for host monitoring.
=> Update host monitoring requirements

.github/workflows/publish-images.yaml
When tag is created on a release branch with the right format, the images are published to all supported registries.
Create a tag
=> Add image publish release workflow

.github/workflows/publish-images.yaml
RHCC secret access is invalid.
=> Remove RHCC from image release workflow

.gitignore, hack/build/bundle.sh, hack/make/manifests/config.mk, hack/make/manifests/kubernetes.mk
Cherry Pick of #848
Same as #848
=> Adapt makefile for release and fix minor issue with bundle command

CONTRIBUTING.md
Adds contribution guidelines for error handling to implement a consistent style that makes sure useful stacktraces are generated in the event of important failures.
* Reading the contribution guidelines and checking for grammar-, spelling- or semantic mistakes.
* Making sure everyone agrees to the amendment
=> Adds contribution guidelines for error handling

src/standalone/files.go
cherry-pick of https://github.com/Dynatrace/dynatrace-operator/pull/877
same as 
=> Remove unnecessary char in `container.conf`

src/standalone/config.go, src/standalone/env.go, src/standalone/env_test.go, src/standalone/run.go
(cherrypick from commit 0922708994b5d1c70e6276c9ea5a9c0e09918aef)
=> Fix arch used in standalone binary download

.gitignore, config/helm/chart/default/generated/dynatrace-operator-crd.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/templates/_helpers.tpl, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, hack/make/manifests/config.mk, hack/make/manifests/kubernetes.mk
cherry-pick of https://github.com/Dynatrace/dynatrace-operator/pull/881
same https://github.com/Dynatrace/dynatrace-operator/pull/881
=> Adds google-autopilot as a new platform to helm 

src/controllers/csi/provisioner/agent.go, src/controllers/dynakube/version/version.go, src/dockerconfig/docker_config.go, src/dockerconfig/docker_config_test.go, src/dockerconfig/system_context.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/888
same as https://github.com/Dynatrace/dynatrace-operator/pull/888
=> Reworks dockerConfig auth setup 

src/standalone/files.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/890
same as https://github.com/Dynatrace/dynatrace-operator/pull/890
=> Changes codemodules container.conf file's filemode

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/webhook/poddisruptionbudget-webhook.yaml
cherry-pick of https://github.com/Dynatrace/dynatrace-operator/pull/896
same as https://github.com/Dynatrace/dynatrace-operator/pull/896
=> Adds namespace to PodDistruptionBudget

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/generated/dynatrace-operator-crd.yaml, config/helm/chart/default/templates/Openshift/activegate/securitycontextconstraints.yaml, config/helm/chart/default/templates/Openshift/oneagent/securitycontextconstraints-unprivileged.yaml, config/helm/chart/default/templates/Openshift/operator/securitycontextconstraints.yaml, config/helm/chart/default/templates/Openshift/webhook/securitycontextconstraints.yaml, config/helm/chart/default/tests/Openshift/oneagent/securitycontextconstraints-unprivileged_test.yaml
Replace `priority` for SecurityContextConstraints with `null`.
Successful deployment on Openshift
=> Set priority to null for SCCs

hack/make/bundle.mk
=> Split bundle step for different platforms

src/standalone/env.go, src/webhook/mutation/pod_mutator.go, src/webhook/mutation/pod_mutator_test.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/898
same as https://github.com/Dynatrace/dynatrace-operator/pull/898
=> Uses arch.Flavor when annotation is not set

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/kubernetes/kustomization.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/csi/role-csi.yaml, config/helm/chart/default/tests/Common/csi/role-csi_test.yaml, src/controllers/dynakube/dynakube_controller.go, src/dockerconfig/docker_config.go, src/dockerconfig/docker_config_test.go
Cherry pick of #909 
Same is in #909
=> Fix usage of trustedCAs 

Dockerfile, hack/build/create_go_build_args.sh, hack/build/push_image.sh
Musl libraries for the right architecture are copied to the target docker image.
Linker parameters are surrounded by question marks.
Docker images should be executable on appropriate platforms.
[x] PR is labeled accordingly
[x] I have read and understood the [contribution guidelines](https://github.com/CONTRIBUTING.md)
=> Use ARM libraries in ARM docker image

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml
Cherry-pick #938 from `release-0.7` to `master`
=> Add `labelSelector` to webhook's `topologySpreadConstraints`

config/helm/chart/default/Chart.yaml
Adds kubeversion to helm chart
=> Adds kubeversion to helm chart

config/helm/chart/default/Chart.yaml
Adds the kubeversion property to the Helm Chart yaml
=> Adds kubeversion to chart yaml

src/controllers/dynakube/dynakube_controller.go, src/controllers/dynakube/dynakube_controller_test.go, src/controllers/dynakube/istio/reconciler.go, src/controllers/dynakube/istio/reconciler_test.go, src/dtclient/communication_hosts.go, src/dtclient/communication_hosts_test.go, src/testing/e2e/integrationtests/istio_integration_test.go
Same as https://github.com/Dynatrace/dynatrace-operator/pull/955
Same as https://github.com/Dynatrace/dynatrace-operator/pull/955
=> Fixes Istio reconciliation depending on a token check that depends on Istio reconciliations

config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Openshift/activegate/securitycontextconstraints.yaml, config/helm/chart/default/templates/Openshift/csi/securitycontextconstraints-csidriver.yaml, config/helm/chart/default/templates/Openshift/oneagent/securitycontextconstraints-privileged.yaml, config/helm/chart/default/templates/Openshift/oneagent/securitycontextconstraints-unprivileged.yaml, config/helm/chart/default/templates/Openshift/operator/securitycontextconstraints.yaml, config/helm/chart/default/templates/Openshift/webhook/securitycontextconstraints.yaml, config/helm/chart/default/tests/Openshift/oneagent/securitycontextconstraints-unprivileged_test.yaml
Sets priority to 1 for the SCCs
Deploy on openshift
=> Sets priority to 1 for the SCCs

config/helm/repos/stable/index.yaml
Adds the 0.7.2 release to the master index.yaml
Can only be tested by installing the Chart after this PR has been merged
=> Updates index.yaml for 0.7.2

assets/samples/applicationMonitoring.yaml, assets/samples/classicFullStack.yaml, assets/samples/cloudNativeFullStack.yaml, assets/samples/hostMonitoring.yaml
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/982
same as https://github.com/Dynatrace/dynatrace-operator/pull/982
=> Updates samples for codeModulesImage

src/controllers/csi/gc/controller.go, src/controllers/csi/gc/controller_test.go, src/controllers/csi/provisioner/controller.go, src/controllers/csi/provisioner/controller_test.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/981
same as https://github.com/Dynatrace/dynatrace-operator/pull/981
=> Adds extra safety check for csi GC

assets/samples/cloudNativeFullStack.yaml
Updates the descriptions of the properties of the cloudnative fullstack  Dynakube custom resource example
to reflect the latest changes.
Proofread the comments
=> Updates cloudnative fullstack Dynakube custom resource example

assets/samples/cloudNativeFullStack.yaml
(cherry picked from commit 663bb9a7ab4af057b45f8fe153fa5a96db6ddfc0)
see https://github.com/Dynatrace/dynatrace-operator/pull/999
see https://github.com/Dynatrace/dynatrace-operator/pull/999
=> Updates cloudnative fullstack Dynakube custom resource example (#999)

src/controllers/csi/provisioner/controller.go
see https://github.com/Dynatrace/dynatrace-operator/pull/1014
see https://github.com/Dynatrace/dynatrace-operator/pull/1014
+ csi priovisioner needs to be refactored to allow for sensible unit tests
=> fixes using incomplete connection info (#1014)

.gitignore, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/templates/_helpers.tpl, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/chart/default/tests/Google/application_test.yaml, config/helm/chart/default/values.yaml, hack/make/deploy/gcr.mk, hack/make/manifests/config.mk, hack/make/manifests/kubernetes.mk
=> Renames helm-chart platform value google-marketplace to gke-marketplace (#1016)

.github/workflows/publish-images.yaml
Authentication to GCR via Service Account.
See [successful run on fork](https://github.com/chrismuellner/dynatrace-operator/actions/runs/2788882017)
=> Update build jobs and configure GCR registry

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/Common/csi/priority-class.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml
=> Add priority class to csi pods

.github/workflows/publish-images.yaml
Matrix condition incorrectly used strings.
Create tag on branch.
=> Fix matrix for publish images action

.github/workflows/publish-images.yaml
=> Fix `needs` for manifest step

.github/workflows/publish-images.yaml
Update matrix names for other registries correctly
=> Fix matrix names for other registries

.github/workflows/publish-images.yaml
Access repositories from secret
=> Load repositories from secrets

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml
Cherry Pick of #1064 
Same as #1064
=> Ensure csi driver availability on node scale-down

assets/samples/cloudNativeFullStack.yaml
=> Small typo

Dockerfile
Cherry Pick of #1065 
Same as #1065
=> Upgrade to ubi9-micro as base image

src/controllers/csi/provisioner/processmoduleconfig.go, src/installer/url/config.go, src/installer/url/installer.go, src/installer/url/installer_test.go, src/installer/zip/zip.go, src/standalone/run.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/1077
same as https://github.com/Dynatrace/dynatrace-operator/pull/1077
=> Make extractor handle standalone usecase (#1077)

src/config/enrichment_injection.go, src/standalone/env.go, src/standalone/env_test.go, src/standalone/run_test.go, src/webhook/mutation/pod_mutator/dataingest_mutation/workload.go, src/webhook/mutation/pod_mutator/dataingest_mutation/workload_test.go
=> Set empty workload kind/name on unknown owner (#1074)

src/controllers/dynakube/activegate/statefulset/statefulset.go
=> Fix custom activegate labels in Dynakube

src/cmd/main.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/1104
same as https://github.com/Dynatrace/dynatrace-operator/pull/1104
=> Readds the version log to the top of the logs (#1104)

config/crd/bases/dynatrace.com_dynakubes.yaml, config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/generated/dynatrace-operator-crd.yaml
Just ran `make manifests`. The manifests are outdated on master.
Not really necessary
=> Updates manifests

config/manifests/bases/dynatrace-operator.clusterserviceversion.yaml
Cherry pick of #1154
Same as #1154
=> Add suggested namespace annotation

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/operator/deployment-operator.yaml, config/helm/chart/default/templates/Common/webhook/deployment-webhook.yaml, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml
cherry pick of #1156 
same as  #1156
=> Makes ephemeral-storage configurable 

src/mapper/mapper.go, src/mapper/mapper_test.go
cherry-pick of https://github.com/Dynatrace/dynatrace-operator/pull/1162
same as https://github.com/Dynatrace/dynatrace-operator/pull/1162
=> Fixes check for ignored namespaces

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/questions.yml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml, config/helm/schema.yaml
=> Make csi limits and resources configurable with helm

src/controllers/csi/driver/volumes/app/publisher.go
cherry pick of  #1189
same as #1189
=> Safer check for dummy volume (#1189)

src/controllers/dynakube/dtclient_reconciler.go
cherry-pick of https://github.com/Dynatrace/dynatrace-operator/pull/1220
same as https://github.com/Dynatrace/dynatrace-operator/pull/1220
=> Only require the activeGate token scope if activeGates are used

src/controllers/csi/provisioner/controller.go, src/controllers/csi/provisioner/controller_test.go
=> Update `ruxitagentproc.conf` file only for cloud native and application monitoring 

config/deploy/kubernetes/kubernetes-all.yaml, config/deploy/openshift/openshift-all.yaml, config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/templates/_csidriver.tpl, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, src/controllers/csi/driver/server.go, src/controllers/csi/metadata/correctness.go, src/controllers/csi/metadata/metadata.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/1252
same as https://github.com/Dynatrace/dynatrace-operator/pull/1252
=> Fix csi-driver stuck in terminating after restart

src/installer/zip/gzip.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/1257
same as https://github.com/Dynatrace/dynatrace-operator/pull/1257
=> Respects folder fileMode during gzip unzip

Dockerfile
With this constant labels regarding the operator are added to the Dockerfile.
=> Update constant labels of operator docker image

src/cmd/troubleshoot/builder.go, src/cmd/troubleshoot/checks.go, src/cmd/troubleshoot/checks_test.go, src/cmd/troubleshoot/connection.go, src/cmd/troubleshoot/context.go, src/cmd/troubleshoot/dynakube.go, src/cmd/troubleshoot/dynakube_test.go, src/cmd/troubleshoot/errors/aggregated.go, src/cmd/troubleshoot/image.go, src/cmd/troubleshoot/logger.go, src/cmd/troubleshoot/namespace.go, src/functional/filter.go, src/functional/filter_test.go, src/functional/map.go, src/functional/map_test.go
Cherry-pick of #1314 
As in #1314 
=> Let troubleshooting command continue execution until unrecoverable error is found

src/standalone/env.go, src/standalone/env_test.go
(cherry picked from commit ff59d1f574ff198dd57a4224a18ebbae13bec2e1)
Same as (https://github.com/Dynatrace/dynatrace-operator/pull/1345)[https://github.com/Dynatrace/dynatrace-operator/pull/1345]
Same as (https://github.com/Dynatrace/dynatrace-operator/pull/1345)[https://github.com/Dynatrace/dynatrace-operator/pull/1345]
=> Adds missing properties for data enrichment (#1345)

src/cmd/troubleshoot/builder.go, src/cmd/troubleshoot/builder_test.go, src/cmd/troubleshoot/checks.go, src/cmd/troubleshoot/checks_test.go, src/cmd/troubleshoot/config.go, src/cmd/troubleshoot/connection.go, src/cmd/troubleshoot/context.go, src/cmd/troubleshoot/crd.go, src/cmd/troubleshoot/dynakube.go, src/cmd/troubleshoot/dynakube_test.go, src/cmd/troubleshoot/image.go, src/cmd/troubleshoot/image_test.go, src/cmd/troubleshoot/logger.go, src/cmd/troubleshoot/namespace.go, src/cmd/troubleshoot/namespace_test.go, src/cmd/troubleshoot/proxy.go, src/cmd/troubleshoot/proxy_test.go, src/kubeobjects/dynakube.go
Cherrypicked #1349 
Cherrypicked #1349
=> Add support for checking all dynakubes in troubleshoot subcommand

src/controllers/csi/gc/unmounted.go
Same as https://github.com/Dynatrace/dynatrace-operator/pull/1353
Same as https://github.com/Dynatrace/dynatrace-operator/pull/1353
=> Lower csi gc interval

Dockerfile
=> Update CSI registrar to v2.6.1 (#1356)

assets/samples/applicationMonitoring.yaml, assets/samples/classicFullStack.yaml, assets/samples/cloudNativeFullStack.yaml, assets/samples/hostMonitoring.yaml
Our sample CRs are missing some fields which are in the CRD. 
This PR adds them.
Look onto the sample yamls.
=> Update CR samples to contain all CRD fields

assets/samples/applicationMonitoring.yaml, assets/samples/classicFullStack.yaml, assets/samples/cloudNativeFullStack.yaml, assets/samples/hostMonitoring.yaml
=> Update CR samples to contain all CRD fields (#1364)

.github/workflows/publish-images.yaml
Need to due changes with https://github.com/Dynatrace/dynatrace-operator/pull/1367
=> Move preflight check after manifest creation

src/controllers/csi/gc/reconciler.go, src/controllers/csi/gc/reconciler_test.go
in case the latest version was not set in the dynakube for the paas agent then the CSI gc ran into a nil pointer exception.
Added a unit test for it, but the codemodules e2e tests could also reproduce it
=> Fix possible nil pointer in GC

src/api/v1beta1/feature_flags.go, src/controllers/dynakube/connectioninfo/reconciler.go, src/controllers/dynakube/connectioninfo/reconciler_test.go, src/controllers/dynakube/oneagent/daemonset/arguments.go, src/controllers/dynakube/oneagent/daemonset/arguments_test.go, src/controllers/dynakube/oneagent/daemonset/volumes.go, src/controllers/dynakube/oneagent/daemonset/volumes_test.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/1381
same as https://github.com/Dynatrace/dynatrace-operator/pull/1381
=> Removes the oneagent immutable image feature-flag (#1381)

src/controllers/csi/gc/reconciler.go, src/controllers/csi/provisioner/controller.go, src/controllers/csi/provisioner/controller_test.go
cherry pick of #1384
same as #1384
=> Fixes hostMonitoring mode with csi volume (#1384)

assets/samples/applicationMonitoring.yaml, assets/samples/classicFullStack.yaml, assets/samples/cloudNativeFullStack.yaml, assets/samples/hostMonitoring.yaml
Samples have redundant description for some of the parameters, e.g. `Add additional ...`
=> Update annotation description in dynakube samples

src/controllers/csi/driver/volumes/app/publisher.go, src/controllers/csi/driver/volumes/app/publisher_test.go
Cherrypick of #1401 
Same as #1401
=> Unmount agent volume incase of failed db call when mounting

assets/samples/applicationMonitoring.yaml, assets/samples/classicFullStack.yaml, assets/samples/cloudNativeFullStack.yaml, assets/samples/hostMonitoring.yaml
=> Update annotation description in dynakube samples (#1402)

config/helm/chart/default/Chart.yaml
Needed for the next release
No need to
=> Adapt Chart.yaml for release of 0.10.1

.github/workflows/publish-images.yaml
=> Add dynamic docker labels on release (#1407)

.github/actions/preflight/action.yaml, .github/actions/upload-image/action.yaml, .github/workflows/publish-images.yaml, hack/build/ci/preflight.sh, hack/build/ci/upload-docker-image.sh
=> [0.10] Remove platform suffix from RHCC release image (#1440)

assets/samples/applicationMonitoring.yaml, assets/samples/classicFullStack.yaml, assets/samples/cloudNativeFullStack.yaml, assets/samples/hostMonitoring.yaml
just some small fixes for the samples
read the samples, check if you understand it (and that it is actually correct english 😄 )
=> Fixes some wording and typos in the samples

README.md
Support lifecycle documented on Github should match the official documentation or link to it.
=> Fix support lifecycle documentation

.github/pull_request_template.md, .github/workflows/ci.yaml, .github/workflows/codeql-analysis.yaml, .github/workflows/openssf-scorecards.yaml, config/helm/chart/default/README.md, hack/make/images.mk, hack/make/manifests/config.mk, hack/make/manifests/kubernetes.mk, hack/make/manifests/manifests.mk, hack/make/manifests/openshift.mk, hack/troubleshoot/README.md
Default branch was updated from `master` to `main` everywhere it was used:
* Replaced default version for `main` branch with `snapshot`, instead of `0.0.0-snapshot`
CI should trigger correctly after updating default branch.
=> Update default branch to main

.github/workflows/ci.yaml, .golangci.yml, go.mod, src/api/v1alpha1/dynakube_types.go, src/cmd/support_archive/logs_test.go, src/dtclient/activegate_auth_token.go, src/dtclient/connection_info.go, src/dtclient/dynatrace_client_test.go, src/dtclient/kubernetes_settings.go, src/dtclient/send_event.go
Last step of finishing upgrade to golang 1.20
Check if build works and operator pod runs as expected
- [] Unit tests have been updated/added
=> Upgrade go lang to 1.20

.golangci.yml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, hack/helm/generate-crd.sh, hack/make/manifests/config.mk, hack/make/manifests/crd.mk
Cherry pick of  #1547 
Same as  #1547
=> Improve CRD generation

hack/build/ci/preflight.sh
Cherry pick of #1497 
Same as #1497
=> Fix failing RHCC image preflight scan upload

src/controllers/csi/gc/unmounted.go
Same as in #1513
Same as in #1513
=> Make CSI log GC more error resilient

src/controllers/dynakube/dynakube_controller.go
Same as in #1483
Same as in #1483
=> Fix error logging on dynakube reconicliation

config/deploy/kubernetes/kustomization.yaml, config/deploy/openshift/kustomization.yaml
Cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/1548
Same as https://github.com/Dynatrace/dynatrace-operator/pull/1548
=> Use csi less target for OLM bundle generation

config/helm/chart/default/Chart.yaml
Adapt Chart.yaml for release version 0.10.4
No need to test
=> Adapt Chart.yaml for release version 0.10.4

src/controllers/dynakube/version/activegate.go, src/controllers/dynakube/version/codemodules.go, src/controllers/dynakube/version/oneagent.go, src/controllers/dynakube/version/oneagent_test.go, src/controllers/dynakube/version/synthetic.go, src/controllers/dynakube/version/updater.go, src/controllers/dynakube/version/updater_test.go
Cherry-pick of #1689
same as #1689
=> Adds downgrade check for the public registry (#1688)

src/controllers/certificates/webhook_cert_controller.go, src/controllers/certificates/webhook_cert_controller_test.go
cherry pick of #1711
same as #1711
=> Make cert secret owned by the webhook deployment (#1711)

hack/build/bundle.sh
Cherry-pick of #1776
Same as in #1776
=> Add OCP 4.13 as supported version for OLM

config/helm/chart/default/templates/Common/csi/csidriver.yaml, config/helm/chart/default/tests/Common/csi/csidriver_test.yaml
Cherry pick of #1778
same as in #1778
=> Add CSI Driver label for to support OCP 4.13 PodSecurityStandards

src/installer/image/installer.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/1779
same as https://github.com/Dynatrace/dynatrace-operator/pull/1779
=> Improves error for unexpected type for image ref in image installer

README.md
Update link to new, combined support lifecycle page for Kubernetes/Openshift.
Links in Readme don't 404.
=> Update link to support lifecycle documentation

.github/actions/build-image/action.yaml, .github/workflows/ci.yaml, .github/workflows/codeql-analysis.yaml, .github/workflows/openssf-scorecards.yaml, .github/workflows/publish-images.yaml, Dockerfile, go.mod, go.sum
Update dependencies for 0.12.0
Unit tests and build should run successfully aswell as no changes in behaviour
=> Update dependencies for 0.12 release

config/helm/chart/default/templates/Common/activegate/clusterrole-activegate.yaml, config/helm/chart/default/templates/Common/csi/clusterrole-csi.yaml, config/helm/chart/default/templates/Common/csi/csidriver.yaml, config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrole-oneagent-privileged.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrole-oneagent-unprivileged.yaml, config/helm/chart/default/templates/Common/operator/clusterrole-operator.yaml, config/helm/chart/default/templates/Common/webhook/clusterrole-webhook.yaml, config/helm/chart/default/templates/_platform.tpl, hack/make/manifests/kubernetes.mk, hack/make/manifests/openshift.mk
=> Removes openshiftOrOlm check in helm manifests

test/scenarios/support_archive/install.go
cherry pick of #1876 
same as #1876 
=> Add unique label to e2e test namespace for support archive test

.github/actions/upload-sbom/action.yaml, .github/workflows/publish-images.yaml
cherry-pick of #1884 
same as #1884 
- ~[x] Unit tests have been updated/added~
=> Adds automated sbom creation and upload to publish-image step

.github/pull_request_template.md
As we have some rules applied that are not written down in the PR template, this adds them.
E.g the guidelines for the PR titles and also that only a single label should be added to the PR
=> Updates pull request template

assets/samples/applicationMonitoring.yaml, assets/samples/classicFullStack.yaml, assets/samples/cloudNativeFullStack.yaml, assets/samples/hostMonitoring.yaml
=> Change ActiveGate `group` field to "recommended"

.github/pull_request_template.md
Refactor PR markdown template and comply with the [Markdownlint project](https://github.com/DavidAnson/markdownlint/tree/main) rules.
It's available as an extension on VSCode marketplace (https://marketplace.visualstudio.com/items\?itemName\=DavidAnson.vscode-markdownlint)
No tests are needed.
=> Refactor PR markdown template following Markdownlint rules

config/helm/chart/default/templates/Common/activegate/clusterrole-activegate.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrole-oneagent-privileged.yaml, config/helm/chart/default/tests/Common/activegate/clusterrole-activegate_test.yaml, config/helm/chart/default/tests/Common/oneagent/clusterrole-oneagent-privileged_test.yaml, hack/make/manifests/openshift.mk
=> Fix duplicated ClusterRole for Openshift

config/helm/chart/default/templates/Common/activegate/clusterrole-activegate.yaml, config/helm/chart/default/templates/Common/csi/clusterrole-csi.yaml, config/helm/chart/default/templates/Common/csi/csidriver.yaml, config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml, config/helm/chart/default/templates/Common/oneagent/clusterrole-oneagent-privileged.yaml, config/helm/chart/default/templates/Common/operator/clusterrole-operator.yaml, config/helm/chart/default/templates/Common/webhook/clusterrole-webhook.yaml, config/helm/chart/default/templates/_platform.tpl, hack/make/manifests/kubernetes.mk, hack/make/manifests/openshift.mk
=> Fix K8s OLM manifests to include serviceAccount for oneAgents

test/scenarios/activegate/installation.go
cherry-picking of https://github.com/Dynatrace/dynatrace-operator/pull/1978
same as in https://github.com/Dynatrace/dynatrace-operator/pull/1978
=> Fix activate gate read only assess (#1978)

src/controllers/csi/provisioner/install.go, src/dtclient/agent_version.go, src/dtclient/agent_version_test.go, src/dtclient/client.go, src/dtclient/endpoints.go, src/dtclient/mock_client.go, src/installer/url/download.go, src/installer/url/installer.go, src/standalone/run.go
cheery pick of #1982 
same as #1982
=> Only use raw codemodules with csiDriver 

src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/serviceport.go, src/controllers/dynakube/activegate/internal/statefulset/builder/modifiers/serviceport_test.go
Routing ActiveGate should  advertise  to OneAgents two  communication addresses:
- IP based address
- AG service name based address 
Communication addresses are set via `DT_DNS_ENTRY_POINT` variable. IP address is already set so the second address has to be added to the list if needed.
Use `ApplicationMonitoring` setup (CSI not needed) with different AG capabilities enabled (see `TestBuildDNSEntryPoint` test for scenarios). For example:
-  modern routing capability
```
activeGate:
capabilities:
- routing
#- kubernetes-monitoring
oneAgent:
applicationMonitoring: {}
```
`kubectl -n dynatrace describe pod/dynakube-activegate-0`
```
Containers:
activegate:
Environment:
DT_DNS_ENTRY_POINT:         https://$(DYNAKUBE_ACTIVEGATE_SERVICE_HOST):$(DYNAKUBE_ACTIVEGATE_SERVICE_PORT)/communication,http …
```
=> Add ActiveGate service to DT_DNS_ENTRY_POINT

config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml
This change relates to [Add EdgeConnect CRD](https://github.com/Dynatrace/dynatrace-operator/pull/1966). I forgot to update helm manifest.
~~Please include some guiding steps on how to test this change during a review.~~
=> Updates helm manifest (because of changed EdgeConnect CRD)

test/scenarios/cloudnative/proxy/proxy.go
fixup: Test cloudnative with proxy with istio
Run cluster with istio:
`make test/e2e/cloudnative/proxy`
=> fixup: Test cloudnative with proxy with istio

test/scenarios/classic/switch_modes/install.go, test/scenarios/cloudnative/switch_modes/install.go
cherry pick of #2021
same as #2021
=> Make switch modes tests more reliable

test/helpers/steps/assess/dynakube.go, test/helpers/steps/assess/operator.go, test/helpers/steps/teardown/operator.go, test/helpers/steps/teardown/uninstall.go, test/scenarios/activegate/installation.go, test/scenarios/applicationmonitoring/labelversiondetection.go, test/scenarios/applicationmonitoring/without_csi.go, test/scenarios/classic/switch_modes/install.go, test/scenarios/cloudnative/switch_modes/install.go
cherry pick of #1988
same as #1988
=> Clean up better in switchmode e2e tests

src/cmd/csi/init/builder.go, src/cmd/csi/init/config.go, src/controllers/csi/metadata/correctness.go, src/controllers/csi/metadata/correctness_test.go, test/testdata/sample-app/restricted-csi.yaml
cherry pick of  #2041 
same as  #2041
=> Not fail csi-init on network problems

config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml
=> hotfix after upgrade

config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, src/api/v1alpha1/edgeconnect/edgeconnect_types.go
Fix smaller wording issues with edgeConnect CRD
No need to be tested just wording changed
=> Fix smaller wording issues with edgeConnect CRD

README.md
=> add different badges to README.md :)

doc/coding-style-guide.md
Add few notes about when to use error types and when sentinel errors
N/A
=> Add notes about special error handling

hack/make/tests/e2e.mk, test/helpers/components/edgeconnect/edgeconnect.go, test/helpers/components/operator/installation.go, test/helpers/setup/setup_builder.go, test/helpers/steps/assess/dynakube.go, test/helpers/steps/assess/edgeconnect.go, test/helpers/steps/teardown/dynakube.go, test/helpers/steps/teardown/operator.go, test/helpers/tenant/secrets.go, test/scenarios/edgeconnect/edgeconnect.go, test/scenarios/edgeconnect/edgeconnect_test.go, test/testdata/secrets-samples/edgeconnect-tenant.yaml
Add EdgeConnect e2e tests
`make test/e2e/edgeconnect`
=> Add EdgeConnect e2e tests

src/dtclient/communication_hosts_test.go, src/dtclient/oneagent_connection_info.go, src/dtclient/oneagent_connection_info_test.go
cherry-picking of https://github.com/Dynatrace/dynatrace-operator/pull/2167
unit-tests
=> [release-0.14] Prevent dups from one agent conn info release

src/registry/client.go
Release branch clone of #2186.
see #2186
=> Use image index digest instead of plain image digest #2186

pkg/controllers/dynakube/activegate/internal/statefulset/statefulset.go, pkg/controllers/dynakube/activegate/internal/statefulset/statefulset_test.go, pkg/util/kubeobjects/affinity.go, pkg/util/kubeobjects/affinity_test.go
Same as in #2200 
Same as in #2200
=> Remove default tolerations for activeGate pods(#2200)

hack/make/deploy/helm.mk
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/2205
same as https://github.com/Dynatrace/dynatrace-operator/pull/2205
=> Keep namespace when running undeploy/helm #2205

.github/actions/build-helm/action.yaml, .github/actions/upload-helm/action.yaml, .github/workflows/release.yaml, hack/build/ci/push-helm-chart.sh
Cherrypick of #2170
Cherrypick of #2170
=> Add helm-package upload to OCI registry (#2161)

.github/workflows/ci.yaml, CONTRIBUTING.md, doc/coding-style-guide.md
To include all markdown files let's just avoid any patterns.
=> Fix files pattern for markdown linter

src/controllers/csi/provisioner/controller.go, src/controllers/csi/provisioner/controller_test.go
Same as in #2243 
Same as in #2243
=> Re-order provisioner structure in order to fix host-monitoring (#2243)

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, config/helm/chart/default/values.yaml, src/controllers/csi/provisioner/controller.go, src/controllers/csi/provisioner/controller_test.go
Same as in #2243 and #2178
Same as in #2243 and #2178
=> Re-order provisioner structure and add CSI init-container limits

Dockerfile
Update UBI9 base image to newer version
Everything should work as before
=> Update UBI9 base image to newer version

test/testdata/network/proxy.yaml
cherry pick of #2422
same as #2422
=> Fix e2e proxy.yaml for latest openshift (#2422)

pkg/webhook/validation/dynakube/config.go, pkg/webhook/validation/dynakube/deprecation.go, pkg/webhook/validation/dynakube/deprecation_test.go
This PR adapts deprecation message for deprecated feature flags
unit-tests
=> Adapt deprecation message for deprecated feature flags

test/helpers/kubeobjects/daemonset/wait.go
OCP e2e tests are currently timing out in `oneagent_started` step.
We discussed making a workaround by logging the error and passing the test.
Hard to make it timeout locally... We have to see in OCP pipelines
=> Fail safe in oneagent_started e2e test step

.github/actions/build-image/action.yaml, .github/actions/preflight/action.yaml, .github/actions/upload-image/action.yaml, .github/workflows/openssf-scorecards.yaml
Combine these two together: https://github.com/Dynatrace/dynatrace-operator/pull/2493/files https://github.com/Dynatrace/dynatrace-operator/pull/2492/files
tests
=> bump actions/download-artifact and actions/upload-artifact

PROJECT, hack/build/bundle.sh, hack/build/create_go_linker_args.sh
#2505
See #2505 (proper log output on operator startup)
=> Fix location of version package (#2505)

.github/workflows/ci.yaml
backport this commit https://github.com/Dynatrace/dynatrace-operator/commit/a0504347436c5e8a2f9734473b13e4c6df64a215
n/a
=> add snyk severity threshold high

cmd/support_archive/resources_test.go
follow up for this one https://github.com/Dynatrace/dynatrace-operator/pull/2481
unit tests
=> Add missing mocks for CRDs

test/features/cloudnative/network_problems/network_problems.go
This PR improves check_for_dummy_volume test, so we subscribe for logs and waiting for error.
Run `make test/e2e/istio` 2-3 times in row, make sure it works :) 
=> fixup flaky e2e test: Istio check_for_dummy_volume E2E test failing

hack/build/build_image.sh, hack/build/push_image.sh
If statement was wrong, fixed it with @andriisoldatenko 
make build
=> Fix make command

README.md
Fancy metric about number of release downloads.
=> Add release downloads shield to README.md

config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml
follow up after this one: https://github.com/Dynatrace/dynatrace-operator/pull/2570/files
N/A
=> run make manifests after bumping controller-gen version

assets/samples/dynakube/kubernetesObservability.yaml
Add new kubernetesObservability sample
No need to test
=> Add new kubernetesObservability sample

.github/renovate.json5
Add new release branch to renovate config
Please include some guiding steps on how to test this change during a review.
- What environment is necessary for the change to be noticeable ?
- What needs to be enabled/applied for the change to be noticeable ?
=> Add new release branch to renovate config for release-1.0

pkg/controllers/csi/driver/volumes/app/publisher.go, pkg/controllers/csi/driver/volumes/app/publisher_test.go, pkg/controllers/csi/metadata/path_resolver.go, pkg/controllers/csi/provisioner/install_test.go
cherry pick of #2668
same as #2668
=> Copy ruxitagentproc.conf config into upper-dir (#2668)

pkg/controllers/dynakube/oneagent/daemonset/arguments.go, pkg/controllers/dynakube/oneagent/daemonset/arguments_test.go, pkg/controllers/dynakube/oneagent/daemonset/env_vars.go, pkg/controllers/dynakube/oneagent/daemonset/env_vars_test.go, pkg/controllers/dynakube/oneagent/oneagent_reconciler_test.go, pkg/controllers/dynakube/version/healthconfig.go, pkg/controllers/dynakube/version/healthconfig_test.go
cherry-pick of #2676
same as #2676
=> Handle custom-image in case of version checks (#2676)

Dockerfile
Reverts Dynatrace/dynatrace-operator#2688
=> Revert "Update golang Docker tag to v1.22.0 (main)"

assets/samples/dynakube/cloudNativeFullStack.yaml
#2668
Documentation changes only.
=> Align requests/limits of init resources in cloud native fullstack sample

test/helpers/sample/app.go
Fix typo in e2e tests: replica count
e2e tests
=> typo: reduce sample apps count

pkg/util/kubeobjects/daemonset/daemonset.go
=> Small refactor in OneAgent daemonset

.github/actions/upload-helm/action.yaml, .github/workflows/release.yaml
same as in: [#2749]
same as in: [#2749]
=> Push Helm Chart to ECR on Release (main)

pkg/arch/consts.go, pkg/arch/ppcle.go
add image arch for ppcle
add image arch for ppcle
=> add image arch for ppcle

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml
Commit missing changes after running `make manifests`.
Run `make manifests` and make sure there are no uncommitted changes.
=> fixup: run `make manifests`

hack/make/go.mk
The target executes unittests and opens coverage report in a browser.
```
make go/testhtml
```
=> Adds go/testhtml make target

hack/build/bundle.sh
Adapt supported OCP versions for OLM
=> Adapt supported OCP versions for OLM

.github/actions/preflight/action.yaml
Update preflight to v1.9.1 for v1.0.0
Follow up task to automate this with renovate was created by me :)
=> Update openshift preflight to v1.9.1 for v1.0.0

.github/actions/preflight/action.yaml
=> Update openshift preflight to v1.9.1 for v1.0.0 (#2896)

config/helm/chart/default/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml, config/helm/chart/default/tests/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring_test.yaml
Add read permissions for DynaKubes to ActiveGate role "dynatrace-kubernetes-monitoring"
=> Add read permissions for DynaKubes to ActiveGate role

hack/build/ci/generate-release-notes.sh
cherry pick of #2947
same as #2947
=> Fix release notes generation script (#2947)

assets/samples/dynakube/multipleDynakubes.yaml
Remove replicas parameter from multi dynakube sample as it is missleading.
No tests needed, just a samples change :)
=> Remove replicas field from multipleDynakubes.yaml sample

pkg/webhook/mutation/pod/oneagent/containers.go
Same as in #3007
Same as in #3007
=> Fix container name and container image env var counter

config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml
Commit missing uncommited changes
n/a
=> hotfix: run makenaifests

pkg/api/v1beta2/dynakube/dynakube_types.go, pkg/api/v1beta2/dynakube/dynakube_webhook.go, pkg/api/v1beta2/groupversion_info.go
Reverts Dynatrace/dynatrace-operator#3073
=> Revert "Remove builder tags from v1beta2 to make conversion webhook work"

hack/build/ci/create-manifest.sh
#3104
Run `/hack/build/ci/create-manifest.sh` with `multiplatform=true`
=> Fix manifest creation for multiarch images

pkg/controllers/dynakube/oneagent/daemonset/volumes.go, pkg/controllers/dynakube/oneagent/daemonset/volumes_test.go
Same as in #3120
Same as in #3120
=> Fix ignore-proxy feature flag for oneAgent daemonset #3120

config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml
Add missing changes after running make manifests
make manifests
=> Add missing changes after running `make manifests`

.github/actions/run-e2e/action.yaml, .github/workflows/e2e-tests-ondemand.yaml
This PR introduces e2e pipeline for all supported k8s and OCP versions.
Run pipeline and see results 🚀 
It resolves [issue](https://dt-rnd.atlassian.net/browse/K8S-9455)
=> Migrate e2e tests on demand part 2

pkg/controllers/csi/metadata/migrations.go, pkg/controllers/csi/metadata/sqlite_gorm_client.go
cherry-pick of 89b922bbb1a12d5be9ed1e417f76835a92afd022
you can find more details here -> https://github.com/Dynatrace/dynatrace-operator/pull/3240
=> Deprecate old csi tables (#3240)

pkg/api/v1beta2/dynakube/oneagent_types.go
cherrypick to release 1.2 for #3235
=> Fixes autoUpdate being enabled when applying a DynaKube in v1beta1 with autoUpdate set to false.

pkg/api/v1beta1/dynakube/convert_from.go, pkg/api/v1beta1/dynakube/convert_to.go
cherry pick of https://github.com/Dynatrace/dynatrace-operator/pull/3254
same as https://github.com/Dynatrace/dynatrace-operator/pull/3254
=> Make conversion nil safe in case of empty annotations (#3254)

.github/renovate.json5
resolves https://github.com/Dynatrace/dynatrace-operator/issues/3260
=> fixup renovate config .github/renovate.json5

pkg/util/dtotel/otel.go
cherry pick of #3266
same as #3266
=> Make otel error log less scary (#3266) 

pkg/webhook/config.go
cherry pick of #3273
same as #3273
=> Correct metadata-enrichment annotation prefix (#3273)

hack/build/ci/get-image-digest.sh
Fix release pipeline version mismatch of docker and skopeo
Not at all
=> Fix release pipeline version mismatch of docker and skopeo

.github/renovate.json5, .github/workflows/renovate.yaml
Cherry-pick changes from main:
=> Cherry pick renovate changes

.github/workflows/release.yaml, config/helm/chart/default/templates/_platform.tpl, config/helm/chart/default/tests/Common/operator/deployment-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/deployment-webhook_test.yaml, config/helm/chart/default/tests/Google/application_test.yaml, config/helm/chart/default/values.yaml, hack/make/deploy/gke.mk, hack/make/manifests/config.mk, hack/make/manifests/kubernetes.mk, hack/make/tests/e2e.mk
Same as in #3331
Same as in #3331
=> Remove gke-autopilot as platform from helm chart (#3331)

pkg/webhook/validation/dynakube/namespace_selector.go
Same is in #3338
Same is in #3338
=> Fix nil-pointer in conflicting namespace validation (#3338)

pkg/controllers/csi/gc/binaries.go, pkg/controllers/csi/gc/binaries_test.go, pkg/controllers/csi/gc/reconciler.go
cherry pick of #3339
same as #3339
=> Make csi-gc less aggressive (#3339)

pkg/api/v1beta1/dynakube/convert_from.go, pkg/api/v1beta1/dynakube/convert_from_test.go, pkg/api/v1beta1/dynakube/convert_to.go
Same as in #3374
Same as in #3374
=> Fix activeGate replica conversion (#3374)

pkg/consts/enrichment_injection.go, pkg/injection/startup/files.go, pkg/injection/startup/run_test.go, pkg/webhook/mutation/pod/metadata/containers.go, pkg/webhook/mutation/pod/metadata/mutator_test.go, pkg/webhook/mutation/pod/metadata/volumes.go, pkg/webhook/mutation/pod/metadata/volumes_test.go
Same as in #3387
Same as in #3387
=> Fix failing initContainer incase of classicFullStack and metadataEnrichment combination #3387

Dockerfile
Same as in #3399 
Same as in #3399
=> Fix incorrect golang digest for golang-1.22.5 image

pkg/oci/dockerkeychain/docker_keychain.go, pkg/oci/dockerkeychain/docker_keychain_test.go
Same as in #3403
Same as in #3403
=> Fix pull secret not found error preventing codeModulesImage download (#3403)

config/helm/chart/default/templates/_platform.tpl, config/helm/chart/default/values.yaml
Same as in #3402 
Same as in #3402
=> Change bracket type for labels and annotations in values.yaml

pkg/controllers/csi/driver/volumes/host/publisher.go, pkg/controllers/csi/driver/volumes/host/publisher_test.go, pkg/controllers/csi/gc/binaries.go, pkg/controllers/csi/gc/binaries_test.go, pkg/controllers/csi/gc/reconciler.go, pkg/controllers/csi/gc/reconciler_test.go, pkg/controllers/csi/metadata/cleaner_test.go
=> Block osmount incase unmount is still in progress (#3388)

.github/renovate.json5, pkg/util/dtotel/otel.go
This PR relates to  https://github.com/Dynatrace/dynatrace-operator/pull/3390, so we want to automate process of bumping OTEL deps.
=> Automate otel via renovate

config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, hack/make/manifests/config.mk, pkg/api/v1beta3/dynakube/dynakube_types.go
Make sure work-in-progress DynaKube v1beta3 is not release yet and does not have negative side-effects.
* Deploy operator
* Deploy v1beta2 Dynakube -> should work
* Deploy v1beta3 Dynakube -> shall be rejected
=> Skip generation of v1beta3 for release 1.3.0 and remove maxDescLen parameter

pkg/controllers/csi/driver/volumes/host/publisher.go, pkg/controllers/csi/driver/volumes/host/publisher_test.go
cherry pick of #3453
same as #3453
=> Handle the force-delete scenario in the OS volume publisher (#3453)

config/helm/chart/default/templates/Common/webhook/validatingwebhookconfiguration.yaml, config/helm/chart/default/tests/Common/webhook/validatingwebhookconfiguration_test.yaml, pkg/api/v1beta2/dynakube/validation/oneagent.go
cherry pick of #3469
same as #3469
=> Specify ns when listing dynakubes during validation (#3469)

test/helpers/components/dynakube/dynakube.go, test/helpers/components/oneagent/daemonset.go, test/helpers/components/operator/installation.go
This PR fixes bug [K8S-10630](https://dt-rnd.atlassian.net/browse/K8S-10630).
how to test:
- run e2e tests and see that 
```
make test/e2e/cloudnative/default
```
> WARNING:
This PR doesn't fix a few tests still; they will be fixed in separate PRs.
=> Fixup e2e tests after introducing v1beta3

cmd/webhook/builder.go, config/helm/chart/default/templates/Common/webhook/validatingwebhookconfiguration.yaml, config/helm/chart/default/tests/Common/webhook/validatingwebhookconfiguration_test.yaml, pkg/api/v1alpha1/edgeconnect/edgeconnect_webhook.go, pkg/api/v1alpha1/edgeconnect/validation/api_server.go, pkg/api/v1alpha1/edgeconnect/validation/api_server_test.go, pkg/api/v1alpha1/edgeconnect/validation/automation_validation.go, pkg/api/v1alpha1/edgeconnect/validation/automation_validation_test.go, pkg/api/v1alpha1/edgeconnect/validation/config.go, pkg/api/v1alpha1/edgeconnect/validation/host_patterns.go, pkg/api/v1alpha1/edgeconnect/validation/host_patterns_test.go, pkg/api/v1alpha1/edgeconnect/validation/name.go, pkg/api/v1alpha1/edgeconnect/validation/name_test.go, pkg/api/v1alpha1/edgeconnect/validation/service_account.go, pkg/api/v1alpha1/edgeconnect/validation/service_account_test.go, pkg/api/v1alpha1/edgeconnect/validation/validation.go, pkg/api/v1alpha1/edgeconnect/validation/validation_test.go
[K8S-10055](https://dt-rnd.atlassian.net/browse/K8S-10055)
Move the validation logic into EdgeConnect API version directory to allow for multi-version CRD validation.
Deploy EdgeConnect with valid and invalid configurations to see if validation works.
=> Refactor EdgeConnect validation to v1alpha1

pkg/controllers/csi/gc/binaries_test.go, pkg/controllers/csi/provisioner/install.go
Cherrypick of #3553 
Cherrypick of #3553
=> Revert back the tenantUUID change in the CSI driver

config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml
commit missing changes after renovate upgrade
n.a
=> run make manifests after renovate

config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, pkg/api/v1beta2/dynakube/metada_enrichment.go, pkg/api/v1beta3/dynakube/metada_enrichment.go
Same as in #3715
Same as in #3715
=> Change default value of metadata enrichment

.github/workflows/e2e-tests-ondemand.yaml
Ensure all supported versions are also tested on Github before the release.
Run ondemand pipelines.
=> Add missing Openshift versions to ondemand platforms

test/features/edgeconnect/edgeconnect.go
We update the hostPatterns field, and check it immidietly on the cluster, without waiting for the reconcile to complete
this is why it may or may not pass
`make e2e/standart/edgeconnect` few times ideally 5 :)
=> Add wait for status.Running after updating hostPatters inside edgeConnect e2e test

hack/build/bundle.sh
Next release should be available on all supported Openshift versions via OperatorHub marketplaces.
Release.
=> Bump supported OperatorHub versions

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, pkg/api/v1beta2/dynakube/convert_from.go, pkg/api/v1beta2/dynakube/convert_to.go, pkg/api/v1beta2/dynakube/dynakube_status.go, pkg/api/v1beta3/dynakube/dynakube_status.go, pkg/consts/enrichment_injection.go, pkg/controllers/dynakube/monitoredentities/reconciler.go, pkg/injection/startup/enrichment.go, pkg/injection/startup/enrichment_test.go, pkg/injection/startup/env.go, pkg/injection/startup/env_test.go, pkg/webhook/mutation/pod/metadata/containers.go, pkg/webhook/mutation/pod/metadata/containers_test.go, pkg/webhook/mutation/pod/metadata/env.go, pkg/webhook/mutation/pod/metadata/env_test.go, pkg/webhook/mutation/pod/metadata/mutator.go, pkg/webhook/mutation/pod/metadata/mutator_test.go
same as https://github.com/Dynatrace/dynatrace-operator/pull/3787
same as https://github.com/Dynatrace/dynatrace-operator/pull/3787
=> Propagate both cluster-name and entity-id to enrichment files (#3787)

.github/actions/run-e2e/action.yaml, .github/workflows/e2e-tests-ondemand.yaml
Currently we use default branch, but we should use input.
=> Fixup ondemand pipeline branch

hack/build/bundle.sh
=> Bump supported OperatorHub versions (#3773)

config/helm/chart/default/templates/Common/extensions-controller/role-extensions-controller.yaml
=> chore: sync format for eec role similar to other role/clusterRoles

pkg/controllers/dynakube/apimonitoring/reconciler.go, pkg/controllers/dynakube/apimonitoring/reconciler_test.go
cherry pick of #3886
same as #3886
=> Don't update k8s-settings object, if already present (#3886)

config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, config/helm/chart/default/templates/Common/operator/role-operator.yaml, config/helm/chart/default/templates/Common/webhook/role-webhook.yaml, config/helm/chart/default/tests/Common/operator/role-operator_test.yaml, config/helm/chart/default/tests/Common/webhook/role-webhook_test.yaml
[DAQ-1581](https://dt-rnd.atlassian.net/browse/DAQ-1581)
These roles were mainly there for historical reasons
No change in behaviour
=> Remove unnecessary roles from operator/webhook

pkg/injection/startup/secret.go
https://dt-rnd.atlassian.net/browse/DAQ-1677
Same as in #3947 
Same as in #3947
=> Fix proxy content logged in init-container logs (#3947)

pkg/util/kubeobjects/volumes/volumes.go, pkg/webhook/mutation/pod/init_container.go, pkg/webhook/mutation/pod/oneagent/mutator.go, pkg/webhook/mutation/pod/webhook.go
cherry pick of #3955
same as #3955
=> More excessively check if the oneagent injection happened (#3955)

.github/actions/preflight/action.yaml
Update preflight action to v1.10.2
=> Update preflight action to v1.10.2

config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml
These files were missing to update.
=> Update controller-gen version on CRD

pkg/controllers/edgeconnect/deployment/deployment.go
Cherry pick of #3360 
see #3360
=> Fix volume mount for EdgeConnect custom CA. (#3360)

pkg/injection/startup/run.go, pkg/util/kubeobjects/container/container.go, pkg/webhook/mutation/pod/webhook.go, pkg/webhook/mutation/pod/webhook_test.go
[K8S-11108](https://dt-rnd.atlassian.net/browse/K8S-11108)
cherry-pick of #3722
same as #3722
[K8S-11108]: https://dt-rnd.atlassian.net/browse/K8S-11108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent the double injection of the init-container (#3700) (#3722)

config/crd/bases/dynatrace.com_dynakubes.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml
Missing fields to update from previous PRs
make deploy on main branch triggers these updates
=> Update missing crd and chart fields

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml, pkg/controllers/csi/config.go, pkg/controllers/csi/driver/server.go
cherry-pick of https://github.com/Dynatrace/dynatrace-operator/pull/4018
=> Implement rate limiter for GRPC server

pkg/controllers/csi/driver/server.go
mostly follow-up for this PR https://github.com/Dynatrace/dynatrace-operator/pull/4037
it resolves https://dt-rnd.atlassian.net/browse/DAQ-2335
=> make grpc max limit configurable

doc/api/dynakube-api-ref.md
Fixes messages in api-ref doc changed by [PR](https://github.com/Dynatrace/dynatrace-operator/pull/4038)
`make doc/api-ref` changes nothing.
=> Fixes api-ref file

.github/workflows/self-update-on-new-release-version.yaml
follow up to this one https://github.com/Dynatrace/dynatrace-operator/pull/4102, we need to add correct file, since we have one automatic PR for 2 files
=> update add paths to commit correct file

.github/workflows/self-update-on-new-release-version.yaml
Reverts Dynatrace/dynatrace-operator#4107
=> Revert "Create-PR github action requires workflows permissions"

pkg/api/v1beta3/dynakube/oneagent_props.go, pkg/controllers/dynakube/version/updater.go
[DAQ-2271](https://dt-rnd.atlassian.net/browse/DAQ-2271)
cherry pick of #4110
same as #4110
[DAQ-2271]: https://dt-rnd.atlassian.net/browse/DAQ-2271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow custom version for cloudnative (#4110) 

pkg/clients/dynatrace/activegate_version.go, pkg/clients/dynatrace/agent_version.go, pkg/clients/dynatrace/agent_version_test.go, pkg/clients/dynatrace/client.go, pkg/clients/dynatrace/dynatrace_client_test.go, pkg/clients/dynatrace/endpoints.go, pkg/controllers/dynakube/activegate/internal/statefulset/statefulset.go, pkg/controllers/dynakube/activegate/internal/statefulset/statefulset_test.go, pkg/controllers/dynakube/extension/eec/reconciler_test.go, pkg/controllers/dynakube/extension/eec/statefulset.go, pkg/controllers/dynakube/extension/otel/statefulset.go, pkg/controllers/dynakube/extension/otel/statefulset_test.go, pkg/controllers/dynakube/kspm/daemonset/reconciler.go, pkg/controllers/dynakube/oneagent/daemonset/affinity.go, pkg/controllers/dynakube/oneagent/daemonset/affinity_test.go, pkg/injection/codemodule/installer/url/download.go, pkg/util/kubeobjects/node/affinity.go, pkg/util/kubeobjects/node/affinity_test.go, pkg/webhook/mutation/pod/oneagent/env.go, test/mocks/pkg/clients/dynatrace/client.go
[DAQ-2193](https://dt-rnd.atlassian.net/browse/DAQ-2193)
cherry pick of #4065
same as #4065
[DAQ-2193]: https://dt-rnd.atlassian.net/browse/DAQ-2193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove arch param where necessary (#4065)

pkg/api/validation/dynakube/logmonitoring_test.go, pkg/api/validation/dynakube/oneagent.go, pkg/api/validation/dynakube/oneagent_test.go
[DAQ-2191](https://dt-rnd.atlassian.net/browse/DAQ-2191)
cherry pick of #4124
same as #4124
[DAQ-2191]: https://dt-rnd.atlassian.net/browse/DAQ-2191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Consider logmonitoring in the node-selector check (#4124)

pkg/clients/dynatrace/agent_version.go, pkg/clients/dynatrace/dynatrace_client_test.go
run `make go/test` and `make go/lint`
=> Remove flaky ARM test

pkg/clients/dynatrace/agent_version.go, pkg/clients/dynatrace/dynatrace_client_test.go
same as https://github.com/Dynatrace/dynatrace-operator/pull/4132
same as https://github.com/Dynatrace/dynatrace-operator/pull/4132
=> Remove flaky ARM test (#4132)

pkg/controllers/dynakube/extension/eec/reconciler_test.go, pkg/util/kubeobjects/statefulset/builder.go, pkg/util/kubeobjects/statefulset/query.go
[cherry-pick](https://github.com/Dynatrace/dynatrace-operator/pull/4131)
=> Recreate EEC statefulset for PVC changes only (release-1.4)

config/helm/chart/default/templates/Common/logmonitoring/clusterrole-logmonitoring.yaml, config/helm/chart/default/tests/Common/logmonitoring/clusterrole-logmonitoring_test.yaml, pkg/controllers/dynakube/logmonitoring/daemonset/env.go, pkg/controllers/dynakube/oneagent/daemonset/env_vars.go, pkg/controllers/dynakube/oneagent/daemonset/env_vars_test.go
[DAQ-2891](https://dt-rnd.atlassian.net/browse/DAQ-2891)
cherry-pick #4140
same as #4140
[DAQ-2891]: https://dt-rnd.atlassian.net/browse/DAQ-2891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add logmonitoring rbac to OA ServiceAccount (#4140)

pkg/api/v1beta3/dynakube/feature_flags.go, pkg/api/v1beta3/dynakube/oneagent_props.go, pkg/controllers/dynakube/oneagent/daemonset/daemonset.go, pkg/controllers/dynakube/oneagent/daemonset/daemonset_test.go
https://dt-rnd.atlassian.net/browse/DAQ-2944
Same as in #4146 
Same as in #4146
=> Add feature flag to skip oneAgent livenessprobe (#4146)

pkg/controllers/edgeconnect/controller.go, pkg/controllers/edgeconnect/deployment/deployment.go, pkg/controllers/edgeconnect/deployment/deployment_test.go
cherry-pick [4153](https://github.com/Dynatrace/dynatrace-operator/pull/4153)
=> Transfer EC.Labels and EC.Annotations to the POD spec

.github/workflows/e2e-tests-ondemand.yaml, test/features/cloudnative/upgrade/upgrade.go, test/helpers/components/dynakube/dynakube.go, test/helpers/components/oneagent/daemonset.go, test/scenarios/release/release_test.go
same as https://github.com/Dynatrace/dynatrace-operator/pull/4123
same as https://github.com/Dynatrace/dynatrace-operator/pull/4123
=> Bump operator prev version in upgrade e2e test to 1.3.2.

pkg/webhook/mutation/pod/metadata/mutator.go, pkg/webhook/mutation/pod/metadata/mutator_test.go, pkg/webhook/mutation/pod/metadata/workload.go, pkg/webhook/mutation/pod/metadata/workload_test.go
Jira: [DAQ-3254](https://dt-rnd.atlassian.net/browse/DAQ-3254)
See #4191 
See #4191 
[DAQ-3254]: https://dt-rnd.atlassian.net/browse/DAQ-3254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Always lowercase workload kind in enrichment file (#4191)

hack/build/bundle.sh
Update min OCP version in bundle.sh to 4.10.
Fix "removal of upper-bound"
n/a
=> Fix ocp upper bound limit

pkg/api/validation/dynakube/image.go, pkg/api/validation/dynakube/image_test.go
[DAQ-3502](https://dt-rnd.atlassian.net/browse/DAQ-3502)
cherry pick of #4220
same as #4220
[DAQ-3502]: https://dt-rnd.atlassian.net/browse/DAQ-3502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove tenant image registry restriction for image fields (#4220)

Dockerfile
With the removal of CGO, cross-compiling with Go has become straightforward. This PR updates the Dockerfile to leverage the build platform, significantly enhancing performance when building for other platforms.
E.g.: CI build times for ARM have been reduced from 17 minutes to just 2 minutes.
[Jira](https://dt-rnd.atlassian.net/browse/DAQ-1877)
- `make build`
- Test if everything is working as before
=> Add cross-compile functionality to dockerfile

test/features/support_archive/support_archive.go
Reverts `Flaky support_archive e2e test` PR #4289
```
make test/e2e/support_archive
```
=> reverts Flaky support_archive e2e test #4289

pkg/controllers/dynakube/logmonitoring/daemonset/args.go, pkg/controllers/dynakube/logmonitoring/daemonset/env.go, pkg/controllers/dynakube/logmonitoring/daemonset/env_test.go
same as https://github.com/Dynatrace/dynatrace-operator/pull/4324
same as https://github.com/Dynatrace/dynatrace-operator/pull/4324
=> [cherry-pick] Log agent args must not contain dynamic strings (#4324)

assets/samples/dynakube/v1beta3/logMonitoring.yaml
[Ticket](https://dt-rnd.atlassian.net/browse/DAQ-4333)
With this the logMonitoring DynaKube sample reflects the up to date state. An activeGate with kubernetes-monitoring capability enabled is needed to enabled logMonitoring.
read
=> Update logMonitoring DynaKube sample

pkg/api/validation/dynakube/eec_test.go, pkg/api/validation/dynakube/extensions.go, pkg/api/validation/dynakube/extensions_test.go, pkg/api/validation/dynakube/validation.go
Cherry pick of #4317 and #4326 
See #4317 and #4326 
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-4227)
=> Require Kubernetes API monitoring config for extensions

pkg/api/validation/dynakube/logmonitoring.go, pkg/api/validation/dynakube/logmonitoring_test.go, pkg/api/validation/dynakube/oneagent_test.go, pkg/api/validation/dynakube/validation.go, pkg/controllers/dynakube/controller.go, pkg/controllers/dynakube/logmonitoring/daemonset/reconciler.go, pkg/controllers/dynakube/logmonitoring/daemonset/volumes_test.go, pkg/controllers/dynakube/logmonitoring/logmonsettings/reconciler.go
same as in #4309 
same as in #4309
=> (cherry-pick) Fix Log monitoring handling without Kubernetes settings available (#4309)

test/features/extensions/extensions.go
same as https://github.com/Dynatrace/dynatrace-operator/pull/4349
same as https://github.com/Dynatrace/dynatrace-operator/pull/4349
=> Cherry-pick e2e tests extensions

config/helm/chart/default/templates/Common/csi/daemonset.yaml, config/helm/chart/default/tests/Common/csi/daemonset_test.yaml
cherry-pick https://github.com/Dynatrace/dynatrace-operator/pull/4406
similar to https://github.com/Dynatrace/dynatrace-operator/pull/4406
=> Increase CSI driver server container livenessProbe default timeouts (#4406)

pkg/controllers/dynakube/logmonitoring/daemonset/volumes.go, pkg/controllers/dynakube/logmonitoring/daemonset/volumes_test.go
same as in #4413 
same as in #4413
=> cherry-pick: Add `/var/log` mount to log agent (#4413)

pkg/api/v1beta3/dynakube/telemetryservice/props.go, pkg/api/validation/dynakube/telemetryservice.go, pkg/api/validation/dynakube/telemetryservice_test.go, pkg/controllers/dynakube/otelc/configuration/conditions.go, pkg/controllers/dynakube/otelc/configuration/config.go, pkg/controllers/dynakube/otelc/configuration/reconciler.go, pkg/controllers/dynakube/otelc/configuration/reconciler_test.go, pkg/controllers/dynakube/otelc/consts/consts.go, pkg/controllers/dynakube/otelc/reconciler.go, pkg/controllers/dynakube/otelc/service/reconciler.go, pkg/controllers/dynakube/otelc/service/reconciler_test.go, pkg/controllers/dynakube/otelc/statefulset/env.go, pkg/controllers/dynakube/otelc/statefulset/env_test.go, pkg/controllers/dynakube/otelc/statefulset/reconciler.go, pkg/controllers/dynakube/otelc/statefulset/reconciler_test.go, pkg/controllers/dynakube/otelc/statefulset/volumes.go, pkg/controllers/dynakube/otelc/statefulset/volumes_test.go, pkg/util/conditions/configmap.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-3222)
Builds OTELC configuration configmap and mounts it to the OTELC POD if `telemetryService` is enabled.
=> Creates OTELC configuration configmap (based on feature branch)

assets/samples/dynakube/v1beta4/kubernetesSecurityPostureManagement.yaml
Small update for KSPM samples
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-5712)
n/a
=> Put ActiveGate `customProperties` in KSPM sample under comment

pkg/controllers/dynakube/logmonitoring/daemonset/container.go, pkg/controllers/dynakube/logmonitoring/daemonset/container_test.go
[DAQ-6362](https://dt-rnd.atlassian.net/browse/DAQ-6362)
cherry-pick of https://github.com/Dynatrace/dynatrace-operator/pull/4633
same as https://github.com/Dynatrace/dynatrace-operator/pull/4633
[DAQ-6362]: https://dt-rnd.atlassian.net/browse/DAQ-6362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make standalone logmon privileged with FF (#4633)

assets/samples/dynakube/v1beta3/applicationMonitoring.yaml, assets/samples/dynakube/v1beta3/classicFullStack.yaml, assets/samples/dynakube/v1beta3/cloudNativeFullStack.yaml, assets/samples/dynakube/v1beta3/hostMonitoring.yaml, assets/samples/dynakube/v1beta3/kubernetesObservability.yaml, assets/samples/dynakube/v1beta3/kubernetesSecurityPostureManagement.yaml, assets/samples/dynakube/v1beta3/logMonitoring.yaml
Similar updates to #4694
* Enable metadataEnrichment by default for log monitoring sample
* Enable metadataEnrichment by default in all webhook injection samples
* `v1beta3` samples now have all possible fields
Samples can be applied and all fields are valid.
=> Update samples for v1.4

.github/workflows/release.yaml
Fix formatting in workflow file.
n/a
=> Fix formatting in release workflow

.github/workflows/release.yaml
=> Fix formatting.

.github/workflows/release.yaml
Combine SBOM and manifest step
n/a
=> Combine the manifest and sbom step

.github/workflows/release.yaml
Fixes a type in the variable name
Look at release pipeline
=> Fix typo in digest of release pipeline

test/scenarios/release/release_test.go
update upgrade e2e test based on most recent release tag **1.4.2**
e2e test
=> bump operator tag for upgrade e2e test

pkg/controllers/dynakube/otelc/service/reconciler.go, pkg/controllers/dynakube/otelc/service/reconciler_test.go
cherry-pick #4272
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-6972)
cherry-pick #4272
=> Switch to UPD ports for StatsD & Jaeger thrift/compact (#4727)

pkg/controllers/dynakube/injection/reconciler.go, pkg/controllers/dynakube/processmoduleconfigsecret/conditions.go, pkg/controllers/dynakube/processmoduleconfigsecret/reconciler.go, pkg/controllers/dynakube/processmoduleconfigsecret/reconciler_test.go, pkg/injection/namespace/bootstrapperconfig/bootstrapperconfig.go, pkg/injection/namespace/bootstrapperconfig/bootstrapperconfig_test.go, pkg/injection/namespace/bootstrapperconfig/conditions.go, pkg/injection/namespace/bootstrapperconfig/endpoints.go, pkg/injection/namespace/bootstrapperconfig/pmc.go, pkg/injection/namespace/bootstrapperconfig/replicate.go
partial fix for [DAQ-7199](https://dt-rnd.atlassian.net/browse/DAQ-7199)
cherry pick of #4745
same as #4745
[DAQ-7199]: https://dt-rnd.atlassian.net/browse/DAQ-7199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Use conditions properly in bootstrapper config reconciler (#4745)

config/helm/chart/default/templates/Common/operator/allowlistsynchronizer.yaml, config/helm/chart/default/templates/_platform.tpl, config/helm/chart/default/tests/Common/activegate/serviceaccount-activegate_test.yaml, config/helm/chart/default/tests/Common/edgeconnect/serviceaccount-edgeconnect_test.yaml, config/helm/chart/default/tests/Common/extensions/clusterrole-extensions-prometheus_test.yaml, config/helm/chart/default/tests/Common/extensions/role-extensions-controller_test.yaml, config/helm/chart/default/tests/Common/extensions/serviceaccount-extensions-controller_test.yaml, config/helm/chart/default/tests/Common/kspm/clusterrole-kubernetes-monitoring_test.yaml, config/helm/chart/default/tests/Common/kspm/serviceaccount-node-config-collector_test.yaml, config/helm/chart/default/tests/Common/logmonitoring/clusterrole-logmonitoring_test.yaml, config/helm/chart/default/tests/Common/logmonitoring/serviceaccount-logmonitoring_test.yaml, config/helm/chart/default/tests/Common/oneagent/clusterrole-oneagent_test.yaml, config/helm/chart/default/tests/Common/oneagent/serviceaccount-oneagent_test.yaml, config/helm/chart/default/tests/Common/opentelemetry-collector/clusterrole-telemetry-endpoints_test.yaml, config/helm/chart/default/tests/Common/opentelemetry-collector/serviceaccount-opentelemetry-collector_test.yaml, config/helm/chart/default/tests/Common/operator/allowlistsynchronizer_test.yaml, config/helm/chart/default/tests/Common/webhook/poddisruptionbudget-webhook_test.yaml
=> Add built-in GKE Autopilot Allowlistsynchronizer (#4740) Cherrypick

.github/workflows/release.yaml
Fixed the URL for ECR in release CI.
Has been tested with release v1.5.0-rc.1
=> Fix ECR image URL

config/helm/chart/default/templates/Common/operator/allowlistsynchronizer.yaml, test/features/applicationmonitoring/label_version_detection.go
=> Add minimal security footprint allowlist (#4766)

pkg/api/validation/dynakube/oneagent.go, pkg/api/validation/dynakube/validation.go
same as in #4775
same as in #4775
=> Remove obsolete validation warning in case of custom image is used (#4775)

assets/samples/dynakube/v1beta4/node-image-pull.yaml, config/crd/bases/dynatrace.com_dynakubes.yaml, config/crd/bases/dynatrace.com_edgeconnects.yaml, config/helm/chart/default/templates/Common/crd/dynatrace-operator-crd.yaml, doc/api/dynakube-api-ref.md, doc/api/edgeconnect-api-ref.md
Sample for node pull image feature.
Adopt sample to your env and deploy it.
=> Add node pull image sample.

assets/samples/dynakube/v1beta3/applicationMonitoring.yaml, assets/samples/dynakube/v1beta3/classicFullStack.yaml, assets/samples/dynakube/v1beta3/cloudNativeFullStack.yaml, assets/samples/dynakube/v1beta3/hostMonitoring.yaml, assets/samples/dynakube/v1beta3/kubernetesObservability.yaml, assets/samples/dynakube/v1beta3/kubernetesSecurityPostureManagement.yaml, assets/samples/dynakube/v1beta3/logMonitoring.yaml, assets/samples/dynakube/v1beta4/applicationMonitoring.yaml, assets/samples/dynakube/v1beta4/classicFullStack.yaml, assets/samples/dynakube/v1beta4/cloudNativeFullStack.yaml, assets/samples/dynakube/v1beta4/hostMonitoring.yaml, assets/samples/dynakube/v1beta4/kubernetesObservability.yaml, assets/samples/dynakube/v1beta4/kubernetesSecurityPostureManagement.yaml, assets/samples/dynakube/v1beta4/logMonitoring.yaml
[DAQ-7626](https://dt-rnd.atlassian.net/browse/DAQ-7626)
Activegate memory requests were too low. Requests/Limits are set to the same value to follow best practices. 
Samples are correct and can be applied.
[DAQ-7626]: https://dt-rnd.atlassian.net/browse/DAQ-7626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Align memory requests and limits for Activegate

assets/samples/dynakube/v1beta3/applicationMonitoring.yaml, assets/samples/dynakube/v1beta3/classicFullStack.yaml, assets/samples/dynakube/v1beta3/cloudNativeFullStack.yaml, assets/samples/dynakube/v1beta3/hostMonitoring.yaml, assets/samples/dynakube/v1beta3/kubernetesObservability.yaml, assets/samples/dynakube/v1beta3/kubernetesSecurityPostureManagement.yaml, assets/samples/dynakube/v1beta3/logMonitoring.yaml, assets/samples/dynakube/v1beta4/applicationMonitoring.yaml, assets/samples/dynakube/v1beta4/classicFullStack.yaml, assets/samples/dynakube/v1beta4/cloudNativeFullStack.yaml, assets/samples/dynakube/v1beta4/hostMonitoring.yaml, assets/samples/dynakube/v1beta4/kubernetesObservability.yaml, assets/samples/dynakube/v1beta4/kubernetesSecurityPostureManagement.yaml, assets/samples/dynakube/v1beta4/logMonitoring.yaml
[DAQ-7626](https://dt-rnd.atlassian.net/browse/DAQ-7626)
cheery pick of https://github.com/Dynatrace/dynatrace-operator/pull/4790
same as https://github.com/Dynatrace/dynatrace-operator/pull/4790
[DAQ-7626]: https://dt-rnd.atlassian.net/browse/DAQ-7626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Align memory requests and limits for Activegate (#4790)

cmd/operator/manager.go, cmd/operator/manager_test.go
[DAQ-7774](https://dt-rnd.atlassian.net/browse/DAQ-7774)
cherry pick https://github.com/Dynatrace/dynatrace-operator/pull/4811
same as https://github.com/Dynatrace/dynatrace-operator/pull/4811
[DAQ-7774]: https://dt-rnd.atlassian.net/browse/DAQ-7774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Setup the cert controller properly (#4811)

.github/actions/build-push-image/action.yaml
cherry pick of #4853
same as #4853
=> Use docker metadata action (#4853)

test/features/cloudnative/upgrade/upgrade.go, test/helpers/components/dynakube/dynakube.go, test/helpers/scheme.go
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-8887)
In the course of adding v1beta5 version we missed to update the schema in the e2e tests. This PR addresses this.
Run e2e tests
Run especially `make test/e2e/release`
=> Update scheme in e2e tests and update release e2e test

assets/samples/dynakube/v1beta3/logMonitoring.yaml, assets/samples/dynakube/v1beta4/logMonitoring.yaml, assets/samples/dynakube/v1beta5/logMonitoring.yaml
[DAQ-9755](https://dt-rnd.atlassian.net/browse/DAQ-9755)
Cherry pick of #4959
Same as #4959
[DAQ-9755]: https://dt-rnd.atlassian.net/browse/DAQ-9755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove non-existent fields in logmon samples (#4959)

.github/workflows/ci.yaml, .github/workflows/fips-ci.yaml
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-9822)
Currently we skip some steps in the CI due to the detect changes step. We should not skip steps when on main or an release branch. This PR fixes this problem.
- fork this repo and push some things to trigger the several scenarios
=> Run whole ci on main and release branches

pkg/controllers/csi/provisioner/cleanup/hostmounts.go, pkg/controllers/csi/provisioner/cleanup/run.go
[DAQ-9735](https://dt-rnd.atlassian.net/browse/DAQ-9735)
cherry pick of #5001
same as #5001
[DAQ-9735]: https://dt-rnd.atlassian.net/browse/DAQ-9735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Properly cleanup CSI host mounts (#5001)

assets/samples/dynakube/v1beta5/telemetryIngest.yaml, assets/samples/dynakube/v1beta5/telemetryIngestWithLocalActiveGate.yaml
Cherry pick #5024 
[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-5911)
just samples
=> Telemetry ingest samples (#5024)

config/helm/repos/stable/index.yaml, config/helm/repos/stable/index.yaml.previous
copy of https://github.com/Dynatrace/dynatrace-operator/pull/5051 to trigger CI
=> Update index for refs/tags/v1.6.0 release

README.md
Please review the last section with instructions on what to do with bug findings or feature requests.
=> Update Readme with Instructions for Bug Findings and Feature Requests

pkg/api/validation/edgeconnect/api_server.go, pkg/api/validation/edgeconnect/api_server_test.go, pkg/api/validation/edgeconnect/validation.go
same as https://github.com/Dynatrace/dynatrace-operator/pull/5123
same as https://github.com/Dynatrace/dynatrace-operator/pull/5123
=> cherry-pick: validate api server url correctly for edgeConnect

.github/workflows/e2e-cleanup-kubernetes-settings.yaml, hack/tenant/cleanup-kubernetes-settings.sh
Workflow returned error becase a secret var was exposed in the name
=> Fix secret in e2e-cleanup-kubernetes-settings GH action name

cmd/supportarchive/archive_test.go, pkg/api/exp/flag.go, pkg/controllers/csi/metadata/correctness.go, pkg/webhook/mutation/pod/attributes.go, pkg/webhook/mutation/pod/attributes_test.go, pkg/webhook/mutation/pod/mutator/oneagent/mutator.go
Clean up code to use newer language features and stdlib functions.
=> chore: update code for newer go version

.github/workflows/e2e-tests-ondemand.yaml, .github/workflows/e2e-tests.yaml
Update the cluster creation message to be less confusing.
Run the e2e tests => look at the message.
=> Update the cluster creation message in e2e tests

hack/build/ci/generate-release-notes.sh
Issues have been disabled for this repository. 
Related to [DAQ-8933](https://dt-rnd.atlassian.net/browse/DAQ-8933)
[DAQ-8933]: https://dt-rnd.atlassian.net/browse/DAQ-8933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Don't tell users to open GitHub issues

pkg/controllers/csi/driver/volumes/host/publisher.go, pkg/controllers/csi/driver/volumes/host/publisher_test.go
[DAQ-13275](https://dt-rnd.atlassian.net/browse/DAQ-13275)
cherry pick of #5335
same as #5335
[DAQ-13275]: https://dt-rnd.atlassian.net/browse/DAQ-13275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Handle dangling symlinks in the host publisher (#5335)

pkg/controllers/csi/driver/volumes/host/publisher.go
Just [this](https://github.com/Dynatrace/dynatrace-operator/pull/5355/commits/68ca767c0f062eb0f76a76db8e18159492ec0c1d) commit from 1.7.
=> Return error if symlink cleanup fails
